// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"idata":{"doctypes":1}
,"doctypes":{"serialization":1,"serializer":1}
,"serialization":{"adapter":1,"deserialization":1}
,"adapter":{"apache":1}
,"apache":{"kafka":1}
,"kafka":{"supports":1}
,"supports":{"serialization":1}
,"deserialization":{"followin":1}
,"followin":{"idata":1}
,"serializer":{"class:-com.wm.adapter.wmkafka.idata.idataserializer":1}
,"class:-com.wm.adapter.wmkafka.idata.idataserializer":{"deserializer":1}
,"deserializer":{"class:-com.wm.adapter.wmkafka.idata.idatadeserializer":1}
}
;Search.control.loadWordPairs(pairs);
