// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"disabling":{"listener":1}
,"listener":{"notifications":1,"notification":1}
,"notifications":{"disable":1,"using":1,"listener":1,"screen":1}
,"disable":{"listener":1}
,"using":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"disable":1,"click":1}
,"notification":{"adapters":1,"want":1,"becomes":1}
,"adapters":{"menu":1}
,"menu":{"navigation":1,"select":1}
,"navigation":{"area":1}
,"area":{"integration":1}
,"click":{"webmethods":1,"enabled":1}
,"webmethods":{"adapter":1}
,"adapter":{"apache":1}
,"apache":{"kafka":1}
,"kafka":{"webmethods":1,"menu":1}
,"select":{"listener":1}
,"screen":{"click":1}
,"enabled":{"column":1}
,"column":{"listener":1}
,"want":{"disable":1}
,"becomes":{"disabled":1}
,"disabled":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
