// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"package":1}
,"package":{"management":1}
,"management":{"following":1}
,"following":{"sections":1}
,"sections":{"describe":1}
,"describe":{"manage":1}
,"manage":{"webmethods":1}
,"webmethods":{"adapter":1}
,"adapter":{"apache":1}
,"apache":{"kafka":1}
,"kafka":{"packages":1}
,"packages":{"access":1}
,"access":{"control":1}
,"control":{"lists":1}
,"lists":{"(acls)":1}
}
;Search.control.loadWordPairs(pairs);
