// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"requirements":{"list":1,"adapter":1,"beyond":1}
,"list":{"operating":1}
,"operating":{"systems":1}
,"systems":{"webmethods":1}
,"webmethods":{"products":1,"adapters":1}
,"products":{"supported":1}
,"supported":{"adapter":1}
,"adapter":{"apache":1}
,"apache":{"kafka":1}
,"kafka":{"webmethods":1,"hardware":1}
,"adapters":{"system":1}
,"system":{"requirements":1}
,"hardware":{"requirements":1}
,"beyond":{"host":1}
,"host":{"integration":1}
,"integration":{"server":1}
}
;Search.control.loadWordPairs(pairs);
