// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"producers":{"producers":1,"publish":1}
,"publish":{"data":1}
,"data":{"topics":1}
,"topics":{"choice":1}
,"choice":{"oducer":1}
,"oducer":{"responsible":1}
,"responsible":{"choosing":1}
,"choosing":{"record":1}
,"record":{"assign":1}
,"assign":{"partition":1}
,"partition":{"within":1,"function":1}
,"within":{"topic":1}
,"topic":{"done":1}
,"done":{"rou":1,"accor":1}
,"rou":{"nd-robin":1}
,"nd-robin":{"fashion":1}
,"fashion":{"balance":1}
,"balance":{"load":1}
,"load":{"done":1}
,"accor":{"ding":1}
,"ding":{"semantic":1}
,"semantic":{"partition":1}
,"function":{"usage":1}
,"usage":{"key":1}
,"key":{"record":1}
}
;Search.control.loadWordPairs(pairs);
