// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"administrator":{"apis":1}
,"apis":{"administrator":1,"available":1,"samples":1}
,"available":{"adapter":1}
,"adapter":{"apache":1,"runtime":1}
,"apache":{"kafka":1}
,"kafka":{"information":1}
,"information":{"administrator":1}
,"samples":{"webmethods":1}
,"webmethods":{"adapter":1}
,"runtime":{"user\u0027s":1}
,"user\u0027s":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
