// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.adapter.wmkafka.topic:describe":{"wm.adapter.wmkafka.topic:describe":1,"allows":1}
,"allows":{"user":1}
,"user":{"describe":1}
,"describe":{"topics":1}
,"topics":{"input":1,"(string":1}
,"input":{"parameters":1}
,"parameters":{"$connectionname":1,"topicname":1}
,"$connectionname":{"(string)":1}
,"(string)":{"name":1}
,"name":{"producer":1,"(s)":1,"topic":1}
,"producer":{"consumer":1}
,"consumer":{"connection":1}
,"connection":{"topics":1}
,"(string":{"list)":1}
,"list)":{"name":1}
,"(s)":{"kafka":1,"dropped":1}
,"kafka":{"topic":1,"cluster":1}
,"topic":{"(s)":1,"isinternal":1,"internal":1,"comprised":1}
,"dropped":{"output":1}
,"output":{"parameters":1}
,"topicname":{"name":1}
,"isinternal":{"indicates":1}
,"indicates":{"topic":1}
,"internal":{"kafka":1}
,"cluster":{"partitions":1}
,"partitions":{"number":1,"kafka":1}
,"number":{"partitions":1}
}
;Search.control.loadWordPairs(pairs);
