// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"listener":1}
,"listener":{"notifications":1,"notification":1,"tification":1}
,"notifications":{"designer":1,"view":1}
,"designer":{"view":1,"expand":1,"displays":1}
,"view":{"listener":1,"select":1,"designer":1}
,"notification":{"review":1,"want":1,"adapte":1,"editor":1}
,"review":{"steps":1}
,"steps":{"configure":1}
,"configure":{"listener":1}
,"expand":{"package":1}
,"package":{"folder":1}
,"folder":{"contain":1}
,"contain":{"listener":1}
,"tification":{"want":1}
,"want":{"view":1}
,"select":{"listener":1}
,"displays":{"configured":1}
,"configured":{"listener":1}
,"adapte":{"r\u0027s":1}
,"r\u0027s":{"adapter":1}
,"adapter":{"notification":1}
}
;Search.control.loadWordPairs(pairs);
