// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"summary":{"elements":1}
,"elements":{"schedule":1,"available":1}
,"schedule":{"folder":1}
,"folder":{"following":1,"element":1}
,"following":{"elements":1}
,"available":{"folder":1}
,"element":{"description":1}
,"description":{"wm.mft.schedule:createremoteurl":1}
,"wm.mft.schedule:createremoteurl":{"creates":1}
,"creates":{"remote":1}
,"remote":{"file":1}
,"file":{"url":1}
,"url":{"format":1}
,"format":{"understood":1}
,"understood":{"activetransfer":1}
,"activetransfer":{"server":1}
,"server":{"wm.mft.schedule:executeevent":1}
,"wm.mft.schedule:executeevent":{"executes":1}
,"executes":{"event":1}
,"event":{"configured":1,"management":1}
,"configured":{"event":1}
,"management":{"page\u2019s":1}
,"page\u2019s":{"scheduled":1}
,"scheduled":{"events":1}
,"events":{"tab":1}
}
;Search.control.loadWordPairs(pairs);
