// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"introduction":{"managing":1}
,"managing":{"file":1}
,"file":{"transfers":1,"transfe":1}
,"transfers":{"webmethods":1}
,"webmethods":{"acti":1,"activetransfer":1}
,"acti":{"vetransfer":1}
,"vetransfer":{"agent":1}
,"agent":{"managing":1,"explains":1,"assumes":1}
,"activetransfer":{"agent":1,"server":1}
,"explains":{"install":1}
,"install":{"configure":1}
,"configure":{"manage":1}
,"manage":{"file":1}
,"transfe":{"webmethods":1}
,"assumes":{"familiar":1}
,"familiar":{"activetransfer":1}
,"server":{"described":1}
,"described":{"managing":1}
}
;Search.control.loadWordPairs(pairs);
