// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"managing":{"agents":1}
,"agents":{"groups":1}
,"groups":{"events":1}
}
;Search.control.loadWordPairs(pairs);
