// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.mft.server:listbannedips":{"based":1}
,"based":{"host":1}
,"host":{"server":1}
,"server":{"(activetransfer":1,"activetransfer":1,"lists":1}
,"(activetransfer":{"server":1}
,"activetransfer":{"gateway":1,"server":1}
,"gateway":{"integration":1,"input":1}
,"integration":{"server":1}
,"lists":{"addresses":1}
,"addresses":{"banned":1,"error":1}
,"banned":{"activetransfer":1,"addresses":1}
,"input":{"parameters":1}
,"parameters":{"none":1,"output":1}
,"none":{"output":1}
,"output":{"parameters":1,"document":1}
,"document":{"document":1,"type":1}
,"type":{"consists":1}
,"consists":{"following":1}
,"following":{"ips":1}
,"ips":{"list":1}
,"list":{"banned":1}
,"error":{"error":1,"message":1}
}
;Search.control.loadWordPairs(pairs);
