// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"adding":{"tunnel":1}
,"tunnel":{"add":1,"accelerate":1,"navigation":1,"dialog":1,"name":1,"created":1}
,"add":{"tunnel":1,"feature":1,"new":1}
,"accelerate":{"data":1}
,"data":{"transfer":1}
,"transfer":{"using":1}
,"using":{"uick":1}
,"uick":{"add":1}
,"feature":{"configure":1}
,"configure":{"additional":1}
,"additional":{"settings":1}
,"settings":{"unnel":1,"tunnel":1,"acceleration":1}
,"unnel":{"configuring":1}
,"configuring":{"additional":1}
,"navigation":{"pane":1}
,"pane":{"select":1}
,"select":{"settings":1}
,"acceleration":{"acceleration":1,"page":1}
,"page":{"click":1}
,"click":{"add":1}
,"dialog":{"box":1}
,"box":{"type":1}
,"type":{"tunnel":1}
,"name":{"click":1}
,"new":{"tunnel":1}
,"created":{"appears":1}
,"appears":{"acceleration":1}
}
;Search.control.loadWordPairs(pairs);
