// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.mft.server:unbanips":{"service":1}
,"service":{"unban":1}
,"unban":{"addresses":1,"output":1}
,"addresses":{"banned":1,"want":1,"provided":1}
,"banned":{"activetransfer":1}
,"activetransfer":{"server":1,"gateway":1}
,"server":{"activetransfer":1}
,"gateway":{"input":1}
,"input":{"parameters":1}
,"parameters":{"ips":1,"output":1}
,"ips":{"string":1}
,"string":{"list":1}
,"list":{"list":1,"addresses":1}
,"want":{"unban":1}
,"output":{"parameters":1,"document":1}
,"document":{"document":1,"type":1}
,"type":{"consists":1}
,"consists":{"following":1}
,"following":{"status":1}
,"status":{"status":1,"addresses":1}
,"provided":{"ser":1}
,"ser":{"vice":1}
,"vice":{"error":1}
,"error":{"error":1,"message":1}
}
;Search.control.loadWordPairs(pairs);
