// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mft.server.ftp.list.allowempty":{"specifies":1}
,"specifies":{"error":1}
,"error":{"code":1}
,"code":{"450":1}
,"450":{"returned":1}
,"returned":{"list":1}
,"list":{"command":1,"error":1}
,"command":{"file":1}
,"file":{"names":1}
,"names":{"exist":1}
,"exist":{"true":1}
,"true":{"activetransfer":1}
,"activetransfer":{"server":1}
,"server":{"returns":1}
,"returns":{"empty":1}
,"empty":{"list":1}
}
;Search.control.loadWordPairs(pairs);
