// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"idp":{"initiated":1}
,"initiated":{"single":1,"sso":1}
,"single":{"sign-on":1}
,"sign-on":{"properties.cnf":1}
,"properties.cnf":{"enable":1,"property":1}
,"enable":{"idp":1}
,"property":{"mft.server.https.auth.saml.redirecturi":1}
,"mft.server.https.auth.saml.redirecturi":{"enable":1}
,"sso":{"option":1}
}
;Search.control.loadWordPairs(pairs);
