// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mft.agent.client.auth.retry.interval":{"specifies":1}
,"specifies":{"interval":1}
,"interval":{"agent":1}
,"agent":{"checks":1}
,"checks":{"client":1}
,"client":{"uthentication":1}
,"uthentication":{"activetransfer":1}
,"activetransfer":{"server":1}
,"server":{"instance":1}
,"instance":{"every":1}
,"every":{"failed":1}
,"failed":{"attempt":1}
,"attempt":{"default":1}
,"default":{"value":1,"parameter":1}
,"value":{"seconds":1,"required":1}
,"seconds":{"modify":1}
,"modify":{"default":1}
,"parameter":{"value":1}
}
;Search.control.loadWordPairs(pairs);
