// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mft.client.file.optimizelisting":{"specifies":1}
,"specifies":{"activetransfer":1}
,"activetransfer":{"optimized":1,"list":1,"uses":1}
,"optimized":{"normal":1,"file":1}
,"normal":{"file":1}
,"file":{"listing":1}
,"listing":{"functionality":1}
,"functionality":{"microsoft":1,"retain":1}
,"microsoft":{"windows":1}
,"windows":{"server":1}
,"server":{"directories":1}
,"directories":{"extremely":1}
,"extremely":{"large":1}
,"large":{"number":1}
,"number":{"files":1}
,"files":{"activetransfer":1}
,"list":{"parameter":1}
,"parameter":{"true":1}
,"true":{"enable":1}
,"enable":{"optimized":1}
,"retain":{"default":1}
,"default":{"value":1}
,"value":{"false":1}
,"false":{"activetransfer":1}
,"uses":{"normal":1}
}
;Search.control.loadWordPairs(pairs);
