// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.mft.assets.rec.user:usertemplate":{"document":1}
,"document":{"type":1}
,"type":{"contains":1}
,"contains":{"activetransfer":1}
,"activetransfer":{"server":1}
,"server":{"user":1}
,"user":{"template":1}
,"template":{"details":1,"name":1,"description":1,"defaulttemplate":1,"configured":1,"activetransfer":1}
,"details":{"variables":1}
,"variables":{"string":1}
,"string":{"(optional)":1,"name":1}
,"(optional)":{"internal":1,"description":1,"variable":1}
,"internal":{"identifier":1}
,"identifier":{"activetransfer":1}
,"name":{"string":1,"user":1}
,"description":{"string":1,"activetransfer":1}
,"defaulttemplate":{"string":1}
,"variable":{"true":1}
,"true":{"template":1}
,"configured":{"default":1}
,"default":{"template":1}
}
;Search.control.loadWordPairs(pairs);
