// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mft.server":{"section":1}
,"section":{"describes":1}
,"describes":{"parameters":1}
,"parameters":{"configure":1}
,"configure":{"activetransfer":1}
,"activetransfer":{"server":1,"web":1}
,"server":{"enable":1,"access":1}
,"enable":{"sso":1}
,"sso":{"mft.server.https.auth.saml":1,"https":1}
,"mft.server.https.auth.saml":{"default":1}
,"default":{"value":1}
,"value":{"false":1}
,"false":{"parameter":1}
,"parameter":{"true":1}
,"true":{"enable":1}
,"https":{"listeners":1}
,"listeners":{"activetransfer":1}
,"access":{"activetransfer":1}
,"web":{"client":1}
,"client":{"mft.server.https.auth.saml.redirecturi":1}
,"mft.server.https.auth.saml.redirecturi":{"specifies":1}
,"specifies":{"redirection":1}
,"redirection":{"uri":1}
,"uri":{"redirection":1,"provided":1}
,"provided":{"registering":1}
,"registering":{"identity":1}
,"identity":{"provider":1}
}
;Search.control.loadWordPairs(pairs);
