// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mft.client.ftp.list.command":{"specifies":1}
,"specifies":{"list":1}
,"list":{"command":1,"activetransfer":1,"file":1,"default":1}
,"command":{"remote":1,"list":1,"activetransfer":1,"used":1}
,"remote":{"ftp":1,"servers":1}
,"ftp":{"servers":1}
,"servers":{"value":1,"list":1,"support":1,"remote":1}
,"value":{"parameter":1,"specified":1}
,"parameter":{"case-sensitive":1,"value":1}
,"case-sensitive":{"possibl":1}
,"possibl":{"values":1}
,"values":{"list":1}
,"activetransfer":{"executes":1}
,"executes":{"list":1,"mlst":1}
,"file":{"directories":1}
,"directories":{"remote":1}
,"default":{"value":1}
,"specified":{"value":1,"invalid":1}
,"invalid":{"mlst":1}
,"mlst":{"remote":1,"command":1}
,"support":{"mlst":1}
}
;Search.control.loadWordPairs(pairs);
