// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"activetransfer":{"agent":1,"server":1}
,"agent":{"works":1,"activetransfer":1}
,"works":{"following":1}
,"following":{"diagram":1}
,"diagram":{"illustrates":1}
,"illustrates":{"typical":1}
,"typical":{"setup":1}
,"setup":{"activetransfer":1}
,"server":{"communicates":1}
,"communicates":{"activetransfer":1}
}
;Search.control.loadWordPairs(pairs);
