// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"configure":1}
,"configure":{"following":1}
,"following":{"global":1}
,"global":{"settings":1}
,"settings":{"activetransfer":1}
}
;Search.control.loadWordPairs(pairs);
