// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"migration":{"methods":1}
,"methods":{"migrate":1}
,"migrate":{"activetransfer":1}
,"activetransfer":{"assets":1,"built-in":1,"details":1}
,"assets":{"assets":1,"certain":1,"thin":1,"wm.mft.admin:exportdata":1,"webmethods":1,"within":1,"importing":1,"exporting":1}
,"certain":{"type":1}
,"type":{"selected":1,"following":1}
,"selected":{"assets":1}
,"thin":{"asset":1}
,"asset":{"type":1}
,"following":{"methods":1}
,"wm.mft.admin:exportdata":{"wm.mft.admin:importdata":1}
,"wm.mft.admin:importdata":{"built-in":1}
,"built-in":{"services":1}
,"services":{"details":1,"webmethods":1,"reference":1}
,"details":{"built-in":1,"deployer":1,"import":1}
,"webmethods":{"activetransfer":1,"deployer":1}
,"reference":{"repository-based":1}
,"repository-based":{"deployment":1}
,"deployment":{"deployer":1}
,"deployer":{"details":1,"migrate":1,"user\u2019s":1}
,"user\u2019s":{"guide":1}
,"guide":{"importing":1}
,"importing":{"exporting":1,"assets":1}
,"exporting":{"assets":1}
,"within":{"activetransfer":1}
,"import":{"export":1}
,"export":{"assets":1}
}
;Search.control.loadWordPairs(pairs);
