// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"user":{"document":1,"user":1,"template":1,"wm.mft.assets.rec.user:userinfo":1,"wm.mft.assets.rec.user:usertemplate":1}
,"document":{"types":1,"type":1}
,"types":{"activetransfer":1,"referred":1,"document":1}
,"activetransfer":{"server":1}
,"server":{"provides":1,"user":1}
,"provides":{"document":1}
,"referred":{"user":1}
,"template":{"services":1,"details":1}
,"services":{"following":1}
,"following":{"table":1}
,"table":{"lists":1}
,"lists":{"document":1}
,"type":{"description":1,"contains":1}
,"description":{"wm.mft.assets.rec.user:user":1}
,"wm.mft.assets.rec.user:user":{"document":1}
,"contains":{"complete":1,"information":1,"activetransfer":1}
,"complete":{"details":1}
,"details":{"activetransfer":1}
,"wm.mft.assets.rec.user:userinfo":{"document":1}
,"information":{"activetransfer":1}
,"wm.mft.assets.rec.user:usertemplate":{"document":1}
}
;Search.control.loadWordPairs(pairs);
