// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"modifying":{"tunnel":1}
,"tunnel":{"edit":1,"navigation":1,"want":1,"click":1,"updated":1}
,"edit":{"configuration":1,"modify":1}
,"configuration":{"settings":1}
,"settings":{"existing":1,"acceleration":1,"tunnel":1}
,"existing":{"tunne":1}
,"tunne":{"modify":1}
,"modify":{"tunnel":1,"required":1}
,"navigation":{"pane":1}
,"pane":{"select":1}
,"select":{"settings":1}
,"acceleration":{"acceleration":1,"page":1}
,"page":{"click":1}
,"click":{"tunnel":1,"save":1}
,"want":{"edit":1}
,"required":{"configuration":1}
,"save":{"save":1,"&close":1}
,"&close":{"tunnel":1}
,"updated":{"modified":1}
,"modified":{"settings":1}
}
;Search.control.loadWordPairs(pairs);
