// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mft.agent.event.log.activitytypes":{"specifies":1}
,"specifies":{"types":1}
,"types":{"agent":1}
,"agent":{"event":1,"asset":1}
,"event":{"activities":1,"agent":1}
,"activities":{"logs":1,"logged":1}
,"logs":{"created":1}
,"created":{"property":1}
,"property":{"controls":1}
,"controls":{"level":1}
,"level":{"loggi":1}
,"loggi":{"happens":1}
,"happens":{"default":1}
,"default":{"value":1,"parameter":1}
,"value":{"mft.agent.event.log.activitytypes=asset":1,"required":1}
,"mft.agent.event.log.activitytypes=asset":{"auth":1}
,"auth":{"event":1}
,"asset":{"authorization":1}
,"authorization":{"event":1}
,"logged":{"modify":1}
,"modify":{"default":1}
,"parameter":{"value":1}
}
;Search.control.loadWordPairs(pairs);
