// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"values":{"server":1,"jump":1,"separate":1}
,"server":{"variables":1}
,"variables":{"specify":1,"values":1}
,"specify":{"values":1,"multiple":1}
,"jump":{"condition":1}
,"condition":{"eck":1,"note":1}
,"eck":{"last":1}
,"last":{"part":1}
,"part":{"jump":1}
,"note":{"specify":1}
,"multiple":{"server":1}
,"separate":{"space":1}
}
;Search.control.loadWordPairs(pairs);
