// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"agent":{"event":1,"events":1}
,"event":{"statuses":1,"status":1,"execution":1,"triggerred":1}
,"statuses":{"activetransfer":1,"event":1}
,"activetransfer":{"server":1}
,"server":{"agent":1}
,"events":{"listed":1,"page":1}
,"listed":{"agent":1}
,"page":{"following":1}
,"following":{"statuses":1}
,"status":{"description":1}
,"description":{"success":1}
,"success":{"event":1}
,"execution":{"successful":1,"failed":1,"triggered":1,"queue":1,"progress":1,"completed":1}
,"successful":{"failure":1}
,"failure":{"event":1}
,"failed":{"started":1}
,"started":{"event":1}
,"triggered":{"queue":1}
,"queue":{"event":1,"progress":1}
,"triggerred":{"waiting":1}
,"waiting":{"execution":1}
,"progress":{"event":1,"done":1}
,"done":{"error":1}
,"error":{"event":1}
,"completed":{"errors":1}
}
;Search.control.loadWordPairs(pairs);
