// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mft.agent.client.assets.refresh.interval":{"specifies":1}
,"specifies":{"time":1}
,"time":{"interval":1}
,"interval":{"agent":1}
,"agent":{"interacts":1,"event":1}
,"interacts":{"activetransfer":1}
,"activetransfer":{"server":1}
,"server":{"instance":1,"modify":1}
,"instance":{"check":1}
,"check":{"updates":1}
,"updates":{"agent":1,"increase":1,"server":1}
,"event":{"assets":1,"updates":1}
,"assets":{"default":1}
,"default":{"value":1,"parameter":1}
,"value":{"300":1,"view":1,"avoid":1,"required":1}
,"300":{"seconds":1}
,"seconds":{"decrease":1}
,"decrease":{"value":1}
,"view":{"recent":1}
,"recent":{"updates":1}
,"increase":{"value":1}
,"avoid":{"unnecessary":1}
,"unnecessary":{"checks":1}
,"checks":{"few":1}
,"few":{"agent":1}
,"modify":{"default":1}
,"parameter":{"value":1}
}
;Search.control.loadWordPairs(pairs);
