// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"creating":{"new":1}
,"new":{"folder":1}
,"folder":{"create":1,"top":1,"organize":1,"web":1,"inside":1,"select":1,"click":1,"dialog":1,"want":1,"immediately":1,"creation":1}
,"create":{"folder":1,"new":1,"select":1}
,"top":{"level":1}
,"level":{"inside":1,"click":1}
,"inside":{"folde":1,"folder":1}
,"folde":{"new":1}
,"organize":{"files":1}
,"files":{"upload":1}
,"upload":{"ownload":1}
,"ownload":{"create":1}
,"web":{"client":1}
,"client":{"following":1}
,"following":{"create":1}
,"click":{"create":1}
,"select":{"folder":1,"navigate":1}
,"dialog":{"box":1}
,"box":{"enter":1}
,"enter":{"name":1}
,"name":{"folder":1}
,"want":{"navigate":1}
,"navigate":{"new":1,"folder":1}
,"immediately":{"create":1}
,"creation":{"click":1}
}
;Search.control.loadWordPairs(pairs);
