// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"modifying":{"listener":1}
,"listener":{"edit":1,"navigation":1,"want":1,"click":1}
,"edit":{"configuration":1,"modify":1}
,"configuration":{"settings":1}
,"settings":{"existing":1,"listener":1}
,"existing":{"liste":1}
,"liste":{"ner":1}
,"ner":{"created":1}
,"created":{"activetransfer":1}
,"activetransfer":{"server":1,"gateway":1}
,"server":{"activetransfer":1}
,"gateway":{"instance":1}
,"instance":{"modify":1,"list":1,"click":1,"updated":1}
,"modify":{"listener":1,"required":1}
,"navigation":{"pane":1}
,"pane":{"select":1}
,"select":{"listeners":1,"activetransfer":1}
,"listeners":{"listeners":1,"page":1}
,"page":{"instance":1}
,"list":{"select":1}
,"click":{"listener":1,"save":1}
,"want":{"edit":1}
,"required":{"configuration":1}
,"save":{"save":1,"&close":1}
,"&close":{"activetransfer":1}
,"updated":{"modified":1}
,"modified":{"settings":1}
}
;Search.control.loadWordPairs(pairs);
