// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mft.server.dmz.cert.hostnames":{"comma-separated":1}
,"comma-separated":{"hostnames":1}
,"hostnames":{"activetransfer":1}
,"activetransfer":{"uses":1}
,"uses":{"validate":1}
,"validate":{"gateways":1}
,"gateways":{"ssl":1}
,"ssl":{"certificate\u0027s":1}
,"certificate\u0027s":{"hostnames":1}
}
;Search.control.loadWordPairs(pairs);
