// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"modifying":{"post-processing":1}
,"post-processing":{"scheduled":1,"actions":1}
,"scheduled":{"monitor":1,"actions":1}
,"monitor":{"folder":1}
,"folder":{"tion":1,"action":1,"actions":1}
,"tion":{"edit":1}
,"edit":{"configuration":1,"modify":1}
,"configuration":{"settings":1}
,"settings":{"existing":1,"action":1}
,"existing":{"post-processing":1}
,"action":{"modify":1,"navigation":1,"want":1,"click":1,"updated":1}
,"modify":{"action":1,"required":1}
,"navigation":{"pane":1}
,"pane":{"select":1}
,"select":{"actions":1}
,"actions":{"post-processing":1,"scheduled":1,"monitor":1,"page":1}
,"page":{"click":1}
,"click":{"action":1,"save":1}
,"want":{"edit":1}
,"required":{"configuration":1}
,"save":{"action":1}
,"updated":{"modified":1}
,"modified":{"settings":1}
}
;Search.control.loadWordPairs(pairs);
