// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"scheduling":{"jobs":1,"services":1,"user":1}
,"jobs":{"run":1,"servers":1}
,"run":{"stateful":1,"tar":1,"servers":1,"rget":1}
,"stateful":{"stateless":1,"cluster":1}
,"stateless":{"cluster":1,"clus":1}
,"cluster":{"stateful":1,"schedule":1}
,"schedule":{"jobs":1}
,"tar":{"node":1}
,"node":{"server":1}
,"server":{"specific":1,"servers":1,"stateless":1}
,"specific":{"server":1}
,"servers":{"jobs":1,"enabled":1,"instructions":1}
,"enabled":{"clusteri":1}
,"clusteri":{"stateless":1}
,"rget":{"node":1}
,"clus":{"ters":1}
,"ters":{"support":1}
,"support":{"running":1}
,"running":{"jobs":1}
,"instructions":{"scheduling":1}
,"services":{"scheduling":1}
,"user":{"task":1}
}
;Search.control.loadWordPairs(pairs);
