// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"connection":1}
,"connection":{"messaging":1,"alias":1}
,"messaging":{"provider":1,"providers":1,"and\u002For":1,"facility":1,"connection":1,"authenticating":1,"server":1}
,"provider":{"want":1,"configure":1,"integration":1,"(broker":1}
,"want":{"webmethods":1}
,"webmethods":{"messaging":1,"broker":1}
,"providers":{"(universal":1}
,"(universal":{"messaging":1}
,"and\u002For":{"broker":1}
,"broker":{"messaging":1,"administering":1}
,"facility":{"distributing":1}
,"distributing":{"documents":1}
,"documents":{"eed":1,"locally":1}
,"eed":{"configure":1}
,"configure":{"least":1,"connecti":1}
,"least":{"messaging":1}
,"alias":{"messaging":1}
,"connecti":{"messaging":1}
,"integration":{"server":1}
,"server":{"publishes":1,"information":1}
,"publishes":{"documents":1}
,"locally":{"detailed":1}
,"detailed":{"information":1}
,"information":{"configuring":1,"broker":1}
,"(broker":{"universal":1}
,"universal":{"messaging":1}
,"authenticating":{"connections":1}
,"connections":{"universal":1}
,"administering":{"webmethods":1}
}
;Search.control.loadWordPairs(pairs);
