// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"universalname":{"folder":1}
,"folder":{"elements":1,"list":1}
,"elements":{"universalname":1}
,"list":{"contents":1}
,"contents":{"universal":1}
,"universal":{"name":1,"names":1}
,"name":{"registry":1}
,"registry":{"look":1}
,"look":{"serv":1}
,"serv":{"ices":1}
,"ices":{"document":1}
,"document":{"types":1}
,"types":{"universal":1}
}
;Search.control.loadWordPairs(pairs);
