// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"supported":{"databases":1}
,"databases":{"webmethods":1,"using":1}
,"webmethods":{"integration":1}
,"integration":{"server":1}
,"server":{"connect":1,"2000":1}
,"connect":{"following":1}
,"following":{"databases":1}
,"using":{"wmdb":1,"jdbc":1}
,"wmdb":{"oracle":1,"connects":1,"package":1}
,"oracle":{"sql":1}
,"sql":{"server":1,"access":1}
,"2000":{"db2":1}
,"db2":{"udb":1}
,"udb":{"8.1":1}
,"8.1":{"sql":1}
,"access":{"wmdb":1}
,"connects":{"databases":1}
,"jdbc":{"driver":1}
,"driver":{"provi":1}
,"provi":{"ded":1}
,"ded":{"vendor":1}
,"vendor":{"important":1}
,"important":{"wmdb":1}
,"package":{"support":1}
,"support":{"sybase":1}
,"sybase":{"ase":1}
,"ase":{"12.5":1}
}
;Search.control.loadWordPairs(pairs);
