// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"output":1}
,"output":{"templates":1}
,"templates":{"format":1}
,"format":{"service":1}
,"service":{"output":1}
}
;Search.control.loadWordPairs(pairs);
