// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"summary":{"elements":1}
,"elements":{"folder":1,"available":1}
,"folder":{"following":1,"element":1}
,"following":{"elements":1}
,"available":{"folder":1}
,"element":{"package":1}
,"package":{"description":1}
,"description":{"pub.report:runfiletemplate":1}
,"pub.report:runfiletemplate":{"wmpublic":1}
,"wmpublic":{"applies":1}
,"applies":{"template":1,"output":1}
,"template":{"file":1,"pipeline":1,"specified":1}
,"file":{"document":1,"specified":1,"pipeline":1}
,"document":{"(idata":1}
,"(idata":{"objec":1,"object)":1}
,"objec":{"pub.report:runfiletemplateonpipe":1}
,"pub.report:runfiletemplateonpipe":{"wmpublic":1}
,"pipeline":{"pub.report:runstringtemplate":1,"pub.report:runtemplate":1}
,"pub.report:runstringtemplate":{"wmpublic":1}
,"output":{"template":1}
,"specified":{"document":1,"docume":1}
,"object)":{"pub.report:runstringtemplateonpipe":1,"pub.report:runtemplateonpipe":1}
,"pub.report:runstringtemplateonpipe":{"wmpublic":1}
,"pub.report:runtemplate":{"wmpublic":1}
,"docume":{"(idata":1}
,"pub.report:runtemplateonpipe":{"wmpublic":1}
}
;Search.control.loadWordPairs(pairs);
