// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"working":{"caches":1}
,"caches":{"procedures":1}
,"procedures":{"section":1}
,"section":{"describe":1}
,"describe":{"create":1}
,"create":{"edit":1}
,"edit":{"clear":1}
,"clear":{"disable":1}
,"disable":{"enable":1}
,"enable":{"delete":1}
,"delete":{"cache":1}
}
;Search.control.loadWordPairs(pairs);
