// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"editing":{"scopes":1}
,"scopes":{"complete":1}
,"complete":{"following":1}
,"following":{"steps":1}
,"steps":{"edit":1}
,"edit":{"scope":1,"update":1}
,"scope":{"edit":1,"open":1,"management":1,"configuration":1,"want":1,"note":1,"click":1}
,"open":{"integration":1,"security":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"already":1}
,"already":{"open":1}
,"security":{"oauth":1}
,"oauth":{"click":1}
,"click":{"scope":1,"name":1,"save":1}
,"management":{"scope":1}
,"configuration":{"click":1}
,"name":{"scope":1,"field":1}
,"want":{"edit":1}
,"update":{"information":1}
,"information":{"scope":1}
,"note":{"cannot":1}
,"cannot":{"change":1}
,"change":{"name":1}
,"field":{"scope":1}
,"save":{"changes":1}
}
;Search.control.loadWordPairs(pairs);
