// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.math:randomdouble":{"wmpublic":1}
,"wmpublic":{"returns":1}
,"returns":{"next":1}
,"next":{"pseudorandom":1}
,"pseudorandom":{"uniformly":1}
,"uniformly":{"distribut":1}
,"distribut":{"double":1}
,"double":{"0.0":1}
,"0.0":{"1.0":1}
,"1.0":{"random":1}
,"random":{"number":1}
,"number":{"generators":1,"string":1}
,"generators":{"often":1,"numbers":1}
,"often":{"referred":1}
,"referred":{"pseudorand":1}
,"pseudorand":{"number":1}
,"numbers":{"produced":1}
,"produced":{"tend":1}
,"tend":{"peat":1}
,"peat":{"themselves":1}
,"themselves":{"time":1}
,"time":{"input":1}
,"input":{"parameters":1}
,"parameters":{"none":1,"number":1}
,"none":{"output":1}
,"output":{"parameters":1}
,"string":{"generated":1}
,"generated":{"random":1}
}
;Search.control.loadWordPairs(pairs);
