// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"suspending":{"user":1}
,"user":{"tasks":1,"task":1}
,"tasks":{"suspend":1,"integration":1}
,"suspend":{"single":1}
,"single":{"user":1}
,"task":{"scheduled":1}
,"scheduled":{"user":1}
,"integration":{"server":1}
}
;Search.control.loadWordPairs(pairs);
