// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mime":{"folder":1,"messages":1}
,"folder":{"elements":1,"create":1}
,"elements":{"mime":1}
,"create":{"mime":1}
,"messages":{"extract":1}
,"extract":{"information":1}
,"information":{"mime":1}
}
;Search.control.loadWordPairs(pairs);
