// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"art":{"folder":1}
,"folder":{"elements":1,"manage":1}
,"elements":{"art":1}
,"manage":{"adapter":1}
,"adapter":{"com":1,"services":1}
,"com":{"ponents":1}
,"ponents":{"including":1}
,"including":{"connections":1}
,"connections":{"adapter":1}
,"services":{"listeners":1}
,"listeners":{"notifications":1}
}
;Search.control.loadWordPairs(pairs);
