// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"editing":{"url":1}
,"url":{"alias":1,"aliases":1}
,"alias":{"integration":1,"open":1,"list":1,"edit":1,"click":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"edit":1,"cannot":1,"already":1}
,"edit":{"url":1,"changes":1}
,"aliases":{"created":1,"http":1}
,"created":{"integration":1,"designer":1}
,"cannot":{"edit":1}
,"designer":{"edit":1}
,"open":{"integration":1,"settings":1}
,"already":{"open":1}
,"settings":{"url":1}
,"http":{"url":1}
,"list":{"select":1}
,"select":{"url":1}
,"changes":{"url":1}
,"click":{"save":1}
,"save":{"changes":1}
}
;Search.control.loadWordPairs(pairs);
