// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"listen":{"mode":1,"keep-alive":1}
,"mode":{"settings":1,"parameter":1}
,"settings":{"following":1}
,"following":{"table":1}
,"table":{"configure":1}
,"configure":{"listen":1}
,"keep-alive":{"mode":1}
,"parameter":{"value":1}
,"value":{"watt.server.brokertransport.dur":1}
,"watt.server.brokertransport.dur":{"2147483647":1}
,"2147483647":{"watt.server.brokertransport.max":1,"watt.server.brokertransport.ret":1}
,"watt.server.brokertransport.max":{"integer":1}
,"integer":{"greater":1}
,"greater":{"zero":1}
,"zero":{"less":1}
,"less":{"2147483647":1}
,"watt.server.brokertransport.ret":{"n\u002Fa":1}
,"n\u002Fa":{"retry":1}
,"retry":{"count":1}
,"count":{"ignored":1}
,"ignored":{"listen":1}
}
;Search.control.loadWordPairs(pairs);
