// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"audit":1}
,"audit":{"logging":1}
,"logging":{"webmethods":1,"data":1,"maintained":1}
,"webmethods":{"products":1,"system":1,"product":1}
,"products":{"provides":1}
,"provides":{"important":1}
,"important":{"data":1}
,"data":{"need":1,"webmethods":1}
,"need":{"monitor":1}
,"monitor":{"webmethods":1}
,"system":{"activity":1}
,"activity":{"correct":1}
,"correct":{"problems":1}
,"problems":{"integration":1}
,"integration":{"server":1}
,"server":{"maintains":1}
,"maintains":{"audit":1}
,"product":{"suite":1}
,"suite":{"chapter":1}
,"chapter":{"describes":1}
,"describes":{"audit":1}
,"maintained":{"integration":1}
}
;Search.control.loadWordPairs(pairs);
