// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.string:isalphanumeric":{"wmpublic":1}
,"wmpublic":{"determines":1}
,"determines":{"whether":1}
,"whether":{"string":1,"characters":1}
,"string":{"consists":1,"optional":1,"checked":1,"indicates":1}
,"consists":{"entirely":1}
,"entirely":{"lphanumeric":1}
,"lphanumeric":{"characters":1}
,"characters":{"(in":1,"output":1,"instring":1}
,"(in":{"ranges":1}
,"ranges":{"input":1}
,"input":{"parameters":1}
,"parameters":{"instring":1,"isalphanumeric":1}
,"instring":{"string":1,"alphanumeric":1,"specified":1}
,"optional":{"string":1}
,"checked":{"alphanumeric":1}
,"alphanumeric":{"characters":1,"true":1,"false":1,"service":1}
,"output":{"parameters":1}
,"isalphanumeric":{"string":1}
,"indicates":{"whether":1,"characters":1}
,"true":{"indicates":1}
,"false":{"indicates":1,"instring":1}
,"service":{"returns":1}
,"returns":{"false":1}
}
;Search.control.loadWordPairs(pairs);
