// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"timestamp":{"element":1}
,"element":{"inbound":1,"supplies":1}
,"inbound":{"messages":1}
,"messages":{"<timestamp>":1,"generate":1}
,"<timestamp>":{"element":1}
,"supplies":{"settings":1}
,"settings":{"enforce":1}
,"enforce":{"message":1}
,"message":{"expiration":1}
,"expiration":{"default":1,"enforced":1}
,"default":{"expired":1,"expiration":1}
,"expired":{"messages":1}
,"generate":{"exception":1}
,"exception":{"however":1}
,"however":{"setting":1}
,"setting":{"turn":1}
,"turn":{"message":1}
,"enforced":{"example":1}
,"example":{"<timestamp":1}
,"<timestamp":{"enforceexpiration=\u0022":1}
,"enforceexpiration=\u0022":{"false":1}
,"false":{"\u0022\u002F>":1}
}
;Search.control.loadWordPairs(pairs);
