// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.string:indexof":{"wmpublic":1}
,"wmpublic":{"returns":1}
,"returns":{"index":1}
,"index":{"first":1,"instring":1}
,"first":{"occurrence":1}
,"occurrence":{"seq":1,"substring":1,"found":1}
,"seq":{"uence":1}
,"uence":{"characters":1}
,"characters":{"string":1,"substring":1,"locate":1}
,"string":{"input":1,"string":1,"want":1,"sequence":1,"optional":1,"output":1,"index":1}
,"input":{"parameters":1}
,"parameters":{"instring":1,"value":1}
,"instring":{"string":1,"start":1,"occurrence":1}
,"want":{"locate":1}
,"locate":{"sequence":1,"fromindex":1}
,"sequence":{"characters":1}
,"substring":{"string":1,"instring":1}
,"fromindex":{"string":1}
,"optional":{"index":1}
,"start":{"search":1}
,"search":{"value":1}
,"value":{"specified":1,"string":1}
,"specified":{"parameter":1}
,"parameter":{"contains":1}
,"contains":{"indicate":1}
,"indicate":{"beginning":1}
,"beginning":{"string":1}
,"output":{"parameters":1}
,"found":{"parameter":1}
}
;Search.control.loadWordPairs(pairs);
