// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"appendix":1}
,"appendix":{"contains":1}
,"contains":{"procedures":1}
,"procedures":{"guidelines":1}
,"guidelines":{"using":1}
,"using":{"sps":1}
,"sps":{"output":1}
,"output":{"templates":1}
,"templates":{"different":1}
,"different":{"languages":1}
,"languages":{"(or":1}
,"(or":{"tran":1}
,"tran":{"slating":1}
,"slating":{"languages)":1}
,"languages)":{"webmethods":1}
,"webmethods":{"integration":1}
,"integration":{"server":1}
}
;Search.control.loadWordPairs(pairs);
