// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"transactions":{"integration":1}
,"integration":{"server":1}
,"server":{"considers":1}
,"considers":{"transaction":1}
,"transaction":{"interactions":1,"eith":1}
,"interactions":{"resources":1,"within":1}
,"resources":{"treated":1}
,"treated":{"single":1}
,"single":{"logical":1}
,"logical":{"unit":1}
,"unit":{"work":1}
,"work":{"interactions":1}
,"within":{"transaction":1}
,"eith":{"committed":1}
,"committed":{"rolled":1}
,"rolled":{"back":1}
,"back":{"example":1}
,"example":{"trans":1}
,"trans":{"action":1}
,"action":{"includes":1}
,"includes":{"multiple":1}
,"multiple":{"database":1}
,"database":{"inserts":1}
,"inserts":{"nserts":1,"rolled":1}
,"nserts":{"fail":1}
,"fail":{"inserts":1}
}
;Search.control.loadWordPairs(pairs);
