// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mapping":{"ldap":1,"acl":1}
,"ldap":{"user\u0027s":1,"groups":1,"group":1}
,"user\u0027s":{"access":1}
,"access":{"acls":1,"integration":1}
,"acls":{"integration":1,"control":1,"page":1,"refer":1}
,"integration":{"server":1}
,"server":{"groups":1,"resources":1}
,"groups":{"associate":1,"acls":1,"done":1,"access":1}
,"associate":{"ldap":1}
,"control":{"access":1}
,"resources":{"associating":1}
,"associating":{"ldap":1}
,"group":{"acl":1,"access":1}
,"acl":{"referre":1,"mapping":1}
,"referre":{"mapping":1}
,"done":{"directly":1}
,"directly":{"security":1}
,"security":{"acls":1}
,"page":{"information":1}
,"information":{"allowing":1}
,"allowing":{"groups":1,"denying":1}
,"refer":{"allowing":1}
,"denying":{"group":1}
}
;Search.control.loadWordPairs(pairs);
