// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"summary":{"elements":1}
,"elements":{"folder":1,"available":1,"pub.datetime:increment":1}
,"folder":{"following":1,"element":1}
,"following":{"elements":1}
,"available":{"folder":1}
,"element":{"package":1}
,"package":{"description":1}
,"description":{"pub.datetime:build":1}
,"pub.datetime:build":{"wmpublic":1}
,"wmpublic":{"builds":1,"increments":1}
,"builds":{"date\u002Ftime":1}
,"date\u002Ftime":{"string":1,"elements":1}
,"string":{"using":1}
,"using":{"specified":1}
,"specified":{"patt":1}
,"patt":{"ern":1}
,"ern":{"supplied":1}
,"supplied":{"date\u002Ftime":1}
,"pub.datetime:increment":{"wmpublic":1}
,"increments":{"decrements":1}
,"decrements":{"date":1}
,"date":{"time":1}
,"time":{"spec":1}
,"spec":{"ified":1}
,"ified":{"amount":1}
,"amount":{"time":1}
}
;Search.control.loadWordPairs(pairs);
