// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"jms":1}
,"jms":{"trigger":1}
,"trigger":{"groups":1}
}
;Search.control.loadWordPairs(pairs);
