// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"session":{"audit":1,"log":1}
,"audit":{"logging":1}
,"logging":{"session":1,"provides":1}
,"provides":{"data":1}
,"data":{"sessions":1}
,"sessions":{"opened":1,"start":1}
,"opened":{"integration":1}
,"integration":{"server":1}
,"server":{"designer":1}
,"designer":{"third-party":1}
,"third-party":{"clients":1}
,"clients":{"servers":1}
,"servers":{"session":1}
,"log":{"entries":1}
,"entries":{"following":1}
,"following":{"track":1}
,"track":{"sessions":1}
,"start":{"current":1}
,"current":{"status":1}
,"status":{"uration":1}
,"uration":{"record":1}
,"record":{"client":1}
,"client":{"initiated":1}
,"initiated":{"session":1}
}
;Search.control.loadWordPairs(pairs);
