// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"schema":{"folder":1}
,"folder":{"elements":1,"validate":1}
,"elements":{"schema":1}
,"validate":{"object":1,"pipeline":1}
,"object":{"validate":1}
}
;Search.control.loadWordPairs(pairs);
