// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"extracting":{"payload":1}
,"payload":{"mime":1}
,"mime":{"message":1,"object":1}
,"message":{"extract":1,"services":1,"extr":1}
,"extract":{"information":1}
,"information":{"mime":1}
,"services":{"pub.mime":1}
,"pub.mime":{"folder":1}
,"folder":{"create":1}
,"create":{"mime":1}
,"object":{"mime":1}
,"extr":{"act":1}
,"act":{"data":1}
}
;Search.control.loadWordPairs(pairs);
