// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"stage":{"archive":1}
,"archive":{"sources":1,"master":1,"copy":1}
,"sources":{"archive":1}
,"master":{"copy":1}
,"copy":{"packages":1,"contents":1,"source":1}
,"packages":{"server":1}
,"server":{"source":1}
,"source":{"files":1}
,"files":{"used":1,"went":1}
,"used":{"build":1}
,"build":{"step":1}
,"step":{"action":1}
,"action":{"done":1}
,"done":{"copy":1}
,"contents":{"server\u005Cpackages":1}
,"server\u005Cpackages":{"directory":1}
,"directory":{"anothe":1}
,"anothe":{"device":1}
,"device":{"backup":1}
,"backup":{"archival":1}
,"archival":{"purposes":1}
,"purposes":{"archive":1}
,"went":{"produc":1}
,"produc":{"ing":1}
,"ing":{"services":1}
,"services":{"deployed":1}
,"deployed":{"server":1}
}
;Search.control.loadWordPairs(pairs);
