// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"resuming":{"http\u002Fhttps":1}
,"http\u002Fhttps":{"port":1}
,"port":{"resume":1,"suspended":1,"open":1,"list":1,"want":1}
,"resume":{"port":1,"http":1,"listener":1,"check":1}
,"suspended":{"resume":1}
,"http":{"https":1}
,"https":{"port":1}
,"open":{"integration":1,"server":1}
,"integration":{"server":1}
,"server":{"administrator":1,"ports":1}
,"administrator":{"already":1}
,"already":{"open":1}
,"ports":{"port":1}
,"list":{"table":1}
,"table":{"click":1}
,"click":{"edit":1,"apply":1,"return":1}
,"edit":{"advanced":1}
,"advanced":{"column":1}
,"column":{"port":1}
,"want":{"resume":1}
,"listener":{"controls":1}
,"controls":{"select":1}
,"select":{"resume":1}
,"check":{"box":1}
,"box":{"click":1}
,"apply":{"save":1}
,"save":{"changes":1}
,"changes":{"click":1}
,"return":{"ports":1}
}
;Search.control.loadWordPairs(pairs);
