// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.websocket:onconnect":{"wmpublic":1}
,"wmpublic":{"specification":1}
,"specification":{"callback":1}
,"callback":{"service":1}
,"service":{"related":1}
,"related":{"bsocket":1}
,"bsocket":{"server":1}
,"server":{"client":1}
,"client":{"endpoint":1}
,"endpoint":{"gets":1}
,"gets":{"invoked":1}
,"invoked":{"ebsocket":1}
,"ebsocket":{"session":1}
,"session":{"successfully":1,"identify":1,"output":1}
,"successfully":{"established":1}
,"established":{"input":1}
,"input":{"parameters":1}
,"parameters":{"sessionid":1,"none":1}
,"sessionid":{"string":1}
,"string":{"session":1}
,"identify":{"websocket":1}
,"websocket":{"session":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
