// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"oracle":{"streams":1,"advanced":1,"database":1}
,"streams":{"advanced":1}
,"advanced":{"queuing":1}
,"queuing":{"(aq)":1}
,"(aq)":{"integration":1,"12.2.0":1}
,"integration":{"server":1}
,"server":{"tested":1}
,"tested":{"oracle":1}
,"12.2.0":{"files":1,"oracle_home":1}
,"files":{"copy":1}
,"copy":{"oracle":1}
,"oracle_home":{"\u005Cjdbc\u005Clib\u005Cojdbc8.jar":1,"\u005Cjlib\u005Corai18n.jar":1,"\u005Clib\u005Cxmlparserv2.jar":1,"\u005Crdbms\u005Cjlib\u005Caqapi.jar":1,"\u005Crdbms\u005Cjlib\u005Cjmscommon.jar":1,"\u005Crdbms\u005Cjlib\u005Cxdb.jar":1,"oracle_base":1}
,"\u005Cjdbc\u005Clib\u005Cojdbc8.jar":{"oracle_home":1}
,"\u005Cjlib\u005Corai18n.jar":{"oracle_home":1}
,"\u005Clib\u005Cxmlparserv2.jar":{"oracle_home":1}
,"\u005Crdbms\u005Cjlib\u005Caqapi.jar":{"oracle_home":1}
,"\u005Crdbms\u005Cjlib\u005Cjmscommon.jar":{"oracle_home":1}
,"\u005Crdbms\u005Cjlib\u005Cxdb.jar":{"oracle_home":1}
,"oracle_base":{"\u005Cproduct\u005C12.2.0\u005Cdb_1":1,"directory":1}
,"\u005Cproduct\u005C12.2.0\u005Cdb_1":{"oracle_base":1}
,"directory":{"oracle":1}
,"database":{"installed":1}
}
;Search.control.loadWordPairs(pairs);
