// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"creating":{"acls":1,"acl":1}
,"acls":{"creating":1,"click":1,"specify":1}
,"acl":{"select":1,"open":1,"name":1}
,"select":{"groups":1}
,"groups":{"allow":1,"denied":1,"previously":1,"create":1}
,"allow":{"groups":1}
,"denied":{"groups":1}
,"previously":{"defined":1}
,"defined":{"groups":1}
,"create":{"acl":1,"acls":1}
,"open":{"integration":1,"security":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"already":1}
,"already":{"open":1}
,"security":{"acls":1}
,"click":{"add":1,"create":1}
,"add":{"remove":1}
,"remove":{"acls":1}
,"specify":{"acl":1}
,"name":{"per":1}
,"per":{"line":1}
,"line":{"press":1}
,"press":{"enter":1}
,"enter":{"separate":1}
,"separate":{"ines":1}
,"ines":{"click":1}
}
;Search.control.loadWordPairs(pairs);
