// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"server":{"output":1,"applies":1}
,"output":{"template":1,"templates":1}
,"template":{"server":1}
,"applies":{"output":1}
,"templates":{"results":1,"pipeline":1}
,"results":{"servic":1}
,"servic":{"invoked":1}
,"invoked":{"http":1}
,"http":{"ftp":1,"https":1}
,"ftp":{"smtp":1}
,"smtp":{"clients":1,"listen":1}
,"clients":{"(i.e":1}
,"(i.e":{"req":1}
,"req":{"uests":1}
,"uests":{"http":1}
,"https":{"ftp":1}
,"listen":{"ers)":1}
,"ers)":{"arbitrarily":1}
,"arbitrarily":{"apply":1}
,"apply":{"output":1}
,"pipeline":{"using":1}
,"using":{"built-in":1}
,"built-in":{"services":1}
,"services":{"pub.report":1}
,"pub.report":{"folder":1}
}
;Search.control.loadWordPairs(pairs);
