// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"increasing":{"cache":1,"maximum":1}
,"cache":{"size":1,"increase":1}
,"size":{"stateful":1,"server":1,"modifying":1,"using":1}
,"stateful":{"cluster":1}
,"cluster":{"think":1}
,"think":{"integration":1}
,"integration":{"server":1}
,"server":{"sessions":1,"array":1,"cluste":1}
,"sessions":{"large":1}
,"large":{"portion":1}
,"portion":{"distributed":1}
,"distributed":{"terracotta":1}
,"terracotta":{"server":1}
,"array":{"cache":1}
,"increase":{"cache":1,"on-heap":1}
,"cluste":{"increase":1}
,"on-heap":{"cache":1}
,"modifying":{"maximum":1}
,"maximum":{"elements":1,"off-heap":1}
,"elements":{"disk":1}
,"disk":{"setting":1,"size":1}
,"setting":{"(see":1,"(working":1}
,"(see":{"increasing":1}
,"using":{"bigmemory":1}
,"bigmemory":{"modify":1}
,"modify":{"maximum":1}
,"off-heap":{"setting":1}
,"(working":{"caches":1}
}
;Search.control.loadWordPairs(pairs);
