// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sending":{"acknowledgement":1}
,"acknowledgement":{"request":1}
,"request":{"direct":1,"reliable":1,"open":1,"click":1}
,"direct":{"reliable":1}
,"reliable":{"messaging":1}
,"messaging":{"client":1,"server":1}
,"client":{"request":1,"sequences":1}
,"server":{"acknowledge":1,"administrator":1,"acknowledgement":1}
,"acknowledge":{"specific":1}
,"specific":{"message":1}
,"message":{"sequence":1}
,"sequence":{"send":1,"want":1}
,"send":{"acknowledgement":1,"acknowle":1,"link":1}
,"open":{"integration":1,"settings":1}
,"integration":{"server":1}
,"administrator":{"already":1}
,"already":{"open":1}
,"settings":{"web":1}
,"web":{"services":1}
,"services":{"click":1}
,"click":{"reliable":1,"send":1}
,"sequences":{"locate":1}
,"locate":{"sequence":1}
,"want":{"send":1}
,"acknowle":{"dgement":1}
,"dgement":{"request":1}
}
;Search.control.loadWordPairs(pairs);
