// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.date:getcurrentdate":{"wmpublic":1}
,"wmpublic":{"returns":1}
,"returns":{"current":1}
,"current":{"date":1}
,"date":{"date":1,"object":1,"java.util.date":1}
,"object":{"input":1}
,"input":{"parameters":1}
,"parameters":{"none":1,"date":1}
,"none":{"output":1}
,"output":{"parameters":1}
,"java.util.date":{"current":1}
}
;Search.control.loadWordPairs(pairs);
