// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"xml":{"namespace":1,"element":1}
,"namespace":{"decoding":1,"arrayof":1,"integration":1,"provided":1}
,"decoding":{"array":1,"xml":1,"document":1,"arrayof":1}
,"array":{"elements":1}
,"elements":{"decoding":1,"soap":1}
,"arrayof":{"listname":1}
,"listname":{"item":1}
,"item":{"arrayofstring":1}
,"arrayofstring":{"elements":1,"element":1}
,"soap":{"message":1}
,"message":{"integration":1,"document":1}
,"integration":{"server":1}
,"server":{"uses":1,"decodes":1,"ignores":1}
,"uses":{"document":1}
,"document":{"type-directed":1,"type":1,"typ":1}
,"type-directed":{"decoding":1}
,"type":{"associated":1,"field":1,"element":1}
,"associated":{"element":1}
,"element":{"determines":1,"corresponds":1,"xml":1,"soap":1,"integration":1}
,"determines":{"decoding":1}
,"corresponds":{"document":1}
,"field":{"contains":1,"contain":1}
,"contains":{"namespace":1}
,"decodes":{"xml":1}
,"typ":{"field":1}
,"contain":{"namespace":1}
,"ignores":{"namespace":1}
,"provided":{"element":1}
}
;Search.control.loadWordPairs(pairs);
