// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.hashtable:remove":{"wmpublic":1}
,"wmpublic":{"removes":1}
,"removes":{"key\u002Fvalue":1}
,"key\u002Fvalue":{"pair":1}
,"pair":{"hashtable":1,"key":1,"removed":1}
,"hashtable":{"input":1,"java.util.hashtable":1,"remove":1,"element":1,"object":1}
,"input":{"parameters":1,"key":1}
,"parameters":{"hashtable":1}
,"java.util.hashtable":{"hashtable":1}
,"remove":{"key\u002Fvalue":1}
,"key":{"string":1,"hashtable":1,"found":1}
,"string":{"key":1}
,"element":{"removed":1}
,"removed":{"value":1,"output":1,"returns":1}
,"value":{"object":1,"hashtable":1}
,"object":{"value":1,"key\u002Fvalue":1}
,"output":{"parameters":1}
,"returns":{"null":1}
,"null":{"input":1}
,"found":{"hashtable":1}
}
;Search.control.loadWordPairs(pairs);
