// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"administering":{"guaranteed":1}
,"guaranteed":{"delivery":1,"livery":1}
,"delivery":{"initialize":1}
,"initialize":{"server":1}
,"server":{"initializes":1,"administrator":1}
,"initializes":{"guaranteed":1}
,"livery":{"capabilities":1}
,"capabilities":{"integration":1}
,"integration":{"server":1}
,"administrator":{"shut":1}
,"shut":{"down":1}
,"down":{"re-initialize":1}
,"re-initialize":{"test":1}
,"test":{"guaranteed":1}
}
;Search.control.loadWordPairs(pairs);
