// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.replicator:distributeviasvcpush":{"wmpublic":1}
,"wmpublic":{"pushes":1}
,"pushes":{"package":1}
,"package":{"server":1}
,"server":{"list":1,"input":1}
,"list":{"sub":1,"list":1,"subscriber\u0027s":1}
,"sub":{"scribers":1}
,"scribers":{"(other":1}
,"(other":{"webmethods":1}
,"webmethods":{"integration":1}
,"integration":{"server":1}
,"input":{"parameters":1}
,"parameters":{"packagename":1,"none":1}
,"packagename":{"string":1}
,"string":{"name":1,"list":1}
,"name":{"release":1}
,"release":{"subscriber":1}
,"subscriber":{"string":1}
,"subscriber\u0027s":{"host":1}
,"host":{"names":1}
,"names":{"addresses":1}
,"addresses":{"output":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
