// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sonicmq":{"integration":1,"versions":1,"version":1,"installed":1}
,"integration":{"server":1}
,"server":{"tested":1}
,"tested":{"sonicmq":1}
,"versions":{"7.5":1}
,"7.5":{"7.6":1,"sonicmq_directory":1}
,"7.6":{"file":1,"copy":1}
,"file":{"copy":1}
,"copy":{"sonicmq":1,"above":1}
,"version":{"7.5":1,"7.6":1}
,"sonicmq_directory":{"\u005Clib\u005Cmfcontext.jar":1,"\u005Clib\u005Csonic_client.jar":1,"\u005Clib\u005Csonic_crypto.jar":1,"\u005Clib\u005Csonic_mgmt_client.jar":1,"\u005Clib\u005Csonic_selector.jar":1,"\u005Clib\u005Csonic_xa.jar":1,"\u005Clib\u005Cmgmt_client.jar":1,"\u005Clib\u005Cmgmt_config.jar":1,"\u005Clib\u005Csonic_xmessage.jar":1,"directory":1}
,"\u005Clib\u005Cmfcontext.jar":{"sonicmq_directory":1}
,"\u005Clib\u005Csonic_client.jar":{"sonicmq_directory":1}
,"\u005Clib\u005Csonic_crypto.jar":{"sonicmq_directory":1}
,"\u005Clib\u005Csonic_mgmt_client.jar":{"sonicmq_directory":1}
,"\u005Clib\u005Csonic_selector.jar":{"sonicmq_directory":1}
,"\u005Clib\u005Csonic_xa.jar":{"sonicmq":1}
,"above":{"files":1}
,"files":{"plus":1}
,"plus":{"sonicmq_directory":1}
,"\u005Clib\u005Cmgmt_client.jar":{"sonicmq_directory":1}
,"\u005Clib\u005Cmgmt_config.jar":{"sonicmq_directory":1}
,"\u005Clib\u005Csonic_xmessage.jar":{"sonicmq_directory":1}
,"directory":{"sonicmq":1}
}
;Search.control.loadWordPairs(pairs);
