// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"reliability":{"guaranteed":1}
,"guaranteed":{"delivery":1}
,"delivery":{"checkpoint":1}
,"checkpoint":{"restart":1}
,"restart":{"features":1}
,"features":{"impr":1}
,"impr":{"ove":1}
,"ove":{"reliability":1}
}
;Search.control.loadWordPairs(pairs);
