// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"enterprise":1}
,"enterprise":{"gateway":1}
,"gateway":{"rule":1,"server":1,"rules":1}
,"rule":{"longer":1,"delete":1,"open":1,"want":1,"click":1}
,"longer":{"need":1}
,"need":{"enterprise":1}
,"delete":{"delete":1,"enterprise":1,"prompted":1,"rule":1}
,"open":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1,"acting":1,"security":1}
,"administrator":{"integration":1}
,"acting":{"enterprise":1}
,"security":{"enterprise":1}
,"rules":{"enterprise":1,"page":1}
,"page":{"click":1}
,"click":{"icon":1,"delete":1}
,"icon":{"row":1}
,"row":{"corresponds":1}
,"corresponds":{"rule":1}
,"want":{"lete":1,"delete":1}
,"lete":{"click":1}
,"prompted":{"confirm":1}
,"confirm":{"want":1}
}
;Search.control.loadWordPairs(pairs);
