// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"http":{"url":1,"urls":1}
,"url":{"aliases":1,"path":1,"alias":1}
,"aliases":{"services":1,"http":1,"easier":1}
,"services":{"create":1,"aliases":1}
,"create":{"aliases":1,"http":1}
,"urls":{"users":1}
,"users":{"specify":1,"directory":1}
,"specify":{"invoke":1}
,"invoke":{"services":1}
,"easier":{"type":1,"move":1}
,"type":{"full":1}
,"full":{"url":1}
,"path":{"names":1}
,"names":{"easier":1,"allow":1,"create":1}
,"move":{"resources":1}
,"resources":{"integration":1}
,"integration":{"server":1}
,"server":{"secure":1,"information":1}
,"secure":{"url":1}
,"allow":{"users":1}
,"directory":{"file":1}
,"file":{"names":1}
,"alias":{"designer":1}
,"designer":{"integration":1}
,"information":{"setting":1}
,"setting":{"http":1}
}
;Search.control.loadWordPairs(pairs);
