// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"required":{"parts":1}
,"parts":{"assertion":1,"assertions":1}
,"assertion":{"required":1}
,"assertions":{"add":1}
,"add":{"ws-policy":1}
,"ws-policy":{"<sp:requiredparts>":1}
,"<sp:requiredparts>":{"specify":1}
,"specify":{"header":1}
,"header":{"elements":1}
,"elements":{"present":1}
,"present":{"message":1}
,"message":{"integration":1}
,"integration":{"server":1}
,"server":{"supports":1}
,"supports":{"following":1}
,"following":{"element":1}
,"element":{"<sp:header>":1}
}
;Search.control.loadWordPairs(pairs);
