// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"package":{"folder":1}
,"folder":{"organization":1,"per":1}
,"organization":{"single":1}
,"single":{"package":1}
,"per":{"developer":1,"java\u002Fc":1}
,"developer":{"per":1}
,"java\u002Fc":{"ervice":1}
}
;Search.control.loadWordPairs(pairs);
