// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"synchronization":{"folder":1}
,"folder":{"elements":1,"perfor":1}
,"elements":{"synchronization":1}
,"perfor":{"latching":1}
,"latching":{"cross-referencing":1}
,"cross-referencing":{"operations":1}
,"operations":{"publish-and":1}
,"publish-and":{"-subscribe":1}
,"-subscribe":{"integration":1}
}
;Search.control.loadWordPairs(pairs);
