// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"limiting":{"external":1}
,"external":{"urls":1}
,"urls":{"used":1,"pag":1,"specif":1,"redirection":1}
,"used":{"redirection":1}
,"redirection":{"validconst":1}
,"validconst":{"tag":1}
,"tag":{"custom":1,"page":1,"specifying":1}
,"custom":{"dsps":1}
,"dsps":{"specify":1}
,"specify":{"list":1}
,"list":{"urls":1,"permitted":1}
,"pag":{"redirected":1}
,"redirected":{"specifying":1,"urls":1}
,"specifying":{"validconst":1,"list":1}
,"page":{"redirected":1}
,"specif":{"information":1}
,"information":{"tag":1}
,"permitted":{"urls":1}
}
;Search.control.loadWordPairs(pairs);
