// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"is_instance":{"script":1}
,"script":{"is_instance.bat\u002Fsh":1,"creates":1,"located":1}
,"is_instance.bat\u002Fsh":{"script":1}
,"creates":{"updates":1}
,"updates":{"deletes":1,"properties":1}
,"deletes":{"integration":1,"packages":1}
,"integration":{"server":1,"server_directory":1}
,"server":{"instance":1}
,"instance":{"installs":1,"updates":1,"is_instance.bat\u002Fsh":1}
,"installs":{"updates":1}
,"packages":{"language":1}
,"language":{"packs":1}
,"packs":{"integration":1}
,"properties":{"database":1}
,"database":{"used":1}
,"used":{"integration":1}
,"located":{"following":1}
,"following":{"rectory":1}
,"rectory":{"integration":1}
,"server_directory":{"\u005Cinstances":1}
}
;Search.control.loadWordPairs(pairs);
