// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"securing":{"web":1}
,"web":{"services":1}
,"services":{"using":1}
,"using":{"ws-security":1}
,"ws-security":{"facility":1}
}
;Search.control.loadWordPairs(pairs);
