// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"specifying":{"alert":1}
,"alert":{"options":1}
,"options":{"specify":1,"apply":1}
,"specify":{"default":1,"rule-specific":1}
,"default":{"alert":1}
,"apply":{"rule":1}
,"rule":{"specify":1}
,"rule-specific":{"alert":1}
}
;Search.control.loadWordPairs(pairs);
