// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"searching":{"order":1}
,"order":{"within":1,"packagename":1,"ithin":1,"required":1}
,"within":{"package":1}
,"package":{"integration":1,"class":1,"requires":1,"refers":1}
,"integration":{"server":1}
,"server":{"searches":1,"first":1,"look":1}
,"searches":{"within":1}
,"class":{"uses":1,"above":1,"integration":1}
,"uses":{"order":1}
,"packagename":{"\u005Cresources":1,"\u005Clib":1,"\u005Ccode\u005Cjars":1,"\u005Ccode\u005Cclasses":1}
,"\u005Cresources":{"packagename":1}
,"\u005Clib":{"packagename":1}
,"\u005Ccode\u005Cjars":{"packagename":1}
,"\u005Ccode\u005Cclasses":{"note":1}
,"note":{"package":1}
,"requires":{"package":1}
,"first":{"look":1}
,"look":{"referenced":1,"above":1}
,"referenced":{"class":1}
,"above":{"order":1}
,"ithin":{"package":1}
,"refers":{"class":1}
,"required":{"packages":1}
}
;Search.control.loadWordPairs(pairs);
