// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"amqp":{"messaging":1,"communicate":1,"0-x":1}
,"messaging":{"providers":1}
,"providers":{"integration":1}
,"integration":{"server":1}
,"server":{"tested":1,"uses":1}
,"tested":{"rabbitmq":1,"qpid":1}
,"rabbitmq":{"azure":1}
,"azure":{"service":1}
,"service":{"bus":1}
,"bus":{"provider":1}
,"provider":{"integration":1}
,"uses":{"qpid":1}
,"qpid":{"jms":1,"website":1}
,"jms":{"client":1,"providers":1,"amqp":1,"1.5.0":1,"library":1}
,"client":{"libraries":1}
,"libraries":{"amqp":1,"download":1}
,"communicate":{"jms":1}
,"0-x":{"6.3.3":1}
,"6.3.3":{"qpid":1}
,"1.5.0":{"jms":1}
,"download":{"copy":1}
,"copy":{"version-appropriate":1}
,"version-appropriate":{"qpid":1}
,"library":{"binary":1}
,"binary":{"apache":1}
,"apache":{"qpid":1}
}
;Search.control.loadWordPairs(pairs);
