// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.art.notification:querylistenernotificationstate":{"wmart":1}
,"wmart":{"returns":1}
,"returns":{"current":1}
,"current":{"state":1}
,"state":{"(enabled\u002Fdisabled)":1}
,"(enabled\u002Fdisabled)":{"stener":1,"returned":1,"listener":1}
,"stener":{"notification":1}
,"notification":{"input":1,"want":1}
,"input":{"parameters":1}
,"parameters":{"notificationname":1,"notificationstate":1}
,"notificationname":{"string":1}
,"string":{"name":1,"current":1}
,"name":{"listener":1}
,"listener":{"notification":1,"notif":1}
,"want":{"current":1}
,"returned":{"output":1}
,"output":{"parameters":1}
,"notificationstate":{"string":1}
,"notif":{"ication":1}
,"ication":{"pub.art.notification:enablelistenernotification":1}
,"pub.art.notification:enablelistenernotification":{"pub.art.notification:disablelistenernotification":1}
}
;Search.control.loadWordPairs(pairs);
