// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.storage:keys":{"wmpublic":1}
,"wmpublic":{"obtains":1}
,"obtains":{"list":1}
,"list":{"keys":1}
,"keys":{"data":1,"output":1,"string":1}
,"data":{"store":1}
,"store":{"input":1,"want":1,"specified":1}
,"input":{"parameters":1}
,"parameters":{"storename":1,"keys":1}
,"storename":{"string":1}
,"string":{"name":1,"list":1}
,"name":{"data":1}
,"want":{"obtain":1}
,"obtain":{"list":1}
,"output":{"parameters":1}
,"specified":{"storename":1}
}
;Search.control.loadWordPairs(pairs);
