// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"kerberosauthentication":{"policy":1}
,"policy":{"kerberosauthentication":1,"uses":1,"enforce":1}
,"uses":{"kerberos":1}
,"kerberos":{"ticket":1}
,"ticket":{"provide":1}
,"provide":{"authentication":1}
,"authentication":{"includes":1}
,"includes":{"timestamp":1}
,"timestamp":{"token":1}
,"token":{"gua":1}
,"gua":{"against":1}
,"against":{"replay":1}
,"replay":{"attacks":1}
,"attacks":{"policy":1}
,"enforce":{"sign":1}
,"sign":{"atures":1}
,"atures":{"encryption":1}
}
;Search.control.loadWordPairs(pairs);
