// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"logging":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1,"cleans":1}
,"administrator":{"log":1,"longer":1,"click":1}
,"log":{"integration":1,"server":1}
,"longer":{"need":1}
,"need":{"continue":1}
,"continue":{"current":1}
,"current":{"session":1}
,"session":{"hen":1,"clear":1}
,"hen":{"log":1}
,"cleans":{"session":1}
,"clear":{"cache":1}
,"cache":{"browser":1}
,"browser":{"log":1}
,"click":{"log":1}
}
;Search.control.loadWordPairs(pairs);
