// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"messages":{"messages":1,"objects":1}
,"objects":{"communicate":1}
,"communicate":{"information":1}
,"information":{"client":1}
,"client":{"app":1}
,"app":{"lications":1}
,"lications":{"following":1}
,"following":{"descriptions":1}
,"descriptions":{"several":1}
,"several":{"key":1}
,"key":{"concept":1}
,"concept":{"related":1}
,"related":{"jms":1}
,"jms":{"messages":1}
}
;Search.control.loadWordPairs(pairs);
