// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"editing":{"port":1}
,"port":{"adding":1,"edit":1,"configuration":1,"disabled":1,"alias":1,"created":1,"open":1,"want":1,"numbe":1,"click":1}
,"adding":{"port":1}
,"edit":{"port":1,"configuratio":1,"click":1,"<port":1}
,"configuration":{"port":1,"update":1}
,"disabled":{"edit":1}
,"configuratio":{"note":1}
,"note":{"cannot":1}
,"cannot":{"edit":1}
,"alias":{"port":1}
,"created":{"edit":1}
,"open":{"integration":1,"server":1}
,"integration":{"server":1}
,"server":{"administrator":1,"ports":1}
,"administrator":{"already":1}
,"already":{"open":1}
,"ports":{"locate":1}
,"locate":{"port":1}
,"want":{"edit":1}
,"click":{"port":1,"edit":1,"save":1}
,"numbe":{"click":1}
,"<port":{"type":1}
,"type":{"port":1}
,"update":{"information":1}
,"information":{"port":1}
,"save":{"changes":1}
}
;Search.control.loadWordPairs(pairs);
