// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"adding":{"response":1}
,"response":{"headers":1,"header":1}
,"headers":{"faults":1}
,"faults":{"affect":1}
,"affect":{"in-only":1}
,"in-only":{"mep":1}
,"mep":{"ope":1,"operation":1,"type":1,"changes":1,"add":1,"chan":1}
,"ope":{"rations":1}
,"rations":{"in-only":1}
,"operation":{"mep":1,"add":1}
,"type":{"changes":1}
,"changes":{"add":1,"in-out":1}
,"add":{"response":1,"fault":1}
,"header":{"fault":1,"in-only":1}
,"fault":{"operation":1,"in-only":1}
,"in-out":{"mep":1}
,"chan":{"ges":1}
,"ges":{"robust":1}
,"robust":{"in-only":1}
}
;Search.control.loadWordPairs(pairs);
