// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.string:length":{"wmpublic":1}
,"wmpublic":{"returns":1}
,"returns":{"length":1}
,"length":{"string":1,"want":1}
,"string":{"input":1,"string":1,"whose":1,"number":1}
,"input":{"parameters":1}
,"parameters":{"instring":1,"value":1}
,"instring":{"string":1}
,"whose":{"length":1}
,"want":{"discover":1}
,"discover":{"output":1}
,"output":{"parameters":1}
,"value":{"string":1}
,"number":{"characters":1}
,"characters":{"instring":1}
}
;Search.control.loadWordPairs(pairs);
