// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"alias":1}
,"alias":{"longer":1,"remote":1,"delete":1,"want":1}
,"longer":{"need":1}
,"need":{"alias":1}
,"remote":{"server":1,"servers":1}
,"server":{"delete":1,"open":1,"administrator":1,"displays":1}
,"delete":{"following":1,"alias":1,"click":1,"icon":1,"field":1}
,"following":{"procedure":1}
,"procedure":{"delete":1}
,"open":{"integration":1}
,"integration":{"server":1}
,"administrator":{"external":1}
,"external":{"servers":1}
,"servers":{"remote":1,"locate":1}
,"locate":{"alias":1}
,"want":{"delete":1}
,"click":{"delete":1,"verify":1}
,"icon":{"icon":1,"delete":1}
,"field":{"server":1}
,"displays":{"dialog":1}
,"dialog":{"box":1}
,"box":{"prompts":1}
,"prompts":{"verify":1}
,"verify":{"action":1,"want":1}
,"action":{"click":1}
}
;Search.control.loadWordPairs(pairs);
