// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sending":{"jms":1}
,"jms":{"message":1,"provider":1}
,"message":{"build":1,"speci":1,"destination":1}
,"build":{"service":1}
,"service":{"sends":1}
,"sends":{"jms":1}
,"speci":{"integration":1}
,"integration":{"server":1}
,"server":{"connects":1}
,"connects":{"jms":1}
,"provider":{"message":1}
,"destination":{"whether":1}
,"whether":{"client":1}
,"client":{"side":1}
,"side":{"queue":1}
,"queue":{"used":1}
}
;Search.control.loadWordPairs(pairs);
