// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sending":{"release":1}
,"release":{"following":1,"send":1,"open":1,"package":1}
,"following":{"procedure":1}
,"procedure":{"send":1}
,"send":{"package":1,"release":1,"available":1}
,"package":{"release":1,"want":1}
,"open":{"integration":1,"packages":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"already":1}
,"already":{"open":1}
,"packages":{"publishing":1}
,"publishing":{"locate":1}
,"locate":{"release":1}
,"want":{"send":1}
,"available":{"releases":1}
,"releases":{"click":1}
,"click":{"send":1}
}
;Search.control.loadWordPairs(pairs);
