// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"truststore":{"file":1,"store":1,"contai":1,"simply":1}
,"file":{"integration":1}
,"integration":{"server":1}
,"server":{"uses":1,"truststore":1}
,"uses":{"truststore":1}
,"store":{"trusted":1}
,"trusted":{"root":1,"roots":1,"directo":1}
,"root":{"certificates":1}
,"certificates":{"publi":1,"within":1}
,"publi":{"keys":1}
,"keys":{"signing":1,"cas":1}
,"signing":{"cas":1}
,"cas":{"although":1,"within":1}
,"although":{"truststore":1}
,"contai":{"trusted":1}
,"roots":{"entire":1}
,"entire":{"certificate":1}
,"certificate":{"chains":1}
,"chains":{"requirement":1}
,"requirement":{"organization":1}
,"organization":{"certificates":1}
,"within":{"integration":1,"specified":1}
,"simply":{"functions":1}
,"functions":{"database":1}
,"database":{"containing":1}
,"containing":{"public":1}
,"public":{"keys":1}
,"specified":{"trusted":1}
}
;Search.control.loadWordPairs(pairs);
