// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"taking":{"server":1}
,"server":{"offline":1,"load":1,"unpublished":1,"administrator":1,"ports":1}
,"offline":{"stateful":1,"integration":1}
,"stateful":{"stateless":1}
,"stateless":{"cluster":1}
,"cluster":{"hide":1}
,"hide":{"server":1}
,"load":{"balancer":1}
,"balancer":{"assigning":1}
,"assigning":{"server":1}
,"unpublished":{"port":1}
,"port":{"server":1,"select":1,"unpublished":1,"exist":1,"just":1}
,"integration":{"server":1}
,"administrator":{"server":1,"unpublished":1}
,"ports":{"change":1}
,"change":{"primary":1}
,"primary":{"port":1}
,"select":{"new":1,"unpublished":1}
,"new":{"primary":1}
,"exist":{"create":1}
,"create":{"click":1}
,"click":{"update":1}
,"update":{"browser":1,"url":1}
,"browser":{"update":1}
,"url":{"integration":1}
,"just":{"selected":1}
,"selected":{"disable":1}
,"disable":{"listening":1}
,"listening":{"ports":1}
}
;Search.control.loadWordPairs(pairs);
