// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"chapter":1}
,"chapter":{"explains":1}
,"explains":{"mime":1,"message":1}
,"mime":{"s\u002Fmime":1}
,"s\u002Fmime":{"message":1}
,"message":{"formats":1,"explains":1,"encryption":1}
,"formats":{"identifies":1}
,"identifies":{"basic":1}
,"basic":{"structures":1}
,"structures":{"describes":1}
,"describes":{"digi":1}
,"digi":{"tal":1}
,"tal":{"certificates":1}
,"certificates":{"signatures":1}
,"signatures":{"work":1}
,"work":{"identify":1}
,"identify":{"sender":1}
,"sender":{"message":1}
,"encryption":{"helps":1}
,"helps":{"nsure":1}
,"nsure":{"privacy":1}
,"privacy":{"message":1}
}
;Search.control.loadWordPairs(pairs);
