// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"locking":{"considerations":1,"requests":1}
,"considerations":{"following":1}
,"following":{"sections":1}
,"sections":{"describe":1}
,"describe":{"general":1}
,"general":{"pub.storage":1}
,"pub.storage":{"services":1}
,"services":{"handle":1}
,"handle":{"locking":1}
,"requests":{"individual":1}
,"individual":{"servic":1}
,"servic":{"descriptions":1}
,"descriptions":{"detailed":1}
,"detailed":{"information":1}
}
;Search.control.loadWordPairs(pairs);
