// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"integration":1}
,"integration":{"server":1}
,"server":{"works":1,"interacts":1,"integration":1,"accesses":1,"authenticates":1}
,"works":{"externally":1}
,"externally":{"defined":1}
,"defined":{"users":1,"central":1,"groups":1}
,"users":{"groups":1,"gro":1,"belong":1}
,"groups":{"following":1,"defined":1,"used":1,"roles":1}
,"following":{"sections":1}
,"sections":{"provide":1}
,"provide":{"information":1}
,"information":{"whe":1,"externally":1}
,"whe":{"integration":1}
,"interacts":{"users":1}
,"central":{"user":1}
,"user":{"irectory":1}
,"irectory":{"ldap":1}
,"ldap":{"specifically":1}
,"specifically":{"externally":1}
,"used":{"integration":1}
,"accesses":{"information":1}
,"gro":{"ups":1}
,"ups":{"integration":1}
,"authenticates":{"users":1}
,"belong":{"externally":1}
}
;Search.control.loadWordPairs(pairs);
