// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.document:insertdocument":{"wmpublic":1}
,"wmpublic":{"inserts":1}
,"inserts":{"new":1}
,"new":{"document":1}
,"document":{"documents":1,"list":1,"inserted":1,"new":1}
,"documents":{"specified":1,"document":1,"new":1,"spe":1,"parameter":1}
,"specified":{"position":1,"document":1,"documents":1}
,"position":{"input":1,"seat":1}
,"input":{"parameters":1}
,"parameters":{"documents":1}
,"list":{"documents":1,"specified":1,"document":1,"inserting":1}
,"inserted":{"insertdocument":1,"documents":1,"index":1,"end":1}
,"insertdocument":{"document":1}
,"spe":{"cified":1}
,"cified":{"documents":1}
,"parameter":{"index":1,"zero-based":1,"specified":1,"output":1}
,"index":{"string":1,"parameter":1}
,"string":{"optional":1}
,"optional":{"position":1}
,"seat":{"document":1}
,"zero-based":{"value":1}
,"value":{"index":1}
,"end":{"document":1}
,"output":{"parameters":1}
,"inserting":{"new":1}
}
;Search.control.loadWordPairs(pairs);
