// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.soap.wsa.submission:schema_wsa_submission":{"wmpublic":1}
,"wmpublic":{"schema":1}
,"schema":{"containing":1}
,"containing":{"elements":1}
,"elements":{"http:\u002F\u002Fschemas.xmlsoap.org\u002Fws\u002F2004\u002F08\u002Faddressing":1}
,"http:\u002F\u002Fschemas.xmlsoap.org\u002Fws\u002F2004\u002F08\u002Faddressing":{"namespace":1}
}
;Search.control.loadWordPairs(pairs);
