// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2019-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"adapter":{"service":1}
,"service":{"transaction":1}
,"transaction":{"processing":1}
}
;Search.control.loadWordPairs(pairs);
