// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2019-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"installing":{"uninstalling":1}
,"uninstalling":{"adapter":1}
,"adapter":{"mongodb":1}
}
;Search.control.loadWordPairs(pairs);
