// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2019-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"webmethods":{"adapter":1}
,"adapter":{"mongodb":1}
,"mongodb":{"installation":1}
,"installation":{"user\u2019s":1}
,"user\u2019s":{"guide":1}
,"guide":{"documentation":1}
}
;Search.control.loadWordPairs(pairs);
