// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2019-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"adapter":1}
,"adapter":{"listeners":1,"mongodb":1}
,"listeners":{"listener":1}
,"listener":{"notifications":1}
,"notifications":{"chapter":1,"detailed":1,"adapter":1}
,"chapter":{"describes":1}
,"describes":{"configure":1}
,"configure":{"manage":1}
,"manage":{"adapter":1}
,"mongodb":{"listeners":1,"notifications":1}
,"detailed":{"descriptions":1}
,"descriptions":{"available":1}
,"available":{"adapter":1}
}
;Search.control.loadWordPairs(pairs);
