// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2019-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"adapter":1}
,"adapter":{"connection":1}
,"connection":{"parameters":1}
,"parameters":{"view":1,"integration":1}
,"view":{"connection\u0027s":1}
,"connection\u0027s":{"parameters":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"software":1}
,"software":{"designer":1}
}
;Search.control.loadWordPairs(pairs);
