// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2019-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"listener":1}
,"listener":{"notification":1,"notifications":1}
,"notification":{"configure":1,"using":1}
,"configure":{"listener":1}
,"using":{"software":1}
,"software":{"designer":1}
,"designer":{"information":1}
,"information":{"adapter":1}
,"adapter":{"listeners":1}
,"listeners":{"listener":1}
}
;Search.control.loadWordPairs(pairs);
