// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2019-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"adapter":1}
,"adapter":{"connections":1,"mongodb":1,"connect":1}
,"connections":{"chapter":1,"information":1}
,"chapter":{"describes":1}
,"describes":{"configure":1}
,"configure":{"manage":1}
,"manage":{"adapter":1}
,"mongodb":{"connections":1}
,"information":{"adapter":1}
,"connect":{"ions":1}
,"ions":{"work":1}
,"work":{"adapter":1}
}
;Search.control.loadWordPairs(pairs);
