// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.4":1}
,"10.4":{"added":1}
,"added":{"services":1}
,"services":{"pub.cloudstreams.upgrade:batchupgrade":1}
,"pub.cloudstreams.upgrade:batchupgrade":{"service":1}
,"service":{"updates":1,"registers":1}
,"updates":{"batches":1}
,"batches":{"cloudstreams":1}
,"cloudstreams":{"connector":1}
,"connector":{"serv":1,"listener":1,"api":1}
,"serv":{"ice":1}
,"ice":{"nodes":1}
,"nodes":{"connector":1,"lower":1}
,"listener":{"nodes":1,"enablement":1}
,"lower":{"version":1}
,"version":{"connector":1,"wm.cloudstreams.listener.metadata.connection:registerextensi":1}
,"api":{"higher":1}
,"higher":{"version":1}
,"wm.cloudstreams.listener.metadata.connection:registerextensi":{"service":1}
,"registers":{"cometd":1}
,"cometd":{"extensions":1}
,"extensions":{"process":1}
,"process":{"listener":1}
}
;Search.control.loadWordPairs(pairs);
