// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"known":{"issues":1,"readme":1}
,"issues":{"section":1,"current":1,"ound":1}
,"section":{"lists":1}
,"lists":{"issues":1}
,"current":{"release":1}
,"release":{"ere":1}
,"ere":{"known":1}
,"readme":{"published":1}
,"published":{"known":1}
,"ound":{"later":1}
,"later":{"knowledge":1}
,"knowledge":{"center":1}
,"center":{"empower":1}
,"empower":{"website":1}
}
;Search.control.loadWordPairs(pairs);
