// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.15":1}
,"10.15":{"wst_10.11_fix2":1}
,"wst_10.11_fix2":{"wst_10.7_fix8":1}
,"wst_10.7_fix8":{"wst_10.5_fix31":1}
}
;Search.control.loadWordPairs(pairs);
