// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.4":1}
,"10.4":{"wst_10.3_fix4":1}
,"wst_10.3_fix4":{"wst_10.1_fix7":1}
,"wst_10.1_fix7":{"wst_9.12_fix8":1}
,"wst_9.12_fix8":{"wst_9.10_fix12":1}
}
;Search.control.loadWordPairs(pairs);
