// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"9.10":1,"changed":1}
,"9.10":{"deprecated":1}
,"deprecated":{"items":1,"release":1}
,"items":{"software":1,"cloudstreams":1}
,"software":{"mashzone":1}
,"mashzone":{"based":1}
,"based":{"cloudstreams":1}
,"cloudstreams":{"analytics":1,"user":1}
,"analytics":{"dashboard":1,"dashb":1}
,"dashboard":{"software":1}
,"dashb":{"oard":1}
,"oard":{"deprecated":1}
,"changed":{"items":1,"change":1}
,"user":{"interface":1}
,"interface":{"html-based":1,"functionality":1}
,"html-based":{"utility":1}
,"utility":{"used":1}
,"used":{"administer":1}
,"administer":{"webmethods":1}
,"webmethods":{"clouds":1}
,"clouds":{"treams":1}
,"treams":{"new":1}
,"new":{"look":1}
,"look":{"feel":1}
,"feel":{"menu":1}
,"menu":{"screen":1}
,"screen":{"locations":1}
,"locations":{"changed":1}
,"change":{"user":1}
}
;Search.control.loadWordPairs(pairs);
