// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.2":1}
,"10.2":{"old":1}
,"old":{"term":1}
,"term":{"login\u002Flogout":1,"start\u002Fstop":1,"cfg":1,"internal":1}
,"login\u002Flogout":{"sequence":1}
,"sequence":{"replaced":1,"old":1}
,"replaced":{"new":1}
,"new":{"term":1}
,"start\u002Fstop":{"sequence":1}
,"cfg":{"parameter":1}
,"parameter":{"replaced":1}
}
;Search.control.loadWordPairs(pairs);
