// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.11":1}
,"10.11":{"wcd_10.7_fix1":1}
,"wcd_10.7_fix1":{"wcd_10.5_fix5":1}
}
;Search.control.loadWordPairs(pairs);
