// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.3":1}
,"10.3":{"wcd_10.2_fix1":1}
,"wcd_10.2_fix1":{"wcd_10.1_fix2":1}
,"wcd_10.1_fix2":{"wcd_9.12_fix2":1}
,"wcd_9.12_fix2":{"wcd_9.10_fix4":1}
}
;Search.control.loadWordPairs(pairs);
