// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"fixes":{"included":1}
,"included":{"release":1}
,"release":{"section":1,"product":1,"listed":1,"knowledge":1}
,"section":{"lists":1,"changes":1}
,"lists":{"latest":1}
,"latest":{"fix":1}
,"fix":{"level":1}
,"level":{"included":1}
,"product":{"com":1}
,"com":{"ponent":1}
,"ponent":{"release":1}
,"listed":{"section":1}
,"changes":{"occurred":1}
,"occurred":{"release":1}
,"knowledge":{"center":1}
,"center":{"empower":1}
,"empower":{"website":1}
,"website":{"detailed":1}
,"detailed":{"information":1}
,"information":{"fixes":1}
}
;Search.control.loadWordPairs(pairs);
