// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"terminology":{"changes":1}
,"changes":{"release":1,"occurred":1}
,"release":{"listed":1}
,"listed":{"section":1}
,"section":{"changes":1}
,"occurred":{"release":1}
}
;Search.control.loadWordPairs(pairs);
