// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.3":1}
,"10.3":{"added":1}
,"added":{"items":1}
,"items":{"support":1}
,"support":{"assignments":1,"applying":1}
,"assignments":{"cookies":1,"resource":1,"resou":1}
,"cookies":{"service":1}
,"service":{"context":1,"contex":1}
,"context":{"apply":1}
,"apply":{"assignments":1}
,"contex":{"support":1}
,"applying":{"assignments":1}
,"resource":{"group":1}
,"group":{"level":1,"further":1}
,"level":{"apply":1,"enables":1}
,"enables":{"apply":1}
,"resou":{"rce":1}
,"rce":{"operation":1}
,"operation":{"selected":1}
,"selected":{"resource":1}
,"further":{"ssignments":1}
,"ssignments":{"applied":1}
,"applied":{"sequence":1}
,"sequence":{"appear":1}
,"appear":{"configure":1}
,"configure":{"assignment":1}
,"assignment":{"panel":1}
}
;Search.control.loadWordPairs(pairs);
