// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"9.8":1}
,"9.8":{"old":1}
,"old":{"term":1}
,"term":{"group":1,"provider":1,"connector":1,"package":1,"plug-in":1}
,"group":{"replaced":1,"old":1}
,"replaced":{"new":1}
,"new":{"term":1}
,"provider":{"group":1}
,"connector":{"package":1,"content":1}
,"package":{"replaced":1,"old":1}
,"plug-in":{"content":1}
,"content":{"replaced":1}
}
;Search.control.loadWordPairs(pairs);
