// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"9.12":1}
,"9.12":{"wcd_9.10_fix2":1}
}
;Search.control.loadWordPairs(pairs);
