// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"customize":{"color":1,"colors":1}
,"color":{"schemes":1,"scheme":1}
,"schemes":{"themes":1,"used":1}
,"themes":{"section":1}
,"section":{"used":1}
,"used":{"customize":1,"gene":1,"screen":1}
,"gene":{"ral":1}
,"ral":{"different":1}
,"different":{"blocks":1}
,"blocks":{"page":1}
,"page":{"customize":1}
,"colors":{"font":1}
,"font":{"size":1}
,"size":{"general":1}
,"general":{"customize":1}
,"scheme":{"used":1}
,"screen":{"headers":1}
,"headers":{"buttons":1}
,"buttons":{"left":1}
,"left":{"navigation":1}
,"navigation":{"bar":1}
}
;Search.control.loadWordPairs(pairs);
