// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"disabling":{"https":1}
,"https":{"port":1}
,"port":{"default":1,"however":1,"open":1}
,"default":{"uses":1}
,"uses":{"https":1}
,"however":{"modify":1}
,"modify":{"havior":1}
,"havior":{"based":1}
,"based":{"requirement":1}
,"requirement":{"disable":1}
,"disable":{"https":1}
,"open":{"dpo_wrapper.conf":1}
,"dpo_wrapper.conf":{"file":1}
,"file":{"following":1,"restart":1}
,"following":{"location":1,"property":1}
,"location":{"sagintalldir":1}
,"sagintalldir":{"\u002Fdeveloperportal\u002Fconfiguration":1}
,"\u002Fdeveloperportal\u002Fconfiguration":{"following":1}
,"property":{"false":1}
,"false":{"wrapper.java.additional.2013=-dserver.ssl.enabled=false":1}
,"wrapper.java.additional.2013=-dserver.ssl.enabled=false":{"save":1}
,"save":{"close":1}
,"close":{"configuration":1}
,"configuration":{"file":1,"changes":1}
,"restart":{"server":1}
,"server":{"configuration":1}
,"changes":{"eff":1}
,"eff":{"ect":1}
}
;Search.control.loadWordPairs(pairs);
