// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.5":1}
,"10.5":{"added":1}
,"added":{"parameters":1}
,"parameters":{"mft.server.https.auth.saml":1}
,"mft.server.https.auth.saml":{"property":1}
,"property":{"enable":1,"cnf":1,"configure":1}
,"enable":{"single":1}
,"single":{"sign-on":1}
,"sign-on":{"property":1}
,"cnf":{"file":1}
,"file":{"mft.server.https.auth.saml.redirecturi":1}
,"mft.server.https.auth.saml.redirecturi":{"property":1}
,"configure":{"identity":1}
,"identity":{"provider":1}
,"provider":{"url":1}
}
;Search.control.loadWordPairs(pairs);
