// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.3":1}
,"10.3":{"changed":1}
,"changed":{"items":1}
,"items":{"smb":1}
,"smb":{"activetransfer":1,"protocol":1}
,"activetransfer":{"supports":1}
,"supports":{"1.0":1}
,"1.0":{"2.0":1}
,"2.0":{"3.0":1}
,"3.0":{"smb":1}
,"protocol":{"vers":1}
,"vers":{"ions":1}
,"ions":{"events":1}
,"events":{"virtual":1}
,"virtual":{"folder":1}
,"folder":{"configurations":1}
}
;Search.control.loadWordPairs(pairs);
