// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"added":{"removed":1}
,"removed":{"deprecated":1}
,"deprecated":{"changed":1}
,"changed":{"parameters":1}
,"parameters":{"release":1}
,"release":{"listed":1}
,"listed":{"section":1}
,"section":{"changes":1}
,"changes":{"occurred":1}
,"occurred":{"release":1}
}
;Search.control.loadWordPairs(pairs);
