// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.4":1}
,"10.4":{"mat_10.3_mws_fix2":1}
,"mat_10.3_mws_fix2":{"mat_10.3_server_fix2":1}
,"mat_10.3_server_fix2":{"mat_10.1_mws_fix11":1}
,"mat_10.1_mws_fix11":{"mat_10.1_server_fix11":1}
,"mat_10.1_server_fix11":{"mat_9.8_mws_fix32":1}
,"mat_9.8_mws_fix32":{"mat_9.8_server_fix32":1}
}
;Search.control.loadWordPairs(pairs);
