// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"release":{"10.1":1}
,"10.1":{"new":1}
,"new":{"section":1}
,"section":{"supporting":1}
,"supporting":{"virus":1}
,"virus":{"scanning":1}
,"scanning":{"internet":1}
,"internet":{"cont":1}
,"cont":{"ent":1}
,"ent":{"adaptation":1}
,"adaptation":{"protocol":1}
,"protocol":{"includes":1}
,"includes":{"conceptual":1}
,"conceptual":{"task":1}
,"task":{"information":1}
,"information":{"added":1}
,"added":{"chapter":1}
,"chapter":{"configuring":1}
,"configuring":{"activ":1}
,"activ":{"etransfer":1}
,"etransfer":{"gateway":1}
,"gateway":{"managing":1}
,"managing":{"file":1}
,"file":{"transfers":1}
,"transfers":{"webmethods":1}
,"webmethods":{"activetransfer":1}
}
;Search.control.loadWordPairs(pairs);
