// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2012-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"activetransfer":{"server":1,"currently":1}
,"server":{"mat-1198":1,"delete":1}
,"mat-1198":{"activetransfer":1}
,"delete":{"event":1}
,"event":{"event":1,"activities":1,"listed":1,"log":1,"name":1}
,"activities":{"logged":1}
,"logged":{"deleted":1}
,"deleted":{"event":1}
,"listed":{"monitoring":1}
,"monitoring":{"integration":1}
,"integration":{"managed":1}
,"managed":{"file":1}
,"file":{"transfer":1}
,"transfer":{"event":1}
,"log":{"page":1}
,"page":{"webmethods":1,"activetransfer":1}
,"webmethods":{"without":1}
,"without":{"event":1}
,"name":{"applicable":1}
,"applicable":{"action":1}
,"action":{"log":1}
,"currently":{"workaround":1}
,"workaround":{"issue":1}
}
;Search.control.loadWordPairs(pairs);
