// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sync":{"external":1,"feature":1,"properties":1}
,"external":{"entity":1}
,"entity":{"type":1}
,"type":{"adapter":1,"ith":1,"modify":1,"working":1}
,"adapter":{"odata":1}
,"odata":{"sync":1,"services":1}
,"feature":{"designer":1,"edit":1}
,"designer":{"sync":1}
,"properties":{"selected":1,"exter":1}
,"selected":{"external":1}
,"ith":{"latest":1}
,"latest":{"changes":1}
,"changes":{"made":1}
,"made":{"database":1}
,"database":{"tables":1}
,"tables":{"sync":1}
,"edit":{"properties":1}
,"exter":{"nal":1}
,"nal":{"entity":1}
,"modify":{"external":1}
,"working":{"odata":1}
,"services":{"chapter":1}
,"chapter":{"webmethods":1}
,"webmethods":{"service":1}
,"service":{"development":1}
,"development":{"help":1}
}
;Search.control.loadWordPairs(pairs);
