// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"considerations":{"installing":1}
,"installing":{"adapter":1,"upgrading":1}
,"adapter":{"jdbc":1}
,"jdbc":{"packages":1,"installation":1}
,"packages":{"integration":1}
,"integration":{"server":1}
,"server":{"cluster":1}
,"cluster":{"standard":1}
,"standard":{"adapter":1}
,"installation":{"procedures":1}
,"procedures":{"machine":1}
,"machine":{"described":1}
,"described":{"overview":1}
,"overview":{"installing":1}
,"upgrading":{"uninstalling":1}
,"uninstalling":{"adapter":1}
}
;Search.control.loadWordPairs(pairs);
