// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"db2":{"app":1}
,"app":{"type":1}
,"type":{"required":1,"udb":1}
,"required":{"connection":1}
,"connection":{"property":1}
,"property":{"fields":1}
,"fields":{"driver":1}
,"driver":{"server":1}
,"server":{"name":1}
,"name":{"user":1,"port":1}
,"user":{"password":1}
,"password":{"database":1}
,"database":{"name":1}
,"port":{"number":1}
,"number":{"network":1}
,"network":{"protocol":1}
,"protocol":{"db2":1}
,"udb":{"v7.2":1}
,"v7.2":{"v8.1":1}
,"v8.1":{"information":1}
,"information":{"limitations":1}
,"limitations":{"limitations":1}
}
;Search.control.loadWordPairs(pairs);
