// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"installing":{"upgrading":1}
,"upgrading":{"uninstalling":1}
,"uninstalling":{"adapter":1}
,"adapter":{"jdbc":1}
}
;Search.control.loadWordPairs(pairs);
