// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuration":{"variables":1}
,"variables":{"templates":1,"template":1}
,"templates":{"adapter":1}
,"adapter":{"assets":1,"runtime":1}
,"assets":{"micr":1}
,"micr":{"oservices":1}
,"oservices":{"runtime":1}
,"runtime":{"webmethods":1,"(art)":1,"information":1,"user\u0027s":1}
,"webmethods":{"adapter":1,"microservices":1}
,"(art)":{"asset":1}
,"asset":{"properties":1}
,"properties":{"configured":1}
,"configured":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"available":1}
,"available":{"configuration":1}
,"template":{"(application.properties":1}
,"(application.properties":{"file)":1}
,"file)":{"generated":1}
,"generated":{"microservices":1}
,"microservices":{"runtime":1,"webmethods":1,"runt":1}
,"information":{"webmethods":1}
,"user\u0027s":{"guide":1}
,"guide":{"developing":1}
,"developing":{"microservices":1}
,"runt":{"ime":1}
}
;Search.control.loadWordPairs(pairs);
