// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"installing":{"default":1}
,"default":{"single":1}
,"single":{"version":1}
,"version":{"jdbc":1}
,"jdbc":{"driver":1}
,"driver":{"integration":1,"jar":1}
,"integration":{"server":1,"server_directory":1}
,"server":{"install":1,"place":1,"typically":1,"integration":1,"uses":1}
,"install":{"default":1}
,"place":{"jdbc":1}
,"jar":{"file":1}
,"file":{"(s)":1}
,"(s)":{"classpath":1,"added":1}
,"classpath":{"integration":1,"resta":1}
,"typically":{"integration":1}
,"server_directory":{"\u002Finstances\u002Finstance_name":1}
,"\u002Finstances\u002Finstance_name":{"\u002Fpackages\u002Fwmjdbcadapter\u002Fcode\u002Fjars":1}
,"\u002Fpackages\u002Fwmjdbcadapter\u002Fcode\u002Fjars":{"folder":1}
,"folder":{"restart":1}
,"restart":{"integration":1}
,"uses":{"jar":1}
,"added":{"classpath":1}
}
;Search.control.loadWordPairs(pairs);
