// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mariadb":{"connector\u002Fj":1}
,"connector\u002Fj":{"type":1}
,"type":{"jdbc":1,"datasource":1}
,"jdbc":{"driver":1}
,"driver":{"datasource":1,"name":1}
,"datasource":{"transaction":1,"class":1}
,"transaction":{"type":1}
,"class":{"no_transaction":1}
,"no_transaction":{"local_transaction":1}
,"local_transaction":{"xa_transaction":1}
,"xa_transaction":{"org.mariadb.jdbc.mysqldatasource":1}
,"org.mariadb.jdbc.mysqldatasource":{"org.mariadb.jdbc.mariadbdatasource":1}
,"org.mariadb.jdbc.mariadbdatasource":{"required":1}
,"required":{"connection":1}
,"connection":{"property":1}
,"property":{"fields":1}
,"fields":{"driver":1}
,"name":{"server":1,"user":1,"port":1}
,"server":{"name":1}
,"user":{"password":1}
,"password":{"database":1}
,"database":{"name":1}
,"port":{"number":1}
,"number":{"network":1}
,"network":{"protocol":1}
,"protocol":{"mariadb":1}
}
;Search.control.loadWordPairs(pairs);
