// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"watt.adapter.jdbc.automaticnotification.joincolumn.buffertab":{"specifies":1}
,"specifies":{"whether":1}
,"whether":{"adapter":1}
,"adapter":{"jdbc":1,"displays":1}
,"jdbc":{"displays":1}
,"displays":{"columns":1}
,"columns":{"buffer":1,"source":1}
,"buffer":{"table":1}
,"table":{"joins":1,"column":1}
,"joins":{"tab":1}
,"tab":{"insert":1,"parameter":1,"notification":1}
,"insert":{"delete":1}
,"delete":{"update":1}
,"update":{"polling":1}
,"polling":{"notification":1}
,"notification":{"notification":1,"output":1,"parameter":1}
,"output":{"field":1}
,"field":{"name":1}
,"name":{"different":1,"source":1}
,"different":{"fro":1}
,"fro":{"column":1}
,"column":{"name":1,"selected":1}
,"source":{"table":1}
,"selected":{"joins":1}
,"parameter":{"true":1,"false":1}
,"true":{"adapter":1}
,"false":{"adapter":1}
}
;Search.control.loadWordPairs(pairs);
