// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.adapter.wmjdbc.utils:doclisttoobject":{"wm.adapter.wmjdbc.utils:doclisttoobject":1,"utility":1}
,"utility":{"service":1}
,"service":{"maps":1}
,"maps":{"input":1}
,"input":{"parameter":1,"parameters":1}
,"parameter":{"type":1}
,"type":{"document":1,"object":1}
,"document":{"list":1}
,"list":{"parameter":1,"represents":1,"value":1}
,"object":{"input":1,"output":1,"represents":1,"value":1}
,"parameters":{"doclist":1,"obj":1}
,"doclist":{"document":1}
,"represents":{"document":1,"object":1}
,"value":{"mapped":1}
,"mapped":{"type":1}
,"output":{"parameters":1}
,"obj":{"object":1}
}
;Search.control.loadWordPairs(pairs);
