// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"support":{"synonyms":1,"database":1}
,"synonyms":{"adapter":1,"important":1,"synonyms":1,"supported":1,"documentation":1}
,"adapter":{"jdbc":1,"supports":1}
,"jdbc":{"provides":1,"drivers":1}
,"provides":{"support":1}
,"database":{"synonyms":1,"vendor":1}
,"important":{"jdbc":1}
,"drivers":{"backends":1}
,"backends":{"adapter":1,"information":1}
,"supports":{"return":1}
,"return":{"synonyms":1}
,"supported":{"backends":1}
,"information":{"working":1}
,"working":{"creating":1}
,"creating":{"synonyms":1}
,"documentation":{"database":1}
}
;Search.control.loadWordPairs(pairs);
