// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"designer":1}
,"designer":{"view":1,"designer":1,"navigation":1}
,"view":{"adapter":1,"parameters":1}
,"adapter":{"connection":1,"jdbc":1}
,"connection":{"parameters":1,"param":1,"using":1,"want":1,"appear":1,"information":1}
,"parameters":{"perform":1,"connection":1,"configuring":1}
,"perform":{"following":1}
,"following":{"steps":1}
,"steps":{"view":1}
,"param":{"eters":1}
,"eters":{"designer":1}
,"navigation":{"area":1}
,"area":{"open":1}
,"open":{"package":1}
,"package":{"folder":1}
,"folder":{"onnection":1}
,"onnection":{"located":1}
,"located":{"double-click":1}
,"double-click":{"connection":1}
,"want":{"view":1}
,"appear":{"connection":1}
,"information":{"tab":1}
,"tab":{"descriptions":1}
,"descriptions":{"connection":1}
,"configuring":{"adapter":1}
,"jdbc":{"connections":1}
}
;Search.control.loadWordPairs(pairs);
