// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"support":{"odata":1}
,"odata":{"service":1}
}
;Search.control.loadWordPairs(pairs);
