// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"basicnotifications":1}
,"basicnotifications":{"basicnotification":1}
,"basicnotification":{"polls":1}
,"polls":{"database":1}
,"database":{"table":1}
,"table":{"data":1}
,"data":{"using":1}
,"using":{"sql":1}
,"sql":{"select":1}
,"select":{"operation":1}
,"operation":{"information":1}
,"information":{"notificatio":1}
,"notificatio":{"adapter":1}
,"adapter":{"notifications":1}
}
;Search.control.loadWordPairs(pairs);
