// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"watt.adapter.jdbc.disableemptyresult":{"specifies":1}
,"specifies":{"whether":1}
,"whether":{"adapter":1}
,"adapter":{"jdbc":1,"services":1}
,"jdbc":{"custom":1}
,"custom":{"sql":1}
,"sql":{"services":1}
,"services":{"dynamic":1,"return":1}
,"dynamic":{"sql":1}
,"return":{"docum":1,"empty":1}
,"docum":{"ent":1}
,"ent":{"result":1}
,"result":{"returned":1}
,"returned":{"database":1}
,"database":{"empty":1}
,"empty":{"hen":1,"results":1}
,"hen":{"parameter":1}
,"parameter":{"true":1,"false":1}
,"true":{"adapter":1}
,"results":{"docume":1,"document":1}
,"docume":{"parameter":1}
,"false":{"default":1}
,"default":{"adapter":1}
}
;Search.control.loadWordPairs(pairs);
