// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"notifications":1}
,"notifications":{"designer":1,"view":1}
,"designer":{"view":1,"expand":1,"displays":1}
,"view":{"notifications":1,"notification":1,"double-click":1,"designer":1}
,"notification":{"designer":1,"want":1,"notification":1,"template\u0027s":1,"editor":1}
,"expand":{"package":1}
,"package":{"folder":1}
,"folder":{"contain":1}
,"contain":{"notificatio":1}
,"notificatio":{"want":1}
,"want":{"view":1}
,"double-click":{"notification":1}
,"displays":{"notification":1}
,"template\u0027s":{"apter":1}
,"apter":{"notification":1}
}
;Search.control.loadWordPairs(pairs);
