// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"exttypemapping":{"includes":1}
,"includes":{"additional":1}
,"additional":{"jdbc":1}
,"jdbc":{"types":1,"type":1}
,"types":{"supported":1}
,"supported":{"java.sql.types":1}
,"java.sql.types":{"class":1}
,"class":{"corresponding":1}
,"corresponding":{"code":1}
,"code":{"jdbc":1}
}
;Search.control.loadWordPairs(pairs);
