// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2006-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"adapter":1}
,"adapter":{"services":1,"service":1}
,"services":{"designer":1,"delete":1}
,"designer":{"delete":1,"expand":1}
,"delete":{"adapter":1,"service":1,"right-click":1}
,"service":{"designer":1,"want":1,"click":1}
,"expand":{"package":1}
,"package":{"folder":1}
,"folder":{"contain":1}
,"contain":{"service":1}
,"want":{"delete":1}
,"right-click":{"adapter":1}
,"click":{"delete":1}
}
;Search.control.loadWordPairs(pairs);
