// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"webmethods":{"api":1}
,"api":{"portal":1}
,"portal":{"providers":1}
,"providers":{"consumers":1}
}
;Search.control.loadWordPairs(pairs);
