// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"members":1}
,"members":{"community":1,"remove":1}
,"community":{"remove":1,"prerequisite":1,"click":1,"name":1}
,"remove":{"members":1,"user":1}
,"prerequisite":{"privileges":1}
,"privileges":{"portal":1}
,"portal":{"administrator":1,"window":1}
,"administrator":{"administrator":1,"given":1}
,"given":{"community":1}
,"click":{"right":1,"communities":1,"community":1,"edit":1,"members":1,"user\u0027s":1,"apply":1}
,"right":{"top":1}
,"top":{"corner":1}
,"corner":{"api":1}
,"api":{"portal":1}
,"window":{"display":1}
,"display":{"menu":1}
,"menu":{"options":1}
,"options":{"click":1}
,"communities":{"click":1}
,"name":{"users":1}
,"users":{"removed":1,"community":1}
,"removed":{"click":1,"users":1}
,"edit":{"click":1}
,"user":{"click":1}
,"user\u0027s":{"row":1}
,"row":{"click":1}
,"apply":{"removed":1}
}
;Search.control.loadWordPairs(pairs);
