// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"api":{"portal":1,"provider":1,"published":1,"gateway":1,"unpublished":1,"longer":1}
,"portal":{"assets":1,"api":1,"object":1,"associated":1,"instances":1,"capable":1,"metadata":1}
,"assets":{"api":1}
,"object":{"registered":1}
,"registered":{"api":1}
,"provider":{"api":1}
,"associated":{"organization":1}
,"organization":{"multiple":1,"api":1}
,"multiple":{"api":1}
,"instances":{"share":1,"api":1}
,"share":{"organization":1}
,"published":{"multiple":1,"centrasite":1}
,"capable":{"managing":1}
,"managing":{"apis":1}
,"apis":{"published":1}
,"centrasite":{"api":1}
,"gateway":{"api":1}
,"unpublished":{"(removed)":1}
,"(removed)":{"api":1}
,"metadata":{"deleted":1}
,"deleted":{"api":1}
,"longer":{"available":1}
,"available":{"access":1}
}
;Search.control.loadWordPairs(pairs);
