// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"creating":{"postgres":1}
,"postgres":{"database":1,"create":1}
,"database":{"user":1,"postgres":1,"create":1,"databasename":1,"postgresdb":1}
,"user":{"create":1,"assign":1,"launch":1,"username":1,"dbuser":1}
,"create":{"database":1,"user":1}
,"assign":{"privileges":1}
,"privileges":{"user":1,"grant":1,"database":1}
,"launch":{"postgressql":1}
,"postgressql":{"run":1}
,"run":{"following":1}
,"following":{"command":1}
,"command":{"create":1,"assign":1}
,"databasename":{"example":1,"username":1}
,"example":{"create":1,"grant":1}
,"postgresdb":{"note":1,"dbuser":1}
,"note":{"dbvisualizer":1}
,"dbvisualizer":{"ensure":1}
,"ensure":{"schemas":1}
,"schemas":{"crea":1}
,"crea":{"ted":1}
,"ted":{"run":1}
,"username":{"encrypted":1,"example":1}
,"encrypted":{"password":1}
,"password":{"*password":1,"*aris":1}
,"*password":{"example":1}
,"dbuser":{"encrypted":1}
,"*aris":{"1dm9n":1}
,"1dm9n":{"run":1}
,"grant":{"privileges":1}
}
;Search.control.loadWordPairs(pairs);
