// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"tenants":1}
,"tenants":{"user":1}
,"user":{"master":1,"administrator":1,"name":1}
,"master":{"tenant":1}
,"tenant":{"tena":1,"delete":1,"execute":1,"tenant.name":1,"user":1,"command":1}
,"tena":{"administrator":1}
,"administrator":{"user":1,"privileges":1}
,"privileges":{"delete":1}
,"delete":{"tenant":1}
,"execute":{"following":1}
,"following":{"command":1}
,"command":{"acc":1,"llows":1}
,"acc":{"delete":1}
,"tenant.name":{"note":1,"master.tenant.user.name=master.tenant.user.name":1}
,"note":{"tenant":1}
,"name":{"passwords":1}
,"passwords":{"changed":1}
,"changed":{"upply":1}
,"upply":{"credentials":1}
,"credentials":{"part":1}
,"part":{"delete":1}
,"llows":{"acc":1}
,"master.tenant.user.name=master.tenant.user.name":{"master.tenant.user.pwd=master.tenant.user.pwd":1}
}
;Search.control.loadWordPairs(pairs);
