// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"view":1}
,"view":{"delete":1,"required":1,"click":1,"want":1}
,"delete":{"view":1,"delete":1,"click":1}
,"required":{"prerequisite":1}
,"prerequisite":{"privileges":1}
,"privileges":{"portal":1}
,"portal":{"administrator":1,"window":1}
,"administrator":{"delete":1}
,"click":{"right":1,"administration":1,"customization":1,"views":1,"delete":1,"confirmation":1}
,"right":{"top":1}
,"top":{"corner":1}
,"corner":{"api":1}
,"api":{"portal":1}
,"window":{"display":1}
,"display":{"menu":1}
,"menu":{"options":1}
,"options":{"click":1}
,"administration":{"click":1}
,"customization":{"click":1}
,"views":{"hover":1}
,"hover":{"mouse":1}
,"mouse":{"view":1}
,"want":{"edit":1}
,"edit":{"click":1}
,"confirmation":{"prompt":1}
,"prompt":{"deleted":1}
,"deleted":{"view":1}
}
;Search.control.loadWordPairs(pairs);
