// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"api":{"package":1,"subscribe":1,"plans":1}
,"package":{"details":1,"detai":1,"apis":1,"click":1}
,"details":{"view":1,"page":1,"package":1,"api":1}
,"view":{"associated":1,"details":1,"field":1}
,"associated":{"apis":1,"api":1}
,"apis":{"plans":1,"list":1,"associated":1,"view":1}
,"plans":{"package":1,"list":1,"associated":1}
,"page":{"view":1}
,"subscribe":{"plan":1,"request":1,"particular":1}
,"plan":{"api":1}
,"detai":{"view":1}
,"field":{"description":1}
,"description":{"brief":1,"api":1}
,"brief":{"description":1}
,"list":{"apis":1,"plans":1}
,"click":{"individual":1,"subscribe":1}
,"individual":{"apis":1}
,"request":{"access":1}
,"access":{"token":1}
,"token":{"subscribe":1}
,"particular":{"pla":1}
}
;Search.control.loadWordPairs(pairs);
