// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"accessing":{"elasticsearch":1}
,"elasticsearch":{"using":1,"runnable":1,"run":1,"service":1}
,"using":{"auto-generated":1,"copied":1}
,"auto-generated":{"access":1,"usernam":1}
,"access":{"details":1,"elasticsearch":1,"secured":1}
,"details":{"access":1}
,"usernam":{"password":1}
,"password":{"access":1}
,"runnable":{"start":1}
,"start":{"acc":1}
,"acc":{"run":1}
,"run":{"following":1,"followi":1}
,"following":{"command":1}
,"command":{"list":1,"using":1}
,"list":{"services":1,"available":1}
,"services":{"list":1,"displayed":1}
,"available":{"services":1}
,"displayed":{"copy":1,"username":1}
,"copy":{"service":1}
,"service":{"elasticsearch":1,"show":1,"elasticsearch_serviceid":1,"displayed":1}
,"followi":{"command":1}
,"copied":{"service":1}
,"show":{"service":1}
,"elasticsearch_serviceid":{"parameters":1}
,"parameters":{"elasticsearch":1}
,"username":{"password":1}
,"secured":{"lasticsearch":1}
,"lasticsearch":{"instance":1}
}
;Search.control.loadWordPairs(pairs);
