// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"modifying":{"details":1}
,"details":{"app":1,"modify":1,"modified":1,"click":1}
,"app":{"creator":1,"modify":1,"click":1,"whose":1,"updated":1}
,"creator":{"app":1}
,"modify":{"details":1,"required":1}
,"click":{"right":1,"manage":1,"corresponding":1,"save":1}
,"right":{"top":1}
,"top":{"corner":1}
,"corner":{"api":1}
,"api":{"portal":1}
,"portal":{"window":1}
,"window":{"display":1}
,"display":{"menu":1}
,"menu":{"options":1}
,"options":{"click":1}
,"manage":{"apps":1}
,"apps":{"click":1,"page":1}
,"corresponding":{"app":1}
,"whose":{"details":1}
,"modified":{"modify":1,"information":1}
,"required":{"details":1}
,"save":{"app":1}
,"updated":{"modified":1}
,"information":{"listed":1}
,"listed":{"manage":1}
}
;Search.control.loadWordPairs(pairs);
