// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2014-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"revoking":{"access":1}
,"access":{"tokens":1,"token":1}
,"tokens":{"revoke":1}
,"revoke":{"access":1,"associated":1}
,"token":{"click":1,"revoked":1}
,"click":{"right":1,"applications":1,"revoke":1}
,"right":{"top":1}
,"top":{"corner":1}
,"corner":{"api":1}
,"api":{"portal":1,"access":1,"ass":1}
,"portal":{"window":1}
,"window":{"display":1}
,"display":{"menu":1}
,"menu":{"options":1}
,"options":{"click":1}
,"applications":{"click":1,"list":1}
,"associated":{"apis":1}
,"apis":{"section":1}
,"section":{"required":1}
,"required":{"api":1}
,"revoked":{"application":1}
,"application":{"removed":1}
,"removed":{"rom":1}
,"rom":{"applications":1}
,"list":{"page":1}
,"page":{"api":1}
,"ass":{"ociated":1}
,"ociated":{"application":1}
}
;Search.control.loadWordPairs(pairs);
