// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"summary":{"elements":1}
,"elements":{"folder":1,"available":1}
,"folder":{"following":1,"element":1}
,"following":{"elements":1}
,"available":{"folder":1}
,"element":{"package":1}
,"package":{"description":1}
,"description":{"wm.b2b.editn.db:deletecontrolnumber":1}
,"wm.b2b.editn.db:deletecontrolnumber":{"wmedifortn":1}
,"wmedifortn":{"deletes":1,"obtains":1}
,"deletes":{"interchange":1}
,"interchange":{"sender\u002Freceiver":1}
,"sender\u002Freceiver":{"pair":1}
,"pair":{"informa":1}
,"informa":{"tion":1}
,"tion":{"edienvelope":1}
,"edienvelope":{"table":1}
,"table":{"module-specific":1,"trading":1}
,"module-specific":{"table":1}
,"trading":{"networks":1}
,"networks":{"database":1}
,"database":{"wm.b2b.editn.crossref:getenvinfo":1}
,"wm.b2b.editn.crossref:getenvinfo":{"wmedifortn":1}
,"obtains":{"interchange":1}
}
;Search.control.loadWordPairs(pairs);
