// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"optional":{"inbound":1}
,"inbound":{"processing":1}
,"processing":{"using":1}
,"using":{"trading":1}
,"trading":{"networks":1}
}
;Search.control.loadWordPairs(pairs);
