// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wmedifortn":{"folder":1}
,"folder":{"services":1,"delete":1}
,"services":{"wm.b2b.editn.db":1}
,"wm.b2b.editn.db":{"folder":1}
,"delete":{"unwanted":1}
,"unwanted":{"information":1}
,"information":{"module-speci":1}
,"module-speci":{"fic":1}
,"fic":{"tables":1}
,"tables":{"trading":1}
,"trading":{"networks":1}
,"networks":{"database":1}
}
;Search.control.loadWordPairs(pairs);
