// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"forming":{"edi":1}
,"edi":{"documents":1}
,"documents":{"sending":1}
,"sending":{"outbound":1}
}
;Search.control.loadWordPairs(pairs);
