// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"instance":{"ids":1}
,"ids":{"functional":1}
,"functional":{"acknowledgments":1}
,"acknowledgments":{"recommended":1,"(fas)":1}
,"recommended":{"following":1}
,"following":{"instance":1}
,"(fas)":{"ansi":1}
,"ansi":{"x12":1}
,"x12":{"997":1}
,"997":{"st\u002Fak1\u002Fak102":1}
,"st\u002Fak1\u002Fak102":{"corresponds":1}
,"corresponds":{"group":1}
,"group":{"control":1}
,"control":{"number":1}
,"number":{"un\u002Fedifact":1}
,"un\u002Fedifact":{"contrl":1}
,"contrl":{"message":1}
,"message":{"uci\u002F03":1}
,"uci\u002F03":{"correspon":1}
,"correspon":{"interchange":1}
,"interchange":{"control":1}
}
;Search.control.loadWordPairs(pairs);
