// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"step":{"define":1}
,"define":{"document":1}
,"document":{"type":1}
,"type":{"information":1}
,"information":{"webmethods":1}
,"webmethods":{"define":1}
}
;Search.control.loadWordPairs(pairs);
