// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.b2b.editn:validateenvelope":{"wmedifortn":1}
,"wmedifortn":{"validates":1}
,"validates":{"edi":1}
,"edi":{"envelope":1,"document":1}
,"envelope":{"adds":1,"input":1,"validation":1}
,"adds":{"entries":1}
,"entries":{"trading":1,"errors":1}
,"trading":{"networks":1}
,"networks":{"activity":1}
,"activity":{"log":1}
,"log":{"validation":1}
,"validation":{"errors":1,"compliance":1}
,"errors":{"encountered":1,"document":1,"edi":1}
,"encountered":{"envelope":1}
,"input":{"parameters":1}
,"parameters":{"bizdoc":1,"errorcount":1}
,"bizdoc":{"document":1}
,"document":{"bizdocenvelope":1,"output":1,"list":1}
,"bizdocenvelope":{"represents":1}
,"represents":{"edi":1}
,"output":{"parameters":1}
,"errorcount":{"string":1}
,"string":{"number":1}
,"number":{"error":1}
,"error":{"entries":1}
,"list":{"errors":1}
,"compliance":{"chec":1}
,"chec":{"inserted":1}
,"inserted":{"trading":1}
}
;Search.control.loadWordPairs(pairs);
