// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.b2b.edi.util.formatservices:formatdate6":{"wmedi":1}
,"wmedi":{"formats":1}
,"formats":{"fields":1}
,"fields":{"edi":1}
,"edi":{"data":1}
,"data":{"type":1}
,"type":{"minimum":1,"format":1}
,"minimum":{"length":1}
,"length":{"maximum":1,"format":1}
,"maximum":{"length":1}
,"format":{"string":1,"follows":1}
,"string":{"internal":1}
,"internal":{"external":1}
,"external":{"date":1}
,"date":{"type":1}
,"follows":{"conventions":1}
,"conventions":{"described":1}
,"described":{"java":1}
,"java":{"class":1}
,"class":{"java.t":1}
,"java.t":{"ext.simpledateformat":1}
,"ext.simpledateformat":{"information":1}
,"information":{"oracle":1}
,"oracle":{"ocumentation":1}
}
;Search.control.loadWordPairs(pairs);
