// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.b2b.editn:gettspace":{"wmedifortn":1}
,"wmedifortn":{"retrieves":1}
,"retrieves":{"content":1}
,"content":{"edi":1}
,"edi":{"document":1,"installation":1}
,"document":{"bizdocenvelope":1,"output":1,"usage":1}
,"bizdocenvelope":{"input":1,"retrieve":1}
,"input":{"parameters":1}
,"parameters":{"bizdoc":1,"edidata":1}
,"bizdoc":{"object":1}
,"object":{"bizdocenvelope":1,"content":1}
,"retrieve":{"content":1}
,"output":{"parameters":1}
,"edidata":{"object":1}
,"usage":{"notes":1}
,"notes":{"information":1}
,"information":{"using":1}
,"using":{"service":1}
,"service":{"chapt":1}
,"chapt":{"processing":1}
,"processing":{"inbound":1}
,"inbound":{"documents":1}
,"documents":{"webmethods":1}
,"webmethods":{"module":1}
,"module":{"edi":1}
,"installation":{"user\u2019s":1}
,"user\u2019s":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
