// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"processing":{"inbound":1,"create":1}
,"inbound":{"edi":1,"processing":1}
,"edi":{"documents":1}
,"documents":{"trading":1}
,"trading":{"networks":1}
,"networks":{"inbound":1,"information":1,"process":1}
,"create":{"clients":1}
,"clients":{"send":1}
,"send":{"edi":1}
,"information":{"trading":1}
,"process":{"documents":1}
}
;Search.control.loadWordPairs(pairs);
