// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"managing":{"document":1}
,"document":{"attributes":1,"attribute":1}
,"attributes":{"perform":1,"task":1}
,"perform":{"following":1}
,"following":{"tasks":1}
,"tasks":{"document":1}
,"task":{"find":1}
,"find":{"information":1}
,"information":{"add":1}
,"add":{"document":1}
,"attribute":{"adding":1,"edit":1,"editing":1,"delete":1,"deleting":1}
,"adding":{"document":1}
,"edit":{"document":1}
,"editing":{"document":1}
,"delete":{"document":1}
,"deleting":{"document":1}
}
;Search.control.loadWordPairs(pairs);
