// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"flat":{"file":1}
,"file":{"schema":1,"trading":1,"schemas":1}
,"schema":{"namespace":1,"edi":1}
,"namespace":{"conventions":1}
,"conventions":{"define":1,"described":1}
,"define":{"edi":1}
,"edi":{"document":1,"creates":1,"transaction":1}
,"document":{"type":1}
,"type":{"module":1}
,"module":{"edi":1}
,"creates":{"flat":1}
,"transaction":{"tradacoms":1}
,"tradacoms":{"file":1}
,"trading":{"networks":1}
,"networks":{"stores":1}
,"stores":{"flat":1}
,"schemas":{"ediffschema":1}
,"ediffschema":{"folder":1}
,"folder":{"medifortn":1}
,"medifortn":{"package":1}
,"package":{"using":1}
,"using":{"namespace":1}
,"described":{"below":1}
}
;Search.control.loadWordPairs(pairs);
