// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wmedifortn":{"crossref":1}
,"crossref":{"folder":1}
,"folder":{"services":1,"manage":1}
,"services":{"wm.b2b.editn.crossref":1}
,"wm.b2b.editn.crossref":{"folder":1}
,"manage":{"interchange":1}
,"interchange":{"sender\u002Freceiver":1}
,"sender\u002Freceiver":{"pair":1}
,"pair":{"informati":1}
,"informati":{"defined":1}
}
;Search.control.loadWordPairs(pairs);
