// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"example":{"sorting":1}
,"sorting":{"documents":1}
,"documents":{"following":1,"schedul":1,"sorted":1}
,"following":{"diagram":1,"figure":1}
,"diagram":{"shows":1}
,"shows":{"three":1,"transactions":1}
,"three":{"edi":1,"documents":1}
,"edi":{"documents":1}
,"schedul":{"delivery":1}
,"delivery":{"queue":1}
,"queue":{"following":1}
,"figure":{"shows":1}
,"transactions":{"abo":1}
,"abo":{"three":1}
,"sorted":{"collection":1}
,"collection":{"areas":1}
}
;Search.control.loadWordPairs(pairs);
