// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"defining":{"control":1}
,"control":{"number":1}
,"number":{"information":1}
,"information":{"trading":1}
,"trading":{"partners":1}
}
;Search.control.loadWordPairs(pairs);
