// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"process":{"inbound":1}
,"inbound":{"edi":1,"non-tradacoms":1}
,"edi":{"documents":1}
,"documents":{"addition":1,"preparing":1,"using":1}
,"addition":{"items":1}
,"items":{"listed":1}
,"listed":{"preparing":1}
,"preparing":{"receive":1,"process":1}
,"receive":{"edi":1}
,"non-tradacoms":{"documents":1}
,"using":{"trading":1,"non-standard":1}
,"trading":{"networks":1}
,"networks":{"using":1}
,"non-standard":{"processing":1}
,"processing":{"define":1}
,"define":{"interchange":1}
,"interchange":{"sender\u002Freceiver":1}
,"sender\u002Freceiver":{"pair":1}
,"pair":{"information":1}
,"information":{"instruct":1,"defining":1}
,"instruct":{"ions":1}
,"ions":{"defining":1}
,"defining":{"information":1,"interchange-level":1}
,"interchange-level":{"sender\u002Freceiver":1}
}
;Search.control.loadWordPairs(pairs);
