// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"defining":{"module":1}
,"module":{"edi":1}
,"edi":{"creates":1,"properties":1}
,"creates":{"control":1}
,"control":{"number":1}
,"number":{"sequence":1}
,"sequence":{"ediallowcustomcontrolnumbersequence":1,"information":1}
,"ediallowcustomcontrolnumbersequence":{"property":1}
,"property":{"defi":1}
,"defi":{"module":1}
,"information":{"defining":1}
}
;Search.control.loadWordPairs(pairs);
