// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.b2b.edi.tradacoms.doc:isfileenvelope":{"wmedifortn":1}
,"wmedifortn":{"determines":1}
,"determines":{"whether":1}
,"whether":{"bizdocenvelope":1}
,"bizdocenvelope":{"contains":1,"object":1,"represents":1,"contain":1}
,"contains":{"radacoms":1,"tradacoms":1}
,"radacoms":{"file":1}
,"file":{"document":1,"output":1,"value":1,"false":1}
,"document":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bizdocenvelope":1,"isfileenvelope":1}
,"object":{"bizdocenvelope":1}
,"represents":{"tradacoms":1}
,"tradacoms":{"file":1}
,"output":{"parameters":1}
,"isfileenvelope":{"string":1}
,"string":{"whether":1}
,"value":{"meaning":1}
,"meaning":{"true":1}
,"true":{"bizdocenvelope":1}
,"false":{"bizdocenvelope":1}
,"contain":{"tradacoms":1}
}
;Search.control.loadWordPairs(pairs);
