// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sorting":{"transactions":1}
,"transactions":{"queued":1,"edi":1}
,"queued":{"documents":1,"edi":1}
,"documents":{"interchan":1,"interchange":1}
,"interchan":{"headers":1}
,"headers":{"section":1,"information":1,"sorting":1}
,"section":{"describes":1}
,"describes":{"module":1}
,"module":{"edi":1}
,"edi":{"sorts":1,"documents":1}
,"sorts":{"transactions":1}
,"interchange":{"transmission":1}
,"transmission":{"headers":1}
,"information":{"bout":1}
,"bout":{"module":1}
}
;Search.control.loadWordPairs(pairs);
