// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"submitting":{"edi":1}
,"edi":{"document":1,"-specific":1,"recognizer":1}
,"document":{"trading":1,"back":1,"recognition":1,"define":1}
,"trading":{"networks":1}
,"networks":{"submit":1,"document":1}
,"submit":{"outbound":1}
,"outbound":{"edi":1}
,"back":{"trading":1}
,"recognition":{"means":1}
,"means":{"module":1}
,"module":{"edi":1}
,"-specific":{"recognizer":1}
,"recognizer":{"edi":1,"receives":1}
,"receives":{"control":1}
,"control":{"perform":1}
,"perform":{"processing":1}
,"processing":{"edi":1,"rule":1}
,"define":{"processing":1}
,"rule":{"indicate":1}
,"indicate":{"deliver":1}
,"deliver":{"outbound":1}
}
;Search.control.loadWordPairs(pairs);
