// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"adding":{"un\u002Fedifact":1}
,"un\u002Fedifact":{"envelopes":1,"edi":1}
,"envelopes":{"add":1,"un\u002Fedifact":1}
,"add":{"appropriate":1}
,"appropriate":{"group":1}
,"group":{"interchange":1}
,"interchange":{"envelopes":1}
,"edi":{"document":1,"built-in":1}
,"document":{"invoke":1}
,"invoke":{"wm.b2b.edi.util:addicenvelopeedifact":1,"wm.b2b.edi.util:addgroupenvelope":1}
,"wm.b2b.edi.util:addicenvelopeedifact":{"service":1}
,"service":{"rather":1,"webmethods":1}
,"rather":{"invoke":1}
,"wm.b2b.edi.util:addgroupenvelope":{"wm.b2b.edi.util:addicenvelope":1}
,"wm.b2b.edi.util:addicenvelope":{"services":1}
,"services":{"shown":1,"reference":1}
,"shown":{"following":1}
,"following":{"diagram":1}
,"diagram":{"information":1}
,"information":{"wm.b2b.edi.util:addicenvelopeedifact":1}
,"webmethods":{"module":1}
,"module":{"edi":1}
,"built-in":{"services":1}
}
;Search.control.loadWordPairs(pairs);
