// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"documentid":{"documentid":1,"system":1,"follows":1,"interchange":1,"000005334":1,"value":1,"0001":1}
,"system":{"attribute":1}
,"attribute":{"identifier":1}
,"identifier":{"document":1}
,"document":{"module":1,"value":1}
,"module":{"edi":1}
,"edi":{"sets":1}
,"sets":{"documentid":1}
,"follows":{"type":1}
,"type":{"document":1}
,"value":{"used":1,"isa13":1,"gs06":1,"st02":1,"new":1}
,"used":{"documentid":1}
,"interchange":{"interchange":1,"control":1}
,"control":{"number":1}
,"number":{"example":1,"field":1}
,"example":{"sample\u2019s":1}
,"sample\u2019s":{"documentid":1}
,"000005334":{"value":1}
,"isa13":{"group":1}
,"group":{"group":1,"control":1}
,"gs06":{"transaction":1}
,"transaction":{"transaction":1,"control":1}
,"0001":{"value":1}
,"st02":{"vda":1}
,"vda":{"documents":1}
,"documents":{"module":1}
,"new":{"control":1}
}
;Search.control.loadWordPairs(pairs);
