// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"reprocessing":{"edi":1}
,"edi":{"documents":1,"invalid":1,"processes":1}
,"documents":{"invalid":1,"action":1}
,"invalid":{"control":1,"ntrol":1}
,"control":{"numbers":1,"number":1}
,"numbers":{"action":1,"information":1,"varies":1}
,"action":{"document":1,"reject":1}
,"document":{"duplic":1}
,"duplic":{"ate":1}
,"ate":{"out-of-sequence":1}
,"out-of-sequence":{"control":1}
,"number":{"reject":1,"dup":1,"out-of-sequence":1}
,"reject":{"later":1,"reject":1,"reprocess":1}
,"later":{"reprocess":1}
,"reprocess":{"documents":1}
,"ntrol":{"numbers":1}
,"information":{"define":1,"module":1}
,"define":{"actio":1}
,"actio":{"defining":1}
,"defining":{"actions":1}
,"actions":{"module":1}
,"module":{"edi":1}
,"processes":{"documents":1}
,"varies":{"based":1}
,"based":{"whether":1}
,"whether":{"invalid":1}
,"dup":{"licate":1}
,"licate":{"control":1}
}
;Search.control.loadWordPairs(pairs);
