// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wmedifortn":{"tpa":1}
,"tpa":{"folder":1}
,"folder":{"service":1,"work":1}
,"service":{"wm.b2b.editn.tpa":1}
,"wm.b2b.editn.tpa":{"folder":1}
,"work":{"editpas":1}
}
;Search.control.loadWordPairs(pairs);
