// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2000-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wmedifortn":{"doc":1,"package":1}
,"doc":{"folder":1}
,"folder":{"module":1,"work":1}
,"module":{"edi":1}
,"edi":{"uses":1}
,"uses":{"services":1}
,"services":{"folder":1}
,"work":{"instanc":1}
,"instanc":{"queries":1}
,"queries":{"wmedifortn":1}
,"package":{"home":1}
,"home":{"page":1}
}
;Search.control.loadWordPairs(pairs);
