// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"link":{"properties":1,"drawn":1,"view":1,"double-click":1,"pipeline":1}
,"properties":{"properties":1,"view":1,"link":1,"links":1}
,"view":{"apply":1,"properties":1}
,"apply":{"conditions":1}
,"conditions":{"link":1}
,"drawn":{"two":1}
,"two":{"variables":1}
,"variables":{"specify":1}
,"specify":{"element":1}
,"element":{"array":1}
,"array":{"want":1}
,"want":{"link":1}
,"double-click":{"link":1}
,"pipeline":{"editor":1}
,"editor":{"related":1}
,"related":{"topics":1}
,"topics":{"general":1}
,"general":{"properties":1}
}
;Search.control.loadWordPairs(pairs);
