// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"prerequisites":{"building":1}
,"building":{"browser-based":1}
,"browser-based":{"client":1}
,"client":{"code":1,"invoke":1,"url":1,"uses":1,"invokes":1}
,"code":{"build":1,"ensure":1}
,"build":{"browser-based":1}
,"ensure":{"integration":1}
,"integration":{"server":1}
,"server":{"running":1,"returns":1}
,"running":{"input":1}
,"input":{"values":1}
,"values":{"service":1,"url":1,"passed":1}
,"service":{"want":1,"related":1,"browser-based":1,"lient":1}
,"want":{"browser-based":1}
,"invoke":{"defined":1,"service":1,"services":1}
,"defined":{"need":1}
,"need":{"include":1}
,"include":{"input":1}
,"url":{"invoke":1,"client":1}
,"related":{"topics":1}
,"topics":{"building":1}
,"uses":{"invoke":1}
,"services":{"input":1}
,"passed":{"service":1}
,"invokes":{"integration":1}
,"returns":{"output":1}
,"output":{"service":1}
,"lient":{"invoked":1}
}
;Search.control.loadWordPairs(pairs);
