// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"building":{"xslt":1}
,"xslt":{"services":1}
,"services":{"designer":1,"transform":1}
,"designer":{"create":1}
,"create":{"xslt":1}
,"transform":{"xml":1}
,"xml":{"source":1}
,"source":{"data":1}
,"data":{"acco":1}
,"acco":{"rding":1}
,"rding":{"instructions":1}
,"instructions":{"associated":1}
,"associated":{"style":1}
,"style":{"sheet":1}
}
;Search.control.loadWordPairs(pairs);
