// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"connection":1}
,"connection":{"cloud":1,"configuration":1,"configurations":1}
,"cloud":{"container":1}
,"container":{"need":1,"designer":1,"ensure":1,"valid":1}
,"need":{"provide":1}
,"provide":{"specific":1}
,"specific":{"information":1}
,"information":{"designer":1,"connection":1}
,"designer":{"initiating":1,"saves":1,"configure":1}
,"initiating":{"connection":1}
,"saves":{"information":1}
,"configuration":{"add":1}
,"add":{"edit":1}
,"edit":{"update":1}
,"update":{"connection":1}
,"configurations":{"designer":1}
,"configure":{"connection":1}
,"ensure":{"following":1}
,"following":{"criteria":1}
,"criteria":{"met":1}
,"met":{"valid":1}
,"valid":{"url":1,"user":1}
,"url":{"exists":1}
,"exists":{"connect":1}
,"connect":{"cloud":1}
,"user":{"account":1}
,"account":{"created":1}
,"created":{"cloud":1}
}
;Search.control.loadWordPairs(pairs);
