// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"concepts":{"flat":1}
,"flat":{"file":1}
,"file":{"features":1,"formats":1,"schema":1,"data":1,"dictio":1,"elements":1,"schemas":1}
,"features":{"translate":1}
,"translate":{"documents":1}
,"documents":{"flat":1}
,"formats":{"translation":1}
,"translation":{"flat":1}
,"schema":{"define":1}
,"define":{"identify":1}
,"identify":{"individua":1}
,"individua":{"records":1}
,"records":{"within":1,"create":1}
,"within":{"flat":1}
,"data":{"contained":1}
,"contained":{"ach":1}
,"ach":{"records":1}
,"create":{"flat":1}
,"dictio":{"nary":1}
,"nary":{"contain":1}
,"contain":{"flat":1}
,"elements":{"(records":1}
,"(records":{"composites":1}
,"composites":{"fields)":1}
,"fields)":{"want":1}
,"want":{"available":1}
,"available":{"flat":1}
}
;Search.control.loadWordPairs(pairs);
