// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"listing":{"locked":1}
,"locked":{"elements":1,"package":1,"elemen":1}
,"elements":{"view":1,"locked":1,"package":1,"click":1,"unlock":1,"clicking":1,"unlocking":1}
,"view":{"list":1,"select":1,"locked":1}
,"list":{"elements":1,"locked":1}
,"package":{"navigator":1}
,"navigator":{"view":1}
,"select":{"server":1}
,"server":{"ant":1}
,"ant":{"view":1}
,"click":{"file":1,"element":1}
,"file":{"properties":1}
,"properties":{"locked":1}
,"unlock":{"individual":1,"unlock":1,"elements":1,"information":1}
,"individual":{"elements":1}
,"elemen":{"page":1}
,"page":{"pressing":1}
,"pressing":{"ctrl":1}
,"ctrl":{"key":1}
,"key":{"click":1}
,"element":{"clicking":1}
,"clicking":{"unlock":1}
,"information":{"unlocking":1}
,"unlocking":{"elements":1}
}
;Search.control.loadWordPairs(pairs);
