// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"property":1}
,"property":{"templates":1,"template":1}
,"templates":{"delete":1,"select":1}
,"delete":{"element":1,"click":1,"template":1}
,"element":{"property":1}
,"template":{"designer":1,"want":1,"elements":1,"reset":1}
,"designer":{"window":1}
,"window":{"preferences":1}
,"preferences":{"preferences":1,"navigation":1,"page":1}
,"navigation":{"tree":1}
,"tree":{"select":1}
,"select":{"software":1,"property":1}
,"software":{"service":1}
,"service":{"development":1}
,"development":{"element":1}
,"want":{"delete":1}
,"click":{"remove":1,"note":1}
,"remove":{"preferences":1}
,"page":{"click":1}
,"note":{"delete":1}
,"elements":{"delete":1}
,"reset":{"default":1}
,"default":{"template":1}
}
;Search.control.loadWordPairs(pairs);
