// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.soap.handler:registerprovider":{"wmpublic":1}
,"wmpublic":{"deprecated":1}
,"deprecated":{"-replaced":1}
,"-replaced":{"pub.soap.handler:registerwmprovider":1}
,"pub.soap.handler:registerwmprovider":{"registers":1}
,"registers":{"handler":1}
,"handler":{"based":1,"handler":1,"object":1}
,"based":{"jax-rpc":1}
,"jax-rpc":{"provider":1}
,"provider":{"web":1,"handler":1}
,"web":{"ser":1}
,"ser":{"vice":1}
,"vice":{"descriptor":1}
,"descriptor":{"input":1}
,"input":{"parameters":1}
,"parameters":{"descriptivename":1,"none":1}
,"descriptivename":{"string":1}
,"string":{"name":1}
,"name":{"want":1}
,"want":{"assign":1}
,"assign":{"soap":1}
,"soap":{"provider":1}
,"object":{"instance":1,"handlerinfo":1,"optional":1,"output":1}
,"instance":{"handler":1,"handlerinfo":1}
,"handlerinfo":{"object":1}
,"optional":{"instance":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
