// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"startup":1}
,"startup":{"service":1,"services":1}
,"service":{"remove":1,"invoked":1,"package":1,"want":1}
,"remove":{"startup":1,"package":1,"selected":1}
,"invoked":{"service":1}
,"package":{"package":1,"identified":1,"pendency":1,"dependency":1,"navigator":1,"want":1}
,"identified":{"package":1}
,"pendency":{"sure":1}
,"sure":{"remove":1}
,"dependency":{"remove":1}
,"navigator":{"view":1}
,"view":{"select":1}
,"select":{"package":1,"startup\u002Fshutdown":1,"service":1}
,"want":{"remove":1}
,"services":{"click":1,"startup":1,"select":1,"list":1}
,"click":{"file":1,"click":1}
,"file":{"properties":1}
,"properties":{"properties":1,"packagename":1}
,"packagename":{"dialog":1}
,"dialog":{"box":1}
,"box":{"select":1}
,"startup\u002Fshutdown":{"services":1}
,"selected":{"services":1}
,"list":{"click":1}
}
;Search.control.loadWordPairs(pairs);
