// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"copying":{"moving":1,"elements":1}
,"moving":{"deleting":1,"copying":1}
,"deleting":{"locked":1,"elements":1}
,"locked":{"elements":1,"element":1,"unlocked":1}
,"elements":{"copy":1,"deleting":1}
,"copy":{"locked":1}
,"element":{"folder":1,"unles":1}
,"folder":{"package":1}
,"package":{"however":1}
,"however":{"cannot":1}
,"cannot":{"move":1}
,"move":{"rename":1}
,"rename":{"delete":1}
,"delete":{"element":1}
,"unles":{"locked":1}
,"unlocked":{"related":1}
,"related":{"topics":1}
,"topics":{"moving":1}
}
;Search.control.loadWordPairs(pairs);
