// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"webmethods":1}
,"webmethods":{"mobile":1}
,"mobile":{"support":1,"application":1}
,"support":{"includes":1}
,"includes":{"built-in":1}
,"built-in":{"service":1}
,"service":{"two":1}
,"two":{"specifications":1}
,"specifications":{"fac":1}
,"fac":{"ilitate":1}
,"ilitate":{"data":1}
,"data":{"synchronization":1}
,"synchronization":{"mobile":1}
,"application":{"environ":1}
,"environ":{"ment":1}
}
;Search.control.loadWordPairs(pairs);
