// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"file":{"polling":1,"processing":1,"user\u0027s":1}
,"polling":{"ports":1,"port":1}
,"ports":{"file":1,"flat":1}
,"port":{"periodically":1}
,"periodically":{"polls":1}
,"polls":{"monitoring":1}
,"monitoring":{"director":1}
,"director":{"arrival":1}
,"arrival":{"files":1}
,"files":{"integration":1}
,"integration":{"server":1}
,"server":{"runs":1}
,"runs":{"special":1}
,"special":{"file":1}
,"processing":{"service":1}
,"service":{"against":1}
,"against":{"fil":1}
,"fil":{"information":1}
,"information":{"file":1}
,"flat":{"file":1}
,"user\u0027s":{"guide":1}
}
;Search.control.loadWordPairs(pairs);
