// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"disabled":{"settings":1}
,"settings":{"following":1}
,"following":{"table":1}
,"table":{"disable":1}
,"disable":{"keep-aliv":1}
,"keep-aliv":{"mode":1}
,"mode":{"parameter":1}
,"parameter":{"value":1}
,"value":{"watt.server.brokertransport.dur":1}
,"watt.server.brokertransport.dur":{"2147483647":1}
,"2147483647":{"watt.server.brokertransport.max":1,"watt.server.brokertransport.ret":1}
,"watt.server.brokertransport.max":{"2147483647":1}
}
;Search.control.loadWordPairs(pairs);
