// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"comparing":{"flow":1,"integration":1}
,"flow":{"services":1}
,"services":{"compare":1,"server":1}
,"compare":{"tool":1,"two":1}
,"tool":{"compare":1}
,"two":{"flow":1}
,"server":{"different":1,"packages":1}
,"different":{"servers":1}
,"servers":{"informati":1}
,"informati":{"comparing":1}
,"integration":{"server":1}
,"packages":{"elements":1}
,"elements":{"related":1}
,"related":{"topics":1}
,"topics":{"comparing":1}
}
;Search.control.loadWordPairs(pairs);
