// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"rest":{"api":1,"resource":1,"definition":1}
,"api":{"descriptor":1,"descriptors":1}
,"descriptor":{"properties":1,"double-click":1,"package":1}
,"properties":{"view":1,"rest":1,"operation":1}
,"view":{"properties":1,"designer":1}
,"double-click":{"rest":1}
,"package":{"navigator":1}
,"navigator":{"view":1}
,"designer":{"related":1}
,"related":{"topics":1}
,"topics":{"general":1}
,"general":{"properties":1}
,"descriptors":{"rest":1}
,"resource":{"properties":1}
,"operation":{"properties":1}
,"definition":{"properties":1,"parameter":1}
,"parameter":{"properties":1}
}
;Search.control.loadWordPairs(pairs);
