// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"watt.frag":{"watt.frag.keep.original.servicename":1}
,"watt.frag.keep.original.servicename":{"specifies":1}
,"specifies":{"whether":1}
,"whether":{"integration":1}
,"integration":{"server":1}
,"server":{"retains":1,"modifies":1,"change":1}
,"retains":{"original":1}
,"original":{"service":1}
,"service":{"name":1,"parameter":1}
,"name":{"input":1,"false":1,"default":1}
,"input":{"fields":1}
,"fields":{"agging":1}
,"agging":{"compiling":1}
,"compiling":{"java":1}
,"java":{"service":1}
,"parameter":{"true":1}
,"true":{"integration":1}
,"false":{"integration":1,"important":1}
,"modifies":{"original":1}
,"default":{"false":1}
,"important":{"change":1}
,"change":{"value":1,"effect":1}
,"value":{"property":1}
,"property":{"restart":1}
,"restart":{"integration":1}
}
;Search.control.loadWordPairs(pairs);
