// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"cloud":{"explorer":1,"service":1,"container":1}
,"explorer":{"view":1}
,"view":{"toolbar":1}
,"toolbar":{"following":1,"button":1}
,"following":{"button":1}
,"button":{"unique":1,"description":1}
,"unique":{"cloud":1}
,"service":{"development":1}
,"development":{"appears":1}
,"appears":{"cloud":1}
,"description":{"opens":1}
,"opens":{"cloud":1}
,"container":{"preferences":1,"connections":1}
,"preferences":{"add":1}
,"add":{"edit":1}
,"edit":{"remove":1}
,"remove":{"cloud":1}
}
;Search.control.loadWordPairs(pairs);
