// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.security.util:convertsecurestring":{"wmpublic":1}
,"wmpublic":{"returns":1}
,"returns":{"wmsecurestring":1}
,"wmsecurestring":{"java":1,"wmsecurestring":1,"converted":1,"string":1}
,"java":{"string":1,"byte":1,"character":1}
,"string":{"byte":1,"format":1,"value":1,"output":1,"string":1,"wmsecurestring":1,"bytes":1}
,"byte":{"arra":1,"char":1,"wmsecurestring":1,"array":1}
,"arra":{"character":1}
,"character":{"array":1,"arr":1}
,"array":{"format":1,"chars":1}
,"format":{"input":1,"wmsecurestring":1}
,"input":{"parameters":1}
,"parameters":{"securestring":1,"string":1}
,"securestring":{"wmsecurestring":1}
,"converted":{"returnas":1,"lid":1,"java":1,"native":1}
,"returnas":{"string":1}
,"lid":{"options":1}
,"options":{"byte":1}
,"char":{"java":1,"wmsecurestring":1}
,"value":{"parameter":1}
,"parameter":{"specified":1}
,"specified":{"default":1}
,"default":{"conve":1}
,"conve":{"wmsecurestring":1}
,"output":{"parameters":1}
,"bytes":{"byte":1}
,"native":{"java":1}
,"chars":{"char":1}
}
;Search.control.loadWordPairs(pairs);
