// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"flat":{"file":1}
,"file":{"element":1,"elements":1,"schema":1,"dicti":1}
,"element":{"properties":1}
,"properties":{"flat":1,"specify":1,"apply":1,"record":1,"composite":1,"field":1}
,"elements":{"define":1,"almost":1}
,"define":{"structure":1}
,"structure":{"flat":1}
,"schema":{"create":1}
,"create":{"contents":1}
,"contents":{"flat":1}
,"dicti":{"onary":1}
,"onary":{"properties":1}
,"specify":{"flat":1}
,"almost":{"property":1}
,"property":{"descriptions":1}
,"descriptions":{"indicate":1}
,"indicate":{"circums":1}
,"circums":{"tances":1}
,"tances":{"properties":1}
,"apply":{"related":1}
,"related":{"topics":1}
,"topics":{"record":1}
,"record":{"definition":1,"reference":1}
,"definition":{"properties":1}
,"reference":{"properties":1}
,"composite":{"definition":1,"reference":1}
,"field":{"definition":1,"reference":1}
}
;Search.control.loadWordPairs(pairs);
