// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"defining":{"clients":1}
,"clients":{"client":1}
,"client":{"application":1,"authorization":1}
,"application":{"(client)":1}
,"(client)":{"request":1}
,"request":{"access":1}
,"access":{"protected":1}
,"protected":{"resource":1}
,"resource":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"register":1}
,"register":{"client":1}
,"authorization":{"server":1}
}
;Search.control.loadWordPairs(pairs);
