// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"cloud":{"container":1}
,"container":{"preferences":1,"connection":1,"host":1,"selected":1}
,"preferences":{"field":1}
,"field":{"description":1}
,"description":{"name":1}
,"name":{"name":1,"cloud":1,"account":1}
,"connection":{"configuration":1,"recipes":1,"install":1}
,"configuration":{"url":1}
,"url":{"url":1,"cloud":1}
,"host":{"designer":1}
,"designer":{"connect":1,"selected":1,"uses":1}
,"connect":{"example":1}
,"example":{"https:\u002F\u002F<sub-domain>":1}
,"https:\u002F\u002F<sub-domain>":{"<domain-name>":1}
,"<domain-name>":{"<domain-suffix>":1}
,"<domain-suffix>":{"user":1}
,"user":{"user":1,"name":1}
,"account":{"cloud":1}
,"selected":{"cloud":1}
,"recipes":{"select":1,"default":1}
,"select":{"check":1}
,"check":{"box":1}
,"box":{"want":1}
,"want":{"designer":1}
,"install":{"recipes":1}
,"default":{"designer":1}
,"uses":{"pre-configured":1}
,"pre-configured":{"cloud":1}
}
;Search.control.loadWordPairs(pairs);
