// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"parquet":{"folder":1,"files":1}
,"folder":{"elements":1,"read":1}
,"elements":{"parquet":1}
,"read":{"write":1}
,"write":{"apa":1}
,"apa":{"che":1}
,"che":{"parquet":1}
,"files":{"integration":1}
,"integration":{"server":1}
,"server":{"idata":1}
}
;Search.control.loadWordPairs(pairs);
