// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"api":{"portal":1,"descriptors":1}
,"portal":{"preferences":1,"connection":1,"tenant":1}
,"preferences":{"field":1}
,"field":{"description":1}
,"description":{"name":1}
,"name":{"name":1,"api":1,"valid":1}
,"connection":{"configuration":1}
,"configuration":{"host":1,"user":1}
,"host":{"host":1,"name":1}
,"user":{"name":1,"account":1}
,"valid":{"user":1}
,"account":{"api":1}
,"tenant":{"tenant":1,"rest":1}
,"rest":{"api":1}
,"descriptors":{"publ":1}
,"publ":{"ished":1}
}
;Search.control.loadWordPairs(pairs);
