// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"branch":{"branch":1,"step":1,"specifying":1,"properties":1}
,"step":{"selects":1,"based":1,"fail":1}
,"selects":{"executes":1}
,"executes":{"child":1}
,"child":{"step":1}
,"based":{"value":1}
,"value":{"variables":1,"writing":1,"branching":1}
,"variables":{"pipeline":1,"want":1}
,"pipeline":{"indic":1}
,"indic":{"ate":1}
,"ate":{"variables":1}
,"want":{"branch":1}
,"specifying":{"swit":1}
,"swit":{"value":1}
,"writing":{"expression":1}
,"expression":{"includes":1}
,"includes":{"varia":1}
,"varia":{"bles":1}
,"bles":{"related":1}
,"related":{"topics":1}
,"topics":{"branching":1}
,"branching":{"switch":1,"expressions":1}
,"switch":{"value":1}
,"expressions":{"branch":1}
,"properties":{"conditions":1}
,"conditions":{"cause":1}
,"cause":{"branch":1}
}
;Search.control.loadWordPairs(pairs);
