// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"external":{"entity":1,"source":1}
,"entity":{"type":1,"note":1}
,"type":{"properties":1,"connection":1,"source":1}
,"properties":{"property":1,"external":1}
,"property":{"description":1}
,"description":{"name":1}
,"name":{"specifies":1,"odata":1,"source":1}
,"specifies":{"name":1,"connection":1}
,"odata":{"external":1}
,"connection":{"alias":1,"used":1}
,"alias":{"specifies":1}
,"used":{"external":1}
,"source":{"type":1,"reference":1,"external":1}
,"reference":{"name":1}
,"note":{"cannot":1}
,"cannot":{"edit":1}
,"edit":{"properties":1}
}
;Search.control.loadWordPairs(pairs);
