// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"webmethods":{"broker":1}
,"broker":{"client":1,"clients":1,"note":1,"deprecated":1}
,"client":{"logging":1}
,"logging":{"instructions":1}
,"instructions":{"configuring":1}
,"configuring":{"system":1}
,"system":{"log":1}
,"log":{"documents":1}
,"documents":{"webmethods":1}
,"clients":{"publish":1}
,"publish":{"subscribe":1}
,"subscribe":{"brokers":1}
,"brokers":{"administering":1}
,"administering":{"webmethods":1}
,"note":{"webmethods":1}
}
;Search.control.loadWordPairs(pairs);
