// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"policy":1}
,"policy":{"web":1,"detach":1,"click":1,"want":1}
,"web":{"service":1,"servi":1}
,"service":{"descriptor":1,"des":1}
,"descriptor":{"longer":1,"governe":1,"remove":1,"package":1,"click":1,"toolbar":1}
,"longer":{"want":1}
,"want":{"web":1,"remove":1,"delete":1}
,"governe":{"particular":1}
,"particular":{"policy":1}
,"detach":{"remove":1}
,"remove":{"polic":1,"policy":1}
,"polic":{"web":1}
,"package":{"navigator":1}
,"navigator":{"view":1}
,"view":{"open":1}
,"open":{"lock":1}
,"lock":{"web":1}
,"des":{"criptor":1}
,"criptor":{"want":1}
,"click":{"policies":1,"web":1}
,"policies":{"tab":1}
,"tab":{"select":1}
,"select":{"policy":1}
,"delete":{"web":1}
,"servi":{"descriptor":1}
,"toolbar":{"right-click":1}
,"right-click":{"lect":1}
,"lect":{"delete":1}
}
;Search.control.loadWordPairs(pairs);
