// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"package":{"properties":1,"dependencies":1,"package":1,"navigator":1,"information":1,"settings":1,"permissions":1,"replication":1,"startup\u002Fshutdown":1}
,"properties":{"properties":1,"dialog":1,"related":1}
,"dialog":{"box":1}
,"box":{"view":1,"click":1}
,"view":{"information":1}
,"information":{"pack":1,"package":1}
,"pack":{"ages":1}
,"ages":{"integration":1}
,"integration":{"server":1}
,"server":{"assign":1}
,"assign":{"package":1}
,"dependencies":{"permissions":1,"package":1}
,"permissions":{"replicatio":1,"package":1}
,"replicatio":{"services":1}
,"services":{"startup":1,"open":1,"package":1}
,"startup":{"shutdown":1}
,"shutdown":{"services":1}
,"open":{"properties":1}
,"click":{"package":1}
,"navigator":{"designer":1}
,"designer":{"select":1}
,"select":{"file":1}
,"file":{"properties":1}
,"related":{"topics":1}
,"topics":{"package":1}
,"settings":{"package":1}
,"replication":{"services":1}
,"startup\u002Fshutdown":{"services":1}
}
;Search.control.loadWordPairs(pairs);
