// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"defining":{"policies":1}
,"policies":{"web":1}
,"web":{"services":1}
,"services":{"(ws-policy)":1}
}
;Search.control.loadWordPairs(pairs);
