// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.alert.notifier:enable":{"wmpublic":1}
,"wmpublic":{"enables":1}
,"enables":{"specified":1}
,"specified":{"notifier":1}
,"notifier":{"input":1,"want":1,"enabled":1}
,"input":{"parameters":1}
,"parameters":{"name":1,"message":1}
,"name":{"string":1,"notifier":1}
,"string":{"name":1,"indicates":1}
,"want":{"enable":1}
,"enable":{"output":1}
,"output":{"parameters":1}
,"message":{"string":1}
,"indicates":{"whether":1}
,"whether":{"specified":1}
}
;Search.control.loadWordPairs(pairs);
