// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.remote.gd:restart":{"wmpublic":1}
,"wmpublic":{"restarts":1}
,"restarts":{"expired":1}
,"expired":{"guaranteed":1}
,"guaranteed":{"delivery":1,"delive":1}
,"delivery":{"transactio":1,"transaction":1}
,"transactio":{"input":1}
,"input":{"parameters":1}
,"parameters":{"tid":1,"none":1}
,"tid":{"string":1}
,"string":{"transaction":1}
,"transaction":{"identification":1,"want":1,"failed":1}
,"identification":{"number":1}
,"number":{"guaranteed":1}
,"delive":{"transaction":1}
,"want":{"restart":1}
,"restart":{"output":1,"transa":1}
,"output":{"parameters":1}
,"none":{"usage":1}
,"usage":{"notes":1}
,"notes":{"guaranteed":1}
,"failed":{"serve":1}
,"serve":{"network":1}
,"network":{"failure":1}
,"failure":{"service":1}
,"service":{"restart":1}
,"transa":{"ction":1}
,"ction":{"without":1}
,"without":{"resubmitting":1}
}
;Search.control.loadWordPairs(pairs);
