// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"clearing":{"exactly-once":1}
,"exactly-once":{"processing":1,"statistics":1}
,"processing":{"statistics":1}
,"statistics":{"start":1,"click":1}
,"start":{"integration":1}
,"integration":{"server":1}
,"server":{"open":1,"administrator":1}
,"open":{"integration":1}
,"administrator":{"settings":1}
,"settings":{"resources":1}
,"resources":{"click":1}
,"click":{"exactly-once":1,"clear":1}
,"clear":{"duplicate":1}
,"duplicate":{"doubt":1}
,"doubt":{"document":1}
,"document":{"statistics":1}
}
;Search.control.loadWordPairs(pairs);
