// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"creating":{"flat":1,"manually":1}
,"flat":{"file":1}
,"file":{"schema":1,"approach":1,"create":1,"creating":1}
,"schema":{"create":1,"using":1,"utomated":1,"educe":1,"creation":1,"sample":1,"add":1,"manually":1}
,"create":{"flat":1,"structure":1,"empty":1}
,"using":{"follo":1,"sample":1}
,"follo":{"wing":1}
,"wing":{"ways":1}
,"ways":{"using":1}
,"sample":{"file":1}
,"approach":{"sample":1,"create":1,"creating":1}
,"utomated":{"wizards":1}
,"wizards":{"create":1}
,"structure":{"schema":1}
,"educe":{"time":1}
,"time":{"involved":1}
,"involved":{"schema":1}
,"creation":{"appr":1}
,"appr":{"oach":1}
,"oach":{"creating":1}
,"manually":{"approach":1}
,"empty":{"flat":1}
,"add":{"elements":1}
,"elements":{"properties":1}
,"properties":{"nually":1}
,"nually":{"approach":1}
}
;Search.control.loadWordPairs(pairs);
