// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.art.service:listadapterservices":{"wmart":1}
,"wmart":{"lists":1,"packag":1}
,"lists":{"adapter":1}
,"adapter":{"services":1,"registered":1,"service":1,"key":1}
,"services":{"associated":1}
,"associated":{"specified":1}
,"specified":{"apter":1}
,"apter":{"input":1}
,"input":{"parameters":1}
,"parameters":{"adaptertypename":1,"servicedatalist":1}
,"adaptertypename":{"string":1}
,"string":{"name":1}
,"name":{"adapter":1,"package":1}
,"registered":{"wmart":1,"ecified":1}
,"packag":{"output":1}
,"output":{"parameters":1}
,"servicedatalist":{"document":1}
,"document":{"list":1}
,"list":{"information":1}
,"information":{"adapter":1}
,"service":{"registered":1,"packagename":1,"reside":1}
,"ecified":{"adapter":1}
,"key":{"description":1}
,"description":{"servicenodename":1}
,"servicenodename":{"string":1}
,"packagename":{"string":1}
,"package":{"adapter":1}
,"reside":{"pub.art:listregisteredadapters":1}
}
;Search.control.loadWordPairs(pairs);
