// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"editing":{"jndi":1}
,"jndi":{"provider":1,"provide":1,"settings":1}
,"provider":{"alias":1}
,"alias":{"following":1,"edit":1,"open":1,"definitions":1,"want":1,"click":1,"information":1}
,"following":{"procedure":1}
,"procedure":{"edit":1}
,"edit":{"existing":1,"jndi":1,"integration":1,"properties":1}
,"existing":{"jndi":1}
,"provide":{"alias":1}
,"open":{"integration":1,"messaging":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"already":1,"displays":1}
,"already":{"open":1}
,"messaging":{"jndi":1}
,"settings":{"jndi":1}
,"definitions":{"list":1}
,"list":{"select":1}
,"select":{"jndi":1}
,"want":{"edit":1}
,"displays":{"details":1}
,"details":{"jndi":1}
,"click":{"edit":1,"save":1}
,"properties":{"jndi":1}
,"information":{"fields":1}
,"fields":{"creating":1}
,"creating":{"jndi":1}
,"save":{"changes":1}
}
;Search.control.loadWordPairs(pairs);
