// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"modifying":{"properties":1}
,"properties":{"graphql":1,"root":1,"open":1,"modify":1,"details":1}
,"graphql":{"descriptor":1}
,"descriptor":{"modify":1,"created":1,"select":1,"click":1,"properties":1}
,"modify":{"properties":1,"property":1,"values":1}
,"root":{"operations":1,"operation":1}
,"operations":{"graphql":1}
,"created":{"modify":1}
,"open":{"graphql":1}
,"select":{"field":1}
,"field":{"root":1}
,"operation":{"name":1}
,"name":{"want":1}
,"want":{"modify":1}
,"property":{"properties":1}
,"values":{"query":1}
,"query":{"depth":1,"complexity":1}
,"depth":{"and\u002For":1}
,"and\u002For":{"query":1}
,"complexity":{"modify":1}
,"click":{"file":1}
,"file":{"save":1}
,"save":{"save":1,"properties":1}
,"details":{"graphql":1}
}
;Search.control.loadWordPairs(pairs);
