// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"shutting":{"down":1}
,"down":{"microservices":1}
,"microservices":{"runtime":1}
,"runtime":{"windows":1}
,"windows":{"shut":1,"click":1}
,"shut":{"down":1}
,"click":{"start":1}
,"start":{"programs":1}
,"programs":{"software":1}
,"software":{"stop":1}
,"stop":{"microservices":1}
}
;Search.control.loadWordPairs(pairs);
