// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"displaying":{"subscribers":1}
,"subscribers":{"specific":1,"single":1,"package":1,"field":1}
,"specific":{"package":1}
,"package":{"procedure":1,"server":1,"open":1,"want":1,"subscribers":1}
,"procedure":{"display":1}
,"display":{"list":1,"subscribers":1}
,"list":{"subscribers":1}
,"server":{"display":1,"administrator":1,"lists":1}
,"single":{"package":1}
,"open":{"integration":1,"packages":1}
,"integration":{"server":1}
,"administrator":{"already":1}
,"already":{"open":1}
,"packages":{"management":1}
,"management":{"click":1}
,"click":{"name":1}
,"name":{"package":1}
,"want":{"view":1}
,"view":{"sub":1}
,"sub":{"scribers":1}
,"scribers":{"server":1}
,"lists":{"subscribers":1}
}
;Search.control.loadWordPairs(pairs);
