// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"cdata":{"blocks":1}
,"blocks":{"inbound":1}
,"inbound":{"outbound":1}
,"outbound":{"soap":1}
,"soap":{"messages":1}
}
;Search.control.loadWordPairs(pairs);
