// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"editing":{"property":1,"edit":1}
,"property":{"templates":1,"template":1}
,"templates":{"change":1,"select":1}
,"change":{"values":1,"click":1}
,"values":{"properties":1,"proper":1}
,"properties":{"specified":1}
,"specified":{"element":1}
,"element":{"property":1}
,"template":{"definition":1,"designer":1,"want":1,"dialog":1}
,"definition":{"editing":1}
,"edit":{"element":1,"click":1,"edit":1,"template":1}
,"designer":{"window":1}
,"window":{"preferences":1}
,"preferences":{"preferences":1,"navigation":1,"page":1}
,"navigation":{"tree":1}
,"tree":{"select":1}
,"select":{"software":1,"property":1}
,"software":{"service":1}
,"service":{"development":1}
,"development":{"element":1}
,"want":{"edit":1,"change":1}
,"click":{"edit":1,"preferences":1}
,"dialog":{"enter":1}
,"enter":{"new":1}
,"new":{"values":1}
,"proper":{"ties":1}
,"ties":{"want":1}
,"page":{"click":1}
}
;Search.control.loadWordPairs(pairs);
