// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"specification":{"properties":1,"doub":1,"package":1,"ite":1}
,"properties":{"properties":1,"view":1,"spe":1,"specification":1,"specifications":1}
,"view":{"properties":1,"edit":1}
,"spe":{"cification":1}
,"cification":{"view":1}
,"doub":{"le-click":1}
,"le-click":{"specification":1}
,"package":{"navigator":1}
,"navigator":{"view":1}
,"edit":{"properties":1}
,"ite":{"access":1}
,"access":{"lock":1}
,"lock":{"related":1}
,"related":{"topics":1}
,"topics":{"general":1}
,"general":{"properties":1}
}
;Search.control.loadWordPairs(pairs);
