// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.xslt.cache:removetemplate":{"wmxslt":1}
,"wmxslt":{"removes":1}
,"removes":{"stylesheet":1}
,"stylesheet":{"xslt":1,"cach":1,"remove":1}
,"xslt":{"stylesheet":1}
,"cach":{"input":1}
,"input":{"parameters":1}
,"parameters":{"stylesheetsystemid":1,"message":1}
,"stylesheetsystemid":{"string":1}
,"string":{"uri":1,"indicates":1}
,"uri":{"xslt":1}
,"remove":{"cache":1,"styles":1}
,"cache":{"output":1}
,"output":{"parameters":1}
,"message":{"string":1}
,"indicates":{"whether":1}
,"whether":{"service":1}
,"service":{"able":1}
,"able":{"remove":1}
,"styles":{"heet":1}
,"heet":{"cache":1}
}
;Search.control.loadWordPairs(pairs);
