// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"summary":{"elements":1}
,"elements":{"folder":1,"available":1}
,"folder":{"following":1,"element":1}
,"following":{"elements":1}
,"available":{"folder":1}
,"element":{"package":1}
,"package":{"description":1}
,"description":{"pub.compress:compressdata":1}
,"pub.compress:compressdata":{"wmpublic":1}
,"wmpublic":{"performs":1}
,"performs":{"compression":1,"decompression":1}
,"compression":{"data":1}
,"data":{"pub.compress:decompressdata":1}
,"pub.compress:decompressdata":{"wmpublic":1}
,"decompression":{"data":1}
}
;Search.control.loadWordPairs(pairs);
