// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"opening":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1,"open":1,"want":1}
,"administrator":{"may":1,"sks":1,"package":1,"select":1}
,"may":{"times":1}
,"times":{"need":1}
,"need":{"perform":1}
,"perform":{"administrator":1}
,"sks":{"integration":1}
,"open":{"integration":1,"administration":1}
,"package":{"navigator":1}
,"navigator":{"view":1}
,"view":{"right-click":1}
,"right-click":{"integration":1}
,"want":{"open":1}
,"select":{"open":1}
,"administration":{"view":1}
}
;Search.control.loadWordPairs(pairs);
