// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"editing":{"connection":1}
,"connection":{"configuration":1}
,"configuration":{"cloud":1,"values":1,"fields":1,"dialog":1}
,"cloud":{"container":1}
,"container":{"edit":1,"changes":1,"designer":1,"click":1}
,"edit":{"connection":1,"enter":1}
,"changes":{"configuration":1}
,"values":{"edit":1,"connection":1}
,"designer":{"select":1}
,"select":{"window":1,"software":1}
,"window":{"preferences":1}
,"preferences":{"preferences":1,"navigation":1}
,"navigation":{"tree":1}
,"tree":{"select":1}
,"software":{"cloud":1}
,"click":{"edit":1,"connections":1}
,"enter":{"new":1}
,"new":{"values":1}
,"fields":{"want":1}
,"want":{"change":1}
,"change":{"edit":1}
,"dialog":{"box":1}
,"box":{"click":1}
,"connections":{"page":1}
,"page":{"click":1}
}
;Search.control.loadWordPairs(pairs);
