// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"building":{"java":1}
,"java":{"services":1,"service":1}
,"services":{"topic":1,"service":1}
,"topic":{"describes":1}
,"describes":{"java":1}
,"service":{"development":1,"editor":1}
,"development":{"project":1}
,"project":{"java":1}
,"editor":{"create":1}
,"create":{"edit":1}
,"edit":{"java":1}
}
;Search.control.loadWordPairs(pairs);
