// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.soap.utils:getencoding":{"wmpublic":1}
,"wmpublic":{"retrieves":1}
,"retrieves":{"encoding":1}
,"encoding":{"soap":1,"want":1,"com.wm.lang.xml.node":1}
,"soap":{"message":1,"object":1}
,"message":{"ngle":1,"whose":1,"pub.soap.utils:getheaderentries":1}
,"ngle":{"string":1}
,"string":{"input":1}
,"input":{"parameters":1}
,"parameters":{"soapdata":1,"encoding":1}
,"soapdata":{"object":1}
,"object":{"soap":1,"containing":1}
,"containing":{"message":1}
,"whose":{"encoding":1}
,"want":{"retrieve":1}
,"retrieve":{"output":1}
,"output":{"parameters":1}
,"com.wm.lang.xml.node":{"encoding":1}
,"pub.soap.utils:getheaderentries":{"pub.soap.utils:getbody":1}
,"pub.soap.utils:getbody":{"pub.soap.utils:getbodyentries":1}
,"pub.soap.utils:getbodyentries":{"pub.soap.utils:getdocument":1}
,"pub.soap.utils:getdocument":{"pub.soap.utils:gettrailers":1}
,"pub.soap.utils:gettrailers":{"pub.soap.utils:addheaderentry":1}
}
;Search.control.loadWordPairs(pairs);
