// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"acl":1}
,"acl":{"information":1}
,"information":{"server":1,"integration":1,"page":1,"read":1}
,"server":{"view":1,"package":1,"click":1,"acl":1,"connected":1,"administrator":1}
,"view":{"users":1,"acl":1,"select":1}
,"users":{"groups":1}
,"groups":{"acls":1,"integration":1}
,"acls":{"server":1,"contained":1,"users":1}
,"integration":{"server":1}
,"package":{"navigator":1}
,"navigator":{"view":1}
,"select":{"integration":1,"server":1}
,"click":{"file":1}
,"file":{"properties":1}
,"properties":{"properties":1,"servername":1}
,"servername":{"dialog":1}
,"dialog":{"box":1}
,"box":{"select":1}
,"page":{"lists":1}
,"lists":{"acls":1}
,"contained":{"integration":1}
,"connected":{"information":1}
,"read":{"edit":1}
,"edit":{"acls":1}
,"administrator":{"related":1}
,"related":{"topics":1}
,"topics":{"server":1}
}
;Search.control.loadWordPairs(pairs);
