// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"date":{"folder":1,"values":1}
,"folder":{"elements":1,"generate":1}
,"elements":{"date":1}
,"generate":{"format":1}
,"format":{"date":1}
}
;Search.control.loadWordPairs(pairs);
