// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"command":{"central":1,"line":1}
,"central":{"command":1,"rest":1}
,"line":{"tool":1}
,"tool":{"upgrade":1,"commands":1}
,"upgrade":{"existing":1}
,"existing":{"integration":1}
,"integration":{"server":1}
,"server":{"automation":1,"instance":1,"instances":1}
,"automation":{"scripts":1}
,"scripts":{"queries":1}
,"queries":{"command":1}
,"rest":{"api":1}
,"api":{"command":1}
,"commands":{"change":1}
,"change":{"integration":1}
,"instance":{"integration":1,"example":1}
,"instances":{"runtimecomponent=integrationserver-engine":1}
,"runtimecomponent=integrationserver-engine":{"runtimecomponent=integrationserver-instancename":1}
,"runtimecomponent=integrationserver-instancename":{"instancename":1}
,"instancename":{"name":1}
,"name":{"integration":1}
,"example":{"integrationserver-default":1}
}
;Search.control.loadWordPairs(pairs);
