// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"xslt":{"xslt":1,"(extensible":1}
,"(extensible":{"stylesheet":1}
,"stylesheet":{"language":1}
,"language":{"transformations)":1}
,"transformations)":{"langu":1}
,"langu":{"age":1}
,"age":{"used":1}
,"used":{"transform":1}
,"transform":{"xml":1}
,"xml":{"documents":1,"data":1}
,"documents":{"xml":1,"formats":1}
,"formats":{"industry":1}
,"industry":{"standard":1}
,"standard":{"xml":1}
,"data":{"mapping":1,"within":1}
,"mapping":{"based":1}
,"based":{"flexibility":1}
,"flexibility":{"reusability":1,"providing":1}
,"reusability":{"integration":1}
,"integration":{"server":1}
,"server":{"supports":1}
,"supports":{"flexibility":1}
,"providing":{"straightforward":1}
,"straightforward":{"chanism":1}
,"chanism":{"converting":1}
,"converting":{"xml":1}
,"within":{"designer":1}
}
;Search.control.loadWordPairs(pairs);
