// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"metadata":{"folder":1}
,"folder":{"elements":1,"publish":1}
,"elements":{"metadata":1}
,"publish":{"metad":1}
,"metad":{"ata":1}
,"ata":{"integration":1}
,"integration":{"server":1}
,"server":{"packages":1}
,"packages":{"administrative":1}
,"administrative":{"assets":1}
,"assets":{"centrasite":1}
,"centrasite":{"shared":1}
,"shared":{"registry":1}
}
;Search.control.loadWordPairs(pairs);
