// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"connecting":{"integration":1}
,"integration":{"server":1}
,"server":{"database":1}
,"database":{"components":1}
,"components":{"external":1}
,"external":{"rdbms":1}
}
;Search.control.loadWordPairs(pairs);
