// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"universal":{"names":1,"name":1}
,"names":{"document":1,"services":1}
,"document":{"types":1,"type":1}
,"types":{"every":1}
,"every":{"service":1}
,"service":{"document":1}
,"type":{"webmethods":1,"universal":1}
,"webmethods":{"integration":1,"name":1}
,"integration":{"server":1}
,"server":{"universal":1,"information":1}
,"name":{"addition":1,"universal":1,"unique":1,"document":1}
,"addition":{"regular":1}
,"regular":{"webmethods":1}
,"unique":{"public":1}
,"public":{"identifier":1}
,"identifier":{"external":1}
,"external":{"protocols":1}
,"protocols":{"(such":1}
,"(such":{"soap)":1}
,"soap)":{"reference":1}
,"reference":{"service":1}
,"information":{"assigning":1}
,"assigning":{"universal":1}
,"services":{"document":1}
}
;Search.control.loadWordPairs(pairs);
