// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"icons":{"topic":1,"used":1}
,"topic":{"describes":1}
,"describes":{"icons":1}
,"used":{"identify":1}
,"identify":{"elements":1}
,"elements":{"service":1}
,"service":{"development":1}
,"development":{"perspective":1}
}
;Search.control.loadWordPairs(pairs);
