// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"oauth":1}
,"oauth":{"integration":1,"client":1,"configuration":1,"eatures":1,"features":1}
,"integration":{"server":1}
,"server":{"integration":1,"oauth":1,"resou":1,"administrator":1,"equipped":1}
,"client":{"authorization":1}
,"authorization":{"server":1}
,"resou":{"rce":1}
,"rce":{"server":1}
,"administrator":{"provides":1}
,"provides":{"oauth":1}
,"configuration":{"feature":1}
,"feature":{"developers":1}
,"developers":{"create":1}
,"create":{"manage":1}
,"manage":{"roles":1}
,"roles":{"enable":1}
,"enable":{"oauth":1}
,"eatures":{"integration":1}
,"equipped":{"license":1}
,"license":{"software":1}
,"software":{"infor":1}
,"infor":{"mation":1}
,"mation":{"licensing":1}
,"licensing":{"important":1}
,"important":{"considerations":1}
,"considerations":{"using":1}
}
;Search.control.loadWordPairs(pairs);
