// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"administrator":{"user":1}
,"user":{"every":1,"account":1,"perfo":1}
,"every":{"integration":1}
,"integration":{"server":1}
,"server":{"installed":1,"administrator":1}
,"installed":{"predefined":1}
,"predefined":{"user":1}
,"account":{"called":1}
,"called":{"adminis":1}
,"adminis":{"trator":1}
,"trator":{"default":1}
,"default":{"user":1}
,"perfo":{"administrative":1}
,"administrative":{"tasks":1}
,"tasks":{"integration":1}
}
;Search.control.loadWordPairs(pairs);
