// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"editing":{"tenants":1}
,"tenants":{"edit":1}
,"edit":{"tenant":1,"settings":1}
,"tenant":{"details":1,"open":1,"connections":1,"want":1,"configuration":1}
,"details":{"specify":1}
,"specify":{"different":1}
,"different":{"webmethods":1}
,"webmethods":{"cloud":1}
,"cloud":{"server":1,"tenant":1}
,"server":{"change":1,"administrator":1}
,"change":{"credentials":1}
,"credentials":{"edit":1}
,"open":{"integration":1}
,"integration":{"server":1}
,"administrator":{"webmethods":1}
,"connections":{"click":1}
,"click":{"name":1,"update":1}
,"name":{"tenant":1}
,"want":{"edit":1}
,"settings":{"edit":1}
,"configuration":{"click":1}
,"update":{"settings":1}
}
;Search.control.loadWordPairs(pairs);
