// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"service":1}
,"service":{"information":1,"details":1,"siding":1,"want":1}
,"information":{"view":1,"package":1,"note":1}
,"view":{"service":1,"right-click":1,"details":1}
,"details":{"built-in":1,"select":1}
,"built-in":{"service":1,"servic":1}
,"siding":{"packages":1}
,"packages":{"provided":1}
,"provided":{"software":1}
,"software":{"view":1}
,"package":{"navigator":1}
,"navigator":{"view":1}
,"right-click":{"built-in":1}
,"want":{"view":1}
,"select":{"open":1}
,"open":{"service":1}
,"note":{"currently":1}
,"currently":{"option":1}
,"option":{"available":1}
,"available":{"built-in":1}
,"servic":{"wmtn":1}
,"wmtn":{"package":1}
}
;Search.control.loadWordPairs(pairs);
