// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"specifying":{"switch":1,"field":1}
,"switch":{"value":1,"variable":1}
,"value":{"variable":1}
,"variable":{"switch":1,"string":1,"variable":1,"exist":1,"(for":1}
,"string":{"constrained":1}
,"constrained":{"object":1}
,"object":{"variable":1}
,"exist":{"pipeline":1}
,"pipeline":{"ranch":1}
,"ranch":{"step":1}
,"step":{"executed":1}
,"executed":{"run":1}
,"run":{"time":1}
,"time":{"formatted":1}
,"formatted":{"document":1}
,"document":{"\u002Fdocumentvariable":1,"switch":1}
,"\u002Fdocumentvariable":{"specifying":1}
,"field":{"document":1}
,"(for":{"example":1}
,"example":{"buyerinfo":1}
,"buyerinfo":{"\u002Faccountnum":1}
}
;Search.control.loadWordPairs(pairs);
