// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"association":{"properties":1}
,"properties":{"properties":1,"view":1,"odata":1}
,"view":{"specify":1}
,"specify":{"properties":1}
,"odata":{"associations":1}
}
;Search.control.loadWordPairs(pairs);
