// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"xml":{"folder":1,"documents":1}
,"folder":{"elements":1,"perform":1}
,"elements":{"xml":1}
,"perform":{"operations":1}
,"operations":{"xml":1}
}
;Search.control.loadWordPairs(pairs);
