// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"message":{"producer":1}
,"producer":{"message":1,"object":1}
,"object":{"session":1}
,"session":{"creates":1}
,"creates":{"send":1}
,"send":{"messages":1}
,"messages":{"estination":1}
,"estination":{"topic":1}
,"topic":{"queue)":1}
}
;Search.control.loadWordPairs(pairs);
