// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.parquet:closebatchiterator":{"wmparquet":1}
,"wmparquet":{"closes":1}
,"closes":{"parquet":1}
,"parquet":{"iterator":1}
,"iterator":{"parquet":1,"object":1}
,"object":{"obtained":1,"iterator":1,"returned":1}
,"obtained":{"pub.parquet:getbatchiterator":1}
,"pub.parquet:getbatchiterator":{"service":1}
,"service":{"cannot":1,"input":1,"output":1}
,"cannot":{"used":1}
,"used":{"running":1}
,"running":{"service":1}
,"input":{"parameters":1}
,"parameters":{"iterator":1,"none":1}
,"returned":{"pub.parquet:getbatchiterator":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
