// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"supported":{"elements":1}
,"elements":{"local":1,"displayed":1}
,"local":{"service":1,"evelopment":1}
,"service":{"development":1}
,"development":{"feature":1}
,"feature":{"works":1,"work":1}
,"works":{"packages":1,"local":1}
,"packages":{"elements":1}
,"displayed":{"package":1}
,"package":{"navigator":1,"contents":1}
,"navigator":{"view":1}
,"view":{"package":1,"supporting":1}
,"contents":{"visible":1}
,"visible":{"package":1}
,"supporting":{"files":1}
,"files":{"associate":1}
,"associate":{"folder":1}
,"folder":{"element":1}
,"element":{"note":1}
,"note":{"local":1}
,"evelopment":{"server":1}
,"server":{"feature":1}
,"work":{"packa":1}
,"packa":{"ges":1}
,"ges":{"servers":1}
,"servers":{"listed":1}
,"listed":{"package":1}
}
;Search.control.loadWordPairs(pairs);
