// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"element":{"properties":1,"listed":1,"package":1,"information":1,"permissions":1}
,"properties":{"properties":1,"dialog":1,"related":1}
,"dialog":{"box":1}
,"box":{"view":1,"click":1}
,"view":{"information":1}
,"information":{"integration":1,"element":1}
,"integration":{"server":1}
,"server":{"element":1,"elements":1}
,"listed":{"package":1}
,"package":{"navigator":1}
,"navigator":{"integration":1,"designer":1}
,"elements":{"include":1}
,"include":{"folders":1}
,"folders":{"subfolders":1}
,"subfolders":{"document":1}
,"document":{"types":1}
,"types":{"rvices":1}
,"rvices":{"open":1}
,"open":{"properties":1}
,"click":{"integration":1}
,"designer":{"select":1}
,"select":{"file":1}
,"file":{"properties":1}
,"related":{"topics":1}
,"topics":{"element":1}
}
;Search.control.loadWordPairs(pairs);
