// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.utils:generateuuid":{"wmpublic":1}
,"wmpublic":{"generates":1}
,"generates":{"random":1}
,"random":{"universally":1}
,"universally":{"unique":1}
,"unique":{"identifier":1}
,"identifier":{"(uuid)":1}
,"(uuid)":{"input":1}
,"input":{"parameters":1}
,"parameters":{"none":1,"uuid":1}
,"none":{"output":1}
,"output":{"parameters":1}
,"uuid":{"string":1}
,"string":{"randomly":1}
,"randomly":{"generated":1}
,"generated":{"universally":1}
}
;Search.control.loadWordPairs(pairs);
