// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.soap.utils:qname":{"wmpublic":1}
,"wmpublic":{"document":1}
,"document":{"type":1}
,"type":{"defines":1}
,"defines":{"structure":1}
,"structure":{"qual":1}
,"qual":{"ified":1}
,"ified":{"name":1}
,"name":{"parameters":1,"localname":1}
,"parameters":{"namespacename":1}
,"namespacename":{"string":1}
,"string":{"namespace":1,"local":1}
,"namespace":{"portion":1}
,"portion":{"qualified":1}
,"qualified":{"name":1}
,"localname":{"string":1}
,"local":{"portion":1}
}
;Search.control.loadWordPairs(pairs);
