// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sending":{"receiving":1}
,"receiving":{"jms":1}
,"jms":{"messages":1}
}
;Search.control.loadWordPairs(pairs);
