// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"considerations":{"changing":1}
,"changing":{"provider\u2019s":1,"provider":1,"pre-8.2":1}
,"provider\u2019s":{"compatibility":1}
,"compatibility":{"mode":1}
,"mode":{"changing":1,"property":1,"false":1,"true":1}
,"provider":{"web":1}
,"web":{"service":1}
,"service":{"descriptor\u2019s":1}
,"descriptor\u2019s":{"pre-8.2":1}
,"pre-8.2":{"compatibility":1}
,"property":{"affect":1,"affects":1}
,"affect":{"operations":1}
,"operations":{"mep":1}
,"mep":{"types":1,"remains":1,"change":1,"impacts":1}
,"types":{"operation":1}
,"operation":{"defined":1}
,"defined":{"output":1}
,"output":{"mep":1}
,"remains":{"in-out":1}
,"in-out":{"change":1}
,"change":{"operation":1,"information":1}
,"information":{"changing":1}
,"affects":{"operation\u2019s":1}
,"operation\u2019s":{"mep":1}
,"impacts":{"changing":1}
,"false":{"impacts":1}
}
;Search.control.loadWordPairs(pairs);
