// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.alert:markasunread":{"wmpublic":1}
,"wmpublic":{"marks":1}
,"marks":{"specific":1}
,"specific":{"alert":1}
,"alert":{"unread":1,"want":1,"marke":1}
,"unread":{"input":1,"notifiername":1,"output":1,"alerts":1}
,"input":{"parameters":1}
,"parameters":{"alertid":1,"updatecount":1}
,"alertid":{"long":1}
,"long":{"alert":1,"updated":1}
,"want":{"mark":1}
,"mark":{"unread":1}
,"notifiername":{"string":1}
,"string":{"optional":1}
,"optional":{"notifier":1}
,"notifier":{"alert":1}
,"marke":{"unread":1}
,"output":{"parameters":1}
,"updatecount":{"long":1}
,"updated":{"count":1}
,"count":{"unread":1}
,"alerts":{"system":1}
}
;Search.control.loadWordPairs(pairs);
