// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"locked":{"elements":1}
,"elements":{"locked":1,"page":1,"elected":1,"property":1,"unlock":1,"want":1,"list":1}
,"page":{"unlock":1,"designer":1}
,"unlock":{"elements":1,"select":1,"ctrl":1,"unlock":1}
,"elected":{"server":1}
,"server":{"open":1}
,"open":{"page":1}
,"designer":{"select":1}
,"select":{"file":1,"elements":1}
,"file":{"properties":1}
,"properties":{"locked":1}
,"property":{"description":1}
,"description":{"select":1}
,"want":{"unlock":1}
,"ctrl":{"click":1}
,"click":{"elect":1,"unlock":1}
,"elect":{"click":1}
}
;Search.control.loadWordPairs(pairs);
