// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"locating":{"invoked":1}
,"invoked":{"services":1,"service":1}
,"services":{"locate":1}
,"locate":{"invoked":1,"select":1}
,"service":{"flow":1,"package":1}
,"flow":{"editor":1}
,"editor":{"select":1}
,"select":{"invoke":1,"navigate":1}
,"invoke":{"step":1}
,"step":{"containing":1}
,"containing":{"rvice":1}
,"rvice":{"want":1}
,"want":{"locate":1}
,"navigate":{"show":1}
,"show":{"package":1}
,"package":{"navigator":1}
,"navigator":{"designer":1,"view":1}
,"designer":{"locates":1}
,"locates":{"selects":1}
,"selects":{"service":1}
}
;Search.control.loadWordPairs(pairs);
