// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"converting":{"string":1}
,"string":{"list":1,"document":1,"child":1}
,"list":{"document":1,"pipeline":1,"pipe":1,"string":1,"following":1,"want":1,"variable":1,"documentlist":1,"link":1}
,"document":{"list":1}
,"pipeline":{"convert":1}
,"convert":{"string":1,"document":1}
,"pipe":{"line":1}
,"line":{"mapping":1}
,"mapping":{"string":1}
,"following":{"image":1}
,"image":{"alist":1}
,"alist":{"string":1,"astring":1}
,"want":{"convert":1,"copy":1}
,"variable":{"documentlist":1}
,"documentlist":{"document":1,"string":1}
,"copy":{"values":1}
,"values":{"ontained":1}
,"ontained":{"string":1}
,"child":{"astring":1}
,"astring":{"convert":1,"converting":1}
,"link":{"alist":1}
}
;Search.control.loadWordPairs(pairs);
