// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"working":{"rest":1}
,"rest":{"resources":1,"api":1,"resource":1}
,"resources":{"rest":1,"descriptor":1}
,"api":{"descriptor":1}
,"descriptor":{"create":1,"(rad)":1,"emove":1,"path":1}
,"create":{"rest":1}
,"(rad)":{"add":1}
,"add":{"rest":1}
,"emove":{"rest":1}
,"resource":{"descriptor":1,"work":1}
,"path":{"suffi":1}
,"suffi":{"resource":1}
,"work":{"operations":1}
,"operations":{"desc":1}
,"desc":{"riptor":1}
}
;Search.control.loadWordPairs(pairs);
