// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.universalname:find":{"wmpublic":1}
,"wmpublic":{"returns":1}
,"returns":{"fully":1}
,"fully":{"qualified":1}
,"qualified":{"service":1,"name":1}
,"service":{"name":1,"associated":1}
,"name":{"plicit":1,"input":1,"localname":1,"output":1,"service":1,"namespacename":1,"registry":1}
,"plicit":{"universal":1}
,"universal":{"name":1}
,"input":{"parameters":1}
,"parameters":{"namespacename":1,"svcname":1}
,"namespacename":{"string":1,"localname":1}
,"string":{"namespace":1,"local":1,"conditional":1}
,"namespace":{"portion":1}
,"portion":{"universal":1}
,"localname":{"string":1,"specified":1}
,"local":{"portion":1}
,"output":{"parameters":1}
,"svcname":{"string":1,"null":1}
,"conditional":{"fully":1}
,"associated":{"universal":1}
,"specified":{"universal":1}
,"registry":{"svcname":1}
}
;Search.control.loadWordPairs(pairs);
