// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.art.connection:disableconnection":{"wmart":1}
,"wmart":{"disables":1}
,"disables":{"connection":1}
,"connection":{"node":1}
,"node":{"input":1,"want":1}
,"input":{"parameters":1}
,"parameters":{"connectionalias":1,"none":1}
,"connectionalias":{"string":1}
,"string":{"name":1}
,"name":{"connection":1}
,"want":{"disable":1}
,"disable":{"output":1}
,"output":{"parameters":1}
,"none":{"pub.art.connection:enableconnection":1}
}
;Search.control.loadWordPairs(pairs);
