// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.io:stringtoreader":{"wmpublic":1}
,"wmpublic":{"converts":1}
,"converts":{"string":1}
,"string":{"object":1,"string":1,"convert":1}
,"object":{"java.io.stringreader":1,"input":1,"output":1}
,"java.io.stringreader":{"object":1,"stringreader":1}
,"input":{"parameters":1}
,"parameters":{"string":1,"reader":1}
,"convert":{"stringreader":1}
,"stringreader":{"object":1}
,"output":{"parameters":1}
,"reader":{"java.io.stringreader":1}
}
;Search.control.loadWordPairs(pairs);
