// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"document":{"type":1,"types":1}
,"type":{"properties":1,"double-click":1,"package":1}
,"properties":{"properties":1,"view":1,"univ":1,"document":1,"universal":1,"working":1}
,"view":{"view":1,"information":1,"properties":1}
,"information":{"documen":1}
,"documen":{"types":1}
,"types":{"integration":1,"webmethods":1}
,"integration":{"server":1}
,"server":{"assign":1}
,"assign":{"permissions":1}
,"permissions":{"publication":1}
,"publication":{"properties":1}
,"univ":{"ersal":1}
,"ersal":{"names":1}
,"names":{"view":1}
,"double-click":{"doc":1}
,"doc":{"ument":1}
,"ument":{"type":1}
,"package":{"navigator":1}
,"navigator":{"designer":1}
,"designer":{"related":1}
,"related":{"topics":1}
,"topics":{"general":1}
,"general":{"properties":1}
,"webmethods":{"messaging":1}
,"messaging":{"properties":1}
,"universal":{"name":1}
,"name":{"properties":1}
,"working":{"document":1}
}
;Search.control.loadWordPairs(pairs);
