// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"integration":1}
,"integration":{"server":1}
,"server":{"properties":1,"want":1,"administrator":1,"event":1,"acls":1,"formation":1}
,"properties":{"package":1,"designer":1,"screen":1,"description":1}
,"package":{"navigator":1}
,"navigator":{"view":1}
,"view":{"right-click":1}
,"right-click":{"integration":1}
,"want":{"open":1}
,"open":{"integration":1}
,"administrator":{"select":1}
,"select":{"properties":1}
,"designer":{"displays":1}
,"displays":{"properties":1}
,"screen":{"display":1}
,"display":{"information":1}
,"information":{"following":1}
,"following":{"areas":1}
,"areas":{"integration":1}
,"event":{"manager":1}
,"manager":{"locked":1}
,"locked":{"elements":1}
,"elements":{"server":1}
,"acls":{"server":1}
,"formation":{"refer":1}
,"refer":{"integration":1}
,"description":{"properties":1}
}
;Search.control.loadWordPairs(pairs);
