// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"failure":{"handling":1}
,"handling":{"flow":1}
,"flow":{"services":1}
,"services":{"using":1}
,"using":{"try":1}
,"try":{"catch":1}
,"catch":{"finally":1}
,"finally":{"steps":1}
}
;Search.control.loadWordPairs(pairs);
