// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"mixed":{"content":1}
,"content":{"model":1}
,"model":{"mixed":1,"allows":1}
,"allows":{"character":1}
,"character":{"data":1}
,"data":{"interspers":1}
,"interspers":{"child":1}
,"child":{"elements":1}
,"elements":{"symbol":1}
,"symbol":{"corresponds":1}
,"corresponds":{"mixed=\u201D":1}
,"mixed=\u201D":{"true":1}
,"true":{"attribute":1}
,"attribute":{"complex":1}
,"complex":{"type":1}
,"type":{"definition":1}
,"definition":{"xml":1}
,"xml":{"schema":1}
,"schema":{"def":1}
,"def":{"inition":1}
,"inition":{"dtd":1}
,"dtd":{"element":1}
,"element":{"list":1}
,"list":{"first":1}
,"first":{"item":1}
,"item":{"data":1}
}
;Search.control.loadWordPairs(pairs);
