// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"integration":{"server":1}
,"server":{"logging":1,"maintains":1,"log":1}
,"logging":{"logging":1,"platform":1,"data":1,"guide":1}
,"platform":{"provides":1,"activity":1}
,"provides":{"important":1}
,"important":{"data":1}
,"data":{"need":1,"complete":1,"webmethods":1}
,"need":{"monitor":1}
,"monitor":{"platform":1}
,"activity":{"correct":1}
,"correct":{"problems":1}
,"problems":{"integration":1}
,"maintains":{"logging":1}
,"complete":{"information":1}
,"information":{"nstructions":1}
,"nstructions":{"working":1}
,"working":{"logging":1}
,"webmethods":{"audit":1}
,"audit":{"logging":1}
,"guide":{"setting":1}
,"setting":{"server":1,"universal":1}
,"log":{"setting":1}
,"universal":{"messaging":1}
,"messaging":{"client":1}
,"client":{"logging":1}
}
;Search.control.loadWordPairs(pairs);
