// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"editing":{"proxy":1}
,"proxy":{"server":1,"servers":1}
,"server":{"alias":1,"administrator":1,"alias>":1}
,"alias":{"need":1,"edit":1,"open":1,"column":1,"wish":1,"properties":1}
,"need":{"changes":1}
,"changes":{"properties":1}
,"properties":{"particula":1,"click":1}
,"particula":{"proxy":1}
,"edit":{"edit":1,"proxy":1,"<proxy":1}
,"open":{"integration":1}
,"integration":{"server":1}
,"administrator":{"external":1}
,"external":{"servers":1}
,"servers":{"proxy":1,"list":1}
,"list":{"table":1}
,"table":{"alias":1}
,"column":{"click":1}
,"click":{"name":1,"save":1}
,"name":{"proxy":1}
,"wish":{"edit":1}
,"<proxy":{"server":1}
,"alias>":{"page":1}
,"page":{"appears":1}
,"appears":{"modify":1}
,"modify":{"required":1}
,"required":{"proxy":1}
,"save":{"changes":1}
}
;Search.control.loadWordPairs(pairs);
