// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.string:substring":{"wmpublic":1}
,"wmpublic":{"returns":1}
,"returns":{"substring":1}
,"substring":{"given":1,"beginindex":1,"extract":1,"extend":1}
,"given":{"string":1}
,"string":{"input":1,"string":1,"extract":1,"beginning":1,"ending":1,"substring":1}
,"input":{"parameters":1}
,"parameters":{"instring":1,"value":1}
,"instring":{"string":1,"output":1}
,"extract":{"substring":1,"(inclusive)":1,"(exclusive)":1}
,"beginindex":{"string":1,"extending":1}
,"beginning":{"index":1}
,"index":{"substring":1}
,"(inclusive)":{"endindex":1}
,"endindex":{"string":1}
,"ending":{"index":1}
,"(exclusive)":{"parameter":1}
,"parameter":{"null":1}
,"null":{"empty":1}
,"empty":{"substring":1}
,"extend":{"end":1}
,"end":{"instring":1}
,"output":{"parameters":1}
,"value":{"string":1}
,"extending":{"character":1}
,"character":{"endindex":1}
}
;Search.control.loadWordPairs(pairs);
