// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"working":{"graphical":1}
,"graphical":{"view":1,"tree":1,"representation":1}
,"view":{"tab":1,"information":1,"mapping":1}
,"tab":{"graphical":1,"allows":1,"provides":1,"reflect":1,"milarly":1,"perform":1}
,"tree":{"tab":1}
,"allows":{"build":1}
,"build":{"edit":1}
,"edit":{"map":1}
,"map":{"service":1,"action":1}
,"service":{"graphical":1,"changes":1}
,"provides":{"graphical":1}
,"representation":{"entire":1}
,"entire":{"map":1}
,"changes":{"made":1}
,"made":{"map":1,"graphical":1}
,"action":{"tree":1}
,"reflect":{"immediately":1,"tree":1}
,"immediately":{"graphical":1}
,"milarly":{"changes":1}
,"perform":{"operations":1}
,"operations":{"milar":1}
,"milar":{"pipeline":1}
,"pipeline":{"view":1}
,"information":{"orking":1}
,"orking":{"pipeline":1}
,"mapping":{"data":1}
,"data":{"flow":1}
,"flow":{"services":1}
}
;Search.control.loadWordPairs(pairs);
