// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"simple":{"property":1}
,"property":{"properties":1,"odata":1}
,"properties":{"properties":1,"view":1}
,"view":{"specify":1}
,"specify":{"general":1}
,"general":{"properti":1}
,"properti":{"selected":1}
,"selected":{"simple":1}
,"odata":{"service":1}
}
;Search.control.loadWordPairs(pairs);
