// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.sync:shutdown":{"wmpublic":1}
,"wmpublic":{"releases":1,"package":1}
,"releases":{"internal":1}
,"internal":{"resources":1}
,"resources":{"used":1}
,"used":{"pub.sync":1}
,"pub.sync":{"ervices":1}
,"ervices":{"service":1}
,"service":{"run":1}
,"run":{"automatically":1}
,"automatically":{"wmpublic":1}
,"package":{"unloaded":1}
,"unloaded":{"explicitly":1}
,"explicitly":{"invoked":1}
,"invoked":{"client":1}
}
;Search.control.loadWordPairs(pairs);
