// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"thread":1}
,"thread":{"usage":1}
,"usage":{"jms":1}
,"jms":{"triggers":1,"trigger":1,"provider":1}
,"triggers":{"integration":1,"open":1,"individual":1}
,"integration":{"server":1}
,"server":{"administrator":1,"threads":1,"view":1,"connected":1}
,"administrator":{"displays":1,"messaging":1}
,"displays":{"number":1,"connected":1}
,"number":{"server":1}
,"threads":{"currently":1,"column":1}
,"currently":{"used":1}
,"used":{"eac":1,"rec":1}
,"eac":{"jms":1}
,"trigger":{"integration":1,"controls":1,"current":1}
,"view":{"thread":1}
,"open":{"integration":1}
,"messaging":{"jms":1}
,"individual":{"standard":1}
,"standard":{"jms":1}
,"controls":{"current":1}
,"current":{"threads":1}
,"column":{"integration":1,"displays":1}
,"rec":{"eive":1}
,"eive":{"process":1}
,"process":{"messages":1}
,"messages":{"jms":1}
,"connected":{"integration":1,"jms":1}
}
;Search.control.loadWordPairs(pairs);
