// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"debugging":{"map":1,"flow":1}
,"map":{"services":1,"service":1}
,"services":{"debugging":1}
,"service":{"similar":1,"used":1,"details":1,"debugging":1}
,"similar":{"flow":1}
,"flow":{"servic":1,"service":1,"services":1}
,"servic":{"designer":1}
,"designer":{"makes":1}
,"makes":{"tools":1}
,"tools":{"commands":1}
,"commands":{"processes":1}
,"processes":{"deb":1}
,"deb":{"map":1}
,"used":{"flow":1}
,"details":{"ebugging":1}
,"ebugging":{"flow":1}
}
;Search.control.loadWordPairs(pairs);
