// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"element":{"information":1,"open":1,"package":1}
,"information":{"element":1,"page":1}
,"page":{"displays":1,"click":1}
,"displays":{"type":1}
,"type":{"name":1}
,"name":{"integration":1}
,"integration":{"server":1}
,"server":{"element":1}
,"open":{"page":1}
,"click":{"element":1}
,"package":{"navigato":1}
,"navigato":{"designer":1}
,"designer":{"select":1}
,"select":{"file":1}
,"file":{"properties":1}
,"properties":{"element":1}
}
;Search.control.loadWordPairs(pairs);
