// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"acl":1}
,"acl":{"protection":1}
,"protection":{"file":1,"want":1}
,"file":{"following":1,"remove":1,"click":1,"delete":1,"whose":1}
,"following":{"procedure":1}
,"procedure":{"remove":1}
,"remove":{"acl":1,"restart":1}
,"click":{"shut":1}
,"shut":{"down":1}
,"down":{"restart":1,"edit":1}
,"restart":{"click":1,"server":1}
,"edit":{".access":1}
,".access":{"file":1}
,"delete":{"line":1}
,"line":{"specifies":1}
,"specifies":{"file":1}
,"whose":{"acl":1}
,"want":{"remove":1}
,"server":{"instructions":1}
,"instructions":{"restarting":1}
,"restarting":{"integration":1}
,"integration":{"server":1}
}
;Search.control.loadWordPairs(pairs);
