// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"package":{"management":1,"expected":1,"preserve":1,"folder":1}
,"management":{"problems":1}
,"problems":{"can\u2019t":1}
,"can\u2019t":{"preserve":1}
,"preserve":{"locking":1,"system":1}
,"locking":{"information":1,"infor":1}
,"information":{"replicate":1}
,"replicate":{"blish":1}
,"blish":{"package":1}
,"expected":{"behavior":1}
,"behavior":{"part":1,"prevents":1}
,"part":{"feature\u2019s":1}
,"feature\u2019s":{"desig":1}
,"desig":{"however":1}
,"however":{"preserve":1}
,"system":{"locks":1}
,"locks":{"(read-only":1}
,"(read-only":{"file":1}
,"file":{"ttributes)":1}
,"ttributes)":{"disable":1}
,"disable":{"package":1}
,"infor":{"mation":1}
,"mation":{"expected":1}
,"prevents":{"conflicts":1}
,"conflicts":{"package":1}
,"folder":{"element":1}
,"element":{"names":1}
,"names":{"gets":1}
,"gets":{"installe":1}
}
;Search.control.loadWordPairs(pairs);
