// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"connection":1}
,"connection":{"configuration":1,"configurations":1}
,"configuration":{"api":1,"remove":1,"want":1,"click":1}
,"api":{"gateway":1,"gatewa":1}
,"gateway":{"remove":1,"time":1,"designer":1,"select":1,"connection":1,"changing":1}
,"remove":{"connection":1,"default":1,"click":1,"designer":1,"selected":1}
,"configurations":{"api":1}
,"time":{"connections":1}
,"connections":{"page":1}
,"page":{"cannot":1}
,"cannot":{"remove":1}
,"default":{"connection":1}
,"designer":{"select":1,"prompts":1}
,"select":{"window":1,"software":1,"api":1}
,"window":{"preferences":1}
,"preferences":{"preferences":1,"navigation":1}
,"navigation":{"tree":1}
,"tree":{"select":1}
,"software":{"api":1}
,"want":{"remove":1}
,"click":{"remove":1,"related":1}
,"prompts":{"confirm":1}
,"confirm":{"want":1}
,"selected":{"connection":1}
,"related":{"topics":1}
,"topics":{"editing":1}
,"editing":{"connection":1}
,"changing":{"default":1}
}
;Search.control.loadWordPairs(pairs);
