// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"finding":{"dependents":1,"references":1}
,"dependents":{"references":1,"reference":1}
,"references":{"performing":1,"element":1,"inspecting":1}
,"performing":{"action":1}
,"action":{"selected":1}
,"selected":{"element":1}
,"element":{"etermine":1,"designer":1,"uses":1,"reference":1,"used":1,"related":1}
,"etermine":{"whether":1}
,"whether":{"elements":1}
,"elements":{"affected":1}
,"affected":{"chan":1}
,"chan":{"finding":1}
,"designer":{"dependent":1}
,"dependent":{"element":1,"finding":1}
,"uses":{"selected":1}
,"reference":{"element":1,"finding":1}
,"used":{"selected":1}
,"related":{"topics":1}
,"topics":{"dependent":1}
,"inspecting":{"pipeline":1}
,"pipeline":{"references":1}
}
;Search.control.loadWordPairs(pairs);
