// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"administrator":{"environment":1,"responsible":1,"alt":1}
,"environment":{"administrator":1}
,"responsible":{"nstalling":1,"ensuring":1}
,"nstalling":{"configuring":1}
,"configuring":{"maintaining":1}
,"maintaining":{"webmethods":1}
,"webmethods":{"integration":1}
,"integration":{"server":1}
,"server":{"responsible":1,"ecure":1}
,"ensuring":{"server":1}
,"ecure":{"available":1}
,"available":{"clients":1}
,"clients":{"running":1}
,"running":{"peak":1}
,"peak":{"performance":1}
,"performance":{"usually":1}
,"usually":{"person":1}
,"person":{"appointed":1,"act":1}
,"appointed":{"administrator":1}
,"alt":{"hough":1}
,"hough":{"sites":1}
,"sites":{"identify":1}
,"identify":{"least":1}
,"least":{"person":1}
,"act":{"backup":1}
}
;Search.control.loadWordPairs(pairs);
