// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"sections":1}
,"sections":{"chapter":1}
,"chapter":{"apply":1}
,"apply":{"stateful":1}
,"stateful":{"clusters":1}
,"clusters":{"unless":1}
,"unless":{"otherwise":1}
,"otherwise":{"indicated":1}
}
;Search.control.loadWordPairs(pairs);
