// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"keystores":{"truststores":1}
,"truststores":{"integration":1,"secure":1}
,"integration":{"server":1}
,"server":{"stores":1}
,"stores":{"private":1}
,"private":{"keys":1}
,"keys":{"ssl":1}
,"ssl":{"certificates":1}
,"certificates":{"keystore":1,"truststore":1}
,"keystore":{"les":1}
,"les":{"trusted":1}
,"trusted":{"roots":1}
,"roots":{"certificates":1}
,"truststore":{"files":1}
,"files":{"keystores":1,"indu":1}
,"secure":{"files":1}
,"indu":{"stry-standard":1}
,"stry-standard":{"file":1}
,"file":{"formats":1}
}
;Search.control.loadWordPairs(pairs);
