// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"files":{"designer":1,"java":1}
,"designer":{"generates":1}
,"generates":{"java":1,"following":1}
,"java":{"client":1}
,"client":{"designer":1,"application":1,"code":1,"related":1,"limitations":1}
,"following":{"files":1}
,"application":{"readme.txt":1,"servicename":1}
,"readme.txt":{"file":1}
,"file":{"contains":1,"information":1,"encoded":1}
,"contains":{"information":1,"app":1}
,"information":{"instructions":1,"compili":1}
,"instructions":{"client":1}
,"code":{"read":1,"java":1,"generating":1}
,"read":{"file":1}
,"compili":{"running":1}
,"running":{"java":1}
,"servicename":{".java":1}
,".java":{"example":1}
,"example":{"file":1}
,"encoded":{"iso8859_1":1}
,"iso8859_1":{"contains":1}
,"app":{"lication":1}
,"lication":{"code":1}
,"related":{"topics":1}
,"topics":{"building":1}
,"building":{"java":1}
,"limitations":{"generating":1}
,"generating":{"java":1}
}
;Search.control.loadWordPairs(pairs);
