// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"securing":{"dsps":1}
,"dsps":{"following":1,"agai":1}
,"following":{"sections":1}
,"sections":{"describe":1}
,"describe":{"secure":1}
,"secure":{"dsps":1,"against":1}
,"agai":{"nst":1}
,"nst":{"unauthorized":1}
,"unauthorized":{"access":1}
,"access":{"secure":1}
,"against":{"cross":1}
,"cross":{"site":1}
,"site":{"scripting":1}
,"scripting":{"(xss)":1}
,"(xss)":{"attacks":1}
,"attacks":{"limit":1}
,"limit":{"external":1}
,"external":{"urls":1}
,"urls":{"page":1}
,"page":{"redirected":1}
}
;Search.control.loadWordPairs(pairs);
