// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"document":1}
,"document":{"types":1,"type":1,"typ":1}
,"types":{"header":1}
,"header":{"fault":1}
,"fault":{"element":1}
,"element":{"view":1,"side-by-side":1,"operation":1,"want":1}
,"view":{"document":1,"open":1}
,"type":{"used":1,"read-only":1,"header":1}
,"used":{"header":1}
,"side-by-side":{"operations":1}
,"operations":{"web":1,"tab":1}
,"web":{"service":1}
,"service":{"escriptor":1,"descriptor":1}
,"escriptor":{"document":1}
,"read-only":{"operatio":1}
,"operatio":{"tab":1}
,"tab":{"view":1,"navigate":1}
,"operation":{"package":1}
,"package":{"navigator":1}
,"navigator":{"view":1}
,"open":{"web":1}
,"descriptor":{"operations":1}
,"navigate":{"select":1}
,"select":{"header":1}
,"want":{"view":1}
,"typ":{"contents":1}
}
;Search.control.loadWordPairs(pairs);
