// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"working":{"load":1}
,"load":{"query":1}
,"query":{"services":1}
,"services":{"load":1,"fetch":1}
,"fetch":{"html":1}
,"html":{"xml":1}
,"xml":{"documents":1}
,"documents":{"internet":1}
,"internet":{"extract":1}
,"extract":{"data":1}
,"data":{"services":1}
}
;Search.control.loadWordPairs(pairs);
