// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.string:makestring":{"wmpublic":1}
,"wmpublic":{"builds":1}
,"builds":{"single":1}
,"single":{"string":1}
,"string":{"concatenating":1,"list":1,"string":1,"insert":1,"result":1}
,"concatenating":{"elemen":1,"strings":1}
,"elemen":{"string":1}
,"list":{"input":1,"strings":1}
,"input":{"parameters":1}
,"parameters":{"elementlist":1,"value":1}
,"elementlist":{"string":1,"output":1,"strings":1}
,"strings":{"concatenate":1,"elementlist":1,"separated":1}
,"concatenate":{"separator":1}
,"separator":{"string":1}
,"insert":{"non-null":1}
,"non-null":{"element":1}
,"element":{"elementlist":1}
,"output":{"parameters":1}
,"value":{"string":1}
,"result":{"concatenating":1}
,"separated":{"characters":1}
,"characters":{"specified":1}
,"specified":{"separator":1}
}
;Search.control.loadWordPairs(pairs);
