// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"fallback":{"mechanisms":1}
,"mechanisms":{"determining":1,"approach":1}
,"determining":{"operation":1}
,"operation":{"endpoint":1,"depends":1}
,"endpoint":{"url":1}
,"url":{"soap":1}
,"soap":{"header":1,"message":1}
,"header":{"contain":1}
,"contain":{"enough":1}
,"enough":{"formation":1}
,"formation":{"integration":1}
,"integration":{"server":1}
,"server":{"determine":1,"employs":1,"takes":1}
,"determine":{"service":1,"operation":1}
,"service":{"invoke":1}
,"invoke":{"integration":1}
,"employs":{"fallback":1}
,"approach":{"integration":1}
,"takes":{"determine":1}
,"depends":{"informatio":1}
,"informatio":{"missing":1}
,"missing":{"endpoint":1}
}
;Search.control.loadWordPairs(pairs);
