// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"controlling":{"thread":1}
,"thread":{"usage":1,"pool":1}
,"usage":{"jms":1}
,"jms":{"triggers":1,"iggers":1}
,"triggers":{"integration":1,"default":1}
,"integration":{"server":1}
,"server":{"administrator":1,"threads":1,"consume":1,"thread":1,"resources":1}
,"administrator":{"limit":1}
,"limit":{"number":1}
,"number":{"server":1}
,"threads":{"jms":1}
,"default":{"integration":1}
,"consume":{"100":1}
,"100":{"server":1}
,"pool":{"jms":1}
,"iggers":{"however":1}
,"however":{"server":1}
,"resources":{"need":1}
,"need":{"available":1}
,"available":{"perform":1}
,"perform":{"functions":1}
}
;Search.control.loadWordPairs(pairs);
