// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"data":{"synchronization":1,"integration":1}
,"synchronization":{"clustered":1,"requests":1,"information":1}
,"clustered":{"environment":1}
,"environment":{"mobile":1,"load":1}
,"mobile":{"support":1}
,"support":{"used":1,"clustered":1}
,"used":{"clustered":1}
,"load":{"balancer":1}
,"balancer":{"load":1,"distributes":1}
,"distributes":{"data":1}
,"requests":{"ong":1}
,"ong":{"host":1}
,"host":{"integration":1}
,"integration":{"server":1}
,"server":{"processing":1,"uses":1,"array":1}
,"processing":{"ensure":1}
,"ensure":{"servers":1}
,"servers":{"cluster":1}
,"cluster":{"working":1}
,"working":{"data":1}
,"uses":{"terracotta":1}
,"terracotta":{"server":1}
,"array":{"facilitate":1}
,"facilitate":{"synchronization":1}
,"information":{"considerations":1}
,"considerations":{"using":1}
,"using":{"mobile":1}
}
;Search.control.loadWordPairs(pairs);
