// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"integration":{"server":1}
,"server":{"uses":1}
,"uses":{"content":1}
,"content":{"handlers":1,"handler":1}
,"handlers":{"client":1}
,"client":{"submits":1}
,"submits":{"http":1}
,"http":{"ftp":1}
,"ftp":{"request":1,"esponse":1}
,"request":{"integration":1,"pass":1}
,"handler":{"parse":1,"building":1}
,"parse":{"contents":1}
,"contents":{"request":1}
,"pass":{"target":1}
,"target":{"service":1}
,"service":{"integration":1}
,"building":{"http":1}
}
;Search.control.loadWordPairs(pairs);
