// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"debugging":{"flow":1,"designer":1}
,"flow":{"services":1,"service":1}
,"services":{"debug":1}
,"debug":{"flow":1,"sessions":1,"perspective":1,"view":1}
,"service":{"designer":1,"examine":1,"pipeline":1,"execution":1}
,"designer":{"provides":1,"save":1}
,"provides":{"tools":1}
,"tools":{"monitor":1}
,"monitor":{"execution":1}
,"execution":{"flow":1,"debugging":1}
,"examine":{"service":1}
,"pipeline":{"arious":1,"related":1}
,"arious":{"points":1}
,"points":{"during":1}
,"during":{"service":1}
,"save":{"modify":1}
,"modify":{"current":1}
,"current":{"pipeline":1}
,"related":{"topics":1}
,"topics":{"debug":1}
,"sessions":{"debug":1}
,"perspective":{"debug":1}
,"view":{"debugging":1}
}
;Search.control.loadWordPairs(pairs);
