// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.hashtable:size":{"wmpublic":1}
,"wmpublic":{"gets":1}
,"gets":{"number":1}
,"number":{"elements":1}
,"elements":{"hashtable":1,"stored":1}
,"hashtable":{"input":1,"java.util.hashtable":1,"number":1}
,"input":{"parameters":1}
,"parameters":{"hashtable":1,"size":1}
,"java.util.hashtable":{"hashtable":1}
,"stored":{"retrieved":1}
,"retrieved":{"output":1}
,"output":{"parameters":1}
,"size":{"string":1}
,"string":{"number":1}
}
;Search.control.loadWordPairs(pairs);
