// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"normal":{"mode":1,"keep-alive":1}
,"mode":{"settings":1,"default":1,"parameter":1}
,"settings":{"following":1}
,"following":{"table":1}
,"table":{"configure":1}
,"configure":{"normal":1}
,"keep-alive":{"mode":1}
,"default":{"mode":1,"watt.server.brokertransport.ret":1}
,"parameter":{"value":1}
,"value":{"watt.server.brokertransport.dur":1}
,"watt.server.brokertransport.dur":{"integer":1}
,"integer":{"greater":1,"2147483647":1}
,"greater":{"less":1}
,"less":{"2147483647":1,"equal":1}
,"2147483647":{"def":1,"default":1}
,"def":{"ault":1}
,"ault":{"watt.server.brokertransport.max":1}
,"watt.server.brokertransport.max":{"integer":1}
,"equal":{"2147483":1}
,"2147483":{"647":1}
,"647":{"default":1}
,"watt.server.brokertransport.ret":{"integer":1}
}
;Search.control.loadWordPairs(pairs);
