// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"database":{"drivers":1}
,"drivers":{"wmdb":1}
,"wmdb":{"package":1}
,"package":{"valid":1}
,"valid":{"type":1}
,"type":{"jdbc":1}
,"jdbc":{"iver":1}
,"iver":{"operating":1}
,"operating":{"system":1}
,"system":{"supported":1}
,"supported":{"webmethods":1}
,"webmethods":{"integration":1}
,"integration":{"server":1}
}
;Search.control.loadWordPairs(pairs);
