// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"packages":{"folder":1}
,"folder":{"elements":1,"install":1}
,"elements":{"packages":1}
,"install":{"load":1}
,"load":{"and\u002For":1}
,"and\u002For":{"alter":1}
,"alter":{"status":1}
,"status":{"package":1}
,"package":{"integration":1}
,"integration":{"server":1}
}
;Search.control.loadWordPairs(pairs);
