// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"adding":{"operations":1,"services":1,"6.5":1}
,"operations":{"add":1,"service":1,"added":1,"adding":1}
,"add":{"operations":1}
,"service":{"first":1,"converted":1,"operation":1}
,"first":{"provider":1}
,"provider":{"wsd":1}
,"wsd":{"operations":1,"alues":1,"add":1,"copying":1,"adding":1}
,"added":{"every":1}
,"every":{"binder":1}
,"binder":{"wsd":1,"apply":1}
,"alues":{"defined":1}
,"defined":{"specific":1}
,"specific":{"binder":1}
,"apply":{"operati":1}
,"operati":{"note":1}
,"note":{"add":1}
,"services":{"package":1}
,"package":{"navigator":1}
,"navigator":{"ach":1}
,"ach":{"service":1}
,"converted":{"operation":1}
,"operation":{"provide":1,"provider":1}
,"provide":{"wsd":1}
,"copying":{"moving":1}
,"moving":{"operation":1}
,"6.5":{"soap-msg":1}
,"soap-msg":{"style":1}
,"style":{"service":1}
}
;Search.control.loadWordPairs(pairs);
