// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"json":{"folder":1,"content":1,"schema":1}
,"folder":{"elements":1,"following":1}
,"elements":{"json":1}
,"following":{"converting":1}
,"converting":{"json":1,"document":1}
,"content":{"document":1,"validating":1,"against":1}
,"document":{"(idata":1}
,"(idata":{"object)":1}
,"object)":{"converting":1,"json":1}
,"validating":{"json":1}
,"against":{"json":1}
}
;Search.control.loadWordPairs(pairs);
