// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"publishable":{"document":1}
,"document":{"type":1}
,"type":{"preferences":1}
,"preferences":{"preference":1}
,"preference":{"description":1}
,"description":{"display":1}
,"display":{"timeout":1}
,"timeout":{"message":1,"limit":1}
,"message":{"selected":1,"timeout":1}
,"selected":{"designer":1}
,"designer":{"displays":1,"receives":1}
,"displays":{"message":1}
,"limit":{"deliver":1}
,"deliver":{"wai":1}
,"wai":{"publish":1}
,"publish":{"wait":1}
,"wait":{"request":1}
,"request":{"elapses":1}
,"elapses":{"designer":1}
,"receives":{"response":1}
}
;Search.control.loadWordPairs(pairs);
