// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"stopping":{"api":1}
,"api":{"gateway":1}
,"gateway":{"container":1,"api":1,"docker":1,"restarting":1}
,"container":{"stop":1,"using":1,"name":1,"assets":1}
,"stop":{"api":1,"command":1,"-t90":1,"parameterized":1,"destroy":1}
,"using":{"docker":1}
,"docker":{"stop":1,"container":1}
,"command":{"docker":1}
,"-t90":{"apigw":1}
,"apigw":{"docker":1}
,"parameterized":{"number":1}
,"number":{"seconds":1}
,"seconds":{"required":1}
,"required":{"graceful":1}
,"graceful":{"shutdown":1}
,"shutdown":{"api":1}
,"name":{"note":1}
,"note":{"docker":1}
,"destroy":{"state":1}
,"state":{"api":1}
,"restarting":{"docker":1}
,"assets":{"created":1}
,"created":{"configured":1}
,"configured":{"available":1}
,"available":{"again":1}
}
;Search.control.loadWordPairs(pairs);
