// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"roles":1}
,"roles":{"permissions":1}
,"permissions":{"user":1,"assigned":1,"expand":1,"section":1,"tha":1}
,"user":{"settings":1,"account":1,"groups":1}
,"settings":{"page":1}
,"page":{"displays":1}
,"displays":{"list":1}
,"list":{"roles":1}
,"assigned":{"user":1}
,"account":{"role":1,"defined":1}
,"role":{"permissions":1}
,"defined":{"user":1}
,"groups":{"corresponding":1,"teams":1}
,"corresponding":{"teams":1}
,"teams":{"(see":1,"information)":1}
,"(see":{"users":1}
,"users":{"groups":1}
,"information)":{"view":1}
,"view":{"roles":1,"list":1}
,"expand":{"menu":1}
,"menu":{"options":1}
,"options":{"icon":1,"roles":1}
,"icon":{"title":1}
,"title":{"bar":1}
,"bar":{"select":1}
,"select":{"profile":1}
,"profile":{"menu":1}
,"section":{"view":1}
,"tha":{"assigned":1}
}
;Search.control.loadWordPairs(pairs);
