// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"data":{"backup":1,"store":1,"using":1}
,"backup":{"using":1,"operation":1}
,"using":{"docker":1}
,"docker":{"container":1}
,"container":{"perform":1,"running":1,"run":1,"requi":1,"involv":1}
,"perform":{"api":1,"backup":1}
,"api":{"data":1}
,"store":{"backup":1}
,"running":{"apigatewayutil":1}
,"apigatewayutil":{"utility":1}
,"utility":{"container":1}
,"run":{"container":1}
,"requi":{"red":1}
,"red":{"command":1}
,"command":{"perform":1}
,"operation":{"process":1}
,"process":{"backing":1}
,"backing":{"data":1}
,"involv":{"following":1}
,"following":{"steps":1}
}
;Search.control.loadWordPairs(pairs);
