// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"transport":{"policies":1}
,"policies":{"stage":1,"included":1}
,"stage":{"specify":1,"enable":1}
,"specify":{"protocol":1}
,"protocol":{"used":1}
,"used":{"incoming":1}
,"incoming":{"request":1}
,"request":{"content":1}
,"content":{"type":1}
,"type":{"rest":1}
,"rest":{"reque":1}
,"reque":{"during":1}
,"during":{"communication":1}
,"communication":{"api":1}
,"api":{"gateway":1}
,"gateway":{"application":1}
,"application":{"policies":1}
,"included":{"stage":1}
,"enable":{"bulkhead":1,"http\u002Fhttps":1,"jms\u002Famqp":1}
,"bulkhead":{"enable":1}
,"http\u002Fhttps":{"enable":1}
,"jms\u002Famqp":{"media":1}
,"media":{"type":1}
}
;Search.control.loadWordPairs(pairs);
