// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"plan":1,"delete":1}
,"plan":{"api":1,"plans":1,"associated":1,"pac":1,"click":1,"deleted":1}
,"api":{"gateway":1}
,"gateway":{"manage":1}
,"manage":{"packages":1}
,"packages":{"plans":1,"title":1}
,"plans":{"functional":1,"list":1,"section":1,"page":1,"appears":1}
,"functional":{"privilege":1}
,"privilege":{"assigned":1}
,"assigned":{"perform":1}
,"perform":{"task":1}
,"task":{"delete":1}
,"delete":{"plan":1,"icon":1}
,"list":{"appears":1,"plans":1}
,"appears":{"plans":1,"click":1}
,"section":{"manage":1}
,"page":{"delete":1}
,"associated":{"package":1}
,"package":{"disassociate":1}
,"disassociate":{"plan":1}
,"pac":{"kage":1}
,"kage":{"deleting":1}
,"click":{"packages":1,"plans":1,"delete":1,"confirmation":1}
,"title":{"navigation":1}
,"navigation":{"bar":1}
,"bar":{"click":1}
,"icon":{"plan":1}
,"deleted":{"click":1}
,"confirmation":{"dialog":1}
}
;Search.control.loadWordPairs(pairs);
