// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"refresh":{"token":1}
,"token":{"process":1,"resource":1,"without":1,"subsequent":1}
,"process":{"flow":1}
,"flow":{"case":1}
,"case":{"explains":1}
,"explains":{"following":1}
,"following":{"workflow":1}
,"workflow":{"access":1}
,"access":{"token":1}
,"resource":{"owner":1}
,"owner":{"permission":1,"permissio":1}
,"permission":{"access":1}
,"without":{"resource":1}
,"permissio":{"using":1}
,"using":{"refresh":1}
,"subsequent":{"attempts":1}
}
;Search.control.loadWordPairs(pairs);
