// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"create":{"api":1}
,"api":{"importing":1,"page":1,"file":1,"name":1,"type":1,"created":1}
,"importing":{"file":1}
,"file":{"create":1,"click":1,"import":1}
,"page":{"select":1}
,"select":{"import":1,"file":1}
,"import":{"api":1,"provide":1}
,"click":{"browse":1,"create":1}
,"browse":{"select":1}
,"provide":{"api":1,"required":1}
,"name":{"name":1,"field":1}
,"field":{"required":1}
,"required":{"provide":1,"description":1}
,"description":{"api":1}
,"type":{"version":1}
,"version":{"click":1}
,"created":{"appears":1}
,"appears":{"apis":1}
,"apis":{"list":1,"tab":1}
,"list":{"apis":1}
}
;Search.control.loadWordPairs(pairs);
