// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"managing":{"api":1}
,"api":{"gateway":1}
,"gateway":{"images":1,"image":1}
,"images":{"manage":1,"using":1}
,"manage":{"api":1}
,"using":{"is_container.sh":1}
,"is_container.sh":{"script":1}
,"script":{"saveimage":1}
,"saveimage":{"save":1}
,"save":{"api":1}
,"image":{"file":1,"docker":1}
,"file":{"(creating":1}
,"(creating":{"tar":1}
,"tar":{"ball":1,"ball)":1}
,"ball":{"image)":1}
,"image)":{"loadimage":1}
,"loadimage":{"load":1}
,"load":{"image":1}
,"docker":{"registry":1}
,"registry":{"(loading":1,"tar":1}
,"(loading":{"image":1}
}
;Search.control.loadWordPairs(pairs);
