// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"custom":1}
,"custom":{"api":1,"properties":1,"parameters":1}
,"api":{"data":1}
,"data":{"store":1}
,"store":{"properties":1,"config":1,"command":1,"configuration":1,"instance":1}
,"properties":{"specify":1,"data":1,"api":1,"drop-down":1}
,"specify":{"custom":1}
,"config":{"uration":1}
,"uration":{"specify":1}
,"command":{"central":1}
,"central":{"navigate":1}
,"navigate":{"environments":1}
,"environments":{"instances":1}
,"instances":{"api":1}
,"configuration":{"select":1}
,"select":{"properties":1}
,"drop-down":{"menu":1}
,"menu":{"click":1}
,"click":{"edit":1}
,"edit":{"content":1}
,"content":{"field":1}
,"field":{"specify":1}
,"parameters":{"yaml":1}
,"yaml":{"syntax":1}
,"syntax":{"property_name":1}
,"property_name":{"value":1}
,"value":{"format":1}
,"format":{"restart":1}
,"restart":{"api":1}
}
;Search.control.loadWordPairs(pairs);
