// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"rollbacks":{"rollback":1}
,"rollback":{"process":1,"assets":1}
,"process":{"restoring":1}
,"restoring":{"asset\u0027s":1}
,"asset\u0027s":{"metadata":1}
,"metadata":{"target":1}
,"target":{"api":1}
,"api":{"gateway":1}
,"gateway":{"instance":1}
,"instance":{"previous":1}
,"previous":{"state":1}
,"state":{"need":1}
,"need":{"rollback":1}
,"assets":{"revert":1}
,"revert":{"promotional":1}
,"promotional":{"data":1}
,"data":{"changes":1}
,"changes":{"made":1}
,"made":{"target":1}
}
;Search.control.loadWordPairs(pairs);
