// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"data":{"backup":1,"bac":1}
,"backup":{"section":1}
,"section":{"covers":1}
,"covers":{"following":1}
,"following":{"topics":1}
,"topics":{"related":1}
,"related":{"data":1}
,"bac":{"kup":1}
}
;Search.control.loadWordPairs(pairs);
