// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"install":{"api":1}
,"api":{"gateway":1}
,"gateway":{"using":1,"either":1,"product":1,"administrator":1}
,"using":{"command":1}
,"command":{"central":1}
,"central":{"install":1,"software":1,"help":1,"templates":1,"product":1}
,"either":{"following":1}
,"following":{"ways":1}
,"ways":{"using":1}
,"software":{"command":1}
,"help":{"using":1}
,"templates":{"begin":1,"basic":1}
,"begin":{"ensure":1}
,"ensure":{"familiar":1}
,"familiar":{"command":1}
,"product":{"familiar":1,"basic":1}
,"basic":{"understanding":1}
,"understanding":{"api":1}
,"administrator":{"configurations":1}
}
;Search.control.loadWordPairs(pairs);
