// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"publish":{"api":1,"icon":1,"select":1,"apis":1}
,"api":{"publish":1,"configured":1,"want":1,"portal":1,"published":1}
,"configured":{"destination":1}
,"destination":{"click":1}
,"click":{"apis":1,"publish":1}
,"apis":{"title":1}
,"title":{"navigation":1}
,"navigation":{"bar":1}
,"bar":{"home":1}
,"home":{"page":1}
,"page":{"click":1}
,"icon":{"next":1}
,"next":{"api":1}
,"want":{"publish":1}
,"select":{"api":1,"required":1}
,"portal":{"select":1,"information":1}
,"required":{"communities":1}
,"communities":{"default":1}
,"default":{"community":1}
,"community":{"public":1,"click":1}
,"public":{"users":1}
,"users":{"access":1}
,"access":{"community":1}
,"published":{"developer":1}
,"developer":{"portal":1}
,"information":{"publish":1}
}
;Search.control.loadWordPairs(pairs);
