// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"running":{"api":1}
,"api":{"gateway":1}
,"gateway":{"utility":1}
,"utility":{"container":1,"perform":1}
,"container":{"built":1,"keep":1,"alive":1}
,"built":{"docker":1}
,"docker":{"image":1}
,"image":{"run":1}
,"run":{"utility":1,"command":1}
,"perform":{"backup":1}
,"backup":{"operation":1}
,"operation":{"either":1}
,"either":{"run":1}
,"command":{"exit":1}
,"exit":{"container":1}
,"keep":{"container":1}
,"alive":{"perform":1}
}
;Search.control.loadWordPairs(pairs);
