// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"expired":1}
,"expired":{"oauth":1}
,"oauth":{"tokens":1,"access":1,"acces":1}
,"tokens":{"remove":1,"using":1,"required":1,"rest":1}
,"remove":{"expired":1}
,"access":{"tokens":1}
,"using":{"given":1}
,"given":{"api":1}
,"api":{"schedule":1}
,"schedule":{"cleanup":1}
,"cleanup":{"expired":1}
,"acces":{"tokens":1}
,"required":{"remove":1}
,"rest":{"call":1}
,"call":{"following":1}
,"following":{"endpoint":1}
,"endpoint":{"hostname":1}
,"hostname":{"port":1}
,"port":{"\u002Finvoke\u002Fpub.oauth\u002Fremoveexpiredaccesstokens":1}
}
;Search.control.loadWordPairs(pairs);
