// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"proxy":1}
,"proxy":{"server":1,"list":1}
,"server":{"alias":1}
,"alias":{"delete":1,"expand":1,"deleted":1}
,"delete":{"proxy":1,"click":1}
,"expand":{"menu":1}
,"menu":{"options":1}
,"options":{"icon":1}
,"icon":{"title":1}
,"title":{"bar":1}
,"bar":{"select":1}
,"select":{"administration":1,"general":1}
,"administration":{"select":1}
,"general":{"outbound":1}
,"outbound":{"proxies":1,"proxy":1}
,"proxies":{"outbound":1}
,"list":{"click":1}
,"click":{"action":1,"confirmation":1}
,"action":{"column":1}
,"column":{"proxy":1}
,"confirmation":{"dialog":1}
,"dialog":{"box":1}
,"box":{"proxy":1}
,"deleted":{"list":1}
}
;Search.control.loadWordPairs(pairs);
