// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"storing":{"analytics":1}
,"analytics":{"data":1}
,"data":{"external":1,"saved":1}
,"external":{"elasticsearch":1,"elast":1}
,"elasticsearch":{"store":1,"configure":1,"information":1,"connecting":1,"apply":1,"destination":1}
,"store":{"analytics":1}
,"configure":{"external":1}
,"information":{"conf":1,"log":1}
,"conf":{"iguring":1}
,"iguring":{"connecting":1}
,"connecting":{"external":1}
,"apply":{"log":1}
,"log":{"invocation":1}
,"invocation":{"policy":1,"analytics":1}
,"policy":{"globally":1,"log":1}
,"globally":{"elasticsearch":1}
,"destination":{"information":1}
,"saved":{"configured":1}
,"configured":{"external":1}
,"elast":{"icsearch":1}
,"icsearch":{"destination":1}
}
;Search.control.loadWordPairs(pairs);
