// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"starting":{"stopping":1}
,"stopping":{"restarting":1}
,"restarting":{"api":1}
,"api":{"data":1}
,"data":{"store":1}
,"store":{"windows":1,"instance":1,"using":1,"10.11":1,"-software":1}
,"windows":{"install":1,"operating":1,"start":1}
,"install":{"api":1,"folder":1}
,"operating":{"syste":1}
,"syste":{"start":1}
,"start":{"stop":1,"menu":1,"product":1,"api":1}
,"stop":{"api":1,"restart":1}
,"instance":{"using":1}
,"using":{"windows":1,"scripts":1}
,"menu":{"using":1,"start":1}
,"scripts":{"start":1,"run":1}
,"product":{"install":1}
,"folder":{"select":1}
,"select":{"start":1}
,"10.11":{"stop":1,"respectively":1}
,"respectively":{"start":1}
,"restart":{"api":1}
,"run":{"start":1}
,"-software":{"ag_directory":1}
,"ag_directory":{"\u005Cinternaldatastore\u005Cbin\u005Cconfig\u005Cstartup.bat":1,"\u005Cinternaldatastore\u005Cconfig\u005Cbin\u005Cshutdown.bat":1,"\u005Cinternaldatastore\u005Cconfig\u005Cbin\u005Crestart.bat":1}
,"\u005Cinternaldatastore\u005Cbin\u005Cconfig\u005Cstartup.bat":{"stop":1}
,"\u005Cinternaldatastore\u005Cconfig\u005Cbin\u005Cshutdown.bat":{"restart":1}
}
;Search.control.loadWordPairs(pairs);
