// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"scaling":{"down":1}
,"down":{"api":1}
,"api":{"data":1}
,"data":{"store":1}
,"store":{"scale":1,"remove":1,"node":1,"removing":1,"scaled":1}
,"scale":{"down":1}
,"remove":{"api":1}
,"node":{"cluster":1,"ensure":1,"specified":1}
,"cluster":{"stopping":1,"formation":1}
,"stopping":{"api":1}
,"removing":{"master":1}
,"master":{"node":1}
,"ensure":{"node":1}
,"specified":{"cluster.initial_master_nodes":1}
,"cluster.initial_master_nodes":{"property":1}
,"property":{"else":1}
,"else":{"cluster":1}
,"formation":{"becomes":1}
,"becomes":{"impossible":1}
,"impossible":{"api":1}
,"scaled":{"down":1}
}
;Search.control.loadWordPairs(pairs);
