// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"create":{"api":1}
,"api":{"create":1,"click":1,"information":1}
,"click":{"apis":1,"create":1}
,"apis":{"title":1}
,"title":{"navigation":1}
,"navigation":{"bar":1}
,"bar":{"home":1}
,"home":{"page":1}
,"page":{"click":1}
,"information":{"defining":1}
,"defining":{"managing":1}
,"managing":{"apis":1}
}
;Search.control.loadWordPairs(pairs);
