// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"url":1}
,"url":{"alias":1,"aliases":1}
,"alias":{"delete":1,"expand":1,"list":1}
,"delete":{"url":1,"click":1}
,"expand":{"menu":1}
,"menu":{"options":1}
,"options":{"icon":1}
,"icon":{"title":1}
,"title":{"bar":1}
,"bar":{"select":1}
,"select":{"administration":1,"general":1}
,"administration":{"select":1}
,"general":{"url":1}
,"aliases":{"url":1}
,"list":{"locate":1}
,"locate":{"row":1}
,"row":{"contains":1}
,"contains":{"alia":1}
,"alia":{"want":1}
,"want":{"delete":1}
,"click":{"click":1,"confirmation":1}
,"confirmation":{"dialog":1}
,"dialog":{"box":1}
}
;Search.control.loadWordPairs(pairs);
