// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"scaling":{"down":1}
,"down":{"api":1,"instance":1}
,"api":{"gateway":1}
,"gateway":{"reverse":1}
,"reverse":{"invoke":1}
,"invoke":{"setup":1}
,"setup":{"-green":1}
,"-green":{"remove":1}
,"remove":{"node":1}
,"node":{"green":1,"shut":1,"in-flight":1,"removed":1}
,"green":{"zone":1}
,"zone":{"performing":1}
,"performing":{"followin":1}
,"followin":{"steps":1}
,"steps":{"disable":1}
,"disable":{"internal":1}
,"internal":{"ports":1}
,"ports":{"node":1}
,"shut":{"down":1}
,"instance":{"node":1}
,"in-flight":{"transactions":1}
,"transactions":{"fail":1}
,"fail":{"communication":1}
,"communication":{"chann":1}
,"chann":{"closed":1}
,"closed":{"node":1}
}
;Search.control.loadWordPairs(pairs);
