// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"licenses":1}
,"licenses":{"section":1,"command":1}
,"section":{"provides":1}
,"provides":{"information":1}
,"information":{"adding":1}
,"adding":{"api":1}
,"api":{"gateway":1}
,"gateway":{"icenses":1,"configuration":1}
,"icenses":{"using":1}
,"using":{"command":1}
,"command":{"central":1}
,"central":{"configure":1,"navigate":1}
,"configure":{"licenses":1}
,"navigate":{"environments":1}
,"environments":{"instances":1}
,"instances":{"api":1}
,"configuration":{"select":1}
,"select":{"license":1}
,"license":{"keys":1,"provide":1}
,"keys":{"drop-down":1,"list":1}
,"drop-down":{"menu":1}
,"menu":{"license":1}
,"list":{"appears":1}
,"appears":{"click":1}
,"click":{"add":1}
,"add":{"new":1}
,"new":{"license":1}
,"provide":{"required":1}
,"required":{"license":1}
}
;Search.control.loadWordPairs(pairs);
