// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"remove":{"user":1}
,"user":{"data":1}
,"data":{"api":1}
,"api":{"gateway":1}
}
;Search.control.loadWordPairs(pairs);
