// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"enabling":{"api":1}
,"api":{"mocking":1,"details":1,"list":1,"appears":1}
,"mocking":{"enable":1,"api":1,"active":1,"click":1,"generates":1}
,"enable":{"disable":1,"api":1,"mocking":1}
,"disable":{"api":1}
,"details":{"page":1}
,"page":{"note":1,"selected":1}
,"note":{"cannot":1}
,"cannot":{"enable":1}
,"active":{"apis":1}
,"apis":{"enable":1,"title":1,"api":1}
,"click":{"apis":1,"select":1}
,"title":{"navigation":1}
,"navigation":{"bar":1}
,"bar":{"select":1}
,"select":{"required":1,"enable":1}
,"required":{"api":1}
,"list":{"available":1}
,"available":{"apis":1}
,"selected":{"api":1}
,"appears":{"click":1}
,"generates":{"default":1}
,"default":{"mock":1}
,"mock":{"responses":1}
}
;Search.control.loadWordPairs(pairs);
