// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"disaster":{"recovery":1}
,"recovery":{"fault":1,"(hadr)":1}
,"fault":{"tolerance":1}
,"tolerance":{"high":1,"(haft)":1}
,"high":{"availability":1}
,"availability":{"disaster":1,"fault":1}
,"(hadr)":{"high":1}
,"(haft)":{"architectures":1}
,"architectures":{"ensure":1}
,"ensure":{"application":1}
,"application":{"runs":1}
,"runs":{"without":1}
,"without":{"system":1}
,"system":{"degradation":1}
,"degradation":{"however":1}
,"however":{"unique":1}
,"unique":{"attributes":1}
,"attributes":{"diff":1}
,"diff":{"erentiate":1}
,"erentiate":{"cost":1}
,"cost":{"design":1}
,"design":{"redundancy":1}
,"redundancy":{"level":1}
,"level":{"behav":1}
,"behav":{"ior":1}
,"ior":{"component":1}
,"component":{"faults":1}
,"faults":{"failures":1}
}
;Search.control.loadWordPairs(pairs);
