// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"appmesh":{"deployment":1,"begin":1,"environment":1}
,"deployment":{"section":1,"service":1}
,"section":{"describes":1}
,"describes":{"microservices":1}
,"microservices":{"discovered":1}
,"discovered":{"deployed":1}
,"deployed":{"appmesh":1}
,"begin":{"kubernetes":1}
,"kubernetes":{"environment":1}
,"environment":{"without":1,"api":1}
,"without":{"servi":1}
,"servi":{"mesh":1}
,"mesh":{"configured":1}
,"configured":{"appmesh":1}
,"api":{"gateway":1,"definition":1}
,"gateway":{"stages":1}
,"stages":{"appmesh":1}
,"service":{"discovery":1}
,"discovery":{"apify":1}
,"apify":{"update":1}
,"update":{"api":1}
,"definition":{"policies":1}
,"policies":{"deploy":1}
,"deploy":{"appmesh":1}
}
;Search.control.loadWordPairs(pairs);
