// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"view":{"published":1,"api":1,"details":1}
,"published":{"api":1}
,"api":{"view":1,"developer":1,"gallery":1,"details":1}
,"developer":{"portal":1}
,"portal":{"gallery":1,"log":1,"click":1}
,"gallery":{"view":1,"navigation":1,"appears":1}
,"log":{"developer":1}
,"click":{"api":1,"view":1}
,"navigation":{"bar":1}
,"bar":{"api":1}
,"appears":{"click":1}
,"details":{"api":1}
}
;Search.control.loadWordPairs(pairs);
