// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2016-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"commands":{"api":1,"listed":1,"additional":1}
,"api":{"data":1}
,"data":{"store":1,"general":1}
,"store":{"supports":1}
,"supports":{"api":1,"platform":1}
,"platform":{"manager":1}
,"manager":{"commands":1}
,"listed":{"following":1}
,"following":{"table":1}
,"table":{"table":1,"lists":1}
,"lists":{"find":1}
,"find":{"information":1}
,"information":{"command":1,"sagcc":1}
,"command":{"commands":1,"software":1,"central":1}
,"additional":{"information":1}
,"sagcc":{"configuration":1,"update":1,"list":1,"exec":1,"monitoring":1}
,"configuration":{"data":1,"instances":1,"types":1,"validation":1}
,"general":{"information":1}
,"software":{"command":1}
,"central":{"help":1}
,"help":{"sagcc":1}
,"update":{"configuration":1,"general":1}
,"instances":{"general":1}
,"list":{"configuration":1}
,"types":{"general":1}
,"exec":{"configuration":1,"lifecycle":1}
,"validation":{"update":1}
,"lifecycle":{"general":1}
,"monitoring":{"general":1}
}
;Search.control.loadWordPairs(pairs);
