// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"processing":{"steps":1,"teps":1}
,"steps":{"connector":1}
,"connector":{"virtual":1}
,"virtual":{"service":1}
,"service":{"connector":1,"contain":1}
,"contain":{"similar":1}
,"similar":{"processing":1}
,"teps":{"virtual":1}
}
;Search.control.loadWordPairs(pairs);
