// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wst.cloudconnectorservice":{"wst.cloudconnectorservice.validation":1}
,"wst.cloudconnectorservice.validation":{"parameter":1}
,"parameter":{"true":1}
,"true":{"want":1}
,"want":{"cloud":1}
,"cloud":{"connector":1}
,"connector":{"services":1}
,"services":{"validated":1}
,"validated":{"agains":1}
,"agains":{"document":1}
,"document":{"types":1}
,"types":{"present":1}
,"present":{"service":1}
,"service":{"signature":1}
,"signature":{"default":1}
,"default":{"false":1}
}
;Search.control.loadWordPairs(pairs);
