// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"data":1}
,"data":{"feed":1}
,"feed":{"configure":1,"open":1}
,"configure":{"data":1}
,"open":{"config.xml":1}
,"config.xml":{"file":1}
,"file":{"located":1}
,"located":{"mashzone_ng_home":1}
,"mashzone_ng_home":{"\u005Cmashzone\u005Cdata\u005Cresources":1}
,"\u005Cmashzone\u005Cdata\u005Cresources":{"folder":1}
,"folder":{"host":1}
,"host":{"port":1}
,"port":{"point":1,"integration":1,"localhost":1}
,"point":{"host":1}
,"integration":{"server":1}
,"server":{"cloudstreams":1}
,"cloudstreams":{"installed":1}
,"installed":{"default":1}
,"default":{"host":1}
,"localhost":{"5555":1}
,"5555":{"respectively":1}
}
;Search.control.loadWordPairs(pairs);
