// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"security":1}
,"security":{"api":1}
,"api":{"services":1,"used":1}
,"services":{"note":1,"cloudstreams":1,"support":1,"included":1}
,"note":{"api":1}
,"used":{"soap-based":1}
,"soap-based":{"virtual":1}
,"virtual":{"services":1}
,"cloudstreams":{"provides":1}
,"provides":{"java":1}
,"java":{"services":1}
,"support":{"ws-secur":1}
,"ws-secur":{"ity":1}
,"ity":{"functionality":1}
,"functionality":{"service":1}
,"service":{"invoke":1}
,"invoke":{"sequence":1}
,"sequence":{"step":1}
,"step":{"following":1}
,"following":{"services":1}
,"included":{"pub.cloudstreams.security.ws.addusernametoken":1}
,"pub.cloudstreams.security.ws.addusernametoken":{"pub.cloudstreams.security.ws.addx509token":1}
,"pub.cloudstreams.security.ws.addx509token":{"pub.cloudstreams.security.ws.addsamlsendervouchestoken":1}
,"pub.cloudstreams.security.ws.addsamlsendervouchestoken":{"pub.cloudstreams.security.ws.addtimestamp":1}
,"pub.cloudstreams.security.ws.addtimestamp":{"pub.cloudstreams.security.ws.addwsaddressingheaders":1}
}
;Search.control.loadWordPairs(pairs);
