// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pub.cloudstreams.admin.listener:querylistenerstate":{"returns":1}
,"returns":{"current":1}
,"current":{"listener":1}
,"listener":{"state":1,"node":1,"enabled":1,"disabled":1}
,"state":{"(enabled\u002Fdisabled)":1}
,"(enabled\u002Fdisabled)":{"listener":1,"values":1}
,"node":{"input":1,"want":1}
,"input":{"parameters":1}
,"parameters":{"listeneralias":1,"listenerstate":1}
,"listeneralias":{"string":1}
,"string":{"name":1,"current":1}
,"name":{"listener":1}
,"want":{"status":1}
,"status":{"returned":1}
,"returned":{"output":1}
,"output":{"parameters":1}
,"listenerstate":{"string":1}
,"values":{"enabled":1}
,"enabled":{"-the":1,"disabled":1}
,"-the":{"listener":1}
,"disabled":{"-the":1}
}
;Search.control.loadWordPairs(pairs);
