// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"setting":{"publishing":1,"database":1}
,"publishing":{"options":1,"performance":1}
,"options":{"performance":1,"described":1,"publishing":1}
,"performance":{"metrics":1}
,"metrics":{"vents":1,"events":1}
,"vents":{"cloudstreams":1}
,"cloudstreams":{"uses":1,"publish":1,"analytics":1}
,"uses":{"integration":1}
,"integration":{"server":1}
,"server":{"jdbc":1}
,"jdbc":{"connection":1}
,"connection":{"pool":1}
,"pool":{"publish":1}
,"publish":{"performance":1}
,"events":{"enable":1,"cloudstreams":1}
,"enable":{"cloudstreams":1}
,"analytics":{"dashboard":1}
,"dashboard":{"options":1}
,"described":{"setting":1}
,"database":{"options":1}
}
;Search.control.loadWordPairs(pairs);
