// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"streaming":{"options":1,"setting":1,"providers":1,"subscribers":1}
,"options":{"integration":1,"solutions":1,"setting":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"following":1}
,"following":{"options":1}
,"solutions":{"cloudstreams":1}
,"cloudstreams":{"streaming":1}
,"setting":{"streaming":1}
,"providers":{"options":1}
,"subscribers":{"options":1}
}
;Search.control.loadWordPairs(pairs);
