// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"need":{"modify":1}
,"modify":{"deployed":1,"virtual":1,"cloudstreams":1}
,"deployed":{"services":1,"assets":1}
,"services":{"need":1}
,"virtual":{"service":1,"service\u0027s":1}
,"service":{"already":1,"put":1}
,"already":{"depl":1}
,"depl":{"oyed":1}
,"oyed":{"redeploy":1}
,"redeploy":{"modify":1,"virtual":1}
,"cloudstreams":{"monitor":1}
,"monitor":{"updates":1}
,"updates":{"deployed":1}
,"assets":{"mak":1}
,"mak":{"changes":1}
,"changes":{"virtual":1,"effect":1}
,"service\u0027s":{"processing":1}
,"processing":{"steps":1}
,"steps":{"examp":1}
,"examp":{"manually":1}
,"manually":{"redeploy":1}
,"put":{"ose":1}
,"ose":{"changes":1}
}
;Search.control.loadWordPairs(pairs);
