// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"pg.http":{"pg.http.ports":1}
,"pg.http.ports":{"specifies":1}
,"specifies":{"http":1,"https":1}
,"http":{"ports":1}
,"ports":{"cloudstreams":1,"configuration":1}
,"cloudstreams":{"available":1,"administration":1}
,"available":{"edit":1}
,"edit":{"parameter":1}
,"parameter":{"http":1,"https":1}
,"configuration":{"field":1}
,"field":{"cloudstreams":1}
,"administration":{"general":1}
,"general":{"page":1}
,"page":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"pg.https.ports":1}
,"pg.https.ports":{"specifies":1}
,"https":{"ports":1}
}
;Search.control.loadWordPairs(pairs);
