// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sequence":{"step":1}
,"step":{"(connector":1,"contain":1,"(required)":1,"(optional)":1}
,"(connector":{"virtual":1}
,"virtual":{"service":1}
,"service":{"soap)":1,"accept":1,"route":1,"requests":1,"step":1}
,"soap)":{"sequence":1}
,"contain":{"following":1}
,"following":{"sub-steps":1}
,"sub-steps":{"entry":1}
,"entry":{"step":1}
,"(required)":{"specifies":1}
,"specifies":{"protocol":1,"connector":1}
,"protocol":{"requests":1}
,"requests":{"connector":1,"native":1}
,"connector":{"virtual":1}
,"accept":{"routing":1}
,"routing":{"rule":1}
,"rule":{"step":1}
,"route":{"service":1}
,"native":{"servic":1,"service":1}
,"servic":{"endpoint":1}
,"endpoint":{"invoke":1}
,"invoke":{"service":1}
,"(optional)":{"pre-processes":1}
,"pre-processes":{"request":1}
,"request":{"message":1}
,"message":{"fore":1}
,"fore":{"submitted":1}
,"submitted":{"native":1}
}
;Search.control.loadWordPairs(pairs);
