// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deploying":{"assets":1}
,"assets":{"using":1}
,"using":{"webmethods":1}
,"webmethods":{"deployer":1}
}
;Search.control.loadWordPairs(pairs);
