// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"policy":{"validation":1,"(or":1,"actions":1}
,"validation":{"deploy":1}
,"deploy":{"service":1}
,"service":{"cloudstreams":1,"info":1}
,"cloudstreams":{"automatically":1,"warn":1}
,"automatically":{"validates":1}
,"validates":{"service\u0027s":1}
,"service\u0027s":{"policy":1}
,"(or":{"policies)":1}
,"policies)":{"ensure":1}
,"ensure":{"action":1}
,"action":{"dependencies":1}
,"dependencies":{"properly":1,"policy":1}
,"properly":{"met":1}
,"met":{"cloudstreams":1}
,"warn":{"violation":1}
,"violation":{"need":1}
,"need":{"correc":1}
,"correc":{"violations":1}
,"violations":{"deploying":1}
,"deploying":{"service":1}
,"info":{"rmation":1}
,"rmation":{"dependencies":1}
}
;Search.control.loadWordPairs(pairs);
