// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"creating":{"esb":1}
,"esb":{"service":1}
,"service":{"streaming":1,"option":1,"invoked":1}
,"streaming":{"subscriber":1,"notification":1}
,"subscriber":{"destinatio":1,"specify":1}
,"destinatio":{"select":1}
,"select":{"esb":1}
,"option":{"destination":1}
,"destination":{"type":1}
,"type":{"field":1}
,"field":{"streaming":1}
,"specify":{"service":1}
,"invoked":{"streaming":1}
,"notification":{"recei":1}
,"recei":{"ved":1}
,"ved":{"following":1}
,"following":{"guidance":1}
,"guidance":{"write":1}
,"write":{"servic":1}
}
;Search.control.loadWordPairs(pairs);
