// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"context":1}
,"context":{"variables":1}
,"variables":{"services":1,"declare":1,"predefin":1,"configure":1,"custom":1,"(see":1}
,"services":{"cloudstreams":1}
,"cloudstreams":{"provides":1}
,"provides":{"predefined":1}
,"predefined":{"context":1}
,"declare":{"custom":1}
,"custom":{"context":1}
,"predefin":{"custom":1}
,"configure":{"various":1}
,"various":{"rocessing":1}
,"rocessing":{"steps":1}
,"steps":{"virtual":1,"routing":1}
,"virtual":{"service":1}
,"service":{"specifically":1,"create":1}
,"specifically":{"service":1}
,"create":{"invoke":1,"routing":1}
,"invoke":{"sequence":1}
,"sequence":{"sequence":1,"steps":1}
,"routing":{"rule":1}
,"rule":{"create":1,"step":1}
,"step":{"type":1}
,"type":{"context-based":1}
,"context-based":{"section":1}
,"section":{"discusses":1}
,"discusses":{"predefined":1}
,"(see":{"api":1}
,"api":{"context":1}
}
;Search.control.loadWordPairs(pairs);
