// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"workspace":1}
,"workspace":{"folder":1}
,"folder":{"navigation":1,"webmethods":1,"content":1,"contains":1,"want":1}
,"navigation":{"pane":1,"ane":1,"workspaces":1}
,"pane":{"longer":1,"folder":1,"remove":1,"navigation":1,"click":1}
,"longer":{"need":1,"listed":1}
,"need":{"workspace":1}
,"ane":{"delete":1}
,"delete":{"delete":1,"workspace":1,"folder":1}
,"webmethods":{"removes":1}
,"removes":{"folder":1}
,"content":{"navigation":1}
,"contains":{"workspaces":1}
,"workspaces":{"workspaces":1,"removed":1,"ares":1,"section":1}
,"removed":{"navigation":1}
,"ares":{"deleted":1}
,"deleted":{"simply":1}
,"simply":{"longer":1}
,"listed":{"navigation":1}
,"remove":{"workspace":1,"select":1}
,"click":{"navigate":1,"name":1}
,"navigate":{"tab":1}
,"tab":{"workspaces":1}
,"section":{"right":1}
,"right":{"click":1}
,"name":{"folder":1}
,"want":{"remove":1}
,"select":{"delete":1}
}
;Search.control.loadWordPairs(pairs);
