// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"installservice":{"installservice":1,"command":1}
,"command":{"registers":1,"accepts":1}
,"registers":{"webmethods":1}
,"webmethods":{"server":1}
,"server":{"service":1,"running":1}
,"service":{"windows":1,"usage":1}
,"windows":{"daemon":1,"systems":1}
,"daemon":{"unix":1}
,"unix":{"systems":1}
,"systems":{"options":1,"installservice":1,"specify":1}
,"options":{"parameters":1}
,"parameters":{"windows":1,"following":1}
,"accepts":{"java":1}
,"java":{"system":1}
,"system":{"properties":1}
,"properties":{"parameters":1}
,"following":{"format":1}
,"format":{"any.java.system.property":1}
,"any.java.system.property":{"=value":1}
,"=value":{"unix":1}
,"specify":{"user":1}
,"user":{"name":1,"installs":1}
,"name":{"user":1}
,"installs":{"service":1}
,"usage":{"notes":1}
,"notes":{"supported":1}
,"supported":{"webmethods":1}
,"running":{"container":1}
}
;Search.control.loadWordPairs(pairs);
