// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"displaying":{"slow":1}
,"slow":{"database":1}
,"database":{"calls":1,"cal":1}
,"calls":{"display":1,"tool":1}
,"display":{"information":1}
,"information":{"ten":1}
,"ten":{"slowest":1}
,"slowest":{"database":1}
,"cal":{"log":1}
,"log":{"administrator":1}
,"administrator":{"webmethods":1}
,"webmethods":{"server":1}
,"server":{"webmethods":1,"tools":1}
,"tools":{"mws":1}
,"mws":{"monitoring":1}
,"monitoring":{"diagnostics":1}
,"diagnostics":{"performance":1}
,"performance":{"informa":1}
,"informa":{"tion":1}
,"tion":{"locate":1}
,"locate":{"slow":1}
,"tool":{"drag":1}
,"drag":{"onto":1}
,"onto":{"workspace":1}
}
;Search.control.loadWordPairs(pairs);
