// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"workspace":{"actions":1,"managem":1,"management":1}
,"actions":{"perform":1,"against":1}
,"perform":{"workspace":1,"actions":1}
,"managem":{"ent":1}
,"ent":{"page":1}
,"page":{"navigate":1,"perform":1,"webmethods":1,"information":1}
,"navigate":{"applications":1}
,"applications":{"administration":1}
,"administration":{"system-wi":1}
,"system-wi":{"workspace":1}
,"management":{"page":1}
,"against":{"rkspaces":1}
,"rkspaces":{"default":1}
,"default":{"webmethods":1}
,"webmethods":{"administrators":1}
,"administrators":{"access":1,"grant":1}
,"access":{"workspace":1,"workspac":1}
,"grant":{"users":1}
,"users":{"access":1}
,"workspac":{"management":1}
,"information":{"allowing":1}
,"allowing":{"users":1}
}
;Search.control.loadWordPairs(pairs);
