// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"displaying":{"thread":1}
,"thread":{"information":1,"dump":1}
,"information":{"display":1,"log":1,"locate":1,"click":1}
,"display":{"webmethods":1,"recent":1}
,"webmethods":{"server":1}
,"server":{"thread":1,"webmethods":1,"tools":1}
,"log":{"administrator":1}
,"administrator":{"webmethods":1}
,"tools":{"mws":1}
,"mws":{"monitoring":1}
,"monitoring":{"diagnostics":1}
,"diagnostics":{"system":1}
,"system":{"information":1}
,"locate":{"thread":1}
,"dump":{"tool":1}
,"tool":{"drag":1}
,"drag":{"onto":1}
,"onto":{"workspace":1}
,"workspace":{"display":1}
,"recent":{"thread":1}
,"click":{"refresh":1}
}
;Search.control.loadWordPairs(pairs);
