// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"shell":1}
,"shell":{"longer":1,"delete":1,"system":1,"administra":1,"click":1}
,"longer":{"needed":1}
,"needed":{"delete":1}
,"delete":{"shell":1}
,"system":{"administrator":1}
,"administrator":{"administration":1}
,"administration":{"dashboard":1}
,"dashboard":{"user":1}
,"user":{"interface":1}
,"interface":{"shell":1}
,"administra":{"tion":1}
,"tion":{"delete":1}
,"click":{"tools":1,"delete":1}
,"tools":{"icon":1}
,"icon":{"click":1}
}
;Search.control.loadWordPairs(pairs);
