// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"working":{"response":1}
,"response":{"header":1,"messages":1}
,"header":{"rules":1}
,"rules":{"webmethods":1,"govern":1}
,"webmethods":{"server":1}
,"server":{"enables":1}
,"enables":{"create":1}
,"create":{"manage":1}
,"manage":{"rules":1}
,"govern":{"http":1}
,"http":{"response":1}
,"messages":{"sent":1}
,"sent":{"receiving":1}
,"receiving":{"interpr":1}
,"interpr":{"eting":1}
,"eting":{"request":1}
,"request":{"message":1}
}
;Search.control.loadWordPairs(pairs);
