// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"getconfig":{"downloads":1,"filename":1}
,"downloads":{"configuration":1}
,"configuration":{"file":1,"files":1}
,"file":{"webmethods":1,"arameter":1}
,"webmethods":{"server":1}
,"server":{"database":1}
,"database":{"specify":1,"modifying":1}
,"specify":{"name":1}
,"name":{"configuration":1}
,"arameter":{"command":1}
,"command":{"follows":1}
,"follows":{"mws":1}
,"mws":{"getconfig":1}
,"filename":{"information":1}
,"information":{"list":1}
,"list":{"configuration":1}
,"files":{"stor":1,"stored":1}
,"stor":{"webmethods":1}
,"modifying":{"configuration":1}
,"stored":{"database":1}
}
;Search.control.loadWordPairs(pairs);
