// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"performing":{"simple":1}
,"simple":{"alias":1,"search":1}
,"alias":{"search":1,"management":1,"want":1}
,"search":{"search":1,"aliases":1,"type":1,"appear":1}
,"aliases":{"following":1,"system":1,"searc":1,"click":1,"match":1}
,"following":{"procedure":1}
,"procedure":{"perform":1}
,"perform":{"simple":1}
,"system":{"administrator":1,"aliases":1}
,"administrator":{"click":1}
,"click":{"administration":1,"aliases":1}
,"administration":{"dashboard":1}
,"dashboard":{"configuration":1}
,"configuration":{"alias":1}
,"management":{"search":1}
,"type":{"name":1}
,"name":{"alias":1}
,"want":{"find":1}
,"find":{"specifically":1}
,"specifically":{"include":1,"including":1}
,"include":{"exclude":1}
,"exclude":{"system":1}
,"searc":{"criteria":1}
,"criteria":{"specifically":1}
,"including":{"excluding":1}
,"excluding":{"system":1}
,"match":{"search":1}
,"appear":{"table":1}
}
;Search.control.loadWordPairs(pairs);
