// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"specifically":{"including":1}
,"including":{"excluding":1}
,"excluding":{"system":1}
,"system":{"aliases":1,"administrator":1}
,"aliases":{"include":1,"during":1,"list":1,"search":1}
,"include":{"exclude":1,"system":1}
,"exclude":{"system":1}
,"during":{"search":1}
,"search":{"following":1,"system":1,"type":1,"-to":1,"click":1,"panel":1}
,"following":{"procedure":1,"-to":1}
,"procedure":{"include":1}
,"administrator":{"click":1}
,"click":{"administration":1,"refine":1,"close":1}
,"administration":{"dashboard":1}
,"dashboard":{"configuration":1}
,"configuration":{"alias":1}
,"alias":{"management":1,"want":1}
,"management":{"search":1}
,"type":{"name":1}
,"name":{"alias":1}
,"want":{"find":1}
,"find":{"click":1}
,"refine":{"include":1}
,"list":{"choose":1}
,"choose":{"following":1}
,"-to":{"include":1,"exclude":1}
,"close":{"refined":1}
,"refined":{"search":1}
,"panel":{"click":1}
}
;Search.control.loadWordPairs(pairs);
