// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"adding":{"items":1}
,"items":{"add":1,"function":1}
,"add":{"item":1,"items":1,"new":1,"button":1,"create":1}
,"item":{"webmethods":1,"click":1,"adding":1}
,"webmethods":{"displays":1}
,"displays":{"button":1,"additional":1}
,"button":{"add":1,"typically":1}
,"function":{"bar":1}
,"bar":{"example":1}
,"example":{"monitoring":1}
,"monitoring":{"system-wide":1}
,"system-wide":{"rules":1}
,"rules":{"rule":1}
,"rule":{"list":1,"button":1,"click":1,"add":1}
,"list":{"page":1}
,"page":{"create":1}
,"create":{"rule":1,"webmethods":1}
,"new":{"rule":1,"item":1}
,"click":{"create":1,"add":1}
,"typically":{"labeled":1}
,"labeled":{"add":1}
,"additional":{"windows":1}
,"windows":{"supply":1}
,"supply":{"requested":1}
,"requested":{"informati":1}
,"informati":{"describe":1}
,"describe":{"new":1}
}
;Search.control.loadWordPairs(pairs);
