// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"accessing":{"command":1}
,"command":{"line":1,"help":1,"accept":1,"prompt":1,"bin":1,"mws":1}
,"line":{"help":1,"utility":1}
,"help":{"contents":1,"access":1,"command":1}
,"contents":{"command":1}
,"utility":{"webmethods":1}
,"webmethods":{"server":1}
,"server":{"provides":1,"software":1}
,"provides":{"command":1}
,"access":{"comma":1}
,"comma":{"prompt":1}
,"prompt":{"using":1,"type":1}
,"using":{"help":1}
,"accept":{"options":1}
,"options":{"parameters":1}
,"parameters":{"command":1}
,"type":{"following":1}
,"following":{"command":1}
,"bin":{"directory":1}
,"directory":{"webmethods":1}
,"software":{"ag_directory":1}
,"ag_directory":{"\u005Cmws\u005Cbin":1}
,"\u005Cmws\u005Cbin":{"type":1}
,"mws":{"help":1}
}
;Search.control.loadWordPairs(pairs);
