// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"jvm":{"configuration":1,"provides":1}
,"configuration":{"java":1,"settings":1}
,"java":{"service":1,"heap":1}
,"service":{"wrapper":1}
,"wrapper":{"launches":1}
,"launches":{"jvm":1}
,"provides":{"configuration":1}
,"settings":{"among":1}
,"among":{"things":1}
,"things":{"specify":1}
,"specify":{"size":1}
,"size":{"java":1}
,"heap":{"directories":1}
,"directories":{"classpath":1}
}
;Search.control.loadWordPairs(pairs);
