// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"working":{"saved":1}
,"saved":{"searches":1}
,"searches":{"perform":1}
,"perform":{"particular":1}
,"particular":{"search":1}
,"search":{"regularly":1}
,"regularly":{"save":1}
,"save":{"earch":1}
,"earch":{"criteria":1}
,"criteria":{"reuse":1}
}
;Search.control.loadWordPairs(pairs);
