// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"create":{"static":1}
,"static":{"role":1}
,"role":{"add":1,"=session.createrole":1}
,"add":{"user":1}
,"user":{"member":1,"=(idirectoryuser)":1}
,"member":{"idirectorysession":1}
,"idirectorysession":{"session":1}
,"session":{"=directorysystemfactory.getdirectorysystem":1}
,"=directorysystemfactory.getdirectorysystem":{".createsession":1}
,".createsession":{"idirectoryuser":1}
,"idirectoryuser":{"user":1}
,"=(idirectoryuser)":{"session.lookupprincipalbyname":1}
,"session.lookupprincipalbyname":{"user1":1}
,"user1":{"idirectoryprincipal.type_user)":1}
,"idirectoryprincipal.type_user)":{"idirectoryrole":1}
,"idirectoryrole":{"role":1}
,"=session.createrole":{"(idirectoryrole.static_role_type":1}
,"(idirectoryrole.static_role_type":{"rolename":1}
,"rolename":{"collections.empty_map)":1}
,"collections.empty_map)":{"session.addprincipaltorole":1}
,"session.addprincipaltorole":{"(user.getid":1}
,"(user.getid":{"role.getid":1}
,"role.getid":{"())":1}
}
;Search.control.loadWordPairs(pairs);
