// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"adding":{"calendar":1}
,"calendar":{"workspace":1,"tool":1,"window":1}
,"workspace":{"add":1,"followin":1,"navigation":1,"tools":1,"content":1}
,"add":{"user":1,"calendar":1}
,"user":{"calendar":1,"calen":1}
,"followin":{"procedure":1}
,"procedure":{"add":1}
,"navigation":{"pane":1}
,"pane":{"click":1}
,"click":{"tools":1}
,"tools":{"tab":1,"section":1}
,"tab":{"workspace":1}
,"section":{"drag":1}
,"drag":{"user":1}
,"tool":{"workspace":1}
,"content":{"area":1}
,"area":{"default":1}
,"default":{"webmethods":1}
,"webmethods":{"configures":1}
,"configures":{"user":1}
,"window":{"show":1,"display":1}
,"show":{"user":1}
,"calen":{"dar":1}
,"dar":{"configure":1,"changing":1}
,"configure":{"window":1}
,"display":{"user\u2019s":1}
,"user\u2019s":{"calen":1,"calendar":1}
,"changing":{"view":1}
,"view":{"user\u2019s":1}
}
;Search.control.loadWordPairs(pairs);
