// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"principal":1}
,"principal":{"attribute":1,"profi":1}
,"attribute":{"provider":1,"providers":1}
,"provider":{"remove":1,"profile":1,"list":1}
,"remove":{"principal":1,"bottom":1}
,"profile":{"page":1}
,"page":{"following":1,"system":1,"click":1}
,"following":{"procedure":1}
,"procedure":{"remove":1}
,"system":{"administrator":1}
,"administrator":{"administration":1}
,"administration":{"dashboard":1,"user":1}
,"dashboard":{"user":1}
,"user":{"management":1,"group":1}
,"management":{"principal":1}
,"profi":{"administration":1}
,"group":{"role":1}
,"role":{"attribute":1}
,"providers":{"area":1}
,"area":{"select":1}
,"select":{"principal":1}
,"list":{"click":1}
,"click":{"remove":1,"apply":1}
,"bottom":{"page":1}
}
;Search.control.loadWordPairs(pairs);
