// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"retaining":{"session":1}
,"session":{"passwords":1}
,"passwords":{"memory":1}
,"memory":{"retain":1,"system":1}
,"retain":{"session":1}
,"system":{"administrator":1,"managers":1}
,"administrator":{"click":1}
,"click":{"administration":1,"edit":1,"update":1,"apply":1}
,"administration":{"folders":1}
,"folders":{"system":1}
,"managers":{"sessionmanage":1}
,"sessionmanage":{"default":1}
,"default":{"validate":1}
,"validate":{"configuration":1}
,"configuration":{"xml":1}
,"xml":{"click":1}
,"edit":{"edit":1,"text":1}
,"text":{"area":1,"clearpassword=true":1}
,"area":{"change":1}
,"change":{"text":1}
,"clearpassword=true":{"clearpassword=false":1}
,"clearpassword=false":{"save":1}
,"save":{"file":1}
,"file":{"close":1}
,"close":{"editor":1}
,"editor":{"click":1}
,"update":{"click":1}
}
;Search.control.loadWordPairs(pairs);
