// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"portlets":1}
,"portlets":{"page":1}
,"page":{"remove":1,"following":1,"system":1,"want":1,"title":1,"switch":1,"editing":1,"portlet":1}
,"remove":{"portlet":1,"portlets":1,"hidden":1}
,"portlet":{"page":1,"want":1}
,"following":{"procedure":1}
,"procedure":{"remove":1}
,"system":{"administrator":1}
,"administrator":{"navigate":1}
,"navigate":{"open":1}
,"open":{"page":1}
,"want":{"remove":1,"delete":1}
,"title":{"bar":1,"page":1}
,"bar":{"click":1,"portlet":1,"title":1}
,"click":{"tools":1,"save":1}
,"tools":{"icon":1}
,"icon":{"edit":1,"delete":1}
,"edit":{"page":1}
,"switch":{"page":1}
,"editing":{"mode":1}
,"mode":{"title":1}
,"hidden":{"select":1}
,"select":{"view":1}
,"view":{"expert":1}
,"expert":{"check":1}
,"check":{"box":1}
,"box":{"title":1}
,"delete":{"ick":1,"click":1}
,"ick":{"tools":1}
}
;Search.control.loadWordPairs(pairs);
