// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"opening":{"workspaces":1}
,"workspaces":{"open":1,"workspaces":1,"oth":1,"sharing":1,"section":1,"navigation":1}
,"open":{"workspaces":1,"workspace":1,"note":1,"navigation":1}
,"oth":{"users":1}
,"users":{"shared":1}
,"shared":{"information":1,"workspaces":1}
,"information":{"shared":1,"adding":1}
,"sharing":{"workspaces":1}
,"workspace":{"navigation":1,"want":1}
,"navigation":{"pane":1,"ane":1,"information":1}
,"pane":{"click":1}
,"click":{"navigate":1,"name":1}
,"navigate":{"tab":1}
,"tab":{"workspaces":1,"browse":1}
,"section":{"navigate":1}
,"browse":{"click":1}
,"name":{"workspace":1}
,"want":{"open":1}
,"note":{"workspace":1}
,"ane":{"search":1}
,"search":{"add":1}
,"add":{"navigation":1}
,"adding":{"workspaces":1}
}
;Search.control.loadWordPairs(pairs);
