// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"renaming":{"workspace":1}
,"workspace":{"folder":1}
,"folder":{"navigation":1,"rename":1,"window":1,"field":1,"specify":1}
,"navigation":{"pane":1}
,"pane":{"following":1,"rename":1,"click":1}
,"following":{"procedure":1}
,"procedure":{"rename":1}
,"rename":{"existing":1,"workspace":1,"sel":1,"folder":1}
,"existing":{"workspace":1}
,"click":{"navigate":1,"name":1}
,"navigate":{"tab":1}
,"tab":{"workspaces":1}
,"workspaces":{"section":1}
,"section":{"right":1}
,"right":{"click":1}
,"name":{"want":1,"folder":1,"characters":1}
,"want":{"rename":1}
,"sel":{"ect":1}
,"ect":{"rename":1}
,"window":{"new":1}
,"new":{"name":1}
,"field":{"type":1}
,"type":{"new":1}
,"specify":{"255":1}
,"255":{"characters":1}
,"characters":{"name":1,"including":1,"click":1}
,"including":{"non-asciis":1}
,"non-asciis":{"special":1}
,"special":{"characters":1}
}
;Search.control.loadWordPairs(pairs);
