// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"run":{"starts":1}
,"starts":{"server":1}
,"server":{"console":1,"running":1}
,"console":{"window":1}
,"window":{"options":1}
,"options":{"parameters":1}
,"parameters":{"stop":1,"following":1}
,"stop":{"command":1}
,"command":{"accepts":1}
,"accepts":{"java":1}
,"java":{"system":1}
,"system":{"properties":1}
,"properties":{"parameters":1}
,"following":{"format":1}
,"format":{"any.java.system.property":1}
,"any.java.system.property":{"=value":1}
,"=value":{"usage":1}
,"usage":{"notes":1}
,"notes":{"supported":1}
,"supported":{"webmethods":1}
,"webmethods":{"server":1}
,"running":{"container":1}
}
;Search.control.loadWordPairs(pairs);
