// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"jvm":1}
,"jvm":{"settings":1}
,"settings":{"webmethods":1,"open":1}
,"webmethods":{"server":1}
,"server":{"modify":1,"instance":1}
,"modify":{"jvm":1,"statements":1}
,"instance":{"custom_wrapper.conf":1,"text":1}
,"custom_wrapper.conf":{"file":1}
,"file":{"modify":1,"server":1,"location":1,"restart":1}
,"open":{"custom_wrapper.conf":1}
,"text":{"editor":1}
,"editor":{"find":1}
,"find":{"file":1}
,"location":{"software":1}
,"software":{"ag_directory":1}
,"ag_directory":{"\u005Cprofiles\u005Cmws_servername":1}
,"\u005Cprofiles\u005Cmws_servername":{"\u005Cconfiguration\u005C2":1}
,"\u005Cconfiguration\u005C2":{"add":1}
,"add":{"modify":1}
,"statements":{"needed":1}
,"needed":{"save":1}
,"save":{"file":1}
,"restart":{"webmethods":1}
}
;Search.control.loadWordPairs(pairs);
