// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"response":1}
,"response":{"header":1}
,"header":{"rule":1,"rules":1}
,"rule":{"remove":1,"system":1,"want":1,"click":1}
,"remove":{"response":1,"rule":1}
,"system":{"administrator":1}
,"administrator":{"administrative":1}
,"administrative":{"folders":1}
,"folders":{"administration":1}
,"administration":{"dashboard":1}
,"dashboard":{"user":1}
,"user":{"int":1}
,"int":{"erface":1}
,"erface":{"manage":1}
,"manage":{"response":1}
,"rules":{"click":1}
,"click":{"tools":1,"remove":1,"confirmation":1}
,"tools":{"icon":1}
,"icon":{"rule":1}
,"want":{"work":1}
,"work":{"click":1}
,"confirmation":{"dialog":1}
,"dialog":{"box":1}
,"box":{"remove":1}
}
;Search.control.loadWordPairs(pairs);
