// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"saved":1}
,"saved":{"alias":1,"ias":1,"searches":1}
,"alias":{"searches":1,"search":1,"management":1}
,"searches":{"save":1,"similar":1,"users":1}
,"save":{"alias":1}
,"search":{"regular":1}
,"regular":{"using":1}
,"ias":{"searches":1}
,"similar":{"using":1}
,"users":{"roups":1,"groups":1}
,"roups":{"roles":1}
,"roles":{"except":1,"working":1}
,"except":{"performed":1}
,"performed":{"locatio":1}
,"locatio":{"system":1}
,"system":{"administrator":1}
,"administrator":{"click":1}
,"click":{"administration":1}
,"administration":{"dashboard":1}
,"dashboard":{"configuration":1}
,"configuration":{"alias":1}
,"management":{"information":1}
,"information":{"saved":1}
,"groups":{"roles":1}
,"working":{"saved":1}
}
;Search.control.loadWordPairs(pairs);
