// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"bookmark":1}
,"bookmark":{"tool":1,"bookmarks":1}
,"tool":{"access":1}
,"access":{"bookmarked":1}
,"bookmarked":{"pages":1}
,"pages":{"display":1,"click":1}
,"display":{"bookmarked":1}
,"click":{"title":1}
,"title":{"bookmark":1}
,"bookmarks":{"window":1}
}
;Search.control.loadWordPairs(pairs);
