// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"creating":{"container":1}
,"container":{"create":1,"level":1,"within":1,"system":1,"current":1,"tab":1,"click":1,"(optional)":1}
,"create":{"container":1,"new":1,"nested":1}
,"level":{"default":1,"click":1}
,"default":{"containers":1}
,"containers":{"create":1}
,"within":{"container":1}
,"new":{"container":1}
,"system":{"administrator":1}
,"administrator":{"click":1}
,"click":{"administration":1,"create":1,"name":1}
,"administration":{"configuration":1,"page":1}
,"configuration":{"security":1}
,"security":{"realms":1}
,"realms":{"administrat":1,"administration":1}
,"administrat":{"ion":1}
,"ion":{"security":1}
,"page":{"following":1}
,"following":{"create":1}
,"current":{"level":1}
,"tab":{"create":1,"name":1,"type":1}
,"nested":{"container":1}
,"name":{"existing":1,"field":1,"container":1}
,"existing":{"container":1}
,"field":{"create":1,"type":1}
,"type":{"display":1,"description":1}
,"display":{"name":1}
,"(optional)":{"description":1}
,"description":{"field":1,"click":1}
}
;Search.control.loadWordPairs(pairs);
