// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"saved":1}
,"saved":{"search":1,"system":1,"user_type":1}
,"search":{"saved":1,"find":1,"navigate":1,"list":1,"click":1}
,"find":{"users":1}
,"users":{"groups":1}
,"groups":{"roles":1}
,"roles":{"hat":1,"saved":1}
,"hat":{"match":1}
,"match":{"criteria":1}
,"criteria":{"perform":1}
,"perform":{"saved":1}
,"navigate":{"correct":1,"applications":1}
,"correct":{"page":1}
,"page":{"following":1}
,"following":{"webmethods":1}
,"webmethods":{"navigate":1}
,"applications":{"administration":1}
,"administration":{"user":1,"dashboard":1}
,"user":{"management":1}
,"management":{"user_type":1,"manage":1}
,"user_type":{"saved":1,"users":1}
,"system":{"administrator":1}
,"administrator":{"administration":1}
,"dashboard":{"user":1}
,"manage":{"user_type":1}
,"list":{"choose":1}
,"choose":{"name":1}
,"name":{"saved":1}
}
;Search.control.loadWordPairs(pairs);
