// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2004-2023 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"removing":{"workspaces":1}
,"workspaces":{"navigation":1,"section":1}
,"navigation":{"pane":1,"deleted":1}
,"pane":{"longer":1,"remove":1,"navigation":1,"click":1}
,"longer":{"need":1,"listed":1}
,"need":{"access":1}
,"access":{"workspace":1}
,"workspace":{"navigat":1,"fro":1,"simply":1,"navigation":1,"wan":1}
,"navigat":{"ion":1}
,"ion":{"pane":1}
,"remove":{"remove":1,"workspace":1,"select":1}
,"fro":{"navigation":1}
,"deleted":{"workspace":1}
,"simply":{"longer":1}
,"listed":{"vigation":1}
,"vigation":{"pane":1}
,"click":{"navigate":1,"name":1}
,"navigate":{"tab":1}
,"tab":{"workspaces":1}
,"section":{"right":1}
,"right":{"click":1}
,"name":{"workspace":1}
,"wan":{"remove":1}
,"select":{"remove":1}
}
;Search.control.loadWordPairs(pairs);
