// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.xml.cachexqlqueryresults":{"whether":1}
,"whether":{"save":1}
,"save":{"reuse":1}
,"reuse":{"results":1}
,"results":{"identifying":1}
,"identifying":{"xql":1}
,"xql":{"que":1,"queries":1}
,"que":{"ries":1}
,"ries":{"executed":1}
,"executed":{"against":1}
,"against":{"xml":1}
,"xml":{"document":1}
,"document":{"during":1,"types":1}
,"during":{"docume":1}
,"docume":{"recognition":1}
,"recognition":{"several":1}
,"several":{"xml":1}
,"types":{"xql":1}
,"queries":{"setting":1}
,"setting":{"property":1}
,"property":{"improve":1,"true":1}
,"improve":{"performance":1}
,"performance":{"property":1}
,"true":{"false":1}
,"false":{"default":1}
,"default":{"true":1}
}
;Search.control.loadWordPairs(pairs);
