// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"conversationid":{"extract":1,"extracted":1}
,"extract":{"attribute":1}
,"attribute":{"want":1}
,"want":{"pass":1}
,"pass":{"document":1}
,"document":{"business":1}
,"business":{"process":1,"proces":1}
,"process":{"want":1,"model":1}
,"proces":{"add":1}
,"add":{"variable":1}
,"variable":{"pipeline":1}
,"pipeline":{"called":1}
,"called":{"prtignoredocument":1}
,"prtignoredocument":{"value":1,"true":1}
,"value":{"true":1}
,"true":{"conversationid":1,"passed":1}
,"extracted":{"prtignoredocument":1}
,"passed":{"process":1}
}
;Search.control.loadWordPairs(pairs);
