// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sending":{"large":1}
,"large":{"xml":1}
,"xml":{"documents":1,"data":1}
,"documents":{"processing":1,"trading":1,"topic":1}
,"processing":{"sure":1}
,"sure":{"trading":1}
,"trading":{"partners":1,"networks":1}
,"partners":{"$xmldata":1,"bmit":1}
,"$xmldata":{"variable":1}
,"variable":{"send":1}
,"send":{"large":1}
,"networks":{"information":1}
,"information":{"methods":1}
,"methods":{"partners":1}
,"bmit":{"xml":1}
,"topic":{"passing":1}
,"passing":{"xml":1}
,"data":{"services":1}
,"services":{"software":1}
,"software":{"designer":1}
,"designer":{"online":1}
,"online":{"help":1}
}
;Search.control.loadWordPairs(pairs);
