// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.tpa.enablelogtpa":{"whether":1}
,"whether":{"log":1}
,"log":{"auditing":1,"modify":1}
,"auditing":{"information":1}
,"information":{"activity":1}
,"activity":{"log":1}
,"modify":{"profiles":1}
,"profiles":{"data":1}
,"data":{"general":1}
,"general":{"functional":1}
,"functional":{"permissio":1}
,"permissio":{"webmethods":1}
,"webmethods":{"property":1}
,"property":{"true":1}
,"true":{"false":1}
,"false":{"default":1}
,"default":{"false":1}
}
;Search.control.loadWordPairs(pairs);
