// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.profile:getinternalidsforuser":{"retrieves":1}
,"retrieves":{"list":1}
,"list":{"partners":1,"internal":1}
,"partners":{"mapped":1,"string":1}
,"mapped":{"spec":1,"specified":1,"user":1}
,"spec":{"ified":1}
,"ified":{"user":1}
,"user":{"account":1,"name":1}
,"account":{"input":1,"service":1,"output":1,"specified":1}
,"input":{"parameters":1}
,"parameters":{"username":1,"partners":1}
,"username":{"string":1}
,"string":{"user":1,"list":1}
,"name":{"user":1}
,"service":{"returns":1}
,"returns":{"partners":1}
,"specified":{"user":1,"username":1}
,"output":{"parameters":1}
,"internal":{"ids":1}
,"ids":{"trading":1}
,"trading":{"partners":1}
}
;Search.control.loadWordPairs(pairs);
