// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"size":{"limit":1}
,"limit":{"delivering":1}
,"delivering":{"large":1}
,"large":{"documents":1,"document":1}
,"documents":{"trading":1,"document":1}
,"trading":{"networks":1}
,"networks":{"supports":1,"configuring":1}
,"supports":{"delivery":1}
,"delivery":{"large":1}
,"document":{"2gb":1,"handling":1}
,"2gb":{"(up":1}
,"(up":{"2,147,483,647":1}
,"2,147,483,647":{"bytes)":1}
,"bytes)":{"inform":1}
,"inform":{"ation":1}
,"ation":{"handling":1}
,"handling":{"large":1}
,"configuring":{"large":1}
}
;Search.control.loadWordPairs(pairs);
