// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.archive.maxrows":{"maximum":1}
,"maximum":{"number":1}
,"number":{"documents":1,"document":1}
,"documents":{"archive":1}
,"archive":{"delete":1,"deletion":1}
,"delete":{"sch":1}
,"sch":{"eduled":1}
,"eduled":{"archive":1}
,"deletion":{"property":1}
,"property":{"greater":1,"default":1}
,"greater":{"tha":1}
,"tha":{"equal":1}
,"equal":{"tn.archive.batchsize":1}
,"tn.archive.batchsize":{"property":1}
,"default":{"indicates":1}
,"indicates":{"limit":1}
,"limit":{"maximum":1}
,"document":{"archived":1}
,"archived":{"deleted":1}
,"deleted":{"scheduled":1}
,"scheduled":{"archive":1}
}
;Search.control.loadWordPairs(pairs);
