// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.profile:deleteusers":{"deletes":1}
,"deletes":{"user":1}
,"user":{"account":1,"accounts":1}
,"account":{"mappings":1,"mapping":1,"associated":1}
,"mappings":{"associated":1}
,"associated":{"trading":1,"profile":1}
,"trading":{"networks":1,"partner":1}
,"networks":{"profile":1,"created":1}
,"profile":{"trading":1,"ervice":1,"output":1}
,"created":{"user":1}
,"mapping":{"deleted":1}
,"deleted":{"user":1}
,"ervice":{"deletes":1}
,"accounts":{"input":1}
,"input":{"parameters":1}
,"parameters":{"partnerid":1,"none":1}
,"partnerid":{"string":1}
,"string":{"internal":1}
,"internal":{"identifier":1}
,"identifier":{"trading":1}
,"partner":{"profile":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
