// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.doc:updateattributes":{"updates":1}
,"updates":{"custom":1}
,"custom":{"attributes":1,"attribute":1}
,"attributes":{"document":1,"service":1}
,"document":{"database":1,"want":1,"instance":1}
,"database":{"input":1,"document":1}
,"input":{"parameters":1}
,"parameters":{"bizdoc":1,"updatecount":1}
,"bizdoc":{"object":1}
,"object":{"document":1}
,"want":{"update":1}
,"update":{"custom":1}
,"attribute":{"values":1}
,"values":{"database":1}
,"instance":{"com.wm.app.tn.doc.bizdocenvelope":1}
,"com.wm.app.tn.doc.bizdocenvelope":{"output":1}
,"output":{"parameters":1}
,"updatecount":{"string":1}
,"string":{"number":1}
,"number":{"attributes":1}
,"service":{"updated":1}
}
;Search.control.loadWordPairs(pairs);
