// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"trading":1}
,"trading":{"networks":1}
,"networks":{"transaction":1}
,"transaction":{"data":1}
,"data":{"optimize":1}
,"optimize":{"b2b":1}
}
;Search.control.loadWordPairs(pairs);
