// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"utility":1}
,"utility":{"services":1}
,"services":{"(services":1,"convert":1}
,"(services":{"wm.tn.util":1}
,"wm.tn.util":{"folder)":1}
,"folder)":{"provide":1}
,"provide":{"services":1}
,"convert":{"java.l":1}
,"java.l":{"ang.string":1}
,"ang.string":{"objects":1}
,"objects":{"formats":1}
}
;Search.control.loadWordPairs(pairs);
