// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"core":1}
,"core":{"services":1}
,"services":{"(services":1}
,"(services":{"wm.tn":1}
,"wm.tn":{"folder)":1}
,"folder)":{"perform":1}
,"perform":{"basic":1}
,"basic":{"business":1}
,"business":{"document":1}
,"document":{"exchange":1}
,"exchange":{"fun":1}
,"fun":{"ctions":1}
}
;Search.control.loadWordPairs(pairs);
