// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.delivery.active.transfer.server.aliases":{"aliases":1}
,"aliases":{"activetransfer":1,"necessary":1}
,"activetransfer":{"server":1}
,"server":{"remote":1,"instances":1,"installed":1}
,"remote":{"integration":1}
,"integration":{"server":1}
,"instances":{"aliases":1,"provide":1}
,"necessary":{"deliver":1}
,"deliver":{"documents":1}
,"documents":{"activetransfer":1}
,"installed":{"remote":1}
,"provide":{"notifications":1}
,"notifications":{"partner":1}
,"partner":{"pro":1}
,"pro":{"file":1}
,"file":{"added":1}
,"added":{"updated":1}
,"updated":{"deleted":1}
,"deleted":{"default":1}
}
;Search.control.loadWordPairs(pairs);
