// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"creating":{"contact":1,"ltiple":1}
,"contact":{"types":1,"type":1,"profile":1,"contact":1,"drop-down":1}
,"types":{"specify":1,"defined":1}
,"specify":{"contacts":1}
,"contacts":{"profiles":1,"partners":1}
,"profiles":{"need":1}
,"need":{"create":1}
,"create":{"contact":1}
,"type":{"wm.tn.dictionary:addcontacttype":1}
,"wm.tn.dictionary:addcontacttype":{"built-in":1}
,"built-in":{"service":1}
,"service":{"contact":1,"start":1}
,"defined":{"creating":1}
,"ltiple":{"contacts":1}
,"partners":{"using":1}
,"using":{"service":1}
,"start":{"showing":1}
,"showing":{"partner":1}
,"partner":{"profile":1}
,"profile":{"contact":1,"add":1}
,"add":{"contact":1}
,"drop-down":{"list":1}
}
;Search.control.loadWordPairs(pairs);
