// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"verify":{"digital":1}
,"digital":{"signature":1}
,"signature":{"pre-processing":1,"field":1}
,"pre-processing":{"action":1}
,"action":{"click":1}
,"click":{"folder":1}
,"folder":{"icon":1}
,"icon":{"next":1}
,"next":{"verify":1}
,"field":{"select":1}
,"select":{"service":1}
}
;Search.control.loadWordPairs(pairs);
