// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"creating":{"custom":1}
,"custom":{"scheduled":1}
,"scheduled":{"delivery":1}
,"delivery":{"services":1}
}
;Search.control.loadWordPairs(pairs);
