// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"revoking":{"api":1}
,"api":{"access":1}
,"access":{"partner":1,"partners":1}
,"partner":{"partner":1,"profile":1,"webmethods":1,"administration":1,"profiles":1,"apis":1}
,"profile":{"revoke":1,"tab":1}
,"revoke":{"api":1}
,"partners":{"delete":1,"partner":1}
,"delete":{"apis":1,"click":1}
,"apis":{"associated":1,"tab":1,"click":1}
,"associated":{"partners":1}
,"tab":{"revoke":1,"select":1}
,"webmethods":{"applications":1}
,"applications":{"administration":1}
,"administration":{"integration":1,"partner":1}
,"integration":{"b2b":1}
,"b2b":{"partner":1}
,"profiles":{"click":1,"page":1}
,"click":{"partner":1,"delete":1,"confirm":1,"save":1}
,"select":{"apis":1}
,"confirm":{"deletion":1}
,"deletion":{"click":1}
,"save":{"&close":1}
,"&close":{"return":1}
,"return":{"partner":1}
}
;Search.control.loadWordPairs(pairs);
