// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"selecting":{"database":1}
,"database":{"work":1,"archive":1,"select":1}
,"work":{"choose":1,"documents":1,"webmethods":1,"production":1}
,"choose":{"work":1}
,"documents":{"tasks":1}
,"tasks":{"activity":1}
,"activity":{"entries":1}
,"entries":{"available":1}
,"available":{"production":1}
,"production":{"database":1,"data":1}
,"archive":{"database":1}
,"select":{"database":1}
,"webmethods":{"monitoring":1}
,"monitoring":{"integration":1}
,"integration":{"b2b":1}
,"b2b":{"transactions":1}
,"transactions":{"datasource":1}
,"datasource":{"panel":1}
,"panel":{"data":1}
,"data":{"source":1,"archived":1}
,"source":{"field":1}
,"field":{"choose":1}
,"archived":{"data":1}
}
;Search.control.loadWordPairs(pairs);
