// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.docattr:add":{"adds":1}
,"adds":{"new":1}
,"new":{"document":1}
,"document":{"attribute":1,"inst":1}
,"attribute":{"input":1,"object":1,"add":1,"-the":1}
,"input":{"parameters":1}
,"parameters":{"attribute":1,"updatecount":1}
,"object":{"document":1}
,"add":{"document":1,"attribute":1}
,"inst":{"ance":1}
,"ance":{"subclass":1}
,"subclass":{"com.wm.app.tn.doc.bizdocattribute":1}
,"com.wm.app.tn.doc.bizdocattribute":{"output":1}
,"output":{"parameters":1}
,"updatecount":{"string":1}
,"string":{"number":1}
,"number":{"attributes":1}
,"attributes":{"service":1}
,"service":{"added":1,"add":1}
,"added":{"values":1,"attribute":1}
,"values":{"ind":1}
,"ind":{"icate":1}
,"icate":{"-the":1}
,"-the":{"service":1}
}
;Search.control.loadWordPairs(pairs);
