// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.tpa:updatecontrolnumberinlock":{"updates":1}
,"updates":{"value":1}
,"value":{"controlnumber":1,"newcontrolnumber":1}
,"controlnumber":{"within":1,"output":1}
,"within":{"locking-block":1}
,"locking-block":{"specified":1}
,"specified":{"value":1}
,"newcontrolnumber":{"integer":1,"string":1}
,"integer":{"service":1}
,"service":{"reports":1}
,"reports":{"error":1}
,"error":{"input":1,"document":1,"reported":1}
,"input":{"parameters":1}
,"parameters":{"lock":1,"error":1}
,"lock":{"object":1}
,"object":{"lock":1,"newcontrolnumber":1}
,"string":{"new":1}
,"new":{"controlnumber":1}
,"output":{"parameters":1}
,"document":{"(optional)":1}
,"(optional)":{"error":1}
,"reported":{"service":1}
}
;Search.control.loadWordPairs(pairs);
