// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.rec:queryoutput":{"contains":1}
,"contains":{"query":1}
,"query":{"execution":1,"specified":1,"results":1,"resultcount":1}
,"execution":{"details":1}
,"details":{"variables":1}
,"variables":{"queryid":1}
,"queryid":{"string":1}
,"string":{"query":1,"number":1}
,"specified":{"input":1}
,"input":{"view":1}
,"view":{"query":1}
,"results":{"cancel":1}
,"cancel":{"query":1}
,"resultcount":{"string":1}
,"number":{"records":1}
,"records":{"result":1}
,"result":{"executing":1}
,"executing":{"que":1}
}
;Search.control.loadWordPairs(pairs);
