// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.partneronboarding.enablelog":{"whether":1}
,"whether":{"log":1}
,"log":{"partner":1,"value":1,"property":1}
,"partner":{"onboarding":1}
,"onboarding":{"activity":1,"activities":1}
,"activity":{"activi":1,"activity":1,"table":1}
,"activi":{"log":1}
,"value":{"tn.partneronboarding.enablel":1,"false":1}
,"tn.partneronboarding.enablel":{"true":1}
,"true":{"logs":1,"false":1}
,"logs":{"partner":1}
,"table":{"value":1}
,"false":{"trading":1,"default":1}
,"trading":{"networks":1}
,"networks":{"log":1}
,"activities":{"activ":1}
,"activ":{"ity":1}
,"ity":{"log":1}
,"property":{"true":1}
,"default":{"true":1}
}
;Search.control.loadWordPairs(pairs);
