// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"subject":{"field":1,"email":1}
,"field":{"type":1}
,"type":{"character":1}
,"character":{"string":1}
,"string":{"subject":1}
}
;Search.control.loadWordPairs(pairs);
