// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.dictionary:changecontacttype":{"updates":1}
,"updates":{"description":1}
,"description":{"contact":1,"string":1}
,"contact":{"type":1,"type\u0027s":1}
,"type":{"input":1,"updated":1,"output":1,"annot":1}
,"input":{"parameters":1}
,"parameters":{"string":1,"none":1}
,"string":{"contact":1,"new":1}
,"updated":{"description":1}
,"new":{"description":1}
,"output":{"parameters":1}
,"none":{"usage":1}
,"usage":{"notes":1}
,"notes":{"change":1}
,"change":{"description":1,"contact":1}
,"annot":{"change":1}
}
;Search.control.loadWordPairs(pairs);
