// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.db.fetchmaxrows":{"maximum":1}
,"maximum":{"number":1}
,"number":{"result":1}
,"result":{"rows":1}
,"rows":{"return":1,"property":1}
,"return":{"query":1}
,"query":{"eturn":1}
,"eturn":{"rows":1}
,"property":{"default":1}
,"default":{"10000":1}
}
;Search.control.loadWordPairs(pairs);
