// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.db.readonly":{"trading":1}
,"trading":{"networks":1}
,"networks":{"points":1}
,"points":{"read-only":1}
,"read-only":{"database":1}
,"database":{"property":1}
,"property":{"true":1,"false":1}
,"true":{"property":1}
,"false":{"integration":1}
,"integration":{"server":1}
,"server":{"logs":1,"log":1}
,"logs":{"sql":1}
,"sql":{"exception":1}
,"exception":{"server":1}
,"log":{"file":1}
,"file":{"default":1}
,"default":{"value":1}
,"value":{"false":1}
}
;Search.control.loadWordPairs(pairs);
