// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"trading":1}
,"trading":{"networks":1}
,"networks":{"work":1}
,"work":{"webmethods":1}
,"webmethods":{"webmethods":1,"interface":1,"user":1}
,"interface":{"central":1}
,"central":{"user":1}
,"user":{"management":1,"account":1}
,"management":{"feature":1,"allows":1}
,"feature":{"central":1}
,"allows":{"integration":1}
,"integration":{"server":1}
,"server":{"credentials":1}
,"credentials":{"webmethods":1}
,"account":{"authenticate":1}
,"authenticate":{"users":1}
,"users":{"determine":1,"authorized":1}
,"determine":{"whether":1}
,"whether":{"users":1}
,"authorized":{"action":1}
}
;Search.control.loadWordPairs(pairs);
