// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"format":{"document":1}
,"document":{"type":1,"types":1}
,"type":{"option":1,"type":1,"name":1,"specify":1}
,"option":{"option":1,"invokes":1}
,"invokes":{"wm.tn.doc.xml:bizdoctorecord":1}
,"wm.tn.doc.xml:bizdoctorecord":{"built-in":1}
,"built-in":{"service":1}
,"service":{"know":1}
,"know":{"fully":1}
,"fully":{"qualified":1}
,"qualified":{"name":1}
,"name":{"document":1,"otherwise":1,"nsname":1}
,"otherwise":{"locate":1}
,"locate":{"document":1}
,"specify":{"package":1}
,"package":{"name":1}
,"nsname":{"click":1}
,"click":{"search":1}
,"search":{"browse":1}
,"browse":{"document":1}
,"types":{"listed":1}
,"listed":{"packages":1}
}
;Search.control.loadWordPairs(pairs);
