// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.store.pool.stmt":{"enables":1}
,"enables":{"caching":1}
,"caching":{"jdbc":1}
,"jdbc":{"statements":1}
,"statements":{"property":1}
,"property":{"true":1}
,"true":{"false":1,"property":1,"preparedstatements":1}
,"false":{"default":1,"preparedstatements":1}
,"default":{"true":1}
,"preparedstatements":{"cached":1}
,"cached":{"memory":1}
,"memory":{"speed":1,"instead":1}
,"speed":{"bsequent":1}
,"bsequent":{"access":1}
,"access":{"data":1}
,"data":{"database":1}
,"database":{"pro":1}
,"pro":{"perty":1}
,"perty":{"false":1}
,"instead":{"created":1}
,"created":{"every":1}
,"every":{"time":1}
,"time":{"access":1}
}
;Search.control.loadWordPairs(pairs);
