// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"sending":{"documents":1}
,"documents":{"trading":1,"sent":1}
,"trading":{"networks":1,"partner":1,"partner\u0027s":1}
,"networks":{"documents":1,"follows":1,"send":1,"trading":1,"deliver":1,"vice":1,"process":1}
,"sent":{"trading":1}
,"follows":{"trading":1}
,"partner":{"trading":1}
,"send":{"document":1}
,"document":{"trading":1,"return":1,"system":1}
,"partner\u0027s":{"trading":1}
,"deliver":{"document":1}
,"vice":{"versa":1}
,"versa":{"trading":1}
,"process":{"document":1}
,"return":{"document":1}
,"system":{"additional":1}
,"additional":{"processing":1}
}
;Search.control.loadWordPairs(pairs);
