// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.profile:getusersforpartner":{"retrieves":1}
,"retrieves":{"users":1}
,"users":{"associated":1,"array":1}
,"associated":{"trading":1,"partner":1}
,"trading":{"partner":1}
,"partner":{"input":1,"output":1}
,"input":{"parameters":1}
,"parameters":{"partnerid":1,"users":1}
,"partnerid":{"string":1}
,"string":{"internal":1}
,"internal":{"identifier":1}
,"identifier":{"trading":1}
,"output":{"parameters":1}
,"array":{"list":1}
,"list":{"user":1}
,"user":{"names":1}
,"names":{"associated":1}
}
;Search.control.loadWordPairs(pairs);
