// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.mime:processcertsonlydata":{"extracts":1}
,"extracts":{"certificates":1}
,"certificates":{"pkcs":1,"object":1,"usage":1}
,"pkcs":{"certificate-only":1}
,"certificate-only":{"s\u002Fmime":1,"information":1}
,"s\u002Fmime":{"entity":1}
,"entity":{"input":1}
,"input":{"parameters":1}
,"parameters":{"mimedata":1,"certificates":1}
,"mimedata":{"object":1}
,"object":{"mime":1,"list":1}
,"mime":{"message":1}
,"message":{"contains":1}
,"contains":{"certificate-only":1,"extracted":1}
,"information":{"output":1}
,"output":{"parameters":1,"service":1}
,"list":{"element":1}
,"element":{"contains":1}
,"extracted":{"certificates":1}
,"usage":{"notes":1}
,"notes":{"service":1}
,"service":{"compatible":1,"services":1}
,"compatible":{"services":1}
,"services":{"pub.mime":1,"wm.tn.mime":1}
,"pub.mime":{"pub.smime":1}
,"pub.smime":{"folders":1}
,"folders":{"output":1}
,"wm.tn.mime":{"folder":1}
}
;Search.control.loadWordPairs(pairs);
