// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"task":1}
,"task":{"services":1}
,"services":{"(services":1}
,"(services":{"wm.tn.task":1}
,"wm.tn.task":{"folder)":1}
,"folder)":{"manage":1}
,"manage":{"delivery":1}
,"delivery":{"tasks":1}
,"tasks":{"service":1}
,"service":{"execution":1}
,"execution":{"task":1}
}
;Search.control.loadWordPairs(pairs);
