// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.mail.from":{"email":1}
,"email":{"address":1,"immediate":1}
,"address":{"deliver":1}
,"deliver":{"documents":1}
,"documents":{"using":1}
,"using":{"email":1}
,"immediate":{"delivery":1}
,"delivery":{"method":1}
,"method":{"defaul":1}
}
;Search.control.loadWordPairs(pairs);
