// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.profile:deleteconnection":{"deletes":1}
,"deletes":{"delivery":1}
,"delivery":{"method":1}
,"method":{"partner\u0027s":1,"delete":1,"string":1}
,"partner\u0027s":{"profile":1}
,"profile":{"input":1,"output":1}
,"input":{"parameters":1}
,"parameters":{"destinationid":1,"errors":1}
,"destinationid":{"string":1}
,"string":{"internal":1,"list":1,"string":1}
,"internal":{"identifier":1}
,"identifier":{"delivery":1}
,"delete":{"partner\u0027s":1,"action":1}
,"output":{"parameters":1}
,"errors":{"string":1,"trading":1,"contains":1}
,"list":{"(optional)":1,"error":1}
,"(optional)":{"errors":1}
,"trading":{"networks":1}
,"networks":{"encountered":1,"perform":1}
,"encountered":{"deleting":1}
,"deleting":{"delivery":1}
,"error":{"errors":1}
,"contains":{"non-null":1}
,"non-null":{"value":1}
,"value":{"trading":1}
,"perform":{"delete":1}
}
;Search.control.loadWordPairs(pairs);
