// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.route:preroute":{"calls":1}
,"calls":{"wm.tn.doc:verify":1}
,"wm.tn.doc:verify":{"wm.tn.doc:persist":1}
,"wm.tn.doc:persist":{"wm.tn.doc:validate":1}
,"wm.tn.doc:validate":{"services":1}
,"services":{"input":1}
,"input":{"parameters":1}
,"parameters":{"bizdoc":1}
,"bizdoc":{"object":1}
,"object":{"recognized":1,"flags":1}
,"recognized":{"document":1}
,"document":{"want":1,"instance":1}
,"want":{"trading":1,"pre-route":1}
,"trading":{"networks":1}
,"networks":{"pre-route":1}
,"pre-route":{"document":1}
,"instance":{"com.wm.app.tn.doc.bizdocenvelope":1}
,"com.wm.app.tn.doc.bizdocenvelope":{"flags":1}
,"flags":{"object":1,"document":1}
}
;Search.control.loadWordPairs(pairs);
