// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"creating":{"external":1}
,"external":{"types":1,"ids":1,"type":1}
,"types":{"specify":1}
,"specify":{"external":1}
,"ids":{"profiles":1,"profile":1}
,"profiles":{"need":1}
,"need":{"create":1}
,"create":{"external":1}
,"type":{"wm.tn.dictionary:addidtype":1}
,"wm.tn.dictionary:addidtype":{"built-in":1}
,"built-in":{"service":1}
,"service":{"webmethods":1}
,"webmethods":{"described":1}
,"described":{"adding":1}
,"adding":{"external":1}
}
;Search.control.loadWordPairs(pairs);
