// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"adding":{"addresses":1}
,"addresses":{"profile":1,"tab":1}
,"profile":{"add":1,"partner":1,"want":1}
,"add":{"addresses":1,"address":1}
,"partner":{"profiles":1}
,"profiles":{"page":1}
,"page":{"select":1}
,"select":{"profile":1}
,"want":{"add":1}
,"address":{"click":1,"add":1,"window":1}
,"click":{"addresses":1,"add":1}
,"tab":{"click":1}
,"window":{"either":1}
,"either":{"followin":1}
,"followin":{"manually":1}
,"manually":{"fill":1}
,"fill":{"details":1}
,"details":{"fields":1}
,"fields":{"copy":1}
,"copy":{"share":1}
,"share":{"information":1}
,"information":{"already":1}
,"already":{"existing":1}
,"existing":{"address":1}
}
;Search.control.loadWordPairs(pairs);
