// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"processing":1}
,"processing":{"rule":1}
,"rule":{"longer":1,"delete":1,"removes":1}
,"longer":{"need":1}
,"need":{"processing":1}
,"delete":{"webmethods":1}
,"webmethods":{"deleting":1}
,"removes":{"entirely":1}
,"entirely":{"trading":1}
,"trading":{"networks":1}
,"networks":{"able":1}
,"able":{"recover":1}
}
;Search.control.loadWordPairs(pairs);
