// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.profile:deleteaddress":{"deletes":1}
,"deletes":{"address":1}
,"address":{"partner\u0027s":1,"delete":1}
,"partner\u0027s":{"profile":1}
,"profile":{"input":1}
,"input":{"parameters":1}
,"parameters":{"partnerid":1,"none":1}
,"partnerid":{"string":1}
,"string":{"internal":1}
,"internal":{"identifier":1}
,"identifier":{"trading":1,"address":1}
,"trading":{"partner\u2019s":1}
,"partner\u2019s":{"associated":1}
,"associated":{"address":1}
,"delete":{"addressid":1,"output":1}
,"addressid":{"string":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
