// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.tpa.cachesize":{"maximum":1}
,"maximum":{"number":1}
,"number":{"trading":1}
,"trading":{"partner":1}
,"partner":{"agreements":1}
,"agreements":{"(tpas)":1}
,"(tpas)":{"agree":1}
,"agree":{"status":1}
,"status":{"cache":1}
,"cache":{"memory":1}
,"memory":{"caching":1,"used":1}
,"caching":{"tpas":1}
,"tpas":{"speeds":1,"however":1}
,"speeds":{"runtime":1}
,"runtime":{"retrieval":1}
,"retrieval":{"tpas":1}
,"however":{"increases":1}
,"increases":{"amount":1}
,"amount":{"memory":1}
,"used":{"integration":1}
,"integration":{"server":1}
,"server":{"default":1}
,"default":{"1000":1}
}
;Search.control.loadWordPairs(pairs);
