// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.tpa:gettpainlock":{"retrieves":1}
,"retrieves":{"tpa":1}
,"tpa":{"within":1,"document":1,"idata":1}
,"within":{"locking-block":1}
,"locking-block":{"service":1}
,"service":{"vocation-or":1,"throws":1}
,"vocation-or":{"database-related":1}
,"database-related":{"errors":1}
,"errors":{"service":1}
,"throws":{"exception":1}
,"exception":{"input":1}
,"input":{"parameters":1}
,"parameters":{"lock":1,"tpa":1}
,"lock":{"object":1}
,"object":{"lock":1,"output":1,"format":1}
,"output":{"parameters":1}
,"document":{"(optional)":1,"type":1,"error":1}
,"(optional)":{"retrieved":1}
,"retrieved":{"tpa":1}
,"idata":{"object":1}
,"format":{"defined":1}
,"defined":{"wm.tn.rec:tpa":1}
,"wm.tn.rec:tpa":{"document":1}
,"type":{"error":1}
,"error":{"document":1,"reported":1}
,"reported":{"service":1}
}
;Search.control.loadWordPairs(pairs);
