// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.dictionary:addfielddefinition":{"adds":1}
,"adds":{"definition":1}
,"definition":{"new":1,"object":1,"added":1,"profilefieldmetadata":1}
,"new":{"extended":1,"field":1}
,"extended":{"profile":1}
,"profile":{"field":1}
,"field":{"input":1,"definition":1}
,"input":{"parameters":1}
,"parameters":{"definition":1,"none":1}
,"object":{"new":1,"output":1}
,"added":{"field":1}
,"profilefieldmetadata":{"object":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
