// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"opening":{"tpa":1}
,"tpa":{"editing":1,"(see":1}
,"editing":{"open":1,"webmethods":1}
,"open":{"tpa":1}
,"webmethods":{"navigate":1}
,"navigate":{"administration":1}
,"administration":{"integration":1}
,"integration":{"b2b":1}
,"b2b":{"trading":1}
,"trading":{"partner":1}
,"partner":{"agreeme":1}
,"agreeme":{"nts":1}
,"nts":{"search":1}
,"search":{"tpa":1}
,"(see":{"searching":1}
,"searching":{"assets":1}
,"assets":{"double":1}
,"double":{"click":1}
,"click":{"row":1}
,"row":{"containing":1}
,"containing":{"tpa":1}
}
;Search.control.loadWordPairs(pairs);
