// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.eda.events.completedtransactions":{"controls":1,"parameter":1}
,"controls":{"whether":1}
,"whether":{"trading":1}
,"trading":{"networks":1}
,"networks":{"publishes":1}
,"publishes":{"runtime":1,"document":1}
,"runtime":{"events":1}
,"events":{"belong":1,"group":1}
,"belong":{"transaction":1}
,"transaction":{"complete":1}
,"complete":{"events":1,"event":1}
,"group":{"tn.eda.events.completedtransactions":1}
,"parameter":{"true":1,"false":1}
,"true":{"trading":1}
,"document":{"processing":1}
,"processing":{"complete":1}
,"event":{"parameter":1,"published":1}
,"false":{"event":1}
,"published":{"default":1}
,"default":{"false":1}
}
;Search.control.loadWordPairs(pairs);
