// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.tpa:validatetpa":{"validates":1}
,"validates":{"tpa":1}
,"tpa":{"data":1,"governs":1,"output":1}
,"data":{"against":1,"schema":1}
,"against":{"tpa":1}
,"schema":{"input":1}
,"input":{"parameters":1}
,"parameters":{"senderid":1,"error":1}
,"senderid":{"string":1}
,"string":{"internal":1,"agreement":1}
,"internal":{"trading":1}
,"trading":{"partner":1}
,"partner":{"sender":1,"receive":1}
,"sender":{"role":1}
,"role":{"transaction":1}
,"transaction":{"tpa":1}
,"governs":{"receiverid":1,"agreementid":1}
,"receiverid":{"string":1}
,"receive":{"role":1}
,"agreementid":{"string":1}
,"agreement":{"tpa":1}
,"output":{"parameters":1}
,"error":{"document":1,"reported":1,"found":1}
,"document":{"list":1}
,"list":{"(optional)":1}
,"(optional)":{"error":1}
,"reported":{"service":1}
,"service":{"error":1}
,"found":{"null":1}
}
;Search.control.loadWordPairs(pairs);
