// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"administrative":1}
,"administrative":{"services":1}
,"services":{"(services":1}
,"(services":{"wm.tn.admin":1}
,"wm.tn.admin":{"folder)":1}
,"folder)":{"export":1}
,"export":{"information":1}
,"information":{"import":1,"trading":1}
,"import":{"information":1}
,"trading":{"networks":1}
,"networks":{"database":1,"properties":1}
,"database":{"retrieve":1}
,"retrieve":{"settings":1}
,"settings":{"defined":1}
,"defined":{"trading":1}
,"properties":{"trading":1,"test":1}
,"test":{"jdbc":1}
,"jdbc":{"connection":1}
,"connection":{"properties":1}
}
;Search.control.loadWordPairs(pairs);
