// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.dictionary:deleteprofilegroup":{"deletes":1}
,"deletes":{"profile":1}
,"profile":{"group":1}
,"group":{"trading":1,"deleted":1,"existing":1,"attempt":1}
,"trading":{"networks":1}
,"networks":{"input":1}
,"input":{"parameters":1}
,"parameters":{"profilegroupid":1,"none":1}
,"profilegroupid":{"string":1}
,"string":{"profile":1}
,"deleted":{"output":1}
,"output":{"parameters":1}
,"none":{"usage":1}
,"usage":{"notes":1}
,"notes":{"cannot":1}
,"cannot":{"delete":1}
,"delete":{"profile":1}
,"existing":{"partner":1}
,"partner":{"profil":1}
,"profil":{"associated":1}
,"associated":{"profile":1}
,"attempt":{"thi":1}
,"thi":{"service":1}
,"service":{"throws":1,"exception":1}
,"throws":{"service":1}
}
;Search.control.loadWordPairs(pairs);
