// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.locale.language":{"two-letter":1}
,"two-letter":{"iso":1}
,"iso":{"639":1}
,"639":{"language":1}
,"language":{"code":1,"messages":1}
,"code":{"language":1}
,"messages":{"screen":1}
,"screen":{"labels":1}
}
;Search.control.loadWordPairs(pairs);
