// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"userstatus":{"extract":1}
,"extract":{"system":1}
,"system":{"attribute":1}
,"attribute":{"want":1}
,"want":{"specify":1,"search":1}
,"specify":{"user":1}
,"user":{"atus":1,"status":1}
,"atus":{"criterion":1}
,"criterion":{"determining":1}
,"determining":{"processing":1}
,"processing":{"rule":1}
,"rule":{"document":1}
,"document":{"want":1,"type":1}
,"search":{"documents":1}
,"documents":{"document":1}
,"type":{"webmethods":1}
,"webmethods":{"based":1}
,"based":{"user":1}
}
;Search.control.loadWordPairs(pairs);
