// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"adding":{"certificate":1}
,"certificate":{"sets":1,"cannot":1}
,"sets":{"profile":1}
,"profile":{"trading":1}
,"trading":{"networks":1}
,"networks":{"needs":1,"uses":1}
,"needs":{"verify":1}
,"verify":{"digital":1}
,"digital":{"signature":1}
,"signature":{"partner":1,"pre-processing":1}
,"partner":{"(verify":1}
,"(verify":{"digital":1}
,"pre-processing":{"action)":1}
,"action)":{"first":1}
,"first":{"looks":1}
,"looks":{"partner\u2019s":1}
,"partner\u2019s":{"certificate":1}
,"cannot":{"find":1}
,"find":{"certi":1}
,"certi":{"ficate":1}
,"ficate":{"trading":1}
,"uses":{"default":1}
,"default":{"certificate":1}
}
;Search.control.loadWordPairs(pairs);
