// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"tpa":1}
,"tpa":{"delete":1,"whose":1,"trading":1,"data":1}
,"delete":{"tpa":1,"non-modifiable":1}
,"whose":{"agreement":1}
,"agreement":{"status":1,"wm.tn.tpa:deletetpa":1}
,"status":{"proposed":1}
,"proposed":{"disabled":1}
,"disabled":{"delete":1}
,"trading":{"networks":1}
,"networks":{"deletes":1}
,"deletes":{"tpa":1}
,"data":{"database":1}
,"database":{"note":1}
,"note":{"want":1}
,"want":{"delete":1}
,"non-modifiable":{"agreement":1}
,"wm.tn.tpa:deletetpa":{"built-in":1}
,"built-in":{"service":1}
}
;Search.control.loadWordPairs(pairs);
