// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.queue.enablelogqueuestartstop":{"whether":1}
,"whether":{"prevent":1}
,"prevent":{"start":1}
,"start":{"stop":1}
,"stop":{"messages":1}
,"messages":{"queues":1}
,"queues":{"eing":1,"activity":1}
,"eing":{"logged":1}
,"logged":{"activity":1}
,"activity":{"log":1}
,"log":{"table":1,"start":1}
,"table":{"val":1,"value":1,"default":1}
,"val":{"property":1}
,"property":{"true":1}
,"true":{"webmethods":1}
,"webmethods":{"trading":1}
,"trading":{"networks":1}
,"networks":{"logs":1,"log":1}
,"logs":{"start":1}
,"value":{"false":1}
,"false":{"webmethods":1}
,"default":{"true":1}
}
;Search.control.loadWordPairs(pairs);
