// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"specifying":{"criteria":1}
,"criteria":{"rule":1,"tab":1}
,"rule":{"click":1}
,"click":{"criteria":1}
,"tab":{"fill":1}
,"fill":{"fields":1}
,"fields":{"identify":1}
,"identify":{"documents":1}
,"documents":{"pro":1}
,"pro":{"cess":1}
,"cess":{"using":1}
,"using":{"rule":1}
}
;Search.control.loadWordPairs(pairs);
