// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.task.dbupdate.retrysweeptime":{"number":1}
,"number":{"seconds":1}
,"seconds":{"attempts":1}
,"attempts":{"retry":1}
,"retry":{"updating":1}
,"updating":{"dat":1}
,"dat":{"abase":1}
,"abase":{"information":1}
,"information":{"task":1}
,"task":{"trading":1}
,"trading":{"networks":1}
,"networks":{"uses":1}
,"uses":{"property":1}
,"property":{"tn.task.dbupdate.retryenabled":1,"true":1}
,"tn.task.dbupdate.retryenabled":{"property":1}
,"true":{"default":1}
,"default":{"300":1}
}
;Search.control.loadWordPairs(pairs);
