// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"defining":{"roles":1}
,"roles":{"create":1,"grant":1,"instructions":1}
,"create":{"webmethods":1}
,"webmethods":{"user":1,"users":1,"server":1}
,"user":{"accounts":1}
,"accounts":{"trading":1}
,"trading":{"networks":1}
,"networks":{"users":1,"access":1}
,"users":{"define":1,"roles":1}
,"define":{"roles":1}
,"grant":{"trading":1}
,"access":{"add":1}
,"add":{"webmethods":1}
,"instructions":{"administering":1}
,"administering":{"webmethods":1}
}
;Search.control.loadWordPairs(pairs);
