// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"performing":{"tasks":1}
,"tasks":{"deliver":1,"need":1}
,"deliver":{"document":1}
,"document":{"action":1,"delivery":1}
,"action":{"want":1,"preparing":1}
,"want":{"delivery":1}
,"delivery":{"document":1,"tasks":1}
,"preparing":{"document":1}
,"need":{"perform":1}
}
;Search.control.loadWordPairs(pairs);
