// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"editing":{"ongoing":1}
,"ongoing":{"delivery":1}
,"delivery":{"suspension":1,"schedule":1}
,"suspension":{"schedule":1}
,"schedule":{"increase":1,"following":1,"locate":1,"suspend":1,"panel":1}
,"increase":{"decrease":1}
,"decrease":{"duration":1}
,"duration":{"validity":1}
,"validity":{"ongoing":1}
,"following":{"proc":1}
,"proc":{"edure":1}
,"edure":{"edit":1}
,"edit":{"ongoing":1,"tpa":1,"end":1}
,"locate":{"ongoing":1}
,"suspend":{"delivery":1}
,"panel":{"click":1}
,"click":{"edit":1}
,"tpa":{"icon":1}
,"icon":{"edit":1}
,"end":{"time":1,"date":1}
,"time":{"end":1}
,"date":{"schedule":1}
}
;Search.control.loadWordPairs(pairs);
