// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"documentid":{"extract":1}
,"extract":{"system":1}
,"system":{"attribute":1}
,"attribute":{"want":1}
,"want":{"documen":1}
,"documen":{"determine":1}
,"determine":{"whether":1}
,"whether":{"document":1}
,"document":{"duplicate":1,"pre-processing":1,"type":1}
,"duplicate":{"(check":1,"document":1}
,"(check":{"duplicate":1}
,"pre-processing":{"action)":1}
,"action)":{"wan":1}
,"wan":{"search":1}
,"search":{"documents":1}
,"documents":{"document":1}
,"type":{"webmethods":1}
,"webmethods":{"based":1}
,"based":{"document":1}
}
;Search.control.loadWordPairs(pairs);
