// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.mime:getnumparts":{"retrieves":1}
,"retrieves":{"number":1}
,"number":{"body":1}
,"body":{"parts":1}
,"parts":{"specified":1,"output":1,"mime":1}
,"specified":{"mime":1}
,"mime":{"obj":1,"object":1,"objects":1}
,"obj":{"ect":1}
,"ect":{"input":1}
,"input":{"parameters":1}
,"parameters":{"mimedata":1,"numparts":1}
,"mimedata":{"object":1}
,"object":{"mime":1,"want":1,"usage":1}
,"want":{"retrieve":1}
,"retrieve":{"number":1}
,"output":{"parameters":1}
,"numparts":{"string":1}
,"string":{"number":1}
,"usage":{"notes":1}
,"notes":{"service":1}
,"service":{"compatible":1,"creates":1}
,"compatible":{"pub.mime":1}
,"pub.mime":{"folder":1}
,"folder":{"mime":1}
,"objects":{"pub.mime:createmimedata":1}
,"pub.mime:createmimedata":{"service":1}
,"creates":{"work":1}
,"work":{"service":1}
}
;Search.control.loadWordPairs(pairs);
