// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"archived":1}
,"archived":{"data":1}
,"data":{"partitioned":1,"artitioned":1,"softwareag_directory\u005Ccommon\u005Cdb\u005Ctradingnetworks\u005Ctradingnetworks\u005Cscripts\u005C9.8.fix1-9.9\u005Coracle\u005Cpartition_support":1,"fro":1}
,"partitioned":{"database":1}
,"database":{"following":1,"delete":1}
,"following":{"procedure":1}
,"procedure":{"delete":1}
,"delete":{"run-time":1,"archived":1}
,"run-time":{"data":1}
,"artitioned":{"database":1}
,"softwareag_directory\u005Ccommon\u005Cdb\u005Ctradingnetworks\u005Ctradingnetworks\u005Cscripts\u005C9.8.fix1-9.9\u005Coracle\u005Cpartition_support":{"edit":1}
,"edit":{"ora_tn_purge_archivedata.sql":1}
,"ora_tn_purge_archivedata.sql":{"modify":1,"delete":1}
,"modify":{"partition":1}
,"partition":{"ames":1}
,"ames":{"sample":1}
,"sample":{"script":1}
,"script":{"according":1}
,"according":{"partitions":1}
,"partitions":{"created":1}
,"created":{"run":1}
,"run":{"ora_tn_purge_archivedata.sql":1}
,"fro":{"partitioned":1}
}
;Search.control.loadWordPairs(pairs);
