// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"polling":1}
,"polling":{"services":1,"trading":1}
,"services":{"partner":1}
,"partner":{"wants":1,"directly":1,"find":1}
,"wants":{"receive":1}
,"receive":{"documents":1}
,"documents":{"polling":1,"partner":1,"available":1,"received":1}
,"trading":{"networks":1}
,"networks":{"without":1,"deliver":1,"environment":1}
,"without":{"requiring":1}
,"requiring":{"trading":1}
,"deliver":{"documents":1}
,"directly":{"allow":1}
,"allow":{"partner":1}
,"find":{"list":1}
,"list":{"documents":1}
,"available":{"local":1}
,"local":{"environment":1}
,"environment":{"remote":1,"update":1}
,"remote":{"trading":1}
,"update":{"processing":1}
,"processing":{"status":1}
,"status":{"documents":1}
,"received":{"ter":1}
,"ter":{"polling":1}
}
;Search.control.loadWordPairs(pairs);
