// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.profile:undeleteprofile":{"undeletes":1}
,"undeletes":{"profile":1}
,"profile":{"previously":1}
,"previously":{"deleted":1}
,"deleted":{"tra":1}
,"tra":{"ding":1}
,"ding":{"network":1}
,"network":{"input":1}
,"input":{"parameters":1}
,"parameters":{"partnerid":1,"none":1}
,"partnerid":{"string":1}
,"string":{"internal":1}
,"internal":{"identifier":1}
,"identifier":{"trading":1}
,"trading":{"partner":1}
,"partner":{"undelete":1}
,"undelete":{"output":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
