// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.locale.variant":{"variant":1}
,"variant":{"code":1,"list":1,"codes":1}
,"code":{"further":1,"diffe":1}
,"further":{"distinguishes":1}
,"distinguishes":{"locale":1}
,"locale":{"neces":1}
,"neces":{"sary":1}
,"sary":{"typically":1}
,"typically":{"variant":1}
,"diffe":{"rence":1}
,"rence":{"based":1}
,"based":{"platform":1}
,"platform":{"integration":1}
,"integration":{"server":1}
,"server":{"running":1}
,"running":{"need":1}
,"need":{"specify":1}
,"specify":{"variant":1}
,"list":{"important":1}
,"important":{"codes":1}
,"codes":{"first":1,"oracle":1}
,"first":{"separate":1}
,"separate":{"ith":1}
,"ith":{"underscore":1}
,"underscore":{"information":1}
,"information":{"variant":1}
,"oracle":{"documentation":1}
,"documentation":{"java.util.locale":1}
,"java.util.locale":{"class":1}
}
;Search.control.loadWordPairs(pairs);
