// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"trading":1}
,"trading":{"networks":1}
,"networks":{"run-time":1,"publish":1}
,"run-time":{"events":1}
,"events":{"organized":1,"makes":1,"enable":1,"event":1}
,"organized":{"several":1}
,"several":{"event":1}
,"event":{"groups":1,"operties":1,"properties":1}
,"groups":{"ouping":1,"chapter":1,"configure":1}
,"ouping":{"events":1}
,"makes":{"easy":1}
,"easy":{"manage":1}
,"manage":{"events":1}
,"enable":{"trading":1,"event":1,"disable":1}
,"publish":{"run-time":1}
,"operties":{"corresponding":1}
,"corresponding":{"event":1}
,"chapter":{"scribes":1}
,"scribes":{"types":1}
,"types":{"run-time":1}
,"configure":{"event":1}
,"properties":{"enable":1}
,"disable":{"events":1}
}
;Search.control.loadWordPairs(pairs);
