// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"overview":{"section":1}
,"section":{"contains":1}
,"contains":{"specifications":1}
,"specifications":{"built-in":1}
,"built-in":{"services":1}
}
;Search.control.loadWordPairs(pairs);
