// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"wm.tn.task:gettasks":{"retrieves":1,"service":1}
,"retrieves":{"tasks":1}
,"tasks":{"server":1,"string":1}
,"server":{"(the":1,"wm.tn.task:gettasks":1}
,"(the":{"server":1}
,"service":{"executes)":1}
,"executes)":{"regardless":1}
,"regardless":{"delivery":1}
,"delivery":{"status":1}
,"status":{"input":1}
,"input":{"parameters":1}
,"parameters":{"none":1,"tasks":1}
,"none":{"output":1}
,"output":{"parameters":1}
,"string":{"list":1}
,"list":{"internal":1}
,"internal":{"identifiers":1}
,"identifiers":{"tasks":1}
}
;Search.control.loadWordPairs(pairs);
