// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2007-2024 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tn.db.tnlocaldateformat":{"determines":1}
,"determines":{"timestamp":1}
,"timestamp":{"storing":1}
,"storing":{"data":1}
,"data":{"eit":1}
,"eit":{"local":1}
,"local":{"time":1}
,"time":{"zone":1}
,"zone":{"gmt":1,"default":1}
,"gmt":{"property":1,"time":1}
,"property":{"applies":1,"exist":1}
,"applies":{"documents":1}
,"documents":{"stored":1}
,"stored":{"property":1}
,"exist":{"ing":1}
,"ing":{"records":1}
,"records":{"updated":1}
,"updated":{"tn.db.tnlocaldateformat=false":1}
,"tn.db.tnlocaldateformat=false":{"uses":1}
,"uses":{"gmt":1,"local":1}
,"default":{"value":1}
,"value":{"tn.db.tnlocaldateformat=true":1}
,"tn.db.tnlocaldateformat=true":{"uses":1}
}
;Search.control.loadWordPairs(pairs);
