// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"on-premise":{"deployment":1,"using":1}
,"deployment":{"assets":1,"based":1,"commands":1}
,"assets":{"deploy":1,"on-premise":1}
,"deploy":{"universal":1}
,"universal":{"messaging":1}
,"messaging":{"assets":1}
,"using":{"command":1}
,"command":{"central":1}
,"central":{"command-line":1}
,"command-line":{"nterface":1}
,"nterface":{"on-premise":1}
,"based":{"push":1}
,"push":{"model":1}
,"model":{"information":1}
,"information":{"asset":1}
,"asset":{"deployment":1}
,"commands":{"asset":1}
}
;Search.control.loadWordPairs(pairs);
