// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"enterprise":{"developer\u0027s":1}
,"developer\u0027s":{"guide":1}
,"guide":{"universal":1,"describes":1}
,"universal":{"messaging":1}
,"messaging":{"client":1,"assumes":1,"installed":1}
,"client":{"api":1}
,"api":{"deprecated":1}
,"deprecated":{"guide":1}
,"describes":{"develop":1}
,"develop":{"deploy":1}
,"deploy":{"applicati":1}
,"applicati":{"ons":1}
,"ons":{"using":1}
,"using":{"universal":1}
,"assumes":{"already":1}
,"already":{"universal":1}
}
;Search.control.loadWordPairs(pairs);
