// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"queue":{"consumer":1}
,"consumer":{"example":1,"using":1}
,"example":{"shows":1}
,"shows":{"create":1}
,"create":{"queue":1}
,"using":{"universal":1}
,"universal":{"messaging":1}
,"messaging":{"reactive":1}
,"reactive":{"library":1}
,"library":{"application":1}
,"application":{"source":1}
,"source":{"code":1}
,"code":{"click":1,"example":1}
,"click":{"code":1}
}
;Search.control.loadWordPairs(pairs);
