// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"groups":{"add":1}
,"add":{"edit":1,"subjects":1}
,"edit":{"delete":1}
,"delete":{"security":1}
,"security":{"group":1}
,"group":{"using":1,"specify":1,"individual":1}
,"using":{"command":1}
,"command":{"central":1}
,"central":{"web":1}
,"web":{"user":1}
,"user":{"interface":1,"format":1,"@host":1}
,"interface":{"create":1}
,"create":{"group":1}
,"specify":{"name":1}
,"name":{"gro":1}
,"gro":{"add":1}
,"subjects":{"subjects":1,"existing":1}
,"existing":{"group":1}
,"individual":{"user":1}
,"format":{"user":1}
}
;Search.control.loadWordPairs(pairs);
