// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"publish":{"\u002Fsubscribe":1}
,"\u002Fsubscribe":{"using":1}
,"using":{"channel":1}
,"channel":{"topics":1}
}
;Search.control.loadWordPairs(pairs);
