// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"command":{"line":1}
,"line":{"administration":1}
,"administration":{"tools":1}
}
;Search.control.loadWordPairs(pairs);
