// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"starting":{"stopping":1}
,"stopping":{"restarting":1}
,"restarting":{"universal":1}
,"universal":{"messaging":1}
,"messaging":{"start":1,"server":1}
,"start":{"stop":1}
,"stop":{"restart":1}
,"restart":{"universal":1}
,"server":{"instance":1}
,"instance":{"instances":1,"command":1}
,"instances":{"tab":1}
,"tab":{"command":1}
,"command":{"central":1}
,"central":{"dashboard":1,"support":1}
,"dashboard":{"server":1}
,"support":{"lifecycle":1}
,"lifecycle":{"actions":1}
,"actions":{"universal":1}
}
;Search.control.loadWordPairs(pairs);
