// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"deleting":{"universal":1}
,"universal":{"messaging":1}
,"messaging":{"server":1}
,"server":{"instance":1}
,"instance":{"delete":1,"command":1,"click":1,"automati":1}
,"delete":{"server":1,"click":1,"instance":1}
,"command":{"central":1}
,"central":{"environments":1}
,"environments":{"pane":1}
,"pane":{"select":1}
,"select":{"environment":1,"installation":1,"universal":1}
,"environment":{"want":1}
,"want":{"delete":1}
,"click":{"installations":1,"instances":1,"click":1,"confirm":1,"finish":1}
,"installations":{"tab":1}
,"tab":{"select":1,"installation":1}
,"installation":{"click":1,"select":1}
,"instances":{"tab":1}
,"confirm":{"deletion":1}
,"deletion":{"click":1}
,"finish":{"windows":1}
,"windows":{"service":1}
,"service":{"associated":1}
,"associated":{"instance":1}
,"automati":{"cally":1}
,"cally":{"deleted":1}
,"deleted":{"delete":1}
}
;Search.control.loadWordPairs(pairs);
