// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"api":{"documentation":1,"docum":1,"enterprise":1,"java":1,"web":1,"javascript":1}
,"documentation":{"developers":1,"includes":1,"available":1}
,"developers":{"using":1}
,"using":{"client":1}
,"client":{"apis":1,"api":1}
,"apis":{"universal":1,"web":1,"mob":1,"apis":1,"api":1}
,"universal":{"messaging":1}
,"messaging":{"documentation":1}
,"includes":{"api":1}
,"docum":{"entation":1}
,"entation":{"enterprise":1}
,"enterprise":{"client":1}
,"web":{"client":1}
,"mob":{"ile":1}
,"ile":{"client":1}
,"available":{"fol":1}
,"fol":{"lows":1}
,"lows":{"enterprise":1}
,"java":{"enterprise":1}
}
;Search.control.loadWordPairs(pairs);
