// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"configuring":{"universal":1}
,"universal":{"messaging":1}
,"messaging":{"active\u002Fpassive":1}
,"active\u002Fpassive":{"cluster":1}
,"cluster":{"unix":1}
}
;Search.control.loadWordPairs(pairs);
