// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"java":{"client":1}
,"client":{"create":1}
,"create":{"security":1}
,"security":{"group":1}
,"group":{"example":1,"usage":1,"name>":1,"note":1}
,"example":{"demonstrates":1}
,"demonstrates":{"create":1}
,"usage":{"nmakesecgroup":1}
,"nmakesecgroup":{"<security":1}
,"<security":{"group":1}
,"name>":{"[-r]":1,"-the":1}
,"[-r]":{"<required":1}
,"<required":{"arguments>":1}
,"arguments>":{"<security":1}
,"-the":{"name":1}
,"name":{"security":1}
,"note":{"provides":1}
,"provides":{"help":1}
,"help":{"environment":1}
,"environment":{"variables":1}
,"variables":{"application":1}
,"application":{"source":1}
,"source":{"code":1}
,"code":{"click":1,"example":1}
,"click":{"code":1}
}
;Search.control.loadWordPairs(pairs);
