// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"viewing":{"queue":1}
,"queue":{"joins":1,"creating":1,"information":1}
,"joins":{"universal":1,"joins":1,"tab":1,"creating":1}
,"universal":{"messaging":1}
,"messaging":{"enables":1,"realm":1}
,"enables":{"join":1}
,"join":{"source":1}
,"source":{"channel":1}
,"channel":{"destination":1,"joins":1}
,"destination":{"queue":1}
,"creating":{"server-side":1,"channel":1}
,"server-side":{"routing":1}
,"routing":{"tables":1}
,"tables":{"wit":1}
,"wit":{"possibility":1}
,"possibility":{"apply":1}
,"apply":{"filters":1}
,"filters":{"based":1}
,"based":{"message":1}
,"message":{"content":1}
,"content":{"local":1}
,"local":{"remote":1}
,"remote":{"universal":1}
,"realm":{"view":1}
,"view":{"joins":1}
,"tab":{"queue":1}
,"information":{"working":1}
,"working":{"annel":1}
,"annel":{"joins":1}
}
;Search.control.loadWordPairs(pairs);
