// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"stopping":{"queue":1}
,"queue":{"snoop":1,"command":1,"want":1}
,"snoop":{"stop":1,"tab":1}
,"stop":{"snooping":1}
,"snooping":{"events":1,"click":1}
,"events":{"queue":1}
,"command":{"central":1}
,"central":{"environments":1}
,"environments":{"instances":1}
,"instances":{"universal-messaging-instancename":1}
,"universal-messaging-instancename":{"administration":1}
,"administration":{"queues":1}
,"queues":{"select":1}
,"select":{"queue":1}
,"want":{"stop":1}
,"click":{"snoop":1,"stop":1}
,"tab":{"click":1}
}
;Search.control.loadWordPairs(pairs);
