// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"code":{"examples":1,"learning":1,"developmen":1}
,"examples":{"section":1,"include":1}
,"section":{"provides":1}
,"provides":{"self-contained":1}
,"self-contained":{"examples":1}
,"include":{"full":1}
,"full":{"application":1}
,"application":{"source":1}
,"source":{"code":1}
,"learning":{"purposes":1}
,"purposes":{"starting":1}
,"starting":{"point":1}
,"point":{"code":1}
}
;Search.control.loadWordPairs(pairs);
