// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"license":{"keys":1,"details":1,"key":1,"file":1}
,"keys":{"view":1}
,"view":{"license":1}
,"details":{"update":1}
,"update":{"license":1}
,"key":{"trieve":1}
,"trieve":{"location":1}
,"location":{"license":1,"universal":1}
,"file":{"universal":1}
,"universal":{"messaging":1}
,"messaging":{"server":1,"license":1}
,"server":{"note":1}
,"note":{"cannot":1}
,"cannot":{"change":1}
,"change":{"location":1}
}
;Search.control.loadWordPairs(pairs);
