// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"tuning":{"linux":1}
,"linux":{"operating":1,"suggestions":1}
,"operating":{"system":1}
,"system":{"topic":1,"kernel":1}
,"topic":{"details":1,"geared":1}
,"details":{"important":1}
,"important":{"operating":1}
,"kernel":{"tings":1}
,"tings":{"considered":1}
,"considered":{"optimizing":1}
,"optimizing":{"server":1}
,"server":{"focus":1}
,"focus":{"topic":1}
,"geared":{"towards":1}
,"towards":{"red":1}
,"red":{"hat":1}
,"hat":{"enterprise":1}
,"enterprise":{"linux":1}
,"suggestions":{"synonymous":1}
,"synonymous":{"commands":1}
,"commands":{"unde":1}
,"unde":{"solaris":1}
,"solaris":{"windows":1}
,"windows":{"applied":1}
,"applied":{"similar":1}
,"similar":{"effect":1}
}
;Search.control.loadWordPairs(pairs);
