// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"universal":{"messaging":1}
,"messaging":{"client":1}
,"client":{"development":1,"apis":1,"api":1}
,"development":{"client":1}
,"apis":{"available":1,"web":1,"mobile":1}
,"available":{"wide":1,"building":1}
,"wide":{"range":1}
,"range":{"languages":1}
,"languages":{"enterprise":1}
,"enterprise":{"level":1,"client":1}
,"level":{"apis":1}
,"building":{"plications":1}
,"plications":{"web-based":1}
,"web-based":{"mobile":1}
,"mobile":{"device":1,"client":1}
,"device":{"scenarios":1}
,"scenarios":{"provide":1}
,"provide":{"client":1}
,"api":{"documentation":1}
,"documentation":{"following":1}
,"following":{"main":1}
,"main":{"headings":1}
,"headings":{"enterprise":1}
,"web":{"client":1}
}
;Search.control.loadWordPairs(pairs);
