// 
// Search index entries generated by WebWorks ePublisher
//
// Copyright (c) 2013-2022 Software AG, Darmstadt, Germany and/or Software AG USA, Inc., Reston, VA, USA, and/or its subsidiaries and/or its affiliates and/or their licensors
//
var pairs =
{
"using":{"command":1}
,"command":{"central":1}
,"central":{"manage":1,"web-user":1,"software":1,"help":1}
,"manage":{"universal":1}
,"universal":{"messaging":1}
,"messaging":{"topics":1,"provide":1,"server":1,"command":1}
,"topics":{"using":1}
,"provide":{"information":1}
,"information":{"manage":1,"working":1}
,"server":{"instances":1}
,"instances":{"configure":1}
,"configure":{"administer":1}
,"administer":{"universal":1}
,"web-user":{"interface":1}
,"interface":{"command-line":1,"general":1}
,"command-line":{"interface":1}
,"general":{"information":1}
,"working":{"command":1}
,"software":{"command":1}
}
;Search.control.loadWordPairs(pairs);
