var pairs =
{
"built-in":{"services":1,"service":1}
,"services":{"connections":1,"enable":1,"located":1,"webmethods":1,"reference":1}
,"connections":{"integration":1,"enable":1}
,"integration":{"server":1}
,"server":{"provides":1,"built-in":1}
,"provides":{"built-in":1}
,"enable":{"programmatica":1,"disa":1}
,"programmatica":{"lly":1}
,"lly":{"control":1}
,"control":{"connections":1}
,"disa":{"ble":1}
,"ble":{"connection":1}
,"connection":{"return":1,"associated":1,"adapter":1}
,"return":{"usage":1}
,"usage":{"statistics":1}
,"statistics":{"cur":1}
,"cur":{"rent":1}
,"rent":{"state":1}
,"state":{"(enabled":1}
,"(enabled":{"disabled)":1}
,"disabled)":{"error":1}
,"error":{"status":1}
,"status":{"conn":1}
,"conn":{"ection":1}
,"ection":{"services":1}
,"located":{"wmart":1}
,"wmart":{"package":1,"services":1}
,"package":{"pub.art.connection":1}
,"pub.art.connection":{"folder":1}
,"folder":{"built-in":1}
,"service":{"pub.art.service:setadapterservicenodeconnection":1,"information":1,"notification":1}
,"pub.art.service:setadapterservicenodeconnection":{"enables":1}
,"enables":{"change":1}
,"change":{"connection":1}
,"associated":{"apter":1}
,"apter":{"service":1}
,"information":{"changing":1}
,"changing":{"connection":1}
,"adapter":{"service":1}
,"notification":{"design":1}
,"design":{"time":1}
,"time":{"details":1}
,"details":{"wmart":1}
,"webmethods":{"integration":1}
,"reference":{"release":1}
}
;Search.control.loadWordPairs(pairs);
