var pairs =
{
"editing":{"adapter":1}
,"adapter":{"services":1,"service":1,"service\u0027s":1}
,"services":{"designer":1,"edit":1}
,"designer":{"edit":1,"browse":1,"displays":1,"select":1}
,"edit":{"adapter":1,"designer":1,"using":1,"complete":1}
,"service":{"designer":1,"want":1,"service":1,"template\u0027s":1,"editor":1,"select":1,"development":1,"options":1,"specific":1,"following":1}
,"browse":{"open":1}
,"open":{"adapter":1}
,"want":{"double-click":1,"edit":1}
,"double-click":{"service":1}
,"displays":{"adapter":1}
,"template\u0027s":{"adap":1}
,"adap":{"ter":1}
,"ter":{"service":1}
,"editor":{"following":1}
,"following":{"vcs":1}
,"vcs":{"integration":1,"client":1}
,"integration":{"feature":1}
,"feature":{"enabled":1,"team":1}
,"enabled":{"right-click":1,"righ":1}
,"right-click":{"service":1}
,"select":{"check":1,"lock":1,"appropriate":1,"unlock":1}
,"check":{"vcs":1,"service":1,"enter":1}
,"righ":{"t-click":1}
,"t-click":{"service":1}
,"lock":{"edit":1}
,"using":{"local":1}
,"local":{"service":1}
,"development":{"feature":1}
,"team":{"menu":1}
,"menu":{"designer":1,"depend":1}
,"appropriate":{"option":1}
,"option":{"check":1}
,"options":{"available":1}
,"available":{"team":1}
,"depend":{"vcs":1}
,"client":{"modify":1,"save":1}
,"modify":{"values":1}
,"values":{"adapter":1}
,"service\u0027s":{"parameters":1}
,"parameters":{"eded":1,"section":1}
,"eded":{"detailed":1}
,"detailed":{"descriptions":1}
,"descriptions":{"service\u0027s":1}
,"section":{"configuring":1}
,"configuring":{"service":1}
,"specific":{"ype":1}
,"ype":{"service":1}
,"complete":{"modifications":1}
,"modifications":{"save":1}
,"save":{"service":1}
,"enter":{"check-in":1}
,"check-in":{"comment":1}
,"comment":{"click":1}
,"click":{"vcs":1}
,"unlock":{"using":1}
}
;Search.control.loadWordPairs(pairs);
