var pairs =
{
"using":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"view":1,"adapters":1,"navigation":1}
,"view":{"adapter":1,"parameters":1,"connection":1}
,"adapter":{"connection":1,"jms":1}
,"connection":{"parameters":1,"param":1,"using":1,"want":1,"screen":1}
,"parameters":{"following":1,"connection":1,"onnection":1,"configuring":1}
,"following":{"procedure":1}
,"procedure":{"view":1}
,"param":{"eters":1}
,"eters":{"using":1}
,"adapters":{"menu":1}
,"menu":{"integration":1}
,"navigation":{"area":1}
,"area":{"click":1}
,"click":{"adapter":1,"down":1,"filter":1,"submit":1,"show":1,"icon":1,"return":1}
,"jms":{"sort":1,"connections":1}
,"sort":{"filter":1,"information":1}
,"filter":{"list":1,"connections":1,"filter":1,"criteria":1}
,"list":{"connections":1}
,"connections":{"appears":1,"screen":1,"connections":1,"type":1,"containing":1,"match":1,"click":1,"displayed":1,"return":1}
,"appears":{"connections":1,"listing":1}
,"screen":{"sort":1,"click":1,"displays":1,"appears":1,"information":1}
,"information":{"connections":1,"controlling":1}
,"down":{"arrows":1}
,"arrows":{"filter":1}
,"type":{"criterion":1,"*abc*in":1}
,"criterion":{"want":1}
,"want":{"filter":1,"display":1,"view":1}
,"criteria":{"box":1,"re-display":1}
,"box":{"filtering":1,"click":1}
,"filtering":{"based":1}
,"based":{"node":1}
,"node":{"name":1}
,"name":{"connectio":1}
,"connectio":{"alias":1}
,"alias":{"locate":1}
,"locate":{"connections":1}
,"containing":{"specific":1,"tring":1}
,"specific":{"alpha":1}
,"alpha":{"numeric":1}
,"numeric":{"characters":1}
,"characters":{"asterisks":1}
,"asterisks":{"(*)":1}
,"(*)":{"wildcards":1}
,"wildcards":{"exam":1}
,"exam":{"ple":1}
,"ple":{"want":1}
,"display":{"connections":1}
,"tring":{"abc":1}
,"abc":{"type":1}
,"*abc*in":{"filter":1}
,"submit":{"connections":1}
,"displays":{"connections":1,"parameters":1}
,"match":{"filter":1}
,"re-display":{"connections":1}
,"show":{"connections":1}
,"listing":{"current":1}
,"current":{"conn":1}
,"conn":{"ections":1}
,"ections":{"control":1}
,"control":{"number":1}
,"number":{"connections":1}
,"displayed":{"screen":1}
,"controlling":{"pagination":1}
,"pagination":{"connections":1}
,"icon":{"connection":1}
,"onnection":{"descriptions":1}
,"descriptions":{"connection":1}
,"configuring":{"adapter":1}
,"return":{"adapter":1,"main":1}
,"main":{"connections":1}
}
;Search.control.loadWordPairs(pairs);
