var pairs =
{
"package":{"dependency":1,"dependencies":1,"wmjmsadapter":1,"first":1,"next":1,"(s)":1,"auto":1,"connections":1,"contains":1,"packages":1,"keep":1,"dependen":1,"disabled":1,"enable":1,"depends":1,"even":1,"enabled":1,"disable":1,"information":1}
,"dependency":{"requirements":1,"associa":1,"wmart":1,"therefore":1}
,"requirements":{"guidelines":1}
,"guidelines":{"section":1,"user-defined":1}
,"section":{"contains":1}
,"contains":{"list":1,"connection":1,"connections":1}
,"list":{"dependency":1}
,"user-defined":{"packages":1,"package":1}
,"packages":{"instructions":1,"proper":1,"package":1,"contain":1,"create":1,"connect":1,"whi":1,"integration":1,"depe":1,"disabling":1,"name":1}
,"instructions":{"etting":1}
,"etting":{"package":1}
,"dependencies":{"webmethods":1,"ensure":1}
,"webmethods":{"service":1}
,"service":{"development":1}
,"development":{"help":1}
,"help":{"release":1}
,"release":{"user-defined":1}
,"associa":{"ted":1}
,"ted":{"adapter":1}
,"adapter":{"package":1,"services":1,"fined":1,"packages":1}
,"wmjmsadapter":{"(the":1,"package":1}
,"(the":{"wmjmsadapter":1}
,"wmart":{"package.)":1,"package":1}
,"package.)":{"package":1}
,"ensure":{"startup":1}
,"startup":{"integration":1}
,"integration":{"server":1}
,"server":{"automatically":1,"need":1,"allow":1}
,"automatically":{"loads":1,"integration":1}
,"loads":{"reloads":1}
,"reloads":{"packages":1}
,"proper":{"rder":1}
,"rder":{"wmart":1}
,"first":{"adapter":1}
,"next":{"user-defined":1}
,"(s)":{"last":1,"depend":1}
,"last":{"wmart":1}
,"auto":{"matically":1}
,"matically":{"installed":1}
,"installed":{"install":1}
,"install":{"integration":1}
,"need":{"manually":1}
,"manually":{"reload":1,"disable":1}
,"reload":{"wmart":1,"adapter":1,"automatically":1}
,"connections":{"adapter":1,"different":1,"two":1}
,"services":{"adapter":1,"dependenc":1,"notification":1}
,"fined":{"different":1}
,"different":{"packages":1,"adapters":1,"adapt":1,"folders":1}
,"connection":{"(s)":1,"package":1}
,"depend":{"ency":1}
,"ency":{"adapter":1}
,"contain":{"adapter":1}
,"dependenc":{"associated":1}
,"associated":{"connection":1}
,"keep":{"connections":1}
,"adapters":{"separate":1,"reload":1}
,"separate":{"packages":1}
,"create":{"interdependencies":1}
,"interdependencies":{"adapter":1}
,"two":{"different":1}
,"adapt":{"ers":1}
,"ers":{"reload":1}
,"connect":{"ions":1}
,"ions":{"adapters":1}
,"allow":{"enable":1,"disable":1}
,"enable":{"package":1,"packages":1}
,"dependen":{"package":1}
,"disabled":{"enable":1}
,"whi":{"package":1}
,"depends":{"information":1}
,"information":{"enabling":1,"disabling":1}
,"enabling":{"pack":1,"packages":1}
,"pack":{"ages":1}
,"ages":{"enabling":1}
,"disable":{"package":1,"user-defined":1,"adapter":1}
,"even":{"package":1}
,"enabled":{"dependency":1}
,"therefore":{"manually":1}
,"depe":{"ndency":1}
,"ndency":{"adapter":1}
,"disabling":{"packages":1}
,"name":{"connections":1,"provided":1}
,"notification":{"name":1}
,"provided":{"different":1}
,"folders":{"packages":1}
}
;Search.control.loadWordPairs(pairs);
