var pairs =
{
"adapter":{"service":1,"jms":1,"connections":1,"connection":1}
,"service":{"run-time":1,"invokes":1,"webmethods":1,"earlier":1,"gets":1,"uses":1,"retrieves":1,"messageconsumer":1,"places":1,"sends":1}
,"run-time":{"processing":1}
,"processing":{"following":1}
,"following":{"diagram":1}
,"diagram":{"illustrates":1}
,"illustrates":{"adapter":1}
,"jms":{"processes":1,"service":1,"provider":1,"apis":1,"destination":1,"message":1,"des":1}
,"processes":{"messageconsumer":1}
,"messageconsumer":{"messageproducer":1,"services":1}
,"messageproducer":{"messagerequ":1,"services":1}
,"messagerequ":{"estor":1}
,"estor":{"services":1}
,"services":{"run":1,"adapter":1}
,"run":{"time":1}
,"time":{"step":1}
,"step":{"description":1}
,"description":{"integration":1}
,"integration":{"server":1}
,"server":{"client":1,"perform":1,"administrator":1}
,"client":{"typically":1}
,"typically":{"using":1}
,"using":{"flow":1,"designer":1,"integration":1}
,"flow":{"java":1}
,"java":{"service":1}
,"invokes":{"adapter":1}
,"webmethods":{"integration":1}
,"perform":{"operation":1}
,"operation":{"jms":1}
,"provider":{"configured":1,"adapter":1}
,"configured":{"adapter":1}
,"earlier":{"using":1}
,"designer":{"adapter":1}
,"gets":{"connection":1}
,"connection":{"service\u0027s":1,"information":1,"earlier":1}
,"service\u0027s":{"con":1}
,"con":{"nection":1}
,"nection":{"pool":1}
,"pool":{"adapter":1}
,"connections":{"contain":1}
,"contain":{"connection":1}
,"information":{"provider":1}
,"uses":{"jms":1}
,"apis":{"operate":1}
,"operate":{"jms":1}
,"destination":{"created":1,"ollows":1}
,"created":{"enabled":1}
,"enabled":{"adapter":1}
,"administrator":{"adapter":1}
,"retrieves":{"jms":1}
,"message":{"jms":1,"queue":1}
,"des":{"tination":1}
,"tination":{"places":1}
,"places":{"jms":1,"message":1}
,"ollows":{"depending":1}
,"depending":{"type":1}
,"type":{"service":1}
,"queue":{"topic":1}
,"topic":{"messageproducer":1,"messagerequestor":1,"waits":1}
,"messagerequestor":{"services":1}
,"sends":{"message":1}
,"waits":{"reply":1}
,"reply":{"implicit":1}
,"implicit":{"temporary":1}
,"temporary":{"queue":1}
}
;Search.control.loadWordPairs(pairs);
