var pairs =
{
"requirements":{"integration":1}
,"integration":{"server":1,"servers":1}
,"server":{"cluster":1,"given":1,"versions":1,"replicated":1,"contain":1,"server":1,"unavailable":1,"replicating":1}
,"cluster":{"following":1,"integration":1,"identical":1,"version":1,"adapter":1,"handle":1}
,"following":{"table":1}
,"table":{"describes":1}
,"describes":{"requirements":1}
,"given":{"cluster":1,"request":1}
,"identical":{"example":1}
,"example":{"integration":1,"client":1}
,"versions":{"integration":1,"adapters":1}
,"version":{"ser":1,"adapter":1}
,"ser":{"vice":1}
,"vice":{"packs":1}
,"packs":{"fixes":1}
,"fixes":{"applied":1}
,"applied":{"adapter":1}
,"adapter":{"packages":1,"versions":1,"connections":1,"services":1,"service":1}
,"packages":{"adapter":1,"integration":1,"webmethods":1,"connect":1}
,"replicated":{"integration":1}
,"adapters":{"cluster":1}
,"connections":{"configure":1,"connection":1}
,"configure":{"connection":1,"specific":1}
,"connection":{"database":1,"pools":1,"pooling":1}
,"database":{"connecti":1}
,"connecti":{"appear":1}
,"appear":{"servers":1}
,"servers":{"cluster":1,"clust":1,"information":1}
,"handle":{"given":1,"request":1}
,"request":{"identically":1,"cannot":1}
,"identically":{"plan":1,"allow":1}
,"plan":{"connection":1}
,"pools":{"clustered":1}
,"clustered":{"environme":1}
,"environme":{"considerations":1}
,"considerations":{"configuring":1}
,"configuring":{"connections":1}
,"pooling":{"enabled":1}
,"enabled":{"adapter":1}
,"services":{"configure":1,"derive":1,"across":1}
,"specific":{"insertsql":1}
,"insertsql":{"adapter":1}
,"service":{"adapter":1,"appear":1,"resides":1}
,"clust":{"integration":1}
,"allow":{"different":1}
,"different":{"integration":1,"services":1}
,"contain":{"different":1}
,"derive":{"benefits":1}
,"benefits":{"clustering":1}
,"clustering":{"example":1}
,"client":{"requests":1}
,"requests":{"service":1}
,"resides":{"server":1}
,"unavailable":{"request":1}
,"cannot":{"successfully":1}
,"successfully":{"redirecte":1}
,"redirecte":{"server":1}
,"replicating":{"packages":1,"adapter":1}
,"webmethods":{"integration":1}
,"information":{"replicating":1}
,"connect":{"ions":1}
,"ions":{"adapter":1}
,"across":{"multiple":1}
,"multiple":{"integration":1}
}
;Search.control.loadWordPairs(pairs);
