var pairs =
{
"implicit":{"transactions":1,"transaction":1}
,"transactions":{"implicit":1,"integration":1,"described":1}
,"integration":{"server":1}
,"server":{"automatically":1,"starts":1}
,"automatically":{"manages":1}
,"manages":{"local":1}
,"local":{"xaresource":1}
,"xaresource":{"transaction":1}
,"transaction":{"without":1,"additi":1,"context":1,"manager":1,"note":1,"contex":1,"comple":1,"pes":1,"management":1}
,"without":{"requiring":1}
,"requiring":{"explicitly":1}
,"explicitly":{"anything":1}
,"anything":{"integration":1}
,"starts":{"completes":1,"adapter":1}
,"completes":{"implicit":1,"transaction":1}
,"additi":{"onal":1}
,"onal":{"service":1}
,"service":{"calls":1,"countered":1,"registered":1,"adapter":1,"uses":1,"development":1}
,"calls":{"required":1}
,"required":{"adapter":1}
,"adapter":{"user":1,"service":1,"servi":1,"services":1,"jms":1}
,"user":{"transaction":1}
,"context":{"transaction":1,"searched":1,"contain":1}
,"manager":{"uses":1}
,"uses":{"define":1,"connec":1}
,"define":{"unit":1}
,"unit":{"work":1}
,"work":{"starts":1}
,"countered":{"flow":1}
,"flow":{"execution":1,"invokes":1,"adapte":1,"transaction":1,"completes":1,"single":1,"contains":1}
,"execution":{"connection":1}
,"connection":{"required":1,"already":1,"registered":1,"instance":1,"flow":1,"plicit":1}
,"registered":{"newly":1,"connection":1,"adapter":1,"new":1,"transaction":1}
,"newly":{"created":1}
,"created":{"conte":1}
,"conte":{"used":1}
,"used":{"adapter":1}
,"servi":{"encountered":1}
,"encountered":{"transaction":1}
,"searched":{"connection":1}
,"already":{"registered":1}
,"connec":{"tion":1}
,"tion":{"connection":1}
,"new":{"connection":1}
,"instance":{"retrieved":1}
,"retrieved":{"registered":1}
,"note":{"top":1}
,"top":{"level":1}
,"level":{"flow":1}
,"invokes":{"flow":1}
,"adapte":{"services":1}
,"services":{"child":1,"local_transaction":1}
,"child":{"flow":1}
,"contex":{"top":1}
,"comple":{"ted":1}
,"ted":{"either":1}
,"either":{"committed":1}
,"committed":{"rolled":1}
,"rolled":{"back":1}
,"back":{"depending":1}
,"depending":{"status":1}
,"status":{"(success":1}
,"(success":{"failure)":1}
,"failure)":{"top":1}
,"single":{"transaction":1}
,"contain":{"number":1}
,"number":{"xa_tr":1}
,"xa_tr":{"ansaction":1}
,"ansaction":{"connections":1}
,"connections":{"local_transaction":1}
,"local_transaction":{"connection":1}
,"contains":{"adapter":1}
,"plicit":{"transactions":1}
,"described":{"next":1}
,"next":{"section":1}
,"section":{"information":1}
,"information":{"designing":1,"transaction":1}
,"designing":{"using":1}
,"using":{"flows":1}
,"flows":{"webmethods":1}
,"webmethods":{"service":1}
,"development":{"help":1}
,"help":{"release":1}
,"release":{"information":1}
,"pes":{"transaction":1}
,"management":{"adapter":1}
,"jms":{"connections":1}
}
;Search.control.loadWordPairs(pairs);
