var pairs =
{
"installing":{"adapter":1,"existing":1,"host":1,"module":1}
,"adapter":{"jms":1,"clustered":1,"clust":1,"existing":1,"example":1,"integration":1,"specify":1}
,"jms":{"6.1":1,"clustered":1,"webmethods":1,"provider":1,"adapter":1,"file-based":1}
,"6.1":{"sp1":1}
,"sp1":{"installing":1,"download":1,"choose":1}
,"clustered":{"environment":1}
,"environment":{"install":1,"adapter":1}
,"install":{"integration":1,"adapter":1,"documentation":1,"libraries":1,"package":1}
,"integration":{"server":1,"server_directory":1}
,"server":{"cluster":1,"shut":1,"start":1,"install":1,"8.2":1,"specify":1,"installing":1,"adapter":1,"classpath":1,"9.6":1,"instance":1,"administrator\u2019s":1}
,"cluster":{"installation":1}
,"installation":{"identical":1,"directory":1,"complete":1}
,"identical":{"information":1}
,"information":{"working":1,"using":1}
,"working":{"adapter":1}
,"clust":{"ered":1}
,"ered":{"environment":1}
,"download":{"software":1}
,"software":{"installer":1}
,"installer":{"empower":1,"wizard":1,"installs":1}
,"empower":{"product":1}
,"product":{"support":1,"selection":1}
,"support":{"web":1}
,"web":{"site":1}
,"site":{"installing":1}
,"existing":{"integration":1}
,"shut":{"down":1}
,"down":{"integration":1}
,"start":{"software":1,"host":1}
,"wizard":{"choose":1}
,"choose":{"webmethods":1,"8.2":1,"install":1}
,"webmethods":{"release":1,"installation":1,"adapter":1,"broker":1,"integration":1}
,"release":{"includes":1,"specify":1}
,"includes":{"integration":1}
,"example":{"want":1}
,"want":{"install":1,"choose":1}
,"8.2":{"choose":1,"release":1}
,"specify":{"installation":1,"webmethods":1}
,"directory":{"follows":1,"contains":1,"product":1,"installing":1,"located":1,"move":1}
,"follows":{"installing":1}
,"contains":{"host":1}
,"host":{"integration":1}
,"selection":{"list":1}
,"list":{"select":1}
,"select":{"adapters":1}
,"adapters":{"webmethods":1}
,"documentation":{"ite":1}
,"ite":{"want":1}
,"broker":{"jms":1,"client":1}
,"provider":{"webmethods":1,"client":1}
,"client":{"libraries":1}
,"libraries":{"jms":1,"want":1,"later":1,"integration":1}
,"file-based":{"jndi":1}
,"jndi":{"implementation":1,"libraries":1}
,"implementation":{"oracle":1}
,"oracle":{"jndi":1}
,"later":{"manually":1}
,"manually":{"instructions":1}
,"instructions":{"adding":1}
,"adding":{"jms":1}
,"classpath":{"software":1}
,"installs":{"adapter":1}
,"server_directory":{"\u002Fpackages":1,"\u005Cinstances\u005Cdefault\u005Cpackages":1}
,"\u002Fpackages":{"directory":1}
,"module":{"integration":1}
,"9.6":{"above":1}
,"above":{"choose":1}
,"package":{"default":1,"install":1,"repository":1,"integration":1}
,"default":{"instance":1}
,"instance":{"case":1,"ackages":1,"choice":1}
,"case":{"package":1}
,"repository":{"default":1}
,"ackages":{"directory":1}
,"located":{"integration":1}
,"\u005Cinstances\u005Cdefault\u005Cpackages":{"directory":1}
,"move":{"package":1}
,"choice":{"using":1}
,"using":{"is_instance":1}
,"is_instance":{"script":1}
,"script":{"information":1,"webmethods":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"installation":1}
,"complete":{"start":1}
}
;Search.control.loadWordPairs(pairs);
