var pairs =
{
"adapter":{"services":1,"jms":1,"service":1,"connection":1}
,"services":{"adapter":1,"enable":1,"using":1}
,"enable":{"adapter":1}
,"jms":{"initiate":1,"providers":1,"template":1,"queue":1,"provider":1,"messages":1,"message":1,"provides":1,"text":1,"object":1,"map":1,"bytes":1,"stream":1}
,"initiate":{"operations":1}
,"operations":{"interact":1}
,"interact":{"jms":1}
,"providers":{"configure":1}
,"configure":{"adapter":1,"service":1}
,"using":{"adapter":1}
,"service":{"templates":1,"configuring":1,"template":1,"lect":1,"incorporate":1,"interact":1,"etrieves":1,"convert":1,"routes":1}
,"templates":{"provided":1,"contain":1,"adapter":1}
,"provided":{"adapter":1}
,"template":{"represents":1,"enables":1,"straightforward":1,"supply":1,"description":1}
,"represents":{"specific":1}
,"specific":{"operation":1,"queue":1}
,"operation":{"example":1,"jms":1}
,"example":{"messageproducer":1}
,"messageproducer":{"template":1,"sends":1}
,"enables":{"send":1}
,"send":{"(publish)":1}
,"(publish)":{"messages":1}
,"messages":{"jms":1,"specific":1,"queue":1}
,"queue":{"topic":1,"call":1}
,"topic":{"adapter":1,"messageconsumer":1,"messagerequestor":1,"waits":1}
,"contain":{"code":1}
,"code":{"cessary":1}
,"cessary":{"perform":1}
,"perform":{"operation":1}
,"provider":{"witho":1,"xample":1}
,"witho":{"data":1}
,"data":{"specifications":1,"different":1}
,"specifications":{"provide":1,"configure":1}
,"provide":{"specifications":1}
,"configuring":{"new":1}
,"new":{"rvice":1}
,"rvice":{"adapter":1}
,"straightforward":{"sing":1}
,"sing":{"designer":1}
,"designer":{"assign":1}
,"assign":{"default":1}
,"default":{"adapter":1}
,"connection":{"service":1}
,"lect":{"adapter":1}
,"supply":{"service\u0027s":1}
,"service\u0027s":{"data":1}
,"incorporate":{"flow":1}
,"flow":{"java":1,"service":1}
,"java":{"service":1}
,"xample":{"create":1}
,"create":{"messageconsumer":1}
,"messageconsumer":{"flow":1,"receives":1}
,"etrieves":{"jms":1}
,"call":{"messaget":1,"service":1}
,"messaget":{"odocument":1}
,"odocument":{"service":1}
,"convert":{"jms":1}
,"message":{"integration":1,"data":1,"documenttotextmessage":1,"textmessagetodocument":1,"objectmessagetodocument":1,"mapmessagetodocument":1,"bytesmessagetodocument":1,"streammessagetodocument":1}
,"integration":{"server":1}
,"server":{"document":1}
,"document":{"call":1,"jms":1,"documenttoobjectmessage":1,"documenttomapmessage":1,"documenttobytesmessage":1,"documenttostreammessage":1}
,"routes":{"jms":1}
,"different":{"backend":1}
,"backend":{"resource":1}
,"resource":{"adapter":1}
,"provides":{"following":1}
,"following":{"adapter":1}
,"description":{"messageproducer":1}
,"sends":{"(publishes)":1,"jms":1}
,"(publishes)":{"jms":1}
,"receives":{"(subscribes":1}
,"(subscribes":{"to)":1}
,"to)":{"jms":1}
,"messagerequestor":{"sends":1}
,"waits":{"reply":1}
,"reply":{"jms":1}
,"documenttotextmessage":{"converts":1}
,"converts":{"integration":1,"jms":1}
,"text":{"message":1}
,"textmessagetodocument":{"converts":1}
,"documenttoobjectmessage":{"converts":1}
,"object":{"message":1}
,"objectmessagetodocument":{"converts":1}
,"documenttomapmessage":{"converts":1}
,"map":{"message":1}
,"mapmessagetodocument":{"converts":1}
,"documenttobytesmessage":{"converts":1}
,"bytes":{"message":1}
,"bytesmessagetodocument":{"converts":1}
,"documenttostreammessage":{"converts":1}
,"stream":{"message":1}
,"streammessagetodocument":{"converts":1}
}
;Search.control.loadWordPairs(pairs);
