var pairs =
{
"using":{"messageconsumer":1,"pipeline":1,"following":1}
,"messageconsumer":{"services":1,"service":1}
,"services":{"enable":1,"textmessagetodocument":1,"information":1}
,"enable":{"messageconsumer":1}
,"service":{"retrieve":1,"within":1,"designer":1,"jmstimeout":1,"waits":1,"cause":1,"contains":1,"convert":1}
,"retrieve":{"jms":1}
,"jms":{"mess":1,"destination":1,"properties":1,"headers":1,"dest":1,"message":1,"destin":1,"services":1,"essage":1}
,"mess":{"age":1}
,"age":{"queue":1}
,"queue":{"topic":1,"jms":1,"adapter":1}
,"topic":{"provide":1,"jms":1,"jmsmessageselector":1,"durable":1}
,"provide":{"values":1}
,"values":{"parameters":1,"pipeline":1,"using":1}
,"parameters":{"listed":1}
,"listed":{"below":1}
,"below":{"service\u0027s":1}
,"service\u0027s":{"input":1}
,"input":{"signature":1}
,"signature":{"configur":1}
,"configur":{"ing":1}
,"ing":{"adapter":1}
,"adapter":{"service":1,"connection":1,"jms":1}
,"within":{"flow":1}
,"flow":{"service":1}
,"designer":{"either":1}
,"either":{"map":1}
,"map":{"values":1}
,"pipeline":{"constant":1,"editor":1}
,"constant":{"values":1}
,"editor":{"parameter":1}
,"parameter":{"description\u002Faction":1,"topics":1,"true":1,"determi":1}
,"description\u002Faction":{"jmsdestination":1,"jmsmessage":1}
,"jmsdestination":{"jms":1}
,"destination":{"object":1,"jndi":1,"queue":1,"topic":1,"messageconsumer":1}
,"object":{"jms":1,"retrieved":1,"using":1}
,"jndi":{"name":1}
,"name":{"(string)":1,"note":1,"java":1}
,"(string)":{"adapter":1}
,"connection":{"configured":1}
,"configured":{"queue":1,"topic":1}
,"jmsmessageselector":{"(optional)":1}
,"(optional)":{"string":1,"parameter":1}
,"string":{"contain":1,"indicates":1,"containing":1}
,"contain":{"sql92":1}
,"sql92":{"conditional":1}
,"conditional":{"expression":1}
,"expression":{"messages":1,"delivered":1}
,"messages":{"jms":1}
,"properties":{"jms":1}
,"headers":{"match":1}
,"match":{"expression":1}
,"delivered":{"value":1}
,"value":{"null":1,"parameter":1}
,"null":{"empty":1}
,"empty":{"string":1}
,"indicates":{"message":1}
,"message":{"selector":1,"arrive":1,"object":1,"document":1}
,"selector":{"service":1}
,"jmstimeout":{"maximum":1}
,"maximum":{"length":1}
,"length":{"time":1}
,"time":{"service":1}
,"waits":{"jms":1}
,"dest":{"ination":1}
,"ination":{"message":1}
,"arrive":{"topic.isdurablesubscriber":1}
,"topic.isdurablesubscriber":{"(optional)":1}
,"topics":{"parameter":1,"subscriber":1}
,"true":{"subscriber":1}
,"subscriber":{"topic":1,"otherwise":1,"field":1}
,"durable":{"subscriber":1,"subs":1}
,"otherwise":{"field":1}
,"field":{"false":1,"subscription":1,"saved":1}
,"false":{"fault":1,"topic.jmssubscriptionname":1}
,"fault":{"false":1}
,"topic.jmssubscriptionname":{"(optional)":1}
,"subscription":{"name":1}
,"note":{"change":1}
,"change":{"field":1}
,"saved":{"service":1}
,"cause":{"doing":1,"orphaned":1}
,"doing":{"potentially":1}
,"potentially":{"cause":1}
,"orphaned":{"durable":1}
,"subs":{"criptions":1}
,"criptions":{"jms":1}
,"contains":{"following":1}
,"following":{"output":1,"adapter":1}
,"output":{"gnature":1}
,"gnature":{"parameter":1}
,"jmsmessage":{"jms":1}
,"retrieved":{"jms":1}
,"destin":{"ation":1}
,"ation":{"convert":1}
,"convert":{"document":1,"message":1}
,"document":{"jms":1}
,"textmessagetodocument":{"objectmessagetodocument":1}
,"objectmessagetodocument":{"mapmessagetodocument":1}
,"mapmessagetodocument":{"bytesmessagetodocument":1}
,"bytesmessagetodocument":{"streammessagetodocument":1}
,"streammessagetodocument":{"configuring":1}
,"configuring":{"message-to-document":1}
,"message-to-document":{"conversion":1,"service":1}
,"conversion":{"services":1}
,"information":{"jmsmessageclass":1}
,"jmsmessageclass":{"string":1}
,"containing":{"name":1}
,"java":{"class":1}
,"class":{"jms":1}
,"essage":{"value":1}
,"determi":{"message-to-document":1}
}
;Search.control.loadWordPairs(pairs);
