var pairs =
{
"considerations":{"configuring":1}
,"configuring":{"connections":1,"adapter":1}
,"connections":{"connection":1,"opened":1,"possible":1,"open":1,"adapter":1,"general":1}
,"connection":{"pooling":1,"uses":1,"pools":1,"configured":1,"initial":1,"servers":1,"across":1,"pool":1}
,"pooling":{"enabled":1}
,"enabled":{"configure":1}
,"configure":{"connection":1}
,"uses":{"connection":1}
,"pools":{"clustered":1,"webmethods":1}
,"clustered":{"environment":1}
,"environment":{"sure":1}
,"sure":{"exceed":1}
,"exceed":{"total":1,"100":1,"maximum":1}
,"total":{"number":1,"200":1}
,"number":{"connections":1,"database":1}
,"opened":{"simultaneou":1,"simultaneously":1}
,"simultaneou":{"sly":1}
,"sly":{"database":1}
,"database":{"example":1,"supports":1,"connections":1}
,"example":{"cluster":1,"consider":1}
,"cluster":{"two":1}
,"two":{"integration":1}
,"integration":{"server":1}
,"server":{"connection":1,"possible":1,"administrator\u2019s":1}
,"configured":{"database":1,"initial":1}
,"supports":{"maximum":1}
,"maximum":{"100":1,"pool":1,"number":1}
,"100":{"connections":1,"means":1,"replicate":1}
,"simultaneously":{"total":1,"database":1}
,"possible":{"time":1,"connection":1}
,"time":{"exceed":1,"information":1}
,"means":{"cannot":1}
,"cannot":{"configure":1}
,"initial":{"pool":1}
,"pool":{"size":1}
,"size":{"100":1,"maximum":1,"serve":1}
,"replicate":{"connection":1}
,"servers":{"possibly":1}
,"possibly":{"total":1}
,"200":{"connections":1}
,"consider":{"connection":1}
,"across":{"cluster":1}
,"serve":{"exceed":1}
,"open":{"time":1}
,"information":{"configuring":1,"connection":1}
,"adapter":{"jms":1}
,"jms":{"configuring":1,"connections":1}
,"general":{"information":1}
,"webmethods":{"integration":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"release":1}
}
;Search.control.loadWordPairs(pairs);
