var pairs =
{
"enabling":{"packages":1,"adapter":1}
,"packages":{"packages":1,"automatically":1,"reloaded":1,"webmethods":1,"menu":1}
,"automatically":{"enabled":1}
,"enabled":{"default":1,"column":1}
,"default":{"enable":1}
,"enable":{"package":1,"user-defined":1,"associated":1}
,"package":{"manually":1,"cause":1,"first":1,"(wmjmsadapter)":1,"open":1}
,"manually":{"following":1,"enable":1}
,"following":{"procedure":1}
,"procedure":{"note":1}
,"note":{"enabling":1}
,"adapter":{"package":1}
,"cause":{"associated":1}
,"associated":{"er-defined":1,"adapter":1}
,"er-defined":{"packages":1}
,"reloaded":{"information":1}
,"information":{"loading":1}
,"loading":{"packages":1}
,"webmethods":{"service":1}
,"service":{"development":1}
,"development":{"help":1}
,"help":{"release":1}
,"release":{"important":1}
,"important":{"manually":1}
,"user-defined":{"package":1}
,"first":{"enable":1}
,"(wmjmsadapter)":{"enable":1}
,"open":{"integration":1,"packages":1}
,"integration":{"server":1}
,"server":{"administrator":1,"displays":1}
,"administrator":{"already":1}
,"already":{"open":1}
,"menu":{"navigation":1}
,"navigation":{"area":1}
,"area":{"click":1}
,"click":{"management":1,"enabled":1}
,"management":{"click":1}
,"column":{"server":1}
,"displays":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
