var pairs =
{
"webmethods":{"integration":1}
,"integration":{"server":1}
,"server":{"clustering":1,"substantially":1,"single":1,"deliver":1,"8.2":1,"level":1,"cannot":1,"cluster":1}
,"clustering":{"clustering":1,"advanced":1,"accomplishes":1,"makes":1,"func":1,"configured":1,"following":1,"enables":1,"redirects":1,"webmethods":1,"guide":1}
,"advanced":{"feature":1}
,"feature":{"webmethods":1,"provided":1}
,"substantially":{"extends":1}
,"extends":{"reliability":1}
,"reliability":{"availability":1}
,"availability":{"scalability":1}
,"scalability":{"integration":1,"failover":1,"increase":1}
,"accomplishes":{"providing":1}
,"providing":{"infrastructure":1}
,"infrastructure":{"tools":1}
,"tools":{"deploy":1}
,"deploy":{"multiple":1}
,"multiple":{"integration":1,"servers":1}
,"single":{"virtual":1,"point":1}
,"virtual":{"server":1}
,"deliver":{"app":1}
,"app":{"lications":1}
,"lications":{"leverage":1}
,"leverage":{"architecture":1}
,"architecture":{"acti":1}
,"acti":{"vity":1}
,"vity":{"transparent":1}
,"transparent":{"client":1}
,"client":{"clustering":1}
,"makes":{"multiple":1}
,"servers":{"look":1,"thus":1}
,"look":{"behave":1}
,"behave":{"integration":1}
,"8.2":{"sp2":1}
,"sp2":{"higher":1}
,"higher":{"supports":1}
,"supports":{"caching":1}
,"caching":{"clustering":1,"mechanism":1}
,"func":{"tionality":1}
,"tionality":{"provided":1}
,"provided":{"terracotta":1,"automatically":1}
,"terracotta":{"caching":1}
,"configured":{"integration":1}
,"level":{"adapter":1}
,"adapter":{"jms":1}
,"jms":{"uses":1,"messagelistener":1}
,"uses":{"caching":1}
,"mechanism":{"enabled":1}
,"enabled":{"integration":1}
,"following":{"benefits":1}
,"benefits":{"load":1}
,"load":{"balancing":1}
,"balancing":{"feature":1}
,"automatically":{"clust":1,"redirected":1}
,"clust":{"ered":1}
,"ered":{"environment":1}
,"environment":{"allows":1,"details":1}
,"allows":{"spread":1}
,"spread":{"workload":1}
,"workload":{"sev":1}
,"sev":{"eral":1}
,"eral":{"servers":1}
,"thus":{"improving":1}
,"improving":{"performance":1}
,"performance":{"scalability":1}
,"failover":{"support":1}
,"support":{"clustering":1}
,"enables":{"avoid":1}
,"avoid":{"single":1}
,"point":{"failure":1}
,"failure":{"server":1}
,"cannot":{"handle":1}
,"handle":{"request":1}
,"request":{"becomes":1,"automatically":1}
,"becomes":{"unavailable":1}
,"unavailable":{"request":1}
,"redirected":{"server":1}
,"cluster":{"note":1}
,"note":{"webmethods":1,"adapter":1}
,"redirects":{"http":1}
,"http":{"https":1}
,"https":{"requests":1}
,"requests":{"redirect":1,"scalability":1}
,"redirect":{"ftp":1}
,"ftp":{"smtp":1}
,"smtp":{"requests":1}
,"increase":{"capacity":1}
,"capacity":{"even":1}
,"even":{"further":1}
,"further":{"adding":1}
,"adding":{"new":1}
,"new":{"chines":1}
,"chines":{"running":1}
,"running":{"webmethods":1}
,"messagelistener":{"notifications":1}
,"notifications":{"supported":1}
,"supported":{"cluste":1}
,"cluste":{"red":1}
,"red":{"environment":1}
,"details":{"webmethods":1}
,"guide":{"release":1}
}
;Search.control.loadWordPairs(pairs);
