var pairs =
{
"upgrading":{"adapter":1}
,"adapter":{"jms":1,"information":1,"installation":1}
,"jms":{"6.1":1,"installing":1,"described":1,"provider":1}
,"6.1":{"sp1":1}
,"sp1":{"upgrade":1,"back":1,"copy":1}
,"upgrade":{"adapter":1}
,"back":{"wmjmsadapter":1}
,"wmjmsadapter":{"package":1}
,"package":{"existing":1,"integration":1,"install":1}
,"existing":{"custom":1}
,"custom":{"ada":1}
,"ada":{"pter":1}
,"pter":{"packages":1}
,"packages":{"uninstall":1,"packages":1,"hat":1,"dependency":1}
,"uninstall":{"older":1,"adapter":1}
,"older":{"version":1}
,"version":{"adapter":1}
,"information":{"uninstall":1}
,"installing":{"webmethods":1,"adapter":1}
,"webmethods":{"products":1}
,"products":{"premises":1}
,"premises":{"release":1}
,"release":{"delete":1}
,"delete":{"wmjmsadapter":1,"packages":1}
,"integration":{"server_directory":1,"server":1}
,"server_directory":{"\u005Cinstances\u005Cinstance_name":1}
,"\u005Cinstances\u005Cinstance_name":{"\u005Cpackages":1,"\u005Cpackages\u005Cwmjmsadapter\u005Ccode\u005Cjars\u005Cstatic":1}
,"\u005Cpackages":{"directory":1}
,"directory":{"delete":1,"restart":1}
,"hat":{"contain":1}
,"contain":{"connections":1}
,"connections":{"services":1}
,"services":{"even":1}
,"even":{"packages":1}
,"dependency":{"wmjmsadapter":1}
,"install":{"adapter":1}
,"described":{"installing":1}
,"copy":{"jms":1}
,"provider":{"client":1}
,"client":{"libraries":1}
,"libraries":{"old":1}
,"old":{"adapter":1}
,"installation":{"integration":1}
,"\u005Cpackages\u005Cwmjmsadapter\u005Ccode\u005Cjars\u005Cstatic":{"directory":1}
,"restart":{"integration":1}
}
;Search.control.loadWordPairs(pairs);
