var pairs =
{
"deleting":{"adapter":1,"disable":1}
,"adapter":{"connections":1,"jms":1,"services":1,"service":1,"connection":1}
,"connections":{"longer":1,"using":1,"screen":1}
,"longer":{"want":1,"work":1}
,"want":{"particular":1,"delete":1}
,"particular":{"adapter":1}
,"jms":{"connection":1,"connections":1}
,"connection":{"delete":1,"adapter":1,"longer":1,"assign":1,"ada":1,"sure":1,"disabled":1,"click":1,"adapters":1,"want":1}
,"delete":{"following":1,"adapter":1,"connection":1,"integration":1}
,"following":{"instructions":1}
,"instructions":{"section":1}
,"section":{"delete":1}
,"using":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1,"function":1,"deletes":1}
,"administrator":{"delete":1,"navigation":1}
,"services":{"defined":1}
,"defined":{"connection":1}
,"work":{"however":1}
,"however":{"hange":1}
,"hange":{"connection":1}
,"service":{"uses":1,"re-use":1,"bui":1,"notification":1}
,"uses":{"delet":1}
,"delet":{"adapter":1}
,"assign":{"different":1}
,"different":{"connection":1}
,"ada":{"pter":1}
,"pter":{"service":1}
,"re-use":{"service":1}
,"bui":{"lt-in":1}
,"lt-in":{"integration":1}
,"function":{"setadapterservicenodeconnection":1}
,"setadapterservicenodeconnection":{"information":1}
,"information":{"changing":1}
,"changing":{"connection":1}
,"notification":{"design":1}
,"design":{"time":1}
,"time":{"delete":1}
,"sure":{"connection":1}
,"disabled":{"deleting":1}
,"disable":{"connection":1}
,"click":{"enabled":1,"confirm":1,"adapter":1,"icon":1}
,"enabled":{"column":1}
,"column":{"click":1,"shows":1}
,"confirm":{"enabled":1}
,"shows":{"(disabled)":1}
,"(disabled)":{"connection":1}
,"adapters":{"menu":1}
,"menu":{"integration":1}
,"navigation":{"area":1}
,"area":{"click":1}
,"screen":{"click":1}
,"icon":{"connection":1}
,"deletes":{"adapter":1}
}
;Search.control.loadWordPairs(pairs);
