var pairs =
{
"group":{"access":1,"inadvertently":1,"allow":1,"others":1}
,"access":{"control":1,"adapt":1,"services":1}
,"control":{"control":1,"development":1,"lists":1}
,"development":{"group":1,"help":1}
,"adapt":{"services":1}
,"services":{"access":1,"restricted":1}
,"lists":{"(acls)":1}
,"(acls)":{"prevent":1}
,"prevent":{"development":1}
,"inadvertently":{"updat":1}
,"updat":{"ing":1}
,"ing":{"work":1}
,"work":{"group":1}
,"allow":{"deny":1}
,"deny":{"access":1}
,"restricted":{"group":1}
,"others":{"general":1}
,"general":{"information":1}
,"information":{"assigning":1}
,"assigning":{"managing":1}
,"managing":{"acls":1}
,"acls":{"webmethods":1}
,"webmethods":{"service":1}
,"service":{"development":1}
,"help":{"release":1}
}
;Search.control.loadWordPairs(pairs);
