var pairs =
{
"configuring":{"managing":1,"adapter":1}
,"managing":{"adapter":1,"dapter":1,"packages":1}
,"adapter":{"services":1,"jms":1,"connection":1,"service":1,"serv":1,"package":1}
,"services":{"perform":1,"prepare":1,"start":1}
,"perform":{"following":1}
,"following":{"tasks":1}
,"tasks":{"configuring":1}
,"dapter":{"services":1}
,"prepare":{"configure":1}
,"configure":{"manage":1,"adapter":1}
,"manage":{"adapter":1}
,"jms":{"services":1,"connections":1}
,"start":{"integration":1,"software":1}
,"integration":{"server":1}
,"server":{"integration":1,"administrator":1,"administrator\u2019s":1}
,"administrator":{"already":1,"privileges":1,"administrative":1,"sure":1,"configure":1}
,"already":{"running":1,"done":1}
,"running":{"sure":1,"using":1}
,"sure":{"webmethods":1,"wmjmsadapter":1}
,"webmethods":{"integration":1}
,"privileges":{"access":1,"webmethods":1}
,"access":{"integration":1}
,"administrative":{"screens":1}
,"screens":{"information":1}
,"information":{"setting":1}
,"setting":{"privileges":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"release":1}
,"release":{"using":1}
,"using":{"integration":1,"designer":1}
,"wmjmsadapter":{"package":1}
,"package":{"enabled":1,"contain":1,"informati":1,"management":1}
,"enabled":{"enabling":1}
,"enabling":{"packages":1}
,"packages":{"instructions":1,"rather":1,"adapter":1}
,"instructions":{"using":1,"configuring":1}
,"connection":{"plan":1}
,"plan":{"adapter":1}
,"service":{"instructions":1,"already":1}
,"connections":{"start":1}
,"software":{"designer":1}
,"designer":{"already":1,"create":1}
,"create":{"user-defined":1}
,"user-defined":{"package":1,"packages":1}
,"contain":{"service":1}
,"done":{"configure":1}
,"serv":{"ices":1}
,"ices":{"always":1}
,"always":{"define":1}
,"define":{"user-defined":1}
,"rather":{"wmjmsadapter":1}
,"informati":{"managing":1}
}
;Search.control.loadWordPairs(pairs);
