var pairs =
{
"dynamically":{"changing":1}
,"changing":{"service\u0027s":1,"connection":1}
,"service\u0027s":{"connection":1}
,"connection":{"run":1,"defa":1,"associated":1,"adapter":1}
,"run":{"time":1,"service":1}
,"time":{"may":1}
,"may":{"run":1}
,"service":{"using":1,"service":1,"created":1,"run":1}
,"using":{"connection":1}
,"defa":{"ult":1}
,"ult":{"connection":1}
,"associated":{"service":1}
,"created":{"override":1}
,"override":{"default":1,"fault":1}
,"default":{"code":1,"override-must":1}
,"code":{"flow":1}
,"flow":{"pass":1}
,"pass":{"value":1}
,"value":{"pipeline":1}
,"pipeline":{"servi":1}
,"servi":{"ce\u0027s":1}
,"ce\u0027s":{"$connectionname":1}
,"$connectionname":{"field":1}
,"field":{"multiple":1}
,"multiple":{"instances":1}
,"instances":{"jms":1,"connections-the":1}
,"jms":{"provider":1,"destination":1}
,"provider":{"running":1}
,"running":{"dynamic":1}
,"dynamic":{"connections":1}
,"connections":{"feature":1}
,"feature":{"override":1}
,"fault":{"switch":1}
,"switch":{"instances":1}
,"connections-the":{"default":1}
,"override-must":{"jms":1}
,"destination":{"type":1}
,"type":{"(topic":1}
,"(topic":{"queue)":1}
,"queue)":{"information":1}
,"information":{"changing":1}
,"adapter":{"service":1}
}
;Search.control.loadWordPairs(pairs);
