var pairs =
{
"configuring":{"managing":1,"adapter":1}
,"managing":{"adapter":1,"dapter":1}
,"adapter":{"connections":1,"jms":1,"adapter":1}
,"connections":{"perform":1,"prepare":1,"install":1,"described":1}
,"perform":{"following":1}
,"following":{"tasks":1}
,"tasks":{"configuring":1}
,"dapter":{"connections":1}
,"prepare":{"configure":1}
,"configure":{"manage":1}
,"manage":{"adapter":1}
,"install":{"webmethods":1}
,"webmethods":{"integration":1}
,"integration":{"server":1}
,"server":{"adapter":1,"classpath":1,"administrator":1,"administrator\u2019s":1,"integration":1}
,"jms":{"machine":1,"client":1,"details":1,"administrative":1,"package":1,"connections":1}
,"machine":{"add":1}
,"add":{"jms":1}
,"client":{"libraries":1}
,"libraries":{"integration":1}
,"classpath":{"installing":1}
,"installing":{"upgrading":1}
,"upgrading":{"uninstalling":1}
,"uninstalling":{"adapter":1}
,"details":{"sure":1}
,"sure":{"webmethods":1,"wmjmsadapter":1}
,"administrator":{"privileges":1,"already":1,"sure":1}
,"privileges":{"access":1,"webmethods":1}
,"access":{"adapter":1}
,"administrative":{"screens":1}
,"screens":{"information":1}
,"information":{"setting":1,"anaging":1}
,"setting":{"user":1}
,"user":{"privileges":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"release":1}
,"release":{"start":1}
,"start":{"integration":1}
,"already":{"running":1,"done":1}
,"running":{"using":1}
,"using":{"integration":1,"designer":1}
,"wmjmsadapter":{"package":1}
,"package":{"enabled":1,"contain":1,"management":1}
,"enabled":{"enabling":1}
,"enabling":{"packages":1}
,"packages":{"instructions":1,"adapter":1}
,"instructions":{"using":1}
,"designer":{"create":1}
,"create":{"user-defined":1,"connections":1}
,"user-defined":{"package":1}
,"contain":{"connection":1}
,"connection":{"already":1}
,"done":{"information":1}
,"anaging":{"packages":1}
,"management":{"create":1}
,"described":{"configuring":1}
}
;Search.control.loadWordPairs(pairs);
