var pairs =
{
"optimize":{"infrastructure":1,"release":1}
,"infrastructure":{"data":1,"external":1}
,"data":{"collector":1,"associated":1}
,"collector":{"support":1,"monitors":1,"automatically":1}
,"support":{"adapter":1}
,"adapter":{"jms":1,"components":1}
,"jms":{"optimize":1}
,"monitors":{"system":1}
,"system":{"operational":1}
,"operational":{"data":1}
,"associated":{"webmethods":1}
,"webmethods":{"run-time":1,"optimize":1}
,"run-time":{"components":1}
,"components":{"integration":1,"optimize":1,"administering":1}
,"integration":{"server":1}
,"server":{"broker":1,"infrastructure":1,"information":1}
,"broker":{"server":1,"adapters":1}
,"adapters":{"reports":1,"installed":1}
,"reports":{"status":1}
,"status":{"components":1}
,"external":{"tools":1}
,"tools":{"start":1}
,"start":{"monitoring":1}
,"monitoring":{"integration":1,"art-based":1}
,"automatically":{"starts":1}
,"starts":{"monitoring":1}
,"art-based":{"adapters":1}
,"installed":{"integration":1}
,"information":{"monitored":1}
,"monitored":{"key":1,"adapter":1}
,"key":{"performance":1}
,"performance":{"indicators":1}
,"indicators":{"(kpis)":1}
,"(kpis)":{"collected":1}
,"collected":{"monitored":1}
,"administering":{"webmethods":1}
}
;Search.control.loadWordPairs(pairs);
