var pairs =
{
"configuring":{"messageconsumer":1,"managing":1,"input\u002Foutput":1}
,"messageconsumer":{"services":1,"service":1,"template":1}
,"services":{"messageconsumer":1,"based":1,"enable":1,"designer":1,"provide":1,"using":1,"configured":1,"start":1,"instructions":1}
,"service":{"enables":1,"invoke":1,"messageconsumer":1,"combination":1,"etrieve":1,"review":1,"conta":1,"select":1,"click":1,"created":1,"editor":1,"properties":1,"template":1,"provide":1,"pipeline":1,"information":1,"development":1}
,"enables":{"synchronously":1}
,"synchronously":{"rec":1}
,"rec":{"eive":1}
,"eive":{"messages":1}
,"messages":{"jms":1,"docum":1,"multiple":1}
,"jms":{"destination":1,"services":1,"messages":1,"destinations":1,"adapter":1}
,"destination":{"(queue\u002Ftopic)":1,"type":1}
,"(queue\u002Ftopic)":{"conf":1}
,"conf":{"igure":1}
,"igure":{"messageconsumer":1}
,"based":{"specific":1}
,"specific":{"adapter":1}
,"adapter":{"con":1,"jms":1,"services":1,"service":1,"type":1,"connection":1,"settings":1,"name":1,"connec":1}
,"con":{"nections":1}
,"nections":{"follow":1}
,"follow":{"steps":1}
,"steps":{"section":1,"configuring":1}
,"section":{"conf":1}
,"invoke":{"flow":1}
,"flow":{"java":1}
,"java":{"service":1}
,"combination":{"adapter":1}
,"enable":{"convert":1}
,"convert":{"jms":1}
,"docum":{"ents":1}
,"ents":{"within":1}
,"within":{"services":1,"service":1}
,"designer":{"messageconsumer":1,"right-click":1,"using":1}
,"provide":{"values":1}
,"values":{"service\u0027s":1,"sig":1}
,"service\u0027s":{"input":1,"associated":1}
,"input":{"signature":1,"output":1,"within":1}
,"signature":{"pipeline":1}
,"pipeline":{"informat":1,"designer":1}
,"informat":{"ion":1}
,"ion":{"using":1}
,"using":{"messageconsumer":1,"ada":1}
,"configured":{"messageconsumer":1}
,"etrieve":{"messages":1}
,"multiple":{"jms":1}
,"destinations":{"provided":1,"available":1}
,"provided":{"jms":1}
,"available":{"using":1,"templates":1}
,"ada":{"pter":1}
,"pter":{"connection":1}
,"connection":{"configure":1,"name":1}
,"configure":{"messageconsumer":1}
,"review":{"steps":1}
,"managing":{"adapter":1}
,"start":{"designer":1}
,"right-click":{"package":1}
,"package":{"service":1}
,"conta":{"ined":1}
,"ined":{"select":1}
,"select":{"new":1,"parent":1,"adapter":1,"appropriate":1,"messageconsumer":1,"file":1}
,"new":{"adapter":1}
,"parent":{"namespace":1}
,"namespace":{"type":1}
,"type":{"name":1,"click":1,"field":1}
,"name":{"adapter":1,"click":1}
,"click":{"next":1,"finish":1}
,"next":{"select":1,"list":1}
,"appropriate":{"adapter":1}
,"list":{"available":1}
,"templates":{"select":1}
,"template":{"click":1,"necessary":1}
,"finish":{"service":1}
,"created":{"parameters":1}
,"parameters":{"controls":1}
,"controls":{"isplayed":1}
,"isplayed":{"adapter":1}
,"editor":{"select":1}
,"settings":{"tab":1,"audit":1}
,"tab":{"time":1,"destination":1,"shows":1}
,"time":{"confirm":1}
,"confirm":{"adapter":1}
,"properties":{"adapter":1}
,"necessary":{"receive":1}
,"receive":{"message":1}
,"message":{"tab":1}
,"field":{"populated":1}
,"populated":{"either":1}
,"either":{"topic":1}
,"topic":{"queue":1}
,"queue":{"lue":1}
,"lue":{"determined":1}
,"determined":{"service\u0027s":1}
,"associated":{"adapter":1}
,"connec":{"tion":1}
,"tion":{"input\u002Foutput":1}
,"input\u002Foutput":{"tab":1,"settings":1}
,"shows":{"service\u0027s":1}
,"output":{"signatures":1}
,"signatures":{"messageconsumer":1}
,"sig":{"nature":1}
,"nature":{"input":1}
,"instructions":{"using":1}
,"information":{"configuring":1}
,"audit":{"permissions":1}
,"permissions":{"results":1}
,"results":{"tabs":1}
,"tabs":{"webmethods":1}
,"webmethods":{"service":1}
,"development":{"help":1}
,"help":{"release":1}
,"release":{"select":1}
,"file":{"save":1}
}
;Search.control.loadWordPairs(pairs);
