var pairs =
{
"architecture":{"components":1}
,"components":{"adapter":1}
,"adapter":{"jms":1,"connections":1,"services":1,"notification":1,"connection":1,"service":1,"notifications":1}
,"jms":{"enables":1,"providers":1,"messagelistener":1,"interfaces":1,"provider":1,"apis":1,"services":1,"installed":1,"wmart":1,"adapter":1,"delivered":1,"provides":1,"connect":1,"connections":1,"connection":1,"produce":1,"destinations":1,"listen":1,"notifications":1,"uses":1,"api":1,"jms":1,"retrieve":1,"dictate":1,"ovider":1,"supports":1}
,"enables":{"configure":1}
,"configure":{"following":1,"manage":1,"adapter":1,"objects":1}
,"following":{"components":1,"diagram":1}
,"connections":{"enable":1,"adapter":1,"jndi":1,"using":1,"underlying":1}
,"enable":{"webmethods":1,"configure":1,"adapter":1,"confi":1,"application":1}
,"webmethods":{"product":1,"integration":1}
,"product":{"suite":1}
,"suite":{"connect":1,"6.x":1}
,"connect":{"jms":1}
,"providers":{"run":1,"using":1,"configure":1,"information":1,"publish":1,"adapter":1}
,"run":{"time":1}
,"time":{"adapter":1,"data":1}
,"services":{"perform":1,"provided":1,"adapter":1,"webmethods":1,"adap":1,"enable":1,"jndi":1,"designer":1,"templates":1,"notifications":1}
,"perform":{"operations":1}
,"operations":{"jms":1}
,"using":{"built-in":1,"jms":1,"integration":1,"adapter":1}
,"built-in":{"services":1}
,"provided":{"adapter":1,"jms":1}
,"messagelistener":{"notifications":1}
,"notifications":{"provide":1,"adapter":1,"enable":1,"jndi":1,"designer":1,"jms":1,"associated":1}
,"provide":{"asynchronous":1}
,"asynchronous":{"notifica":1}
,"notifica":{"tion":1}
,"tion":{"messages":1}
,"messages":{"queues":1,"jms":1,"receive":1,"queue":1}
,"queues":{"topics":1,"application":1}
,"topics":{"following":1,"application":1}
,"diagram":{"illustrates":1,"descriptions":1}
,"illustrates":{"adapter":1}
,"interfaces":{"jms":1,"enable":1}
,"provider":{"using":1,"adapter":1,"publish":1}
,"apis":{"following":1,"adapter":1,"interface":1}
,"descriptions":{"different":1}
,"different":{"architectural":1,"types":1}
,"architectural":{"eces":1}
,"eces":{"involved":1}
,"involved":{"integration":1}
,"integration":{"process":1,"server":1}
,"process":{"detailed":1}
,"detailed":{"description":1}
,"description":{"run":1,"adapter":1,"dapter":1}
,"data":{"flow":1}
,"flow":{"different":1}
,"types":{"adapter":1}
,"server":{"adapter":1,"wmart":1,"functionality":1,"run-time":1,"administrator":1}
,"installed":{"runs":1,"integration":1}
,"runs":{"integration":1}
,"wmart":{"package":1}
,"package":{"wmart":1,"provides":1,"installed":1,"called":1}
,"provides":{"common":1,"integration":1,"adapter":1}
,"common":{"framework":1}
,"framework":{"webmethods":1}
,"6.x":{"later":1}
,"later":{"adapters":1}
,"adapters":{"utilize":1}
,"utilize":{"integration":1}
,"functionality":{"making":1}
,"making":{"integration":1}
,"run-time":{"environment":1}
,"environment":{"adapter":1}
,"delivered":{"single":1}
,"single":{"package":1}
,"called":{"wmjmsadapter":1}
,"wmjmsadapter":{"adapter":1}
,"administrator":{"designer":1,"detailed":1}
,"designer":{"user":1,"using":1}
,"user":{"interfaces":1}
,"manage":{"ada":1}
,"ada":{"pter":1}
,"pter":{"connections":1}
,"notification":{"adapter":1,"template":1,"templates":1}
,"connection":{"templates":1,"configure":1,"factorie":1}
,"templates":{"adapter":1,"enable":1,"detailed":1}
,"adap":{"ter":1}
,"ter":{"notifications":1}
,"jndi":{"look":1,"naming":1}
,"look":{"jms":1}
,"factorie":{"configure":1}
,"service":{"templates":1,"adapter":1,"configure":1,"administrative":1}
,"produce":{"consume":1}
,"consume":{"messages":1}
,"destinations":{"(queu":1,"configure":1,"ueues":1,"(queues":1}
,"(queu":{"topics)":1}
,"topics)":{"adapter":1,"jms":1}
,"confi":{"gure":1}
,"gure":{"adapter":1}
,"dapter":{"services":1}
,"template":{"adapter":1,"enables":1}
,"listen":{"retrieve":1}
,"retrieve":{"messages":1,"configured":1}
,"ueues":{"topics)":1}
,"uses":{"jms":1}
,"interface":{"jms":1}
,"information":{"jms":1}
,"api":{"libraries":1}
,"libraries":{"apter":1}
,"apter":{"requires":1}
,"requires":{"installing":1}
,"installing":{"upgrading":1}
,"upgrading":{"uninstalling":1}
,"uninstalling":{"adapter":1}
,"associated":{"specific":1}
,"specific":{"jms":1}
,"(queues":{"topics)":1}
,"configured":{"connectionfactory":1}
,"connectionfactory":{"destination":1,"class":1}
,"destination":{"lass":1,"entities":1,"class":1}
,"lass":{"objects":1}
,"objects":{"jndi-supported":1,"ese":1,"identify":1}
,"jndi-supported":{"naming":1}
,"naming":{"service":1}
,"dictate":{"jms":1}
,"publish":{"connecti":1,"objects":1,"subscribe":1}
,"connecti":{"factory":1}
,"factory":{"message":1}
,"message":{"destination":1}
,"entities":{"however":1}
,"however":{"sup":1}
,"sup":{"ports":1}
,"ports":{"jms":1}
,"ese":{"classes":1}
,"classes":{"register":1}
,"register":{"jndi":1}
,"administrative":{"tools":1}
,"tools":{"provided":1}
,"ovider":{"connectionfactory":1}
,"class":{"exposes":1,"objects":1}
,"exposes":{"methods":1}
,"methods":{"enable":1}
,"application":{"establish":1,"may":1}
,"establish":{"connections":1}
,"underlying":{"mes":1}
,"mes":{"saging":1}
,"saging":{"system":1}
,"system":{"destination":1}
,"identify":{"topics":1}
,"may":{"publish":1,"send":1}
,"subscribe":{"topic":1}
,"topic":{"queues":1}
,"send":{"messages":1}
,"receive":{"messages":1}
,"queue":{"complete":1}
,"complete":{"list":1}
,"list":{"jms":1}
,"supports":{"installing":1}
}
;Search.control.loadWordPairs(pairs);
