var pairs =
{
"using":{"exactly":1}
,"exactly":{"once":1}
,"once":{"notification":1,"feature":1}
,"notification":{"feature":1,"data":1,"used":1}
,"feature":{"adapter":1,"feature":1,"ensures":1,"enable":1,"notification":1}
,"adapter":{"notifications":1}
,"notifications":{"exactly":1}
,"ensures":{"notification":1}
,"data":{"duplicated":1}
,"duplicated":{"even":1}
,"even":{"failure":1}
,"failure":{"occurs":1,"integration":1}
,"occurs":{"during":1}
,"during":{"processing":1}
,"processing":{"achieved":1,"failure":1}
,"achieved":{"assigning":1}
,"assigning":{"unique":1}
,"unique":{"ids":1}
,"ids":{"publishabl":1,"exactly":1}
,"publishabl":{"document":1}
,"document":{"processing":1,"associated":1}
,"integration":{"server":1}
,"server":{"checks":1,"details":1,"administrator\u2019s":1}
,"checks":{"duplicate":1}
,"duplicate":{"records":1}
,"records":{"storage":1}
,"storage":{"ignores":1}
,"ignores":{"dup":1}
,"dup":{"licate":1}
,"licate":{"ids":1}
,"enable":{"client-side":1}
,"client-side":{"queuing":1}
,"queuing":{"integration":1}
,"details":{"webmethods":1}
,"webmethods":{"integration":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"release":1}
,"release":{"note":1}
,"note":{"feature":1}
,"used":{"publish":1}
,"publish":{"document":1}
,"associated":{"service":1}
}
;Search.control.loadWordPairs(pairs);
