var pairs =
{
"package":{"management":1,"called":1,"manage":1,"integration":1,"dependencies":1,"dependency":1}
,"management":{"adapter":1,"understand":1}
,"adapter":{"jms":1,"package":1,"services":1}
,"jms":{"provided":1,"package":1,"clustered":1}
,"provided":{"package":1}
,"called":{"wmjmsadapter":1}
,"wmjmsadapter":{"manage":1}
,"manage":{"adapter":1,"package":1,"packages":1,"connections":1}
,"integration":{"server":1}
,"server":{"several":1,"described":1,"works":1}
,"several":{"considerations":1}
,"considerations":{"regarding":1}
,"regarding":{"manage":1}
,"packages":{"integration":1,"connections":1,"details":1,"disabling":1}
,"described":{"following":1}
,"following":{"list":1}
,"list":{"create":1}
,"create":{"user-defined":1}
,"user-defined":{"packages":1}
,"connections":{"adapte":1,"apter":1}
,"adapte":{"services":1}
,"services":{"details":1,"det":1}
,"details":{"adapter":1,"package":1,"group":1,"enabling":1}
,"understand":{"package":1,"clustering":1}
,"dependencies":{"work":1}
,"work":{"bes":1}
,"bes":{"decisions":1}
,"decisions":{"regarding":1}
,"apter":{"services":1}
,"dependency":{"requirements":1}
,"requirements":{"guidelines":1}
,"guidelines":{"control":1}
,"control":{"groups":1,"understand":1}
,"groups":{"access":1}
,"access":{"adapter":1,"control":1}
,"group":{"access":1}
,"clustering":{"advanced":1}
,"advanced":{"feature":1}
,"feature":{"webmethods":1}
,"webmethods":{"integration":1}
,"works":{"effectively":1}
,"effectively":{"manage":1}
,"det":{"ails":1}
,"ails":{"adapter":1}
,"clustered":{"environment":1}
,"environment":{"enable":1}
,"enable":{"disable":1}
,"disable":{"packages":1}
,"enabling":{"packages":1}
,"disabling":{"packages":1}
}
;Search.control.loadWordPairs(pairs);
