var pairs =
{
"editing":{"adapter":1,"disabling":1}
,"adapter":{"connections":1,"jms":1}
,"connections":{"login":1,"using":1,"instructions":1,"screen":1,"click":1}
,"login":{"information":1}
,"information":{"server":1}
,"server":{"changes":1,"update":1,"administrator":1}
,"changes":{"wan":1,"save":1}
,"wan":{"redefine":1}
,"redefine":{"parameters":1}
,"parameters":{"connection":1,"edit":1,"typ":1,"configuring":1}
,"connection":{"uses":1,"sure":1,"disabled":1,"want":1,"screen":1,"update":1,"parameters":1,"return":1,"edited":1}
,"uses":{"connect":1}
,"connect":{"ing":1}
,"ing":{"server":1,"selecting":1}
,"update":{"connection\u0027s":1}
,"connection\u0027s":{"parameters":1}
,"edit":{"adapter":1,"connection":1,"edit":1}
,"using":{"integration":1}
,"integration":{"server":1}
,"administrator":{"edit":1,"navigation":1}
,"sure":{"connection":1}
,"disabled":{"editing":1}
,"disabling":{"adapter":1}
,"instructions":{"adapters":1,"enabling":1}
,"adapters":{"menu":1}
,"menu":{"integration":1}
,"navigation":{"area":1}
,"area":{"click":1}
,"click":{"adapter":1,"icon":1,"save":1}
,"jms":{"connections":1}
,"screen":{"click":1,"displays":1,"enable":1}
,"icon":{"connection":1}
,"want":{"edit":1,"specify":1}
,"displays":{"current":1}
,"current":{"parameters":1}
,"typ":{"ing":1}
,"selecting":{"values":1}
,"values":{"want":1}
,"specify":{"descriptions":1}
,"descriptions":{"connection":1}
,"configuring":{"adapter":1}
,"save":{"changes":1,"connection":1}
,"return":{"connections":1}
,"enable":{"connection":1}
,"edited":{"instructions":1}
,"enabling":{"adapter":1}
}
;Search.control.loadWordPairs(pairs);
