var pairs =
{
"pub.art.transaction:starttransaction":{"service":1}
,"service":{"starts":1,"pub.art.transaction:rollbacktransaction":1,"corresponding":1,"flow":1,"receive":1,"just":1}
,"starts":{"explicit":1}
,"explicit":{"transaction":1,"transactio":1}
,"transaction":{"used":1,"management":1,"started":1,"name":1,"service":1}
,"used":{"conjunction":1}
,"conjunction":{"either":1}
,"either":{"pub.art.transaction:committransaction":1}
,"pub.art.transaction:committransaction":{"service":1}
,"pub.art.transaction:rollbacktransaction":{"service":1}
,"corresponding":{"pub.art.transaction:committransaction":1}
,"flow":{"service":1}
,"receive":{"run-time":1}
,"run-time":{"error":1}
,"error":{"transaction":1}
,"management":{"overview":1}
,"overview":{"information":1}
,"information":{"implicit":1}
,"implicit":{"explicit":1}
,"transactio":{"input":1}
,"input":{"parameters":1}
,"parameters":{"starttransactioninput":1,"starttransactionoutput":1}
,"starttransactioninput":{"document":1}
,"document":{"document":1,"contains":1}
,"contains":{"variable":1}
,"variable":{"transactionname":1}
,"transactionname":{"described":1,"string":1}
,"described":{"below":1}
,"below":{"transactionname":1}
,"string":{"specifies":1,"name":1}
,"specifies":{"name":1}
,"name":{"transaction":1,"implementations":1,"inpu":1}
,"started":{"arameter":1}
,"arameter":{"optional":1}
,"optional":{"leave":1}
,"leave":{"parameter":1}
,"parameter":{"blank":1}
,"blank":{"integration":1}
,"integration":{"server":1}
,"server":{"generate":1}
,"generate":{"name":1}
,"implementations":{"necessary":1}
,"necessary":{"provide":1}
,"provide":{"transaction":1}
,"inpu":{"output":1}
,"output":{"parameters":1}
,"starttransactionoutput":{"document":1}
,"just":{"started":1}
}
;Search.control.loadWordPairs(pairs);
