var pairs =
{
"adapter":{"jms":1,"services":1,"otifications":1,"notifications":1}
,"jms":{"package":1,"provided":1}
,"package":{"management":1,"called":1,"manage":1,"integration":1,"doing":1,"easily":1,"wmjmsadapter":1,"dependencies":1,"dependency":1}
,"management":{"adapter":1,"functionality":1,"tasks":1}
,"provided":{"package":1,"designer":1}
,"called":{"wmjmsadapter":1}
,"wmjmsadapter":{"manage":1,"package":1,"pac":1}
,"manage":{"wmjmsadapter":1,"package":1}
,"integration":{"server":1}
,"server":{"create":1}
,"create":{"connections":1,"user-defined":1}
,"connections":{"adapter":1}
,"services":{"adapter":1}
,"otifications":{"define":1}
,"define":{"user-defined":1}
,"user-defined":{"packages":1}
,"packages":{"rather":1,"store":1,"dependency":1,"load":1,"disabling":1,"importing":1}
,"rather":{"wmjmsadapter":1}
,"doing":{"allow":1}
,"allow":{"anage":1}
,"anage":{"package":1}
,"easily":{"create":1}
,"store":{"connec":1}
,"connec":{"tions":1}
,"tions":{"adapter":1}
,"notifications":{"package":1}
,"functionality":{"provided":1}
,"designer":{"user-defined":1}
,"dependency":{"wmjmsadapter":1,"requirements":1}
,"pac":{"kage":1}
,"kage":{"loads":1}
,"loads":{"reloads":1}
,"reloads":{"user-defined":1}
,"load":{"automa":1}
,"automa":{"tically":1}
,"tically":{"following":1}
,"following":{"diagram":1}
,"diagram":{"package":1}
,"tasks":{"include":1}
,"include":{"setting":1}
,"setting":{"package":1}
,"dependencies":{"(see":1}
,"(see":{"package":1}
,"requirements":{"guidelines":1}
,"guidelines":{"enabling":1}
,"enabling":{"packages":1}
,"disabling":{"packages":1}
,"importing":{"exporting":1}
,"exporting":{"packages":1}
}
;Search.control.loadWordPairs(pairs);
