var pairs =
{
"changing":{"connection":1}
,"connection":{"adapter":1,"associated":1}
,"adapter":{"service":1,"notifica":1,"services":1}
,"service":{"notificati":1,"notification":1,"adapter":1,"run":1,"directly":1,"running":1}
,"notificati":{"design":1}
,"design":{"time":1}
,"time":{"integration":1,"change":1,"need":1,"within":1}
,"integration":{"server":1}
,"server":{"provides":1,"flow":1,"built-in":1}
,"provides":{"built-in":1}
,"built-in":{"services":1}
,"services":{"design":1,"named":1,"change":1,"notifications":1,"run":1,"webmethods":1,"reference":1,"enable":1,"connections":1}
,"change":{"connection":1,"specific":1}
,"associated":{"adapter":1}
,"notification":{"built-in":1}
,"named":{"pub.art.service:setadapterservicenodeconnection":1}
,"pub.art.service:setadapterservicenodeconnection":{"pub.art.notification:setpollingnotificationnodeconnection":1}
,"pub.art.notification:setpollingnotificationnodeconnection":{"using":1}
,"using":{"services":1}
,"specific":{"connecti":1}
,"connecti":{"associated":1}
,"notifica":{"tion":1}
,"tion":{"design":1}
,"need":{"create":1}
,"create":{"intain":1}
,"intain":{"multiple":1}
,"multiple":{"adapter":1}
,"notifications":{"note":1}
,"note":{"built-in":1}
,"run":{"design":1,"service":1}
,"within":{"integration":1}
,"flow":{"java":1}
,"java":{"service":1}
,"directly":{"designer":1}
,"designer":{"selecting":1}
,"selecting":{"service":1}
,"running":{"details":1}
,"details":{"services":1}
,"webmethods":{"integration":1}
,"reference":{"release":1}
,"release":{"built-in":1}
,"enable":{"control":1}
,"control":{"connections":1}
,"connections":{"information":1}
,"information":{"built-in":1}
}
;Search.control.loadWordPairs(pairs);
