var pairs =
{
"adding":{"jms":1}
,"jms":{"provider":1,"provider\u0027s":1,"file\u2011based":1}
,"provider":{"client":1,"1.2":1}
,"client":{"libraries":1,"ibraries":1}
,"libraries":{"integration":1,"server\u0027s":1,"weblogic":1}
,"integration":{"server":1,"server_directory":1}
,"server":{"classpath":1,"requires":1,"automatically":1,"integration":1,"create":1}
,"classpath":{"integration":1,"copying":1,"add":1,"going":1}
,"requires":{"access":1}
,"access":{"jms":1}
,"provider\u0027s":{"java":1,"client":1}
,"java":{"client":1,"api":1,"-jar":1}
,"ibraries":{"place":1}
,"place":{"libraries":1,"wlfullclient.jar":1}
,"server\u0027s":{"classpath":1}
,"copying":{"integration":1}
,"server_directory":{"\u005Cinstances\u005Cinstance_name":1}
,"\u005Cinstances\u005Cinstance_name":{"\u005Cpackages\u005Cwmjmsadapter\u005Ccode\u005Cjars\u005Cstatic":1}
,"\u005Cpackages\u005Cwmjmsadapter\u005Ccode\u005Cjars\u005Cstatic":{"directory":1}
,"directory":{"descri":1,"copy":1,"restart":1}
,"descri":{"bed":1}
,"bed":{"following":1}
,"following":{"sections":1,"command":1}
,"sections":{"server":1}
,"automatically":{"add":1}
,"add":{".jar":1,"jms":1}
,".jar":{"files":1}
,"files":{"classpath":1,"fscontext-1_2_beta3.zip":1,"integration":1}
,"going":{"adapter":1}
,"adapter":{"jms":1}
,"file\u2011based":{"jndi":1}
,"jndi":{"implementation":1,"1.2.1":1}
,"implementation":{"download":1}
,"download":{"fsconte":1,"jndi":1,"fscontext-1_2_beta3.zip":1}
,"fsconte":{"xt-1_2_beta3.zip":1}
,"xt-1_2_beta3.zip":{"file":1}
,"file":{"oracle":1,"system":1,"extract":1,"copy":1}
,"oracle":{"website":1}
,"website":{"download":1}
,"1.2.1":{"&more":1}
,"&more":{"menu":1}
,"menu":{"select":1}
,"select":{"file":1}
,"system":{"service":1}
,"service":{"provider":1}
,"1.2":{"beta":1}
,"beta":{"download":1}
,"fscontext-1_2_beta3.zip":{"file":1}
,"extract":{"fscontext.jar":1}
,"fscontext.jar":{"providerutil.jar":1}
,"providerutil.jar":{"files":1}
,"copy":{"files":1,"java":1}
,"api":{"libraries":1}
,"weblogic":{"10.3.1.0":1,"installation":1}
,"10.3.1.0":{"server":1}
,"create":{"wlfullclient.jar":1}
,"wlfullclient.jar":{"weblogic":1,"integration":1}
,"installation":{"using":1}
,"using":{"following":1}
,"command":{"java":1}
,"-jar":{"wljarbuilder.jar":1}
,"wljarbuilder.jar":{"place":1}
,"restart":{"host":1}
,"host":{"integration":1}
}
;Search.control.loadWordPairs(pairs);
