var pairs =
{
"messagelistener":{"notification":1,"notifications":1}
,"notification":{"run-time":1,"periodically":1,"step":1,"gets":1,"uses":1,"retrieves":1,"following":1,"notification":1,"creates":1,"invokes":1,"details":1}
,"run-time":{"processing":1}
,"processing":{"following":1}
,"following":{"diagram":1,"actions":1}
,"diagram":{"steps":1}
,"steps":{"illustrate":1}
,"illustrate":{"happens":1}
,"happens":{"time":1}
,"time":{"messagelistener":1}
,"notifications":{"invoked":1}
,"invoked":{"integration":1,"configure":1}
,"integration":{"server":1,"scen":1}
,"server":{"continues":1,"trigger":1,"option":1,"publishable":1}
,"continues":{"invoke":1}
,"invoke":{"notification":1,"flow":1}
,"periodically":{"defin":1}
,"defin":{"configured":1}
,"configured":{"schedule":1,"notification":1}
,"schedule":{"parameters":1}
,"parameters":{"messa":1}
,"messa":{"gelistener":1}
,"gelistener":{"notification":1}
,"step":{"description":1}
,"description":{"jms":1}
,"jms":{"messages":1,"destination":1,"apis":1,"destin":1,"message":1}
,"messages":{"placed":1,"queue":1}
,"placed":{"jms":1}
,"destination":{"(queue":1}
,"(queue":{"topic":1}
,"topic":{"notification":1}
,"gets":{"connection":1}
,"connection":{"notification\u0027s":1}
,"notification\u0027s":{"onnection":1}
,"onnection":{"pool":1}
,"pool":{"notification":1}
,"uses":{"jms":1,"integration":1}
,"apis":{"monitor":1}
,"monitor":{"jms":1}
,"destin":{"ation":1}
,"ation":{"notification":1}
,"retrieves":{"jms":1}
,"queue":{"topic":1}
,"actions":{"dependin":1}
,"dependin":{"configured":1}
,"creates":{"publishable":1}
,"publishable":{"document":1,"documents":1}
,"document":{"conta":1,"option":1,"notification":1}
,"conta":{"ins":1}
,"ins":{"jms":1}
,"message":{"publishes":1}
,"publishes":{"document":1}
,"option":{"create":1,"specify":1}
,"create":{"integration":1}
,"scen":{"ario":1}
,"ario":{"uses":1}
,"trigger":{"invoke":1}
,"flow":{"java":1}
,"java":{"service":1}
,"service":{"using":1,"integration":1,"invoked":1}
,"using":{"data":1}
,"data":{"con":1}
,"con":{"tained":1}
,"tained":{"publishable":1}
,"invokes":{"service":1}
,"specify":{"name":1}
,"name":{"service":1}
,"configure":{"notification":1}
,"details":{"integration":1}
,"documents":{"publish-subscribe":1}
,"publish-subscribe":{"developer\u2019s":1}
,"developer\u2019s":{"guide":1}
,"guide":{"release":1}
}
;Search.control.loadWordPairs(pairs);
