var pairs =
{
"transaction":{"management":1,"types":1,"type":1,"boundary":1,"beginning":1,"adap":1,"ust":1,"manager":1,"conte":1}
,"management":{"adapter":1,"services":1,"connection\u0027s":1,"requirements":1}
,"adapter":{"jms":1}
,"jms":{"connections":1,"providers":1,"provider":1,"destination":1,"specification":1,"roviders":1}
,"connections":{"adapter":1,"support":1,"involved":1,"xa_transaction":1}
,"support":{"following":1,"two-p":1,"xa_transactio":1,"xa_transaction":1}
,"following":{"transaction":1,"jms":1}
,"types":{"transaction":1,"preceding":1}
,"type":{"description":1,"allows":1,"webmethods":1,"note":1,"notifications":1,"choose":1,"transaction":1}
,"description":{"xa_transaction":1}
,"xa_transaction":{"transaction":1,"trans":1}
,"allows":{"connection":1}
,"connection":{"support":1,"automatically":1,"transaction":1}
,"two-p":{"hase":1}
,"hase":{"transactions":1}
,"transactions":{"executed":1,"manually":1,"integration":1,"types":1,"using":1}
,"executed":{"across":1}
,"across":{"multiple":1}
,"multiple":{"resources":1,"con":1}
,"resources":{"transaction":1}
,"boundary":{"operations":1,"means":1}
,"operations":{"multiple":1,"implicitly":1}
,"con":{"nections":1}
,"nections":{"committed":1}
,"committed":{"rolled":1}
,"rolled":{"back":1}
,"back":{"together":1,"operation":1}
,"together":{"transa":1}
,"transa":{"ction":1}
,"ction":{"boundary":1}
,"means":{"scope":1}
,"scope":{"transaction":1}
,"beginning":{"end":1}
,"end":{"transaction":1}
,"adap":{"ter":1}
,"ter":{"service":1}
,"service":{"flow":1,"java":1,"several":1,"following":1,"requesting":1,"sends":1,"automatically":1}
,"flow":{"service":1}
,"java":{"service":1}
,"several":{"steps":1}
,"steps":{"flow":1}
,"providers":{"support":1}
,"xa_transactio":{"transaction":1}
,"webmethods":{"broker":1}
,"broker":{"8.2":1}
,"8.2":{"sp2":1}
,"sp2":{"9.0":1}
,"9.0":{"sp1":1}
,"sp1":{"9.5":1,"used":1}
,"9.5":{"sp1":1}
,"used":{"jms":1}
,"provider":{"bea":1,"note":1,"deliver":1}
,"bea":{"weblogic":1}
,"weblogic":{"10.3.1.0":1}
,"10.3.1.0":{"jms":1}
,"note":{"connections":1,"cannot":1,"using":1}
,"involved":{"two-phase":1}
,"two-phase":{"transaction":1}
,"ust":{"support":1}
,"cannot":{"connections":1,"lled":1}
,"trans":{"action":1}
,"action":{"type":1}
,"notifications":{"no_transaction":1}
,"no_transaction":{"receiving":1}
,"receiving":{"messages":1}
,"messages":{"connection":1,"message":1}
,"automatically":{"acknow":1,"delivered":1,"commit":1,"comm":1}
,"acknow":{"ledges":1}
,"ledges":{"received":1}
,"received":{"message":1}
,"message":{"(sessions":1,"automatically":1,"jms":1}
,"(sessions":{"created":1}
,"created":{"client_acknowledge":1}
,"client_acknowledge":{"acknowledge":1}
,"acknowledge":{"mode.)":1}
,"mode.)":{"sending":1}
,"sending":{"messages":1}
,"delivered":{"instructions":1}
,"instructions":{"managing":1}
,"managing":{"transactions":1,"transacti":1}
,"manually":{"built-in":1,"define":1}
,"built-in":{"transaction":1,"ervices":1}
,"services":{"local_transaction":1,"define":1}
,"local_transaction":{"connection":1}
,"commit":{"transactions":1}
,"define":{"transactions":1,"connection":1}
,"integration":{"server":1}
,"server":{"transaction":1}
,"manager":{"manage":1,"note":1}
,"manage":{"instruction":1,"transactions":1}
,"instruction":{"managing":1}
,"choose":{"determines":1}
,"determines":{"type":1}
,"connection\u0027s":{"operations":1}
,"implicitly":{"implicit":1}
,"implicit":{"transacti":1}
,"transacti":{"ons":1}
,"ons":{"include":1,"built-in":1}
,"include":{"transactions":1}
,"preceding":{"able":1}
,"able":{"managed":1}
,"managed":{"integration":1}
,"using":{"messagerequestor":1,"built-in":1}
,"messagerequestor":{"service":1}
,"requesting":{"messag":1,"message":1}
,"messag":{"service":1}
,"sends":{"jms":1}
,"destination":{"cannot":1}
,"lled":{"back":1}
,"operation":{"fails":1}
,"fails":{"within":1}
,"within":{"transaction":1}
,"conte":{"messagerequestor":1}
,"comm":{"requesting":1}
,"deliver":{"request":1}
,"request":{"therefore":1}
,"therefore":{"ceive":1}
,"ceive":{"reply":1}
,"reply":{"message":1}
,"specification":{"formation":1}
,"formation":{"transaction":1}
,"requirements":{"jms":1}
,"roviders":{"explicitly":1}
,"explicitly":{"manage":1,"managing":1}
,"ervices":{"information":1}
,"information":{"explicitly":1}
}
;Search.control.loadWordPairs(pairs);
