var pairs =
{
"pub.art.transaction:settransactiontimeout":{"service":1}
,"service":{"enables":1,"temporarily":1,"within":1,"flow":1,"execution":1,"overrides":1,"call":1}
,"enables":{"manually":1}
,"manually":{"transaction":1}
,"transaction":{"timeo":1,"timeout":1,"start":1,"takes":1,"manager":1}
,"timeo":{"interval":1}
,"interval":{"implicit":1,"changing":1,"change":1,"transacted":1,"flow":1}
,"implicit":{"explicit":1,"transaction":1}
,"explicit":{"transactions":1,"transac":1}
,"transactions":{"service":1,"implicit":1,"start":1}
,"temporarily":{"overriding":1}
,"overriding":{"integration":1}
,"integration":{"server":1}
,"server":{"transaction":1}
,"timeout":{"interval":1,"call":1}
,"changing":{"integration":1}
,"change":{"server\u0027s":1}
,"server\u0027s":{"default":1}
,"default":{"transaction":1}
,"call":{"service":1,"adapter":1,"pub.art.transaction:starttransaction":1,"input":1}
,"within":{"flow":1}
,"flow":{"start":1,"explicit":1,"service":1}
,"start":{"implicit":1,"call":1}
,"adapter":{"service":1}
,"pub.art.transaction:starttransaction":{"service":1}
,"execution":{"transaction":1}
,"takes":{"longer":1}
,"longer":{"tran":1}
,"tran":{"saction":1}
,"saction":{"timeout":1}
,"transacted":{"operations":1}
,"operations":{"roll":1}
,"roll":{"back":1}
,"back":{"service":1}
,"overrides":{"transaction":1}
,"input":{"parameters":1}
,"parameters":{"timeoutseconds":1,"none":1}
,"timeoutseconds":{"integer":1}
,"integer":{"number":1}
,"number":{"seconds":1}
,"seconds":{"implicit":1}
,"transac":{"tion":1}
,"tion":{"stays":1}
,"stays":{"open":1}
,"open":{"transaction":1}
,"manager":{"marks":1}
,"marks":{"rollback":1}
,"rollback":{"output":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
