var pairs =
{
"using":{"messageproducer":1,"integration":1,"designer":1}
,"messageproducer":{"messageconsumer":1}
,"messageconsumer":{"messagerequestor":1}
,"messagerequestor":{"following":1,"adapter":1}
,"following":{"steps":1}
,"steps":{"lists":1}
,"lists":{"tasks":1}
,"tasks":{"required":1}
,"required":{"mess":1}
,"mess":{"ageproducer":1}
,"ageproducer":{"messageconsumer":1}
,"adapter":{"ervices":1,"connection":1,"connections":1,"service":1,"services":1}
,"ervices":{"configure":1}
,"configure":{"adapter":1}
,"connection":{"using":1}
,"integration":{"server":1}
,"server":{"administrator":1,"flow":1}
,"administrator":{"information":1}
,"information":{"adapter":1,"webmethods":1,"package":1}
,"connections":{"select":1}
,"select":{"appropriate":1}
,"appropriate":{"adapter":1}
,"service":{"template":1,"using":1,"invoke":1,"design":1,"adapter":1,"development":1}
,"template":{"configur":1}
,"configur":{"adapter":1}
,"designer":{"information":1,"integration":1}
,"services":{"plan":1}
,"plan":{"integration":1}
,"flow":{"java":1}
,"java":{"service":1}
,"invoke":{"adapter":1}
,"design":{"flow":1}
,"webmethods":{"service":1}
,"development":{"help":1}
,"help":{"release":1}
,"release":{"manage":1}
,"manage":{"adapter":1}
,"package":{"management":1}
}
;Search.control.loadWordPairs(pairs);
