var pairs =
{
"transaction":{"management":1}
,"management":{"overview":1,"services":1}
,"overview":{"appendix":1,"examples":1}
,"appendix":{"provides":1}
,"provides":{"overview":1}
,"examples":{"using":1}
,"using":{"tra":1}
,"tra":{"nsactions":1}
,"nsactions":{"describes":1}
,"describes":{"integration":1}
,"integration":{"server":1}
,"server":{"supports":1}
,"supports":{"built-in":1}
,"built-in":{"services":1,"transaction":1,"transacti":1}
,"services":{"used":1,"wmart":1,"descriptions":1}
,"used":{"manage":1,"wmart":1}
,"manage":{"explicit":1}
,"explicit":{"tran":1}
,"tran":{"sactions":1}
,"sactions":{"adapter":1}
,"adapter":{"jms":1}
,"jms":{"services":1}
,"wmart":{"package":1,"packa":1}
,"package":{"built-in":1}
,"descriptions":{"specific":1}
,"specific":{"built-in":1}
,"transacti":{"management":1}
}
;Search.control.loadWordPairs(pairs);
