var pairs =
{
"adapter":{"connections":1,"jms":1,"services":1,"notifications":1,"requires":1,"connecti":1,"service":1}
,"connections":{"adapter":1,"define":1,"using":1}
,"jms":{"uses":1,"providers":1,"connection":1,"provider":1,"connections":1,"two":1,"queueconnection":1,"topicconnection":1}
,"uses":{"adapter":1}
,"define":{"adapter":1}
,"services":{"adapter":1}
,"notifications":{"connect":1}
,"connect":{"jms":1,"queue":1,"topic":1}
,"providers":{"adapter":1}
,"connection":{"contains":1,"parameters":1,"type":1}
,"contains":{"connection":1}
,"parameters":{"includi":1,"adapter":1}
,"includi":{"logon":1}
,"logon":{"parameters":1}
,"requires":{"connect":1}
,"provider":{"configure":1}
,"configure":{"adapter":1,"connections":1}
,"connecti":{"configure":1}
,"service":{"configure":1}
,"using":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"instructions":1}
,"instructions":{"configuring":1}
,"configuring":{"managing":1}
,"managing":{"adapter":1}
,"two":{"types":1}
,"types":{"connections":1}
,"queueconnection":{"select":1}
,"select":{"connection":1}
,"type":{"connect":1}
,"queue":{"adapter":1}
,"topicconnection":{"select":1}
}
;Search.control.loadWordPairs(pairs);
