var pairs =
{
"using":{"messagerequestor":1,"pipeline":1,"following":1}
,"messagerequestor":{"services":1,"service":1}
,"services":{"enable":1,"documenttotextmessage":1,"information":1,"textmessagetodocument":1}
,"enable":{"messagerequestor":1}
,"service":{"send":1,"within":1,"designer":1,"contains":1,"convert":1}
,"send":{"jms":1}
,"jms":{"message":1,"dest":1,"services":1,"destination":1,"destin":1,"essage":1}
,"message":{"queue":1,"object":1,"document":1}
,"queue":{"topic":1,"jms":1,"adapter":1}
,"topic":{"wait":1,"jms":1,"messagerequestor":1}
,"wait":{"temporary":1}
,"temporary":{"destinatio":1}
,"destinatio":{"reply":1}
,"reply":{"provide":1}
,"provide":{"values":1}
,"values":{"parameters":1,"pipeline":1,"using":1}
,"parameters":{"listed":1}
,"listed":{"belo":1}
,"belo":{"service\u0027s":1}
,"service\u0027s":{"input":1}
,"input":{"signature":1}
,"signature":{"configuring":1}
,"configuring":{"adap":1,"document-to-message":1,"message-to-document":1}
,"adap":{"ter":1}
,"ter":{"service":1}
,"within":{"flow":1}
,"flow":{"service":1}
,"designer":{"either":1}
,"either":{"map":1}
,"map":{"values":1}
,"pipeline":{"constant":1,"editor":1}
,"constant":{"values":1}
,"editor":{"parameter":1}
,"parameter":{"description\u002Faction":1,"determi":1}
,"description\u002Faction":{"jmsmessage":1}
,"jmsmessage":{"jms":1}
,"object":{"want":1,"using":1,"jms":1,"retrieved":1}
,"want":{"send":1}
,"dest":{"ination":1}
,"ination":{"create":1}
,"create":{"jms":1}
,"following":{"adapter":1,"output":1}
,"adapter":{"jms":1,"connection":1}
,"documenttotextmessage":{"documenttoobjectmessage":1}
,"documenttoobjectmessage":{"documenttomapmessage":1}
,"documenttomapmessage":{"documenttobytesmessage":1}
,"documenttobytesmessage":{"documenttostreammessage":1}
,"documenttostreammessage":{"configuring":1}
,"document-to-message":{"conversion":1}
,"conversion":{"services":1}
,"information":{"jmsdestination":1,"jmsmessageclass":1}
,"jmsdestination":{"jms":1}
,"destination":{"object":1,"jndi":1,"queue":1,"topic":1}
,"jndi":{"name":1}
,"name":{"(string)":1,"java":1}
,"(string)":{"adapter":1}
,"connection":{"configured":1}
,"configured":{"queue":1,"topic":1}
,"contains":{"following":1}
,"output":{"ignature":1}
,"ignature":{"parameter":1}
,"retrieved":{"jms":1}
,"destin":{"ation":1}
,"ation":{"convert":1}
,"convert":{"document":1,"message":1}
,"document":{"jms":1}
,"textmessagetodocument":{"objectmessagetodocument":1}
,"objectmessagetodocument":{"mapmessagetodocument":1}
,"mapmessagetodocument":{"bytesmessagetodocument":1}
,"bytesmessagetodocument":{"streammessagetodocument":1}
,"streammessagetodocument":{"configuring":1}
,"message-to-document":{"conversion":1,"service":1}
,"jmsmessageclass":{"string":1}
,"string":{"containing":1}
,"containing":{"name":1}
,"java":{"class":1}
,"class":{"jms":1}
,"essage":{"value":1}
,"value":{"parameter":1}
,"determi":{"message-to-document":1}
}
;Search.control.loadWordPairs(pairs);
