var pairs =
{
"replicating":{"packages":1}
,"packages":{"webmethods":1,"define":1}
,"webmethods":{"integration":1}
,"integration":{"server":1}
,"server":{"every":1,"cluster":1,"replicate":1,"server":1,"unavailable":1,"information":1,"administrator\u2019s":1}
,"every":{"webmethods":1}
,"cluster":{"contain":1}
,"contain":{"identical":1,"different":1}
,"identical":{"packages":1}
,"define":{"using":1}
,"using":{"adapter":1}
,"adapter":{"jms":1}
,"jms":{"replicate":1,"services":1}
,"replicate":{"adapter":1,"polling":1,"servers":1}
,"services":{"connections":1}
,"connections":{"replicate":1}
,"polling":{"notifications":1}
,"notifications":{"ensure":1}
,"ensure":{"consistency":1}
,"consistency":{"recommend":1}
,"recommend":{"create":1}
,"create":{"pack":1}
,"pack":{"ages":1}
,"ages":{"server":1}
,"servers":{"allow":1,"contain":1}
,"allow":{"different":1}
,"different":{"servers":1,"service":1}
,"service":{"derive":1,"resides":1}
,"derive":{"full":1}
,"full":{"benefits":1}
,"benefits":{"clustering":1}
,"clustering":{"example":1}
,"example":{"client":1}
,"client":{"requests":1}
,"requests":{"service":1}
,"resides":{"onl":1}
,"onl":{"server":1}
,"unavailable":{"request":1}
,"request":{"nnot":1}
,"nnot":{"successfully":1}
,"successfully":{"redirected":1}
,"redirected":{"server":1}
,"information":{"replicating":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"release":1}
}
;Search.control.loadWordPairs(pairs);
