var pairs =
{
"pub.art.transaction:rollbacktransaction":{"service":1}
,"service":{"rolls":1,"corresponding":1,"flow":1,"receive":1}
,"rolls":{"back":1}
,"back":{"explicit":1,"output":1}
,"explicit":{"transaction":1,"transactio":1}
,"transaction":{"used":1,"management":1,"transactionname":1,"value":1}
,"used":{"conjunction":1,"associate":1}
,"conjunction":{"pub.art.transaction:starttransaction":1}
,"pub.art.transaction:starttransaction":{"service":1,"pub.art.transaction:committransaction":1,"previously":1}
,"corresponding":{"pub.art.transaction:starttransaction":1}
,"flow":{"service":1}
,"receive":{"run-time":1}
,"run-time":{"error":1}
,"error":{"transaction":1}
,"management":{"overview":1}
,"overview":{"information":1}
,"information":{"implicit":1}
,"implicit":{"explicit":1}
,"transactio":{"input":1}
,"input":{"parameters":1}
,"parameters":{"rollbacktransactioninput":1,"none":1}
,"rollbacktransactioninput":{"document":1}
,"document":{"document":1,"contains":1}
,"contains":{"variable":1}
,"variable":{"transactionname":1}
,"transactionname":{"described":1,"string":1,"correspond":1,"pub.art.transaction:starttransaction":1}
,"described":{"below":1}
,"below":{"transactionname":1}
,"string":{"used":1}
,"associate":{"name":1}
,"name":{"explicit":1}
,"correspond":{"transactionname":1}
,"pub.art.transaction:committransaction":{"services":1}
,"services":{"associated":1}
,"associated":{"explicit":1}
,"value":{"mapped":1}
,"mapped":{"recent":1}
,"recent":{"pub.art.transaction:starttransaction":1}
,"previously":{"committed":1}
,"committed":{"rolled":1}
,"rolled":{"back":1}
,"output":{"parameters":1}
}
;Search.control.loadWordPairs(pairs);
