var pairs =
{
"configuring":{"managing":1,"adapter":1}
,"managing":{"notifications":1,"dapter":1,"packages":1,"messagelistener":1}
,"notifications":{"perform":1,"prepare":1,"instructions":1}
,"perform":{"following":1}
,"following":{"tasks":1}
,"tasks":{"configuring":1}
,"dapter":{"notifications":1}
,"prepare":{"configure":1}
,"configure":{"manage":1,"adapter":1,"notific":1}
,"manage":{"messagelistener":1}
,"messagelistener":{"notificati":1,"notifications":1}
,"notificati":{"ons":1,"configuring":1}
,"ons":{"start":1}
,"start":{"integration":1,"designer":1}
,"integration":{"server":1}
,"server":{"integration":1,"administrator":1,"administrative":1,"administrator\u2019s":1,"solves":1}
,"administrator":{"already":1,"software":1,"sure":1,"configure":1}
,"already":{"running":1,"done":1}
,"running":{"sure":1,"using":1}
,"sure":{"integration":1,"wmjmsadapter":1}
,"software":{"designer":1}
,"designer":{"privileges":1,"already":1,"create":1}
,"privileges":{"access":1,"webmethods":1}
,"access":{"integration":1}
,"administrative":{"screens":1}
,"screens":{"information":1}
,"information":{"setting":1,"changing":1}
,"setting":{"privileges":1}
,"webmethods":{"integration":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"release":1}
,"release":{"plan":1}
,"plan":{"once":1}
,"once":{"notification":1}
,"notification":{"feature":1,"information":1,"design":1,"already":1,"enable":1,"managing":1}
,"feature":{"using":1,"details":1}
,"using":{"exactly":1,"integration":1,"designer":1}
,"exactly":{"once":1}
,"details":{"using":1}
,"wmjmsadapter":{"package":1}
,"package":{"enabled":1,"contain":1,"informa":1,"management":1}
,"enabled":{"enabling":1}
,"enabling":{"packages":1}
,"packages":{"instructions":1,"adapter":1}
,"instructions":{"using":1,"note":1}
,"adapter":{"connection":1,"jms":1,"service":1,"package":1}
,"connection":{"notificati":1,"associa":1,"adapter":1}
,"jms":{"connections":1}
,"connections":{"instructions":1}
,"note":{"integration":1}
,"solves":{"limitation":1}
,"limitation":{"providing":1}
,"providing":{"built-in":1}
,"built-in":{"service":1}
,"service":{"design":1,"notification":1}
,"design":{"time":1}
,"time":{"change":1,"start":1}
,"change":{"connection":1}
,"associa":{"ted":1}
,"ted":{"polling":1}
,"polling":{"notification":1}
,"changing":{"connection":1}
,"create":{"user-defined":1}
,"user-defined":{"package":1,"packag":1}
,"contain":{"notification":1}
,"done":{"configure":1}
,"notific":{"ations":1}
,"ations":{"always":1}
,"always":{"define":1}
,"define":{"user-defined":1}
,"packag":{"rather":1}
,"rather":{"wmjmsadapter":1}
,"informa":{"tion":1}
,"tion":{"managing":1}
,"management":{"schedule":1}
,"schedule":{"notification":1}
,"enable":{"notification":1}
}
;Search.control.loadWordPairs(pairs);
