var pairs =
{
"deleting":{"adapter":1}
,"adapter":{"services":1,"service":1}
,"services":{"designer":1,"delete":1}
,"designer":{"delete":1,"expand":1}
,"delete":{"adapter":1,"right-click":1}
,"service":{"review":1,"want":1,"click":1}
,"review":{"steps":1}
,"steps":{"configuring":1}
,"configuring":{"managing":1}
,"managing":{"adapter":1}
,"expand":{"package":1}
,"package":{"folder":1}
,"folder":{"contain":1}
,"contain":{"service":1}
,"want":{"delete":1}
,"right-click":{"service":1}
,"click":{"delete":1}
}
;Search.control.loadWordPairs(pairs);
