var pairs =
{
"using":{"messagelistener":1,"integration":1,"designer":1}
,"messagelistener":{"notifications":1}
,"notifications":{"following":1,"instructions":1,"plan":1,"details":1}
,"following":{"steps":1}
,"steps":{"lists":1}
,"lists":{"tasks":1}
,"tasks":{"required":1}
,"required":{"pes":1}
,"pes":{"notification":1}
,"notification":{"create":1,"using":1}
,"create":{"adapter":1}
,"adapter":{"connection":1,"jms":1,"notification":1,"notifications":1}
,"connection":{"using":1}
,"integration":{"server":1}
,"server":{"administrator":1,"flow":1,"trigger":1}
,"administrator":{"configuring":1,"managing":1,"package":1}
,"configuring":{"adapter":1,"messagelistener":1,"notifications":1}
,"jms":{"connections":1}
,"connections":{"details":1}
,"details":{"configure":1,"webmethods":1}
,"configure":{"notification":1}
,"designer":{"configuring":1,"details":1,"integration":1}
,"instructions":{"configuring":1,"manage":1}
,"plan":{"integration":1}
,"flow":{"java":1}
,"java":{"service":1}
,"service":{"design":1,"development":1}
,"design":{"react":1}
,"react":{"data":1}
,"data":{"change":1}
,"change":{"contained":1}
,"contained":{"notification\u0027s":1}
,"notification\u0027s":{"publishable":1}
,"publishable":{"document":1}
,"document":{"crea":1,"usin":1}
,"crea":{"integration":1}
,"trigger":{"notification\u0027s":1}
,"usin":{"designer":1}
,"webmethods":{"service":1}
,"development":{"help":1}
,"help":{"release":1}
,"release":{"schedule":1}
,"schedule":{"enable":1}
,"enable":{"adapter":1}
,"managing":{"messagelistener":1}
,"manage":{"notification":1}
,"package":{"management":1}
,"management":{"adapter":1}
}
;Search.control.loadWordPairs(pairs);
