var pairs =
{
"configuring":{"adapter":1,"connections":1}
,"adapter":{"jms":1,"connect":1,"connection":1,"connections":1,"creates":1,"reuse":1,"wait":1,"violate":1}
,"jms":{"connections":1,"provider":1,"queueconnection":1,"topicconnection":1,"connection":1,"folder":1,"queue":1,"user":1,"login":1,"provide":1,"password":1,"api":1,"leveraging":1}
,"connections":{"configure":1,"specify":1,"using":1,"screen":1,"define":1,"client":1,"connection":1,"information":1,"default":1,"active":1,"pool":1,"needed":1,"remain":1,"enabling":1}
,"configure":{"adapter":1,"connection":1,"new":1,"connection.you":1}
,"specify":{"information":1,"parameter":1,"field":1,"java.naming.security.protocol":1,"name":1,"along":1,"seconds":1,"10000":1,"timeout":1}
,"information":{"integration":1,"special":1,"connection":1,"enabling":1}
,"integration":{"server":1}
,"server":{"uses":1,"administrator":1,"designer":1,"transaction":1,"side":1,"specify":1,"wait":1}
,"uses":{"connect":1,"transactions":1}
,"connect":{"jms":1,"queue":1,"topic":1,"ion":1}
,"provider":{"configure":1,"select":1,"example":1,"url":1,"state":1}
,"using":{"integration":1,"designer":1,"spec":1,"semicolon":1}
,"administrator":{"configure":1,"navigation":1}
,"connection":{"adapters":1,"connection":1,"types":1,"type":1,"section":1,"user-defined":1,"name":1,"names":1,"properties":1,"provides":1,"uses":1,"auto":1,"automatically":1,"purposes":1,"client":1,"purpose":1,"objects":1,"factory":1,"reated":1,"imits":1,"pool":1,"management":1,"pooling":1,"become":1,"times":1,"remain":1,"configured":1,"enabl":1}
,"adapters":{"menu":1}
,"menu":{"integration":1}
,"navigation":{"area":1}
,"area":{"click":1}
,"click":{"adapter":1,"configure":1,"connection":1,"save":1}
,"screen":{"click":1,"designer":1}
,"new":{"connection":1}
,"types":{"screen":1,"xa_transaction":1}
,"type":{"want":1,"connect":1,"type":1,"transaction":1}
,"want":{"adapter":1,"give":1}
,"select":{"adapter":1,"following":1}
,"queueconnection":{"connection":1}
,"queue":{"select":1,"topic":1,"connec":1,"connectionfactory":1}
,"topicconnection":{"connection":1,"only)":1}
,"topic":{"adapter":1,"connec":1,"connectio":1,"connectionfactory":1,"connection":1}
,"section":{"provide":1}
,"provide":{"values":1,"additional":1,"topic":1,"queue":1,"jms":1}
,"values":{"following":1}
,"following":{"fields":1,"transaction":1,"format":1}
,"fields":{"parameter":1}
,"parameter":{"description\u002Faction":1,"general":1,"description":1,"connections":1}
,"description\u002Faction":{"package":1}
,"package":{"package":1,"configure":1,"using":1,"rather":1,"management":1,"folder":1,"navigator":1}
,"connection.you":{"eate":1}
,"eate":{"package":1}
,"designer":{"specify":1,"information":1,"creating":1,"package":1}
,"general":{"nformation":1}
,"nformation":{"creating":1}
,"creating":{"packages":1,"connection":1}
,"packages":{"webmethods":1,"adapter":1}
,"webmethods":{"service":1}
,"service":{"development":1,"topic":1}
,"development":{"help":1}
,"help":{"release":1}
,"release":{"note":1,"connection":1}
,"note":{"configure":1,"property":1,"need":1,"plan":1,"note":1,"adapter":1}
,"user-defined":{"package":1}
,"rather":{"adapter\u0027s":1}
,"adapter\u0027s":{"package":1,"conne":1}
,"management":{"important":1,"services":1,"properties":1}
,"important":{"considerations":1}
,"considerations":{"creating":1,"configuring":1}
,"folder":{"name":1,"configure":1,"element":1}
,"name":{"folder":1,"name":1,"want":1,"initial":1,"security":1,"custom":1,"full":1,"identifying":1,"queue":1,"jms":1,"connect":1}
,"give":{"connection":1}
,"names":{"annot":1,"webmethods":1}
,"annot":{"spaces":1}
,"spaces":{"special":1}
,"special":{"characters":1}
,"characters":{"integration":1,"package":1}
,"element":{"names":1}
,"properties":{"section":1,"(optional)":1,"properties":1,"specify":1,"following":1,"using":1}
,"description":{"transaction":1,"enable":1}
,"transaction":{"type":1,"support":1,"types":1,"manager":1,"management":1}
,"support":{"connection":1,"durable":1}
,"provides":{"select":1}
,"xa_transaction":{"connection":1}
,"transactions":{"no_transaction":1,"manually":1,"integration":1}
,"no_transaction":{"receiving":1}
,"receiving":{"messages":1}
,"messages":{"connection":1,"message":1}
,"auto":{"matically":1}
,"matically":{"acknowledges":1}
,"acknowledges":{"received":1}
,"received":{"message":1}
,"message":{"(sessions":1,"automatically":1}
,"(sessions":{"reated":1}
,"reated":{"client_acknowledge":1,"connection":1}
,"client_acknowledge":{"acknowledge":1}
,"acknowledge":{"mode.)":1}
,"mode.)":{"ending":1}
,"ending":{"messages":1}
,"automatically":{"delivered":1,"com":1}
,"delivered":{"local_transaction":1}
,"local_transaction":{"connection":1}
,"com":{"mit":1}
,"mit":{"transactions":1}
,"manually":{"define":1,"built-in":1}
,"define":{"transactions":1,"securi":1}
,"manager":{"manage":1}
,"manage":{"instruction":1}
,"instruction":{"managing":1}
,"managing":{"transactions":1}
,"built-in":{"transaction":1}
,"services":{"jndi":1}
,"jndi":{"initial":1,"provider":1,"directory":1,"security":1,"login":1,"lookup":1,"properties":1,"naming":1,"name":1,"service":1}
,"initial":{"context":1,"attempt":1}
,"context":{"factory":1,"facto":1,"within":1,"using":1}
,"factory":{"fully":1,"note":1,"adapter":1,"jms":1,"connection":1}
,"fully":{"qualified":1}
,"qualified":{"class":1}
,"class":{"name":1}
,"facto":{"used":1}
,"used":{"jndi":1}
,"example":{"weblogic.jndi.wl":1,"t3:\u002F\u002Fmyhost.mycompany.com:7001":1,"specify":1}
,"weblogic.jndi.wl":{"initialcontextfactory":1}
,"initialcontextfactory":{"jndi":1}
,"url":{"url":1,"starting":1}
,"starting":{"context":1}
,"within":{"jndi":1}
,"directory":{"rvice":1}
,"rvice":{"example":1}
,"t3:\u002F\u002Fmyhost.mycompany.com:7001":{"jndi":1}
,"security":{"principal":1,"credentials":1,"protocol":1}
,"principal":{"(optional)":1,"ndi":1}
,"(optional)":{"jndi":1,"enables":1,"jms":1}
,"login":{"name":1,"password":1}
,"ndi":{"lookup":1}
,"lookup":{"purposes":1}
,"purposes":{"jndi":1,"connection":1}
,"credentials":{"(optional)":1,"jndi":1}
,"password":{"security":1,"(optional)":1,"connection":1}
,"enables":{"provide":1,"adapter":1}
,"additional":{"jndi":1}
,"field":{"differ":1,"specifies":1}
,"differ":{"depen":1}
,"depen":{"ding":1}
,"ding":{"specific":1}
,"specific":{"jndi":1}
,"naming":{"context":1}
,"spec":{"ify":1}
,"ify":{"properties":1}
,"format":{"separating":1}
,"separating":{"multiple":1}
,"multiple":{"properties":1}
,"semicolon":{"(;)":1}
,"(;)":{"propertyname1=value1":1}
,"propertyname1=value1":{"prop":1}
,"prop":{"ertyname2=value2.for":1}
,"ertyname2=value2.for":{"jboss":1}
,"jboss":{"connections":1,"server":1}
,"securi":{"protocol":1}
,"protocol":{"server":1,"custom":1}
,"side":{"default":1}
,"default":{"authentication":1,"client":1,"true":1,"maximum":1,"pool":1,"1000":1,"startup":1,"configure":1}
,"authentication":{"module":1}
,"module":{"specify":1,"defined":1,"value":1}
,"java.naming.security.protocol":{"property":1}
,"property":{"value":1,"java.naming.security.protocol=custommodule":1,"default":1}
,"value":{"follows":1,"java.naming.security.pr":1}
,"follows":{"java.naming.security.protocol=other":1}
,"java.naming.security.protocol=other":{"alternatively":1}
,"alternatively":{"need":1}
,"need":{"assign":1,"client":1}
,"assign":{"security":1}
,"custom":{"module":1}
,"defined":{"client-login":1}
,"client-login":{"conf\u002Flogin":1}
,"conf\u002Flogin":{"-config.xml":1}
,"-config.xml":{"entry":1}
,"entry":{"jboss":1}
,"java.naming.security.pr":{"otocol":1}
,"otocol":{"property":1}
,"java.naming.security.protocol=custommodule":{"topic\u002Fqueue":1}
,"topic\u002Fqueue":{"connectionfactory":1}
,"connectionfactory":{"jndi":1,"name":1}
,"full":{"path":1}
,"path":{"name":1}
,"identifying":{"jms":1}
,"connec":{"tionfactory":1,"tions":1}
,"tionfactory":{"bound":1}
,"bound":{"jndi":1}
,"connectio":{"provide":1}
,"tions":{"provide":1}
,"user":{"(optional)":1}
,"client":{"(adapter":1,"ident":1,"identif":1,"provider":1,"stored":1,"notifications":1,"specified":1}
,"(adapter":{"jms":1}
,"only)":{"unique":1}
,"unique":{"client":1}
,"ident":{"ifier":1}
,"ifier":{"connection":1}
,"purpose":{"client":1}
,"identif":{"ier":1}
,"ier":{"associate":1}
,"associate":{"connection":1}
,"objects":{"stat":1,"remain":1,"exist":1}
,"stat":{"maintained":1}
,"maintained":{"behalf":1}
,"behalf":{"client":1}
,"state":{"identified":1}
,"identified":{"jms":1}
,"api":{"required":1}
,"required":{"support":1}
,"durable":{"subscriptions":1}
,"subscriptions":{"note":1}
,"stored":{"topic":1}
,"notifications":{"better":1}
,"better":{"specify":1}
,"along":{"notification":1}
,"notification":{"param":1}
,"param":{"eters":1}
,"eters":{"using":1}
,"specified":{"connect":1}
,"ion":{"factory":1}
,"imits":{"adapter":1}
,"leveraging":{"connection":1}
,"pool":{"connection":1,"size":1,"times":1,"create":1,"adapter":1,"connections":1,"reached":1,"increment":1,"incremented":1,"closed":1,"example":1,"regardless":1,"startup":1,"click":1}
,"enable":{"connection":1}
,"pooling":{"enables":1,"default":1,"note":1,"clustered":1,"enabled":1}
,"true":{"adapter":1}
,"plan":{"enable":1}
,"clustered":{"envi":1}
,"envi":{"ronment":1}
,"ronment":{"consider":1}
,"consider":{"connection":1}
,"size":{"details":1,"connection":1,"maximum":1,"adapter":1,"defau":1,"parameter":1}
,"details":{"considerations":1}
,"enabled":{"minimum":1,"field":1}
,"minimum":{"pool":1}
,"specifies":{"inimum":1,"umber":1}
,"inimum":{"number":1}
,"number":{"connection":1,"connections":1,"times":1,"seconds":1}
,"remain":{"conne":1,"pool":1}
,"conne":{"ction":1,"ctions":1}
,"ction":{"pool":1}
,"times":{"adapter":1,"turns":1,"system":1}
,"creates":{"pool":1}
,"create":{"number":1}
,"maximum":{"pool":1,"number":1,"size":1}
,"exist":{"connection":1}
,"reuse":{"inactive":1}
,"inactive":{"conn":1,"connection":1,"startup":1}
,"conn":{"ections":1}
,"ections":{"pool":1}
,"active":{"connection":1}
,"reached":{"maximum":1}
,"wait":{"connection":1,"obtain":1,"tempts":1}
,"become":{"available":1}
,"available":{"default":1}
,"increment":{"size":1}
,"umber":{"connections":1,"milliseconds":1}
,"incremented":{"connections":1}
,"needed":{"maximum":1}
,"defau":{"block":1}
,"block":{"timeout":1}
,"timeout":{"connection":1,"default":1,"number":1}
,"milliseconds":{"integration":1,"inactive":1}
,"obtain":{"connection":1}
,"turns":{"error":1}
,"error":{"default":1}
,"1000":{"expire":1,"note":1}
,"expire":{"timeout":1}
,"closed":{"removed":1}
,"removed":{"pool":1}
,"seconds":{"specify":1,"system":1}
,"10000":{"enter":1}
,"enter":{"specify":1}
,"violate":{"minimum":1}
,"regardless":{"long":1}
,"long":{"inactive":1}
,"startup":{"retry":1,"initial":1,"backoff":1}
,"retry":{"count":1}
,"count":{"number":1}
,"system":{"attempt":1,"wait":1}
,"attempt":{"initia":1,"ails":1}
,"initia":{"lize":1}
,"lize":{"connection":1}
,"ails":{"default":1}
,"backoff":{"timeout":1}
,"tempts":{"initialize":1}
,"initialize":{"connection":1}
,"save":{"connection":1}
,"configured":{"appears":1}
,"appears":{"adapter\u0027s":1}
,"ctions":{"screen":1}
,"navigator":{"default":1}
,"enabl":{"information":1}
,"enabling":{"connections":1,"adapter":1}
}
;Search.control.loadWordPairs(pairs);
