var pairs =
{
"managing":{"messagelistener":1,"notifications":1}
,"messagelistener":{"notifications":1,"notification":1}
,"notifications":{"schedule":1,"review":1,"start":1,"configured":1,"displayed":1,"table":1,"return":1}
,"schedule":{"messagelistener":1,"polling":1,"click":1,"view":1,"selected":1,"parameters":1,"create":1}
,"notification":{"able":1,"monitor":1,"adapter":1,"using":1,"field":1,"name":1,"package":1,"state":1,"enab":1,"icon":1,"performs":1,"removed":1,"suspended":1,"scheduled":1,"control":1,"described":1,"first":1,"page":1,"click":1,"enable":1}
,"able":{"notification":1}
,"monitor":{"jms":1}
,"jms":{"estinations":1,"navigation":1,"notifications":1,"polling":1}
,"estinations":{"messages":1}
,"messages":{"integration":1,"topic":1}
,"integration":{"server":1}
,"server":{"administrator":1,"privileges":1,"administrator\u2019s":1}
,"administrator":{"along":1,"administrative":1,"adapters":1,"select":1}
,"along":{"following":1}
,"following":{"procedures":1,"table":1,"parameters":1}
,"procedures":{"note":1,"doing":1}
,"note":{"cannot":1,"webmethods":1,"even":1,"edit":1}
,"cannot":{"enable":1}
,"enable":{"notification":1,"run":1,"state":1,"polling":1}
,"adapter":{"connection":1,"jms":1,"notification":1}
,"connection":{"hat":1}
,"hat":{"notification":1}
,"using":{"disabled":1}
,"disabled":{"note":1,"polling":1}
,"webmethods":{"integration":1}
,"privileges":{"access":1,"webmethods":1}
,"access":{"integration":1}
,"administrative":{"screens":1}
,"screens":{"information":1}
,"information":{"setting":1}
,"setting":{"privileges":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"release":1}
,"release":{"manage":1}
,"manage":{"messagelistener":1,"adapter":1}
,"review":{"steps":1}
,"steps":{"configuring":1}
,"configuring":{"managing":1}
,"start":{"integration":1,"polling":1}
,"adapters":{"menu":1}
,"menu":{"navigation":1}
,"navigation":{"area":1}
,"area":{"integration":1,"select":1}
,"select":{"adapter":1,"polling":1,"option":1}
,"polling":{"notifications":1,"notification":1,"notifica":1,"otifications.if":1,"notificat":1,"schedule":1,"notifi":1,"interval":1,"immediately":1}
,"configured":{"adapter":1}
,"displayed":{"adapter":1}
,"table":{"fields":1,"manage":1}
,"fields":{"following":1}
,"field":{"description\u002Faction":1,"isabled":1,"described":1}
,"description\u002Faction":{"notification":1,"interval":1}
,"name":{"name":1,"notification":1,"package":1}
,"package":{"name":1,"notification":1}
,"state":{"schedule":1,"enabled":1,"functionally":1,"suspend":1}
,"enab":{"schedule":1}
,"icon":{"described":1,"create":1,"provide":1}
,"described":{"procedures":1,"step":1}
,"doing":{"option\u0027s":1}
,"option\u0027s":{"dropdown":1}
,"dropdown":{"list":1}
,"list":{"polling":1}
,"notifica":{"tion\u0027s":1}
,"tion\u0027s":{"state":1}
,"enabled":{"polling":1,"resume":1,"field":1}
,"performs":{"scheduled":1}
,"scheduled":{"suspended":1,"given":1}
,"suspended":{"polling":1,"state":1,"links":1}
,"removed":{"scheduler":1}
,"scheduler":{"disabled":1,"note":1}
,"even":{"enable":1}
,"run":{"true":1}
,"true":{"listener":1}
,"listener":{"option":1}
,"option":{"configure":1,"otherwise":1,"start":1}
,"configure":{"messagelistener":1}
,"functionally":{"identical":1}
,"identical":{"disabl":1}
,"disabl":{"state":1}
,"suspend":{"enabled":1}
,"resume":{"suspended":1}
,"links":{"help":1}
,"help":{"change":1}
,"change":{"states":1}
,"states":{"quickly":1}
,"quickly":{"multiple":1}
,"multiple":{"polling":1}
,"otifications.if":{"polling":1}
,"given":{"adapter":1}
,"control":{"field":1}
,"isabled":{"icon":1}
,"create":{"polling":1,"modify":1}
,"step":{"edit":1,"note":1,"enable":1}
,"edit":{"schedule":1}
,"click":{"icon":1,"icon.click":1,"save":1}
,"modify":{"schedule":1}
,"notificat":{"ion":1}
,"ion":{"continue":1}
,"continue":{"step":1}
,"first":{"disable":1}
,"disable":{"view":1}
,"view":{"schedule":1,"polling":1}
,"selected":{"polling":1,"ada":1}
,"notifi":{"cation":1}
,"cation":{"click":1}
,"icon.click":{"return":1}
,"return":{"adapter":1,"main":1}
,"main":{"polling":1}
,"page":{"create":1}
,"parameters":{"selected":1,"field":1}
,"ada":{"pter":1}
,"pter":{"notification":1}
,"provide":{"values":1}
,"values":{"following":1}
,"interval":{"(seconds)":1,"time":1}
,"(seconds)":{"type":1}
,"type":{"polling":1}
,"time":{"seconds":1}
,"seconds":{"overlap":1}
,"overlap":{"option":1}
,"otherwise":{"exception":1}
,"exception":{"generated":1}
,"generated":{"potentially":1}
,"potentially":{"receive":1}
,"receive":{"duplicate":1}
,"duplicate":{"messages":1}
,"topic":{"immediate":1}
,"immediate":{"select":1}
,"immediately":{"click":1}
,"save":{"schedule":1}
}
;Search.control.loadWordPairs(pairs);
