var pairs =
{
"configuring":{"messagerequestor":1,"managing":1,"input\u002Foutput":1}
,"messagerequestor":{"services":1,"service":1,"template":1}
,"services":{"messagerequestor":1,"based":1,"enable":1,"designer":1,"provide":1,"using":1,"configured":1,"start":1,"information":1}
,"service":{"allow":1,"invoke":1,"messagerequestor":1,"combination":1,"retrieve":1,"review":1,"conta":1,"select":1,"click":1,"created":1,"editor":1,"properties":1,"template":1,"provide":1,"pipeline":1,"using":1,"development":1}
,"allow":{"synchronously":1}
,"synchronously":{"request\u002Freply":1}
,"request\u002Freply":{"jms":1}
,"jms":{"destination":1,"services":1,"messages":1,"destinations":1,"adapter":1}
,"destination":{"(queue\u002Ftopic)":1,"type":1}
,"(queue\u002Ftopic)":{"conf":1}
,"conf":{"igure":1}
,"igure":{"messagerequestor":1}
,"based":{"specific":1}
,"specific":{"adapter":1}
,"adapter":{"nnections":1,"jms":1,"services":1,"service":1,"type":1,"connection":1,"settings":1,"name":1,"connec":1}
,"nnections":{"follow":1}
,"follow":{"steps":1}
,"steps":{"section":1,"configuring":1}
,"section":{"con":1}
,"con":{"figure":1}
,"figure":{"messagerequestor":1}
,"invoke":{"flow":1}
,"flow":{"java":1}
,"java":{"service":1}
,"combination":{"adapter":1}
,"enable":{"create":1}
,"create":{"jms":1}
,"messages":{"add":1,"int":1,"multiple":1}
,"add":{"service\u0027s":1}
,"service\u0027s":{"input":1,"associated":1}
,"input":{"signature":1,"output":1,"within":1}
,"signature":{"convert":1,"pipeline":1}
,"convert":{"jms":1}
,"int":{"documents":1}
,"documents":{"within":1}
,"within":{"services":1,"service":1}
,"designer":{"messagerequestor":1,"right-click":1,"instructions":1}
,"provide":{"values":1}
,"values":{"service\u0027s":1,"gnature":1}
,"pipeline":{"informa":1,"designer":1}
,"informa":{"tion":1}
,"tion":{"using":1,"input\u002Foutput":1}
,"using":{"messagerequestor":1,"apter":1}
,"configured":{"messagerequestor":1}
,"retrieve":{"messages":1}
,"multiple":{"jms":1}
,"destinations":{"provided":1,"available":1}
,"provided":{"hat":1}
,"hat":{"jms":1}
,"available":{"using":1,"templates":1}
,"apter":{"connection":1}
,"connection":{"configure":1,"name":1}
,"configure":{"messagerequestor":1}
,"review":{"steps":1}
,"managing":{"adapter":1}
,"start":{"designer":1}
,"right-click":{"package":1}
,"package":{"service":1}
,"conta":{"ined":1}
,"ined":{"select":1}
,"select":{"new":1,"parent":1,"adapter":1,"appropriate":1,"messagerequestor":1,"file":1}
,"new":{"adapter":1}
,"parent":{"namespace":1}
,"namespace":{"type":1}
,"type":{"name":1,"click":1,"field":1}
,"name":{"adapter":1,"click":1}
,"click":{"next":1,"finish":1}
,"next":{"select":1,"list":1}
,"appropriate":{"adapter":1}
,"list":{"available":1}
,"templates":{"select":1}
,"template":{"click":1,"necessary":1}
,"finish":{"service":1}
,"created":{"parameters":1}
,"parameters":{"controls":1}
,"controls":{"isplayed":1}
,"isplayed":{"adapter":1}
,"editor":{"select":1}
,"settings":{"tab":1,"audit":1}
,"tab":{"time":1,"destination":1,"shows":1}
,"time":{"confirm":1}
,"confirm":{"adapter":1}
,"properties":{"adapter":1}
,"necessary":{"send":1}
,"send":{"message":1}
,"message":{"tab":1}
,"field":{"populated":1}
,"populated":{"either":1}
,"either":{"topic":1}
,"topic":{"queue":1}
,"queue":{"lue":1}
,"lue":{"determined":1}
,"determined":{"service\u0027s":1}
,"associated":{"adapter":1}
,"connec":{"tion":1}
,"input\u002Foutput":{"tab":1,"settings":1}
,"shows":{"service\u0027s":1}
,"output":{"signatures":1}
,"signatures":{"messagerequestor":1}
,"gnature":{"input":1}
,"instructions":{"using":1}
,"information":{"configuring":1}
,"audit":{"permissions":1}
,"permissions":{"results":1}
,"results":{"tabs":1}
,"tabs":{"webmethods":1}
,"webmethods":{"service":1}
,"development":{"help":1}
,"help":{"release":1}
,"release":{"select":1}
,"file":{"save":1}
}
;Search.control.loadWordPairs(pairs);
