var pairs =
{
"configuring":{"watt.jmsadapter.weblogic":1}
,"watt.jmsadapter.weblogic":{"parameter":1,"=true":1}
,"parameter":{"authenticate":1,"watt.jmsadapter.weblogic":1,"integration":1,"listed":1}
,"authenticate":{"successfully":1,"multiple":1}
,"successfully":{"multiple":1}
,"multiple":{"weblogic":1}
,"weblogic":{"servers":1}
,"servers":{"watt.jmsadapter.weblogic":1,"exten":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"click":1}
,"click":{"settings":1,"save":1,"show":1}
,"settings":{"extended":1,"authenticate":1,"editor":1}
,"extended":{"edit":1,"settings":1,"setting":1}
,"edit":{"extended":1}
,"exten":{"ded":1}
,"ded":{"settings":1}
,"editor":{"specify":1}
,"specify":{"following":1}
,"following":{"watt.jmsadapter.weblogic":1}
,"=true":{"default":1}
,"default":{"value":1}
,"value":{"false":1}
,"false":{"click":1}
,"save":{"changes":1}
,"changes":{"key":1}
,"key":{"new":1,"visible":1}
,"new":{"property":1}
,"property":{"appears":1}
,"appears":{"extended":1}
,"setting":{"list":1}
,"list":{"click":1}
,"show":{"hide":1}
,"hide":{"keys":1}
,"keys":{"watt.jmsadapter.weblogic":1}
,"listed":{"key":1}
,"visible":{"restart":1}
,"restart":{"integration":1}
}
;Search.control.loadWordPairs(pairs);
