var pairs =
{
"connection":{"pooling":1,"management":1,"pools":1,"adapter":1,"pool":1}
,"pooling":{"integration":1,"connection":1}
,"integration":{"server":1}
,"server":{"includes":1,"maintains":1}
,"includes":{"connection":1}
,"management":{"service":1}
,"service":{"dynamically":1}
,"dynamically":{"anages":1}
,"anages":{"connections":1}
,"connections":{"connection":1,"attributes":1}
,"pools":{"based":1,"memory":1,"impr":1}
,"based":{"configurati":1}
,"configurati":{"settings":1}
,"settings":{"specify":1}
,"specify":{"connection":1}
,"adapter":{"services":1}
,"services":{"connection":1,"reuse":1}
,"pool":{"collection":1}
,"collection":{"connections":1}
,"attributes":{"integration":1}
,"maintains":{"connection":1}
,"memory":{"connection":1}
,"impr":{"ove":1}
,"ove":{"performance":1}
,"performance":{"enabling":1}
,"enabling":{"adapter":1}
,"reuse":{"open":1}
,"open":{"onnections":1}
,"onnections":{"instead":1}
,"instead":{"opening":1}
,"opening":{"new":1}
,"new":{"connections":1}
}
;Search.control.loadWordPairs(pairs);
