var pairs =
{
"uninstalling":{"adapter":1}
,"adapter":{"jms":1,"directory":1}
,"jms":{"6.1":1,"start":1,"oracle":1,"installed":1}
,"6.1":{"sp1":1}
,"sp1":{"uninstall":1,"shut":1,"choose":1}
,"uninstall":{"adapter":1,"documentation":1}
,"shut":{"down":1}
,"down":{"integration":1}
,"integration":{"server":1,"server_directory":1}
,"server":{"hosts":1,"product":1,"uninstaller":1}
,"hosts":{"adapter":1}
,"start":{"software":1}
,"software":{"uninstaller":1,"ag_directory":1}
,"uninstaller":{"selecting":1,"removes":1,"delete":1}
,"selecting":{"software":1}
,"ag_directory":{"contains":1}
,"contains":{"host":1}
,"host":{"integration":1}
,"product":{"selection":1}
,"selection":{"list":1}
,"list":{"select":1}
,"select":{"adapters":1}
,"adapters":{"webmethods":1}
,"webmethods":{"adapter":1,"broker":1}
,"choose":{"uninstall":1}
,"documentation":{"tems":1}
,"tems":{"installed":1}
,"installed":{"webmethods":1,"integration":1,"adapt":1}
,"broker":{"client":1}
,"client":{"libraries":1}
,"libraries":{"jms":1,"restart":1}
,"oracle":{"jndi":1}
,"jndi":{"libraries":1}
,"restart":{"host":1}
,"removes":{"files":1}
,"files":{"related":1,"created":1}
,"related":{"adapter":1}
,"server_directory":{"\u005Cpackages\u005Cwmjmsadapter":1,"\u005Cpackages":1,"\u005Cinstances\u005Cdefault\u005Cpackages":1}
,"\u005Cpackages\u005Cwmjmsadapter":{"directory":1}
,"directory":{"however":1,"structure":1,"integration":1}
,"however":{"uninstaller":1}
,"delete":{"files":1,"adapter":1,"wmjmsadapter":1}
,"created":{"installed":1}
,"adapt":{"(for":1}
,"(for":{"example":1}
,"example":{"user-created":1}
,"user-created":{"configuration":1}
,"configuration":{"files)":1}
,"files)":{"oes":1}
,"oes":{"delete":1}
,"structure":{"integration":1}
,"\u005Cpackages":{"directory":1}
,"\u005Cinstances\u005Cdefault\u005Cpackages":{"delete":1}
,"wmjmsadapter":{"directo":1}
}
;Search.control.loadWordPairs(pairs);
