var pairs =
{
"changing":{"integration":1}
,"integration":{"server":1}
,"server":{"transaction":1,"default":1,"edit":1,"add":1,"administrator\u2019s":1}
,"transaction":{"timeout":1,"manager":1}
,"timeout":{"interval":1,"timeout":1,"(no_timeout)":1,"transaction":1,"parameter":1,"value":1}
,"interval":{"integration":1,"text":1}
,"default":{"transaction":1,"server.cnf":1}
,"(no_timeout)":{"change":1}
,"change":{"server\u0027s":1}
,"server\u0027s":{"transaction":1}
,"text":{"editor":1}
,"editor":{"modify":1}
,"modify":{"server.cnf":1}
,"server.cnf":{"file":1}
,"file":{"add":1,"describ":1,"changes":1,"watt.art.tmgr.timeout=transactiontimeout":1,"webmethods":1}
,"add":{"parameter":1,"file":1,"following":1}
,"parameter":{"below":1,"exist":1,"server.cnf":1,"halt":1}
,"below":{"note":1,"shut":1}
,"note":{"parameter":1}
,"exist":{"default":1}
,"describ":{"below":1}
,"shut":{"down":1}
,"down":{"integration":1}
,"edit":{"file":1}
,"changes":{"restart":1}
,"restart":{"server":1}
,"following":{"parameter":1}
,"watt.art.tmgr.timeout=transactiontimeout":{"transactiontimeout":1}
,"transactiontimeout":{"number":1}
,"number":{"seconds":1}
,"seconds":{"transaction":1,"tra":1,"flow":1,"complete":1}
,"halt":{"executi":1}
,"executi":{"flow":1}
,"flow":{"maximum":1,"takes":1}
,"maximum":{"number":1}
,"tra":{"nsaction":1}
,"nsaction":{"remain":1}
,"remain":{"open":1}
,"open":{"considered":1}
,"considered":{"valid":1}
,"valid":{"example":1}
,"example":{"current":1}
,"current":{"transaction":1}
,"value":{"seconds":1}
,"takes":{"120":1}
,"120":{"seconds":1}
,"complete":{"transaction":1}
,"manager":{"rollback":1}
,"rollback":{"registered":1}
,"registered":{"operations":1}
,"operations":{"regardless":1}
,"regardless":{"execution":1}
,"execution":{"status":1}
,"status":{"information":1}
,"information":{"adding":1}
,"adding":{"parameters":1}
,"parameters":{"server.c":1}
,"server.c":{"file":1}
,"webmethods":{"integration":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"release":1}
}
;Search.control.loadWordPairs(pairs);
