var pairs =
{
"disabling":{"adapter":1}
,"adapter":{"connections":1,"jms":1,"connection":1}
,"connections":{"adapter":1,"disabled":1,"using":1,"screen":1}
,"jms":{"connections":1,"destination":1}
,"disabled":{"edit":1,"enabled":1}
,"edit":{"delete":1}
,"delete":{"disable":1}
,"disable":{"adapter":1,"connection":1}
,"using":{"integration":1}
,"integration":{"server":1}
,"server":{"administrator":1}
,"administrator":{"note":1,"navigation":1,"enables":1}
,"note":{"disable":1}
,"connection":{"stops":1,"however":1,"used":1,"adapters":1,"want":1,"becomes":1,"displays":1}
,"stops":{"(but":1}
,"(but":{"disable)":1}
,"disable)":{"notifications":1}
,"notifications":{"associated":1,"notification":1}
,"associated":{"connection":1}
,"however":{"disable":1}
,"used":{"ification":1}
,"ification":{"run":1}
,"run":{"true":1}
,"true":{"listener":1}
,"listener":{"enabled":1}
,"enabled":{"(see":1,"column":1}
,"(see":{"configuring":1}
,"configuring":{"messagelistener":1}
,"messagelistener":{"notifications":1}
,"notification":{"continues":1}
,"continues":{"function":1}
,"function":{"usual":1}
,"usual":{"runs":1}
,"runs":{"whenever":1}
,"whenever":{"message":1}
,"message":{"arrives":1}
,"arrives":{"jms":1}
,"destination":{"disable":1}
,"adapters":{"menu":1}
,"menu":{"integration":1}
,"navigation":{"area":1}
,"area":{"click":1}
,"click":{"adapter":1,"enabled":1}
,"screen":{"click":1}
,"column":{"connection":1,"connections":1}
,"want":{"disable":1,"enable":1}
,"becomes":{"disabled":1}
,"enable":{"integration":1}
,"enables":{"adapter":1}
,"displays":{"enabled":1}
}
;Search.control.loadWordPairs(pairs);
