var pairs =
{
"importing":{"exporting":1}
,"exporting":{"packages":1,"allows":1}
,"packages":{"import":1,"using":1,"export":1,"webmethods":1}
,"import":{"export":1,"renam":1}
,"export":{"packages":1,"package":1,"rename":1}
,"using":{"designer":1}
,"designer":{"exporting":1}
,"allows":{"export":1}
,"package":{".zip":1,"important":1,"import":1,"lose":1,"details":1}
,".zip":{"file":1}
,"file":{"save":1,"ported":1}
,"save":{"hard":1}
,"hard":{"drive":1}
,"drive":{".zip":1}
,"ported":{"package":1}
,"important":{"rename":1}
,"rename":{"packages":1,"function":1}
,"function":{"omparable":1}
,"omparable":{"moving":1}
,"moving":{"package":1}
,"renam":{"package":1}
,"lose":{"triggers":1}
,"triggers":{"connections":1}
,"connections":{"notifica":1}
,"notifica":{"tions":1}
,"tions":{"associated":1}
,"associated":{"package":1}
,"details":{"importing":1}
,"webmethods":{"service":1}
,"service":{"development":1}
,"development":{"help":1}
,"help":{"release":1}
}
;Search.control.loadWordPairs(pairs);
