var pairs =
{
"exactly":{"once":1}
,"once":{"notifications":1,"notification":1}
,"notifications":{"adapter":1,"exactly":1,"supported":1}
,"adapter":{"notifications":1}
,"notification":{"feature":1,"data":1,"publish":1}
,"feature":{"feature":1,"ensures":1}
,"ensures":{"notification":1}
,"data":{"duplicated":1,"directly":1}
,"duplicated":{"even":1}
,"even":{"failure":1}
,"failure":{"occurs":1,"integration":1}
,"occurs":{"during":1}
,"during":{"processing":1}
,"processing":{"achieved":1,"failure":1}
,"achieved":{"assigning":1}
,"assigning":{"unique":1}
,"unique":{"ids":1}
,"ids":{"publishabl":1,"note":1}
,"publishabl":{"document":1}
,"document":{"processing":1}
,"integration":{"server":1}
,"server":{"checks":1}
,"checks":{"duplicate":1}
,"duplicate":{"records":1}
,"records":{"storage":1}
,"storage":{"ignores":1}
,"ignores":{"dup":1}
,"dup":{"licate":1}
,"licate":{"ids":1}
,"note":{"exactly":1}
,"supported":{"notification":1}
,"publish":{"messages":1}
,"messages":{"associate":1}
,"associate":{"notification":1}
,"directly":{"service":1}
}
;Search.control.loadWordPairs(pairs);
