var pairs =
{
"using":{"messageproducer":1,"pipeline":1,"following":1}
,"messageproducer":{"services":1,"service":1}
,"services":{"enable":1,"documenttotextmessage":1,"information":1}
,"enable":{"messageproducer":1}
,"service":{"send":1,"within":1,"designer":1}
,"send":{"jms":1}
,"jms":{"message":1,"dest":1,"services":1,"destination":1}
,"message":{"queue":1,"object":1}
,"queue":{"topic":1,"jms":1,"adapter":1}
,"topic":{"provide":1,"jms":1,"jmsdeliverymode":1}
,"provide":{"values":1,"string":1}
,"values":{"parameters":1,"pipeline":1,"using":1}
,"parameters":{"lis":1}
,"lis":{"ted":1}
,"ted":{"below":1}
,"below":{"service\u0027s":1}
,"service\u0027s":{"input":1}
,"input":{"signature":1}
,"signature":{"configuring":1}
,"configuring":{"adapter":1,"document-to-message":1}
,"adapter":{"service":1,"jms":1,"connection":1}
,"within":{"flow":1}
,"flow":{"service":1}
,"designer":{"either":1}
,"either":{"map":1}
,"map":{"values":1}
,"pipeline":{"constant":1,"editor":1}
,"constant":{"values":1}
,"editor":{"parameter":1}
,"parameter":{"description\u002Faction":1}
,"description\u002Faction":{"jmsmessage":1}
,"jmsmessage":{"jms":1}
,"object":{"want":1,"using":1,"jms":1}
,"want":{"send":1}
,"dest":{"ination":1}
,"ination":{"create":1}
,"create":{"jms":1}
,"following":{"adapter":1}
,"documenttotextmessage":{"documenttoobjectmessage":1}
,"documenttoobjectmessage":{"documenttomapmessage":1}
,"documenttomapmessage":{"documenttobytesmessage":1}
,"documenttobytesmessage":{"documenttostreammessage":1}
,"documenttostreammessage":{"configuring":1}
,"document-to-message":{"conversion":1}
,"conversion":{"services":1}
,"information":{"jmsdestination":1}
,"jmsdestination":{"jms":1}
,"destination":{"object":1,"jndi":1,"queue":1,"topic":1}
,"jndi":{"name":1}
,"name":{"(string)":1}
,"(string)":{"adapter":1}
,"connection":{"configured":1}
,"configured":{"queue":1,"topic":1}
,"jmsdeliverymode":{"(optional)":1}
,"(optional)":{"delivery":1,"message\u0027s":1}
,"delivery":{"mode":1}
,"mode":{"(persistent":1}
,"(persistent":{"non_persi":1}
,"non_persi":{"stent)":1}
,"stent)":{"provide":1}
,"string":{"literals":1}
,"literals":{"\u0027persistent":1}
,"\u0027persistent":{"\u0027non":1,"jmspriority":1}
,"\u0027non":{"_persistent":1}
,"_persistent":{"integer":1}
,"integer":{"value":1}
,"value":{"default":1}
,"default":{"\u0027persistent":1,"jmstimetolive":1,"(forever)":1}
,"jmspriority":{"(optional)":1}
,"message\u0027s":{"priority":1,"lifetime":1}
,"priority":{"0-9":1}
,"0-9":{"default":1}
,"jmstimetolive":{"(optional)":1}
,"lifetime":{"(in":1}
,"(in":{"milliseconds)":1}
,"milliseconds)":{"default":1}
}
;Search.control.loadWordPairs(pairs);
