var pairs =
{
"editing":{"notifications":1}
,"notifications":{"designer":1,"change":1,"integration":1}
,"designer":{"edit":1,"expand":1,"displays":1,"select":1}
,"edit":{"notifications":1,"notification":1,"select":1,"designer":1,"using":1,"note":1}
,"change":{"connection":1}
,"connection":{"associated":1,"adapter":1,"notification":1}
,"associated":{"adapter":1}
,"adapter":{"ification":1,"service":1,"connections":1}
,"ification":{"built-in":1}
,"built-in":{"service":1}
,"service":{"pub.art.notification:setpollingnotificationnodeconnection":1,"notification":1,"development":1}
,"pub.art.notification:setpollingnotificationnodeconnection":{"information":1}
,"information":{"changing":1}
,"changing":{"connection":1}
,"notification":{"design":1,"review":1,"want":1,"notification":1,"template\u0027s":1,"editor":1,"select":1,"spe":1,"parameters":1,"reset":1,"following":1,"options":1}
,"design":{"time":1}
,"time":{"edit":1}
,"review":{"steps":1}
,"steps":{"configuring":1}
,"configuring":{"managing":1,"notification":1}
,"managing":{"notifications":1}
,"integration":{"server":1,"feature":1}
,"server":{"administrator":1}
,"administrator":{"enable":1}
,"enable":{"connection":1}
,"want":{"edi":1,"edit":1}
,"edi":{"refer":1}
,"refer":{"enabling":1}
,"enabling":{"adapter":1,"connections":1}
,"connections":{"instructions":1,"designer":1}
,"instructions":{"enabling":1}
,"expand":{"package":1}
,"package":{"folder":1}
,"folder":{"contain":1}
,"contain":{"notificatio":1}
,"notificatio":{"want":1,"options":1}
,"select":{"notification":1,"check":1,"lock":1,"appropriate":1,"unlock":1}
,"displays":{"notification":1}
,"template\u0027s":{"apter":1}
,"apter":{"notification":1}
,"editor":{"following":1}
,"following":{"vcs":1}
,"vcs":{"integration":1,"client":1}
,"feature":{"enabled":1,"team":1}
,"enabled":{"right-click":1,"righ":1}
,"right-click":{"notification":1}
,"check":{"vcs":1,"notificatio":1,"enter":1,"notification":1}
,"righ":{"t-click":1}
,"t-click":{"notification":1}
,"lock":{"edit":1}
,"using":{"local":1}
,"local":{"service":1}
,"development":{"feature":1}
,"team":{"menu":1}
,"menu":{"designer":1,"depend":1}
,"appropriate":{"option":1}
,"option":{"check":1}
,"options":{"available":1}
,"available":{"team":1}
,"depend":{"vcs":1}
,"client":{"modify":1}
,"modify":{"values":1}
,"values":{"notification\u0027s":1}
,"notification\u0027s":{"parameters":1,"parameter":1}
,"parameters":{"neede":1,"adap":1}
,"neede":{"detailed":1}
,"detailed":{"descriptions":1}
,"descriptions":{"notification\u0027s":1}
,"parameter":{"section":1}
,"section":{"configuring":1}
,"spe":{"cific":1}
,"cific":{"type":1}
,"type":{"notification":1}
,"note":{"edit":1}
,"adap":{"ter":1}
,"ter":{"notification":1}
,"reset":{"complete":1}
,"complete":{"modifications":1}
,"modifications":{"save":1}
,"save":{"notification":1}
,"enter":{"check-in":1}
,"check-in":{"comment":1}
,"comment":{"click":1}
,"click":{"vcs":1}
,"unlock":{"using":1}
}
;Search.control.loadWordPairs(pairs);
