var pairs =
{
"considerations":{"installing":1}
,"installing":{"adapter":1,"upgrading":1}
,"adapter":{"jms":1}
,"jms":{"packages":1,"installation":1}
,"packages":{"integration":1}
,"integration":{"server":1}
,"server":{"cluster":1}
,"cluster":{"standard":1}
,"standard":{"adapter":1}
,"installation":{"procedures":1}
,"procedures":{"machine":1}
,"machine":{"described":1}
,"described":{"installing":1}
,"upgrading":{"uninstalling":1}
,"uninstalling":{"adapter":1}
}
;Search.control.loadWordPairs(pairs);
