var pairs =
{
"disabling":{"redirection":1}
,"redirection":{"administrative":1}
,"administrative":{"services":1}
,"services":{"mentioned":1,"ould":1,"used":1,"stored":1,"reside":1,"shut":1}
,"mentioned":{"webmethods":1}
,"webmethods":{"integration":1}
,"integration":{"server":1}
,"server":{"clustering":1,"cannot":1,"cluster":1,"othe":1,"remember":1,"administrator":1,"administrator\u2019s":1}
,"clustering":{"server":1}
,"cannot":{"handle":1}
,"handle":{"client\u0027s":1}
,"client\u0027s":{"service":1}
,"service":{"request":1}
,"request":{"automatically":1,"server":1}
,"automatically":{"redirect":1}
,"redirect":{"request":1}
,"cluster":{"however":1,"disable":1}
,"however":{"adapter":1}
,"adapter":{"jms":1,"allow":1}
,"jms":{"uses":1,"services":1}
,"uses":{"certain":1}
,"certain":{"predefined":1}
,"predefined":{"administrative":1}
,"ould":{"allow":1}
,"allow":{"redirected":1,"ervices":1}
,"redirected":{"services":1,"configuration":1}
,"used":{"int":1}
,"int":{"ernally":1}
,"ernally":{"configure":1}
,"configure":{"adapter":1,"two":1}
,"ervices":{"redirected":1}
,"configuration":{"specifications":1}
,"specifications":{"saved":1}
,"saved":{"multiple":1}
,"multiple":{"servers":1}
,"servers":{"undesirable":1}
,"undesirable":{"result":1}
,"result":{"example":1}
,"example":{"configure":1}
,"two":{"adapter":1}
,"stored":{"server":1}
,"othe":{"stored":1}
,"remember":{"dapter":1}
,"dapter":{"services":1}
,"reside":{"webmethods":1}
,"disable":{"redirection":1}
,"shut":{"down":1}
,"down":{"integration":1}
,"administrator":{"procedure":1}
,"procedure":{"webmethods":1}
,"administrator\u2019s":{"guide":1}
,"guide":{"release":1}
,"release":{"edit":1}
,"edit":{"following":1}
,"following":{"file":1,"line":1}
,"file":{"integrationserver_directory":1,"<value":1,"restart":1}
,"integrationserver_directory":{"\u005Cconfig\u005Credir.cnf":1}
,"\u005Cconfig\u005Credir.cnf":{"add":1}
,"add":{"following":1}
,"line":{"file":1}
,"<value":{"name=\u0022":1}
,"name=\u0022":{"wm.art":1}
,"wm.art":{"false":1}
,"false":{"<\u002Fvalue>":1}
,"<\u002Fvalue>":{"save":1}
,"save":{"file":1}
,"restart":{"webmethods":1}
}
;Search.control.loadWordPairs(pairs);
