var pairs =
{
"considerations":{"using":1}
,"using":{"messagelistener":1}
,"messagelistener":{"notifications":1,"notification":1}
,"notifications":{"using":1}
,"notification":{"integration":1,"publishes":1,"configured":1,"subscribe":1,"adapt":1,"ith":1}
,"integration":{"server":1}
,"server":{"broker":1,"hosts":1,"able":1,"adapter":1}
,"broker":{"configured":1}
,"configured":{"(and":1,"publish":1}
,"(and":{"service":1}
,"service":{"associated":1,"(rather":1}
,"associated":{"notification)":1}
,"notification)":{"notification":1}
,"publishes":{"document":1}
,"document":{"ocal":1,"integration":1,"type":1}
,"ocal":{"mode":1}
,"mode":{"integration":1}
,"hosts":{"messagelistener":1,"notification":1}
,"publish":{"document":1,"document)":1}
,"subscribe":{"notific":1}
,"notific":{"ation\u0027s":1}
,"ation\u0027s":{"publishable":1}
,"publishable":{"document":1}
,"type":{"differe":1,"notif":1}
,"differe":{"integration":1}
,"able":{"understand":1}
,"understand":{"document\u0027s":1}
,"document\u0027s":{"serialized":1}
,"serialized":{"ssage":1}
,"ssage":{"unless":1}
,"unless":{"integration":1}
,"adapter":{"jms":1}
,"jms":{"installed":1}
,"installed":{"configure":1}
,"configure":{"messagelistener":1}
,"adapt":{"creates":1}
,"creates":{"publishable":1}
,"notif":{"ication":1}
,"ication":{"associate":1}
,"associate":{"messagelistener":1}
,"ith":{"service":1}
,"(rather":{"publish":1}
,"document)":{"servic":1}
,"servic":{"input":1}
,"input":{"signature":1}
,"signature":{"notification\u0027s":1}
,"notification\u0027s":{"blishable":1}
,"blishable":{"document":1}
}
;Search.control.loadWordPairs(pairs);
