var pairs =
{
"using":{"document-to-message":1,"pipeline":1}
,"document-to-message":{"conversion":1}
,"conversion":{"services":1}
,"services":{"document-to-message":1,"contain":1,"documenttobytesmessage":1,"jmsheader":1,"properties":1}
,"contain":{"foll":1,"jms":1}
,"foll":{"owing":1}
,"owing":{"input":1,"output":1}
,"input":{"signatures":1,"signature":1}
,"signatures":{"provide":1}
,"provide":{"values":1}
,"values":{"parameters":1,"pipeline":1,"using":1}
,"parameters":{"listed":1,"corresponding":1}
,"listed":{"below":1}
,"below":{"servic":1}
,"servic":{"e\u0027s":1}
,"e\u0027s":{"input":1}
,"signature":{"configuring":1,"parameter":1}
,"configuring":{"adapter":1,"document-to-message":1}
,"adapter":{"service":1}
,"service":{"wit":1,"designer":1}
,"wit":{"hin":1}
,"hin":{"flow":1}
,"flow":{"service":1}
,"designer":{"either":1}
,"either":{"map":1}
,"map":{"values":1,"message":1}
,"pipeline":{"constant":1,"editor":1}
,"constant":{"values":1}
,"editor":{"parameter":1}
,"parameter":{"description\u002Faction":1}
,"description\u002Faction":{"message":1,"jmsmessageclass":1}
,"message":{"body":1,"data":1,"object":1}
,"body":{"documenttotextmessage":1,"string":1,"obj":1,"documen":1,"fields":1,"obje":1,"docu":1}
,"documenttotextmessage":{"message":1}
,"string":{"called":1,"containing":1}
,"called":{"textmessagebody":1,"objectmessagebody":1,"mapmessagebody":1,"bytesmessagebody":1}
,"textmessagebody":{"map":1}
,"data":{"field":1,"object":1}
,"field":{"documenttoobjectmessage":1,"documenttomapmessage":1,"documenttostreammessage":1}
,"documenttoobjectmessage":{"message":1}
,"obj":{"ect":1}
,"ect":{"called":1}
,"objectmessagebody":{"map":1,"contains":1}
,"object":{"field":1,"sent":1,"passed":1}
,"documenttomapmessage":{"message":1}
,"documen":{"called":1}
,"mapmessagebody":{"contains":1}
,"contains":{"parameters":1}
,"corresponding":{"mess":1}
,"mess":{"age":1}
,"age":{"body":1}
,"fields":{"added":1}
,"added":{"step":1}
,"step":{"configuring":1}
,"documenttobytesmessage":{"message":1}
,"obje":{"called":1}
,"bytesmessagebody":{"map":1}
,"documenttostreammessage":{"message":1}
,"docu":{"ment":1}
,"ment":{"called":1}
,"jmsheader":{"document":1}
,"document":{"contain":1}
,"jms":{"header":1,"property":1,"essage":1,"message":1,"destination":1}
,"header":{"fields":1}
,"properties":{"document":1}
,"property":{"fields":1}
,"output":{"signature":1}
,"jmsmessageclass":{"string":1}
,"containing":{"name":1}
,"name":{"java":1}
,"java":{"class":1}
,"class":{"jms":1}
,"essage":{"jmsmessage":1}
,"jmsmessage":{"jms":1}
,"sent":{"jms":1}
,"destination":{"object":1}
,"passed":{"messageproducer":1}
,"messageproducer":{"messagerequest":1}
,"messagerequest":{"service":1}
}
;Search.control.loadWordPairs(pairs);
