var pairs =
{
"using":{"version":1}
,"version":{"control":1}
,"control":{"systems":1,"system":1}
,"systems":{"manage":1}
,"manage":{"adapter":1}
,"adapter":{"elements":1,"supports":1,"packages":1,"suppo":1}
,"elements":{"adapter":1,"version":1,"supporting":1}
,"supports":{"version":1}
,"system":{"(vcs)":1,"esigner":1}
,"(vcs)":{"integr":1}
,"integr":{"ation":1}
,"ation":{"feature":1}
,"feature":{"provided":1,"beginning":1,"designer":1,"extends":1,"webmethods":1}
,"provided":{"designer":1}
,"designer":{"enable":1,"feature":1,"informa":1}
,"enable":{"feat":1}
,"feat":{"ure":1}
,"ure":{"integration":1,"administering":1}
,"integration":{"server":1,"feat":1,"feature":1,"fea":1}
,"server":{"check":1,"8.2":1}
,"check":{"adapter":1,"package":1}
,"packages":{"elements":1}
,"esigner":{"information":1}
,"information":{"vcs":1}
,"vcs":{"integration":1,"directly":1}
,"administering":{"vcs":1}
,"beginning":{"integration":1}
,"8.2":{"sp3":1}
,"sp3":{"adapter":1}
,"suppo":{"rts":1}
,"rts":{"local":1}
,"local":{"service":1}
,"service":{"development":1}
,"development":{"feature":1,"compares":1,"help":1}
,"extends":{"functionality":1}
,"functionality":{"vcs":1}
,"fea":{"ture":1}
,"ture":{"check":1}
,"package":{"elements":1}
,"supporting":{"files":1}
,"files":{"vcs":1}
,"directly":{"designer":1}
,"informa":{"tion":1}
,"tion":{"local":1}
,"compares":{"vcs":1}
,"webmethods":{"service":1}
}
;Search.control.loadWordPairs(pairs);
