var pairs =
{
"changing":{"connection":1,"service\u0027s":1}
,"connection":{"adapter":1,"service":1,"run":1}
,"adapter":{"service":1}
,"service":{"run":1,"uses":1,"interact":1}
,"run":{"time":1}
,"time":{"integration":1,"dynamically":1}
,"integration":{"server":1}
,"server":{"enables":1}
,"enables":{"dynamically":1}
,"dynamically":{"select":1,"changing":1}
,"select":{"connection":1}
,"uses":{"interact":1}
,"interact":{"adapter\u0027s":1,"multiple":1}
,"adapter\u0027s":{"resource":1}
,"resource":{"feature":1}
,"feature":{"nables":1}
,"nables":{"service":1}
,"multiple":{"similar":1}
,"similar":{"backen":1}
,"backen":{"resources":1}
,"resources":{"information":1}
,"information":{"overriding":1}
,"overriding":{"service\u0027s":1}
,"service\u0027s":{"default":1,"connection":1}
,"default":{"nnection":1}
,"nnection":{"run":1}
}
;Search.control.loadWordPairs(pairs);
