var pairs =
{
"adapter":{"notifications":1,"jms":1,"message":1}
,"notifications":{"adapter":1,"better":1}
,"jms":{"provides":1,"destination":1,"connections":1,"leveraging":1}
,"provides":{"notification":1}
,"notification":{"called":1,"either":1,"invoke":1,"notification":1,"publishes":1,"integration":1,"param":1}
,"called":{"messagelistener":1}
,"messagelistener":{"monit":1,"notificatio":1,"notifications":1}
,"monit":{"ors":1}
,"ors":{"specified":1}
,"specified":{"jms":1,"connect":1}
,"destination":{"(queue":1,"configure":1}
,"(queue":{"topic)":1}
,"topic)":{"notifie":1}
,"notifie":{"adapter":1}
,"message":{"arrives":1}
,"arrives":{"destination":1}
,"configure":{"notification":1}
,"either":{"publish":1}
,"publish":{"ification\u0027s":1}
,"ification\u0027s":{"associated":1}
,"associated":{"publishable":1}
,"publishable":{"document":1,"documents":1}
,"document":{"confi":1,"integration":1,"associa":1,"invokes":1,"details":1}
,"confi":{"gure":1}
,"gure":{"notification":1}
,"invoke":{"flow":1}
,"flow":{"java":1,"service":1}
,"java":{"service":1}
,"service":{"using":1,"registered":1,"reacts":1}
,"using":{"data":1,"designer":1}
,"data":{"notification":1,"changes":1}
,"publishes":{"document":1}
,"integration":{"server":1}
,"server":{"trigger":1,"receives":1,"publishable":1}
,"trigger":{"monitor":1,"flow":1}
,"monitor":{"given":1}
,"given":{"publishable":1}
,"associa":{"ted":1}
,"ted":{"notification":1}
,"receives":{"publishable":1}
,"invokes":{"flow":1}
,"registered":{"trigger":1}
,"reacts":{"data":1}
,"changes":{"contained":1}
,"contained":{"notification\u0027s":1}
,"notification\u0027s":{"publishable":1}
,"details":{"abou":1}
,"abou":{"integration":1}
,"documents":{"publish-subscribe":1}
,"publish-subscribe":{"developer\u2019s":1}
,"developer\u2019s":{"guide":1}
,"guide":{"release":1}
,"release":{"note":1}
,"note":{"need":1}
,"need":{"client":1}
,"client":{"notifications":1,"specified":1}
,"better":{"specify":1}
,"specify":{"along":1}
,"along":{"notification":1}
,"param":{"eters":1}
,"eters":{"using":1}
,"designer":{"creating":1}
,"creating":{"connection":1}
,"connection":{"factory":1,"reated":1,"imits":1,"pool":1}
,"factory":{"adapter":1,"jms":1,"connection":1}
,"connections":{"client":1,"connection":1}
,"connect":{"ion":1}
,"ion":{"factory":1}
,"reated":{"connection":1}
,"imits":{"adapter":1}
,"leveraging":{"connection":1}
,"pool":{"instructions":1}
,"instructions":{"configuring":1}
,"configuring":{"messagelistener":1}
,"notificatio":{"configuring":1}
}
;Search.control.loadWordPairs(pairs);
