var pairs =
{
"explicit":{"transactions":1,"transaction":1}
,"transactions":{"explicit":1,"need":1,"singl":1,"sure":1}
,"need":{"explicitly":1}
,"explicitly":{"ntrol":1}
,"ntrol":{"transactional":1}
,"transactional":{"units":1}
,"units":{"work":1}
,"work":{"dditional":1}
,"dditional":{"services":1}
,"services":{"known":1,"flow":1}
,"known":{"built-in":1}
,"built-in":{"services":1}
,"flow":{"note":1}
,"note":{"using":1,"explicit":1}
,"using":{"messagerequestor":1,"flows":1}
,"messagerequestor":{"service":1}
,"service":{"requesting":1,"sends":1,"automatically":1,"executed":1,"development":1}
,"requesting":{"messag":1,"message":1}
,"messag":{"service":1}
,"sends":{"jms":1}
,"jms":{"destination":1,"provider":1,"specification":1,"roviders":1,"connections":1}
,"destination":{"cannot":1}
,"cannot":{"lled":1}
,"lled":{"back":1}
,"back":{"operation":1}
,"operation":{"fails":1}
,"fails":{"within":1}
,"within":{"transaction":1,"ransaction":1}
,"transaction":{"conte":1,"management":1,"context":1,"require":1,"start":1,"complete":1,"pes":1}
,"conte":{"messagerequestor":1}
,"automatically":{"comm":1}
,"comm":{"requesting":1}
,"message":{"jms":1}
,"provider":{"deliver":1}
,"deliver":{"request":1}
,"request":{"therefore":1}
,"therefore":{"ceive":1}
,"ceive":{"reply":1}
,"reply":{"message":1}
,"specification":{"formation":1}
,"formation":{"transaction":1}
,"management":{"requirements":1,"adapter":1}
,"requirements":{"jms":1}
,"roviders":{"transaction":1}
,"context":{"starts":1,"completed":1,"contain":1,"started":1,"provided":1}
,"starts":{"pub.art.transaction.starttransaction":1}
,"pub.art.transaction.starttransaction":{"service":1,"pub.art.transaction.starttransaction":1,"pub.art.transaction.committransaction":1}
,"executed":{"transaction":1,"implicit":1}
,"completed":{"hen":1,"everse":1}
,"hen":{"either":1}
,"either":{"pub.art.transaction.committransaction":1,"committransaction":1}
,"pub.art.transaction.committransaction":{"pub.art.transaction.rollbacktransaction":1,"pub.art.transaction.committransaction":1,"following":1,"information":1}
,"pub.art.transaction.rollbacktransaction":{"service":1}
,"implicit":{"transactions":1}
,"singl":{"transaction":1}
,"contain":{"number":1}
,"number":{"xa_transacti":1}
,"xa_transacti":{"connections":1}
,"connections":{"local_transaction":1}
,"local_transaction":{"connec":1}
,"connec":{"tion":1}
,"tion":{"note":1}
,"sure":{"call":1}
,"call":{"either":1}
,"committransaction":{"rollbacktransaction":1}
,"rollbacktransaction":{"star":1}
,"star":{"ttransaction":1}
,"ttransaction":{"otherwise":1}
,"otherwise":{"dangling":1}
,"dangling":{"transaction":1}
,"require":{"reboot":1}
,"reboot":{"integration":1}
,"integration":{"server":1}
,"server":{"new":1}
,"new":{"explicit":1}
,"started":{"within":1}
,"ransaction":{"context":1}
,"provided":{"ensure":1}
,"ensure":{"transa":1}
,"transa":{"ctions":1}
,"ctions":{"within":1}
,"everse":{"order":1}
,"order":{"started-that":1}
,"started-that":{"last":1}
,"last":{"transaction":1}
,"start":{"first":1}
,"first":{"transaction":1}
,"complete":{"forth":1}
,"forth":{"example":1}
,"example":{"consider":1,"shows":1}
,"consider":{"following":1}
,"following":{"valid":1,"example":1}
,"valid":{"construct":1}
,"construct":{"pub.art.transaction.starttransaction":1}
,"shows":{"invalid":1}
,"invalid":{"construct":1}
,"information":{"designing":1,"transaction":1}
,"designing":{"using":1}
,"flows":{"webmethods":1}
,"webmethods":{"service":1}
,"development":{"help":1}
,"help":{"release":1}
,"release":{"information":1}
,"pes":{"transaction":1}
,"adapter":{"jms":1}
}
;Search.control.loadWordPairs(pairs);
