var pairs =
{
"overview":{"adapter":1}
,"adapter":{"webmethods":1,"jms":1,"provides":1}
,"webmethods":{"adapter":1,"integration":1,"clients":1,"adapters":1}
,"jms":{"add-on":1,"providers":1,"apis":1,"webmethods":1,"provider":1,"supports":1}
,"add-on":{"webmethods":1}
,"integration":{"server":1}
,"server":{"enables":1}
,"enables":{"exchange":1}
,"exchange":{"messages":1,"messa":1}
,"messages":{"jms":1}
,"providers":{"rough":1,"using":1,"adapter":1}
,"rough":{"jms":1}
,"apis":{"adapter":1}
,"provides":{"seamless":1}
,"seamless":{"real-time":1}
,"real-time":{"communication":1}
,"communication":{"jms":1}
,"using":{"adapter":1}
,"clients":{"create":1}
,"create":{"run":1}
,"run":{"services":1}
,"services":{"exchange":1}
,"messa":{"ges":1}
,"ges":{"queues":1}
,"queues":{"topics":1}
,"topics":{"jms":1}
,"provider":{"list":1}
,"list":{"jms":1}
,"supports":{"webmethods":1}
,"adapters":{"system":1}
,"system":{"requirements":1}
}
;Search.control.loadWordPairs(pairs);
