var pairs =
{
"configuring":{"jaas":1}
,"jaas":{"authentication":1,"sample":1}
,"authentication":{"jaas":1,"multiple":1,"create":1}
,"multiple":{"weblogic":1}
,"weblogic":{"servers":1}
,"servers":{"configure":1}
,"configure":{"jaas":1}
,"create":{"file":1}
,"file":{"named":1,"${java_dir}\u002Fjre\u002Flib\u002Fsecurity":1,"(server.sh":1}
,"named":{"wmjmsadapter_jaas.config":1}
,"wmjmsadapter_jaas.config":{"follo":1}
,"follo":{"wing":1}
,"wing":{"content":1}
,"content":{"\u002F**login":1}
,"\u002F**login":{"configuration":1}
,"configuration":{"jaas":1}
,"sample":{"application":1}
,"application":{"**\u002Fwmjmsadapter":1}
,"**\u002Fwmjmsadapter":{"{weblogic.security.auth.login.usernamepasswordloginmodule":1}
,"{weblogic.security.auth.login.usernamepasswordloginmodule":{"required":1}
,"required":{"debug=true":1}
,"debug=true":{"save":1}
,"save":{"file":1}
,"${java_dir}\u002Fjre\u002Flib\u002Fsecurity":{"directory":1}
,"directory":{"${java_dir}":1,"append":1}
,"${java_dir}":{"server.bat":1}
,"server.bat":{"file":1}
,"(server.sh":{"unix)":1}
,"unix)":{"located":1}
,"located":{"integration":1}
,"integration":{"server_directory":1}
,"server_directory":{"\u005Cbin":1}
,"\u005Cbin":{"directory":1}
,"append":{"following":1}
,"following":{"line":1}
,"line":{"${java_dir}\u002Fjre\u002Flib\u002Fsecurit":1}
,"${java_dir}\u002Fjre\u002Flib\u002Fsecurit":{"y\u002Fjava.security":1}
,"y\u002Fjava.security":{"package":1}
,"package":{"login.config.url.1=file:${java.home}\u002Flib\u002Fsecurity\u002Fwmjmsadapter_jaas.config":1}
}
;Search.control.loadWordPairs(pairs);
